import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {deflateSync} from 'node:zlib';
import {verifyOriginals,digest} from '../full-campaign-gate/evidence.mjs';
function png(){const crc=b=>{let c=0xffffffff;for(const x of b){c^=x;for(let i=0;i<8;i++)c=c&1?0xedb88320^(c>>>1):c>>>1;}return(c^0xffffffff)>>>0;};const chunk=(type,data)=>{const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length);b.write(type,4);data.copy(b,8);b.writeUInt32BE(crc(b.subarray(4,8+data.length)),8+data.length);return b;};const h=Buffer.alloc(13);h.writeUInt32BE(1);h.writeUInt32BE(1,4);h[8]=8;h[9]=6;return Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',h),chunk('IDAT',deflateSync(Buffer.alloc(5))),chunk('IEND',Buffer.alloc(0))]);}
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'full-evidence-'));const files={'shot.png':png(),'case.json':Buffer.from('{"setup":"synthetic guard fixture"}')};const sourceFingerprint='1'.repeat(64),buildFingerprint='2'.repeat(64);for(const [name,bytes]of Object.entries(files))fs.writeFileSync(path.join(root,name),bytes);const options={required:Object.keys(files),rows:Object.entries(files).map(([name,bytes])=>({path:name,bytes:bytes.length,sha256:digest(bytes),sourceFingerprint,buildFingerprint,...(name.endsWith('.png')?{dimensions:[1,1]}:{})})),sourceFingerprint,buildFingerprint,byteLimit:1024,pngLimit:1};return{root,options,remove:()=>fs.rmSync(root,{recursive:true,force:true})};}
test('exact original set verifies bytes and PNG dimensions',()=>{const f=fixture();try{assert.equal(verifyOriginals(f.root,f.options).files,2);}finally{f.remove();}});
test('missing required manifest row cannot become partial success',()=>{const f=fixture();try{f.options.rows.pop();assert.throws(()=>verifyOriginals(f.root,f.options),/Missing/);}finally{f.remove();}});
test('missing expected on-disk original fails even if its row exists',()=>{const f=fixture();try{fs.unlinkSync(path.join(f.root,'shot.png'));assert.throws(()=>verifyOriginals(f.root,f.options));}finally{f.remove();}});
test('duplicate or unexpected original fails',()=>{const f=fixture();try{f.options.rows.push(f.options.rows[0]);assert.throws(()=>verifyOriginals(f.root,f.options),/Duplicate/);}finally{f.remove();}});
test('changed PNG bytes or invented source/build fingerprints fail',()=>{const f=fixture();try{for(const key of ['sourceFingerprint','buildFingerprint','sha256']){const options=structuredClone(f.options);options.rows[0][key]='3'.repeat(64);assert.throws(()=>verifyOriginals(f.root,options));}fs.writeFileSync(path.join(f.root,'shot.png'),Buffer.from('not a screenshot'));assert.throws(()=>verifyOriginals(f.root,f.options));}finally{f.remove();}});
test('byte and PNG caps fail closed',()=>{const f=fixture();try{assert.throws(()=>verifyOriginals(f.root,{...f.options,byteLimit:1}));assert.throws(()=>verifyOriginals(f.root,{...f.options,pngLimit:0}));}finally{f.remove();}});
test('unsafe paths and symlink evidence are rejected',()=>{const f=fixture();try{const row={...f.options.rows[0],path:'../shot.png'};assert.throws(()=>verifyOriginals(f.root,{...f.options,required:['../shot.png'],rows:[row]}));fs.unlinkSync(path.join(f.root,'shot.png'));fs.symlinkSync(path.join(f.root,'case.json'),path.join(f.root,'shot.png'));assert.throws(()=>verifyOriginals(f.root,f.options),/symlink/);}finally{f.remove();}});
