import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {C,E,chapterEntry,chapterEnd,heldAtFive,quantityReadyPartial,finalePair,allArt} from '../tests/full-campaign-browser/fixtures.mjs';import {digest} from '../full-campaign-gate/evidence.mjs';
test('all chapter browser checkpoints validate and complete exactly 113 letters',()=>{for(let n=1;n<=16;n++){E.validateCareer(chapterEntry(n));const s=chapterEnd(n);assert(E.chapterComplete(s));}assert.equal(chapterEnd(16).milestones.length,113);});
test('held quantity finale and all-art setup states are honest reachable fixtures',()=>{const held=heldAtFive();assert.equal(held.heldOrders.length,2);const q=quantityReadyPartial(),o=q.orders.find(o=>o.storyLetterId==='fine-print-letter-4');assert.equal(E.matchingTiles(q,o),null);assert.equal(q.board.filter(t=>t?.pieceId==='ob3').length,1);const final=finalePair();assert(!final.orders.some(o=>o.storyLetterId==='sound-advice-letter-8'));assert(final.orders.some(o=>o.storyLetterId==='sound-advice-letter-7'));assert.equal(allArt().discoveries.length,160);});
test('original 21-case harness bytes remain preserved',()=>{const m=JSON.parse(fs.readFileSync('full-browser-evidence/legacy-harness-preservation.json'));for(const row of m.files){const b=fs.readFileSync(row.file);assert.equal(b.length,row.bytes);assert.equal(digest(b),row.sha256,row.file);}});
test('native stale-selection setup has pruned receipts and no resurrectable delivered promise',async()=>{const {d}=await import('../tests/full-campaign-browser/fixtures.mjs');let s=heldAtFive(),id=s.heldOrders[0].id;s=d.act(s,{type:'resume-optional',orderId:id});s=d.complete(s,s.orders.find(o=>o.id===id));for(const storyId of C.CHAPTERS[4].storyIds)if(!s.milestones.includes(storyId))s=d.complete(s,s.orders.find(o=>o.storyLetterId===storyId));s=d.act(s,{type:'purchase',upgradeId:'order-desk',expectedLevel:0});for(let n=0;n<41;n++)s=d.complete(s,s.orders.find(o=>!o.storyLetterId));E.validateCareer(s);assert.equal(s.receipts.length,40);assert(![...s.orders,...s.heldOrders].some(o=>o.id===id));});
test('later phone entry has retained high-tier stock and a used purchased sorter cursor',async()=>{const {d,retainedAtEight}=await import('../tests/full-campaign-browser/fixtures.mjs');const before=retainedAtEight();assert(before.board.some(t=>t?.pieceId==='b5'));assert.equal(before.upgrades['bird-sorter'],1);assert.equal(before.sources.bird.cursor,1);const after=d.act(before,{type:'start-next-chapter',chapterId:C.CHAPTERS[8].id});for(const key of ['board','sources','material'])assert.deepEqual(after[key],before[key]);});
test('oversize-write fixture reads below the bound and supply crosses the real encoding limit',async()=>{const {oversizeWrite}=await import('../tests/full-campaign-browser/fixtures.mjs');const {storageHarness}=await import('../tests/campaign-browser/save-fixtures.mjs');const {createCareerSession}=await import('../src/career/session.js');const state=oversizeWrite(),h=storageHarness(state),session=createCareerSession(h);assert.equal((await session.open()).status,'saved');const before=h.map.get(C.STORAGE_KEY);const result=await session.commit(E.commandFor(state,{type:'supply',familyId:state.activeSourceIds[0]}));assert.equal(result.status,'practice');assert.equal(result.code,'practice-applied');assert.match(result.warning,/too large to save safely/);assert.equal(h.map.get(C.STORAGE_KEY),before);});

test('continuation browser fixtures require explicit entry and expose200 while original remains160',()=>{for(let n=17;n<=20;n++){const start=chapterEntry(n),end=chapterEnd(n);E.validateCareer(start);assert(start.continuationEntries['after-the-first-correspondence']);assert(E.chapterComplete(end));}assert.equal(chapterEnd(16).milestones.length,113);assert.deepEqual(chapterEnd(16).continuationEntries,{});assert.equal(chapterEnd(20).milestones.length,139);assert.equal(allArt().discoveries.length,160);assert.equal(allArt({continuation:true}).discoveries.length,200);});

test('native Stage A setup saves retain authentic old promises and exact competing stock',async()=>{const {originalSaveEntryFixtures,secondLookRetained,looseEndsCompetition,d}=await import('../tests/full-campaign-browser/fixtures.mjs');const old=originalSaveEntryFixtures();assert.equal(old.inProgress.schemaVersion,4);assert(old.inProgress.milestones.length<113);assert.equal(old.completed.milestones.length,113);assert(old.completed.orders.some(o=>o.slot===2));const migrated=E.upgradeCareer(old.completed);assert(E.canEnterContinuation(migrated));for(const key of ['board','orders','heldOrders','focusedOrderId','purchases'])assert.deepEqual(migrated[key],old.completed[key]);const second=secondLookRetained();assert(second.state.board.some(t=>t?.id===second.callbackId&&t.pieceId==='pn2'));assert(second.state.board.some(t=>t?.id===second.retainedId&&t.pieceId==='b5'));let state=second.state;for(const id of C.CHAPTERS[17].storyIds.slice(0,3)){state=d.complete(state,state.orders.find(o=>o.storyLetterId===id));assert(state.board.some(t=>t?.id===second.retainedId));if(id.endsWith('-1'))assert(state.unlockedSources.includes('camera'));}const q=looseEndsCompetition(),a=q.orders.find(o=>o.storyLetterId==='loose-ends-letter-4'),b=q.orders.find(o=>o.storyLetterId==='loose-ends-letter-5');assert.equal(q.board.filter(t=>t?.pieceId==='sp2').length,1);assert.equal(q.board.filter(t=>t?.pieceId==='sp1').length,2);assert.equal(E.matchingTiles(q,a),null);assert.equal(E.matchingTiles(q,b).length,2);const pair=q.board.flatMap((t,i)=>t?.pieceId==='sp1'?[i]:[]),ready=d.act(q,{type:'move',from:pair[0],to:pair[1],tileId:q.board[pair[0]].id,targetTileId:q.board[pair[1]].id});assert.equal(E.matchingTiles(ready,a).length,3);const after=d.complete(ready,a);assert(after.board.some(t=>t?.pieceId==='cj3'));assert.equal(E.matchingTiles(after,b),null);});
