import test from 'node:test';import assert from 'node:assert/strict';
import {inspectHudReadability,hudReadabilityViolations} from '../tests/full-campaign-browser/hud-readability.mjs';
const rect=(x,y,width,height)=>({x,y,width,height,right:x+width,bottom:y+height});
function scene({large=false,replay=false}={}){
 const doc={defaultView:{getComputedStyle:e=>({display:'block',visibility:'visible',contentVisibility:'visible',opacity:'1',fontSize:'14px',color:'rgb(0, 0, 0)',...e.style})},createTreeWalker:root=>{const nodes=[];const walk=e=>{for(const child of e.children??[])child.nodeType===3?nodes.push(child):walk(child);};walk(root);let i=-1;return{nextNode(){return!!nodes[++i];},get currentNode(){return nodes[i];}};},createRange:()=>{let node;return{selectNodeContents:n=>node=n,getClientRects:()=>node.rects};}};
 const element=(kind,r)=>({kind,style:{},children:[],parentElement:null,ownerDocument:doc,hidden:false,attributes:{},getAttribute(name){return this.attributes[name]??null;},matches(selector){return selector==='.'+this.kind;},getBoundingClientRect(){return this.rect;},getClientRects(){return this.noLayout?[]:[this.rect];},querySelector(selector){return this.children.find(c=>c.tag===selector.split(' > ')[1])??null;},rect:r,clientWidth:r.width,clientHeight:r.height,scrollWidth:r.width,scrollHeight:r.height});
 const hud=element('career-mobile-hud',rect(0,0,390,large?112:52)),kinds=['career-mobile-progress-button','career-mobile-coins',replay?'career-mobile-return':'career-mobile-orders-button','career-mobile-more-button'];
 const boxes=large?[rect(0,0,390,54),rect(0,62,110,44),rect(118,62,126,44),rect(252,62,138,44)]:[rect(0,0,144,44),rect(150,0,44,44),rect(200,0,72,44),rect(278,0,44,44)];
 const addText=(parent,text,r)=>{parent.children.push({nodeType:3,parentElement:parent,textContent:text,rects:[r]});};
 const addLabel=(control,tag,text,r)=>{const label=element(tag,r);label.tag=tag;label.parentElement=control;control.children.push(label);addText(label,text,r);return label;};
 for(const [i,kind]of kinds.entries()){const c=element(kind,boxes[i]);c.parentElement=hud;hud.children.push(c);const {x,y}=c.rect;if(i===0){addLabel(c,'strong','Chapter 17',rect(x+4,y+4,90,15));addLabel(c,'span','One letter to go',rect(x+4,y+24,122,14));}else if(i===1){addLabel(c,'strong','125',rect(x+8,y+4,24,16));addLabel(c,'small','coins',rect(x+4,y+28,34,10));}else if(i===2&&replay)addText(c,'Return',rect(x+5,y+25,54,14));else addLabel(c,'span',i===2?'Orders 2':'More',rect(x+4,y+25,i===2?62:34,14));}
 return hud;
}
const failures=hud=>hudReadabilityViolations(inspectHudReadability(hud));
test('visible compact large-text wrapped and replay HUDs pass with measured labels',()=>{for(const options of [{},{large:true},{replay:true}])assert.deepEqual(failures(scene(options)),[]);const hud=scene({large:true}),cue=hud.children[0].children[1];cue.rect=rect(4,22,190,28);cue.children[0].rects=[rect(4,22,160,13),rect(4,37,110,13)];assert.deepEqual(failures(hud),[]);});
test('hidden HUD controls and ancestors fail even when geometry still looks valid',()=>{for(const style of [{display:'none'},{visibility:'hidden'},{visibility:'collapse'},{contentVisibility:'hidden'},{opacity:'0'}]){const hud=scene();hud.children[2].style=style;assert(failures(hud).some(s=>/hidden/.test(s)),JSON.stringify(style));}for(const mutate of [h=>h.hidden=true,h=>h.attributes['aria-hidden']='true',h=>h.children[0].hidden=true,h=>h.children[3].attributes['aria-hidden']='true']){const hud=scene();mutate(hud);assert(failures(hud).length>0);}assert(hudReadabilityViolations(inspectHudReadability(null)).length>0);});
test('missing controls zero-size invalid geometry and absent layout cannot pass vacuously',()=>{for(const mutate of [h=>h.children=[],h=>h.children.pop(),h=>h.children[0].kind='unknown',h=>h.children[2].rect=rect(200,0,0,44),h=>h.children[2].rect=rect(200,0,72,0),h=>h.children[2].noLayout=true,h=>h.rect=rect(0,0,0,0),h=>h.children[2].rect.x=NaN]){const hud=scene();mutate(hud);assert(failures(hud).length>0);}});
test('each required text slot must exist and have visible nonempty positive-sized glyph rectangles',()=>{for(const mutate of [h=>h.children[3].children=[],h=>h.children[0].children.shift(),h=>h.children[1].children.pop(),h=>h.children[0].children[0].children[0].textContent='  ',h=>h.children[0].children[0].children[0].rects=[],h=>h.children[0].children[0].children[0].rects=[rect(4,4,0,15)],h=>h.children[0].children[0].style.visibility='hidden',h=>h.children[0].children[0].style.fontSize='0px',h=>h.children[0].children[0].style.color='transparent',h=>h.children[0].children[0].style.color='rgba(0, 0, 0, 0)']){const hud=scene();mutate(hud);assert(failures(hud).some(s=>/text|label/.test(s)));}});
test('same-left-edge containment reversed-order partial and vertical overlaps all fail',()=>{for(const r of [rect(0,0,144,44),rect(0,0,44,44),rect(130,0,44,44),rect(200,0,44,44),rect(0,43.5,44,44)]){const hud=scene();hud.children[1].rect=r;assert(failures(hud).some(s=>/overlapping rectangles/.test(s)),JSON.stringify(r));}const hud=scene();hud.children[1].rect=rect(148,0,44,44);assert(failures(hud).some(s=>/separation/.test(s)));});
test('text cannot use an oversized nested label to escape its owning control on any edge',()=>{for(const r of [rect(-3,5,80,14),rect(10,-3,80,14),rect(100,5,80,14),rect(10,36,80,14)]){const hud=scene(),label=hud.children[0].children[0];label.rect=rect(-50,-50,500,500);label.children[0].rects=[r];assert(failures(hud).some(s=>/text overflows its own control/.test(s)),JSON.stringify(r));}});
test('scroll clipping on either axis and label-local overflow remain failures',()=>{for(const axis of ['Width','Height']){const hud=scene();hud.children[0]['scroll'+axis]+=8;assert(failures(hud).some(s=>/content overflows/.test(s)));}const hud=scene();hud.children[0].children[0].rect=rect(4,4,20,15);assert(failures(hud).some(s=>/overflows its label/.test(s)));});

test('browser helper applies the new DOM proof and rejects absent or invalid HUDs',async()=>{
 const {readFileSync}=await import('node:fs'),source=readFileSync('tests/full-campaign-browser/helpers.mjs','utf8'),code=source.slice(source.indexOf('export async function hudReadability(page)'),source.indexOf('export async function wayfinderLines')).replace(/^export /,'');
 const expect=value=>({toHaveCount:async count=>assert.equal(value.count,count),toEqual:expected=>assert.deepEqual(value,expected)}),run=new Function('inspectHudReadability','hudReadabilityViolations','expect',code+';return hudReadability;')(inspectHudReadability,hudReadabilityViolations,expect);
 const page=(hud,count=1)=>({locator:()=>({count,evaluate:async fn=>fn(hud)})});assert.equal((await run(page(scene()))).controls.length,4);await assert.rejects(()=>run(page(null,0)));const hidden=scene();hidden.children[2].style.opacity='0';await assert.rejects(()=>run(page(hidden)));const blank=scene();blank.children[0].children=[];await assert.rejects(()=>run(page(blank)));
});

test('two labels cannot overlap inside an otherwise well-sized control',()=>{const hud=scene(),cue=hud.children[0].children[1];cue.rect=rect(4,4,122,14);cue.children[0].rects=[cue.rect];assert(failures(hud).some(s=>/overlapping text rectangles/.test(s)));});

test('empty malformed coercible and legacy-shaped evidence always returns violations',()=>{
 for(const bad of [undefined,null,{},[],false,0,''])assert(hudReadabilityViolations(bad).length>0);
 const changes=[p=>p.hud.visible='false',p=>p.hud.visible=1,p=>p.controls[0].visible='false',p=>p.controls[0].text[0].visible='false',p=>p.controls[0].labels[0].present='false',p=>p.controls[0].layoutRects='1',p=>p.controls[0].layoutRects=.5,p=>p.controls[0].scrollWidth=-1,p=>p.controls[0].scrollHeight='44',p=>p.controls[0].clientWidth=.5,p=>p.controls[0].text=[null],p=>p.controls[0].text[0].rects=[null],p=>p.controls[0].labels=[null],p=>p.controls[0].text[0].rects[0].width='90',p=>p.controls[0].style={display:'none'},p=>p.controls=p.controls.map(c=>c.rect),p=>p.extra='ignored',p=>delete p.hud.clientWidth];
 for(const [i,change]of changes.entries()){const proof=inspectHudReadability(scene());change(proof);let issues;assert.doesNotThrow(()=>issues=hudReadabilityViolations(proof),`malformed ${i}`);assert(issues.length>0,`malformed ${i} must reject`);}
});
test('serialized producer proof matches strict schema and CSS visibility remains boolean',()=>{
 const serialized=new Function('return ('+inspectHudReadability.toString()+')')();
 for(const options of [{},{large:true},{replay:true}]){const proof=JSON.parse(JSON.stringify(serialized(scene(options))));assert.equal(typeof proof.hud.visible,'boolean');for(const c of proof.controls){assert.equal(typeof c.visible,'boolean');assert(Number.isSafeInteger(c.layoutRects));for(const text of c.text){assert.equal(typeof text.visible,'boolean');assert(text.rects.every(r=>r.x>=c.rect.x&&r.right<=c.rect.right&&r.y>=c.rect.y&&r.bottom<=c.rect.bottom));}}assert.deepEqual(hudReadabilityViolations(proof),[]);}
 for(const style of [{display:'none'},{visibility:'hidden'},{opacity:'0'},{contentVisibility:'hidden'}]){const hud=scene();hud.children[0].style=style;const proof=JSON.parse(JSON.stringify(serialized(hud)));assert.equal(proof.controls[0].visible,false);assert(hudReadabilityViolations(proof).length>0);}
 const hud=scene(),label=hud.children[0].children[0];label.rect=rect(-10,-10,900,900);label.children[0].rects=[rect(130,5,80,14)];const proof=JSON.parse(JSON.stringify(serialized(hud)));assert(proof.controls[0].text[0].parent.width>proof.controls[0].rect.width);assert(hudReadabilityViolations(proof).some(s=>/own control/.test(s)));
});

// Source contracts protect the container dependency exposed by native WebKit B16.
// They do not substitute for rendered geometry checks in the unchanged browser cases.
const compactHudCss=async()=>await(await import('node:fs/promises')).readFile(new URL('../src/career/career.css',import.meta.url),'utf8');
function hudRules(css){return [...css.matchAll(/([^{}]+)\{([^{}]*)\}/g)].map(m=>({selector:m[1].trim(),index:m.index,props:Object.fromEntries(m[2].split(';').filter(s=>s.includes(':')).map(s=>{const i=s.indexOf(':');return[s.slice(0,i).trim(),s.slice(i+1).trim()];}))}));}
function normalHudContract(css){const rules=hudRules(css),last=s=>rules.findLast(r=>r.selector===s),normal='.career-shell:not(.is-large-text) ';
 const container=last(normal+'.career-mobile-hud');assert.equal(container?.props.display,'flex','Wrapped progress must contribute to a flex row, not a nested grid track');
 assert(container.index>last('.career-mobile-hud').index,'Normal override must follow shared HUD declarations');
 assert.equal(last(normal+'.career-mobile-progress-button').props.flex,'1 1 0%','Progress receives responsive remaining width');
 assert.equal(last(normal+'.career-mobile-progress-button').props['min-height'],'44px');
 assert.equal(last(normal+'.career-mobile-coins').props.flex,'none','Wallet retains intrinsic content width');
 assert.equal(last(normal+'.career-mobile-orders-button,'+normal+'.career-mobile-return').props.flex,'0 0 72px');
 assert.equal(last(normal+'.career-mobile-more-button').props.flex,'0 0 44px');
 assert(!Object.hasOwn(container.props,'width'),'Do not hard-code a viewport width');
}
test('normal HUD owns wrapped height and preserves responsive wallet/action allocation',async()=>{const css=await compactHudCss();normalHudContract(css);assert.throws(()=>normalHudContract(css.replace('.career-shell:not(.is-large-text) .career-mobile-hud{display:flex}', '.career-shell:not(.is-large-text) .career-mobile-hud{display:grid}')));});
test('HUD container override ordering rejects regression while large-text keeps its grid',async()=>{const css=await compactHudCss();assert.throws(()=>normalHudContract(css+'\n@media(max-width:650px){.career-shell:not(.is-large-text) .career-mobile-hud{display:grid}}'));const rules=hudRules(css),large=rules.findLast(r=>r.selector==='.career-shell.is-large-text .career-mobile-hud');assert.equal(large.props['grid-template-columns'],'minmax(0,1fr) minmax(82px,1fr) minmax(64px,1fr)');assert.equal(rules.findLast(r=>r.selector==='.career-shell.is-large-text .career-mobile-progress-button').props['grid-column'],'1/-1');assert(!rules.some(r=>r.selector==='.career-mobile-hud'&&r.props.display==='flex'),'Flex override must stay normal-text only');});
