import {STAGE_A_TESTS,STAGE_A_TEST_COUNT,stageContractProof} from '../full-campaign-gate/stage-contracts.mjs';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {deflateSync} from 'node:zlib';import {verifyPackage} from '../full-campaign-gate/package.mjs';import {digest} from '../full-campaign-gate/evidence.mjs';import {CASES,REQUIRED_SCREENSHOTS,expectedOriginals,validateInvocation,eligibleBudget} from '../full-campaign-gate/scope.mjs';
function png(w=1,h=1){const crc=b=>{let c=0xffffffff;for(const x of b){c^=x;for(let i=0;i<8;i++)c=c&1?0xedb88320^(c>>>1):c>>>1;}return(c^0xffffffff)>>>0;};const chunk=(type,data)=>{const b=Buffer.alloc(data.length+12);b.writeUInt32BE(data.length);b.write(type,4);data.copy(b,8);b.writeUInt32BE(crc(b.subarray(4,8+data.length)),8+data.length);return b;};const hd=Buffer.alloc(13);hd.writeUInt32BE(w);hd.writeUInt32BE(h,4);hd[8]=8;hd[9]=6;return Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',hd),chunk('IDAT',deflateSync(Buffer.alloc((w*4+1)*h))),chunk('IEND',Buffer.alloc(0))]);}
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'aggregate-evidence-')),manifest={files:STAGE_A_TESTS.map(file=>({file,bytes:1,sha256:digest(file)}))},source=JSON.stringify(manifest),proof={sourceFingerprint:digest(source),buildFingerprint:digest('{"build":true}')};const write=(p,data)=>{fs.mkdirSync(path.dirname(path.join(root,p)),{recursive:true});fs.writeFileSync(path.join(root,p),typeof data==='string'||Buffer.isBuffer(data)?data:JSON.stringify(data));};write('source.json',source);write('build.json','{"build":true}');write('preflight.json',{status:'passed',...proof,steps:[{name:'stage-a',status:0,signal:null,args:['--test','--test-reporter=tap',...STAGE_A_TESTS]}]});const stageLog=Buffer.from(`# tests ${STAGE_A_TEST_COUNT}\n# pass ${STAGE_A_TEST_COUNT}\n# fail 0\n# cancelled 0\n# skipped 0\n# todo 0\n`);write('stage-a.log',stageLog);write('stage-a-contracts.json',stageContractProof(manifest,stageLog));const routes=JSON.parse(fs.readFileSync(new URL('../full-browser-fixtures/stage-a-reviewed-routes.json',import.meta.url)));write('stage-a/basic-runtime-route.json',routes.basic);write('stage-a/purchase-runtime-routes.json',routes.purchases);const config={workers:1,fullyParallel:false,forbidOnly:true,maxFailures:1};const suites=[];for(const [profile,cases]of Object.entries(CASES)){write(`${profile}/launcher.json`,{status:'passed',profile,exitCode:0,signal:null,timedOut:false});const specs=cases.map(([id,title])=>({id:profile+id,title:`${id} ${title}`,tests:[{projectName:profile,expectedStatus:'passed',status:'expected',results:[{status:'passed',retry:0}]}]}));write(`${profile}/results.json`,{config,errors:[],stats:{unexpected:0,skipped:0,flaky:0,expected:cases.length},suites:[{specs}]});const collect=structuredClone(specs);collect.forEach(s=>s.tests[0].results=[]);suites.push({specs:collect});const events=[{event:'begin',workers:1,maxFailures:1,retries:[0],projects:[profile]},...cases.flatMap(([id])=>[{event:'test-begin',id:profile+id,project:profile,retry:0},{event:'test-end',id:profile+id,project:profile,retry:0,status:'passed',errors:[]}]),{event:'end',status:'passed',durationMs:1}];write(`${profile}/progress/browser-events.jsonl`,events.map(e=>JSON.stringify({...proof,...e})).join('\n')+'\n');for(const[id]of cases)write(`${profile}/${id}.json`,{caseId:id,...proof});}write('collection.json',{config,errors:[],suites});const rows=expectedOriginals().map(p=>{const dims=p.includes('/postcards/')?[1536,1120]:[1,1],bytes=png(...dims);write(p,bytes);return{path:p,bytes:bytes.length,sha256:digest(bytes),dimensions:dims,...proof};});for(const profile of Object.keys(CASES))write(`${profile}/screenshots/manifest.json`,rows.filter(r=>r.path.startsWith(profile+'/screenshots/')));write('full-chromium/postcards/manifest.json',rows.filter(r=>r.path.includes('/postcards/')));return{root,proof,write,remove:()=>fs.rmSync(root,{recursive:true,force:true})};}
test('aggregate requires all 22 terminal cases and all 25 originals',()=>{const f=fixture();try{assert.equal(verifyPackage(f.root,f.proof).originals.files,25);}finally{f.remove();}});
test('any missing case record original or terminal report fails aggregate',()=>{for(const p of ['full-chromium/D11.json','full-chromium/D12.json','full-chromium/D13.json','full-chromium/D14.json','full-chromium/screenshots/D11-entry.png','full-chromium/screenshots/D12-camera.png','full-chromium/screenshots/D13-competition.png','full-chromium/screenshots/D14-new-family.png','full-webkit-phone/M08.json','full-chromium/results.json',expectedOriginals()[0],'full-chromium/postcards/D14-cm5.png','preflight.json','source.json','stage-a.log','stage-a-contracts.json','stage-a/basic-runtime-route.json','stage-a/purchase-runtime-routes.json']){const f=fixture();try{fs.unlinkSync(path.join(f.root,p));assert.throws(()=>verifyPackage(f.root,f.proof));}finally{f.remove();}}});
test('incomplete or source-mismatched preflight cannot pass',()=>{const f=fixture();try{f.write('preflight.json',{status:'incomplete-or-failed',...f.proof});assert.throws(()=>verifyPackage(f.root,f.proof));}finally{f.remove();}});
test('missing terminal event cannot be replaced with a passing report',()=>{const f=fixture();try{const p='full-chromium/progress/browser-events.jsonl',s=fs.readFileSync(path.join(f.root,p),'utf8').trim().split('\n');s.pop();f.write(p,s.join('\n')+'\n');assert.throws(()=>verifyPackage(f.root,f.proof));}finally{f.remove();}});
test('exact scope remains 22 cases 23 screenshots and two exports',()=>{assert.equal(Object.values(CASES).flat().length,22);assert.equal(Object.values(REQUIRED_SCREENSHOTS).flat().length,23);assert.equal(expectedOriginals().length,25);assert.throws(()=>validateInvocation(['test','--config=playwright.full-campaign.config.mjs','--project=full-chromium']));assert.throws(()=>eligibleBudget('full-chromium',1100));});

test('timed-out launcher or over-budget terminal duration cannot pass',()=>{for(const kind of ['launcher','duration']){const f=fixture();try{if(kind==='launcher')f.write('full-chromium/launcher.json',{status:'passed',profile:'full-chromium',exitCode:0,signal:null,timedOut:true});else{const p='full-chromium/progress/browser-events.jsonl',rows=fs.readFileSync(path.join(f.root,p),'utf8').trim().split('\n').map(x=>JSON.parse(x));rows.at(-1).durationMs=600001;f.write(p,rows.map(r=>JSON.stringify(r)).join('\n')+'\n');}assert.throws(()=>verifyPackage(f.root,f.proof));}finally{f.remove();}}});

test('Stage A omission tampering skipped tests or changed arguments cannot pass aggregate',()=>{for(const change of ['missing-step','wrong-args','changed-log','changed-proof']){const f=fixture();try{if(change==='changed-log')fs.appendFileSync(path.join(f.root,'stage-a.log'),'# skipped 1\n');else if(change==='changed-proof')f.write('stage-a-contracts.json',{});else{const p=JSON.parse(fs.readFileSync(path.join(f.root,'preflight.json')));if(change==='missing-step')p.steps=[];else p.steps[0].args=['--test',STAGE_A_TESTS[0]];f.write('preflight.json',p);}assert.throws(()=>verifyPackage(f.root,f.proof));}finally{f.remove();}}});

test('aggregate rejects parseable but invalid basic and purchase route records',()=>{for(const [name,bad]of [['basic-runtime-route.json',null],['basic-runtime-route.json',{}],['basic-runtime-route.json',[]],['purchase-runtime-routes.json',null],['purchase-runtime-routes.json',{}],['purchase-runtime-routes.json',[]]]){const f=fixture();try{f.write('stage-a/'+name,bad);assert.throws(()=>verifyPackage(f.root,f.proof));}finally{f.remove();}}});
