import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {CASES,BUDGETS,JOB_SECONDS,PREFLIGHT_SECONDS,SETUP_SECONDS,RESERVE_SECONDS,MAX_SCREENSHOTS,MAX_POSTCARDS,MAX_ARTIFACT_BYTES,REQUIRED_SCREENSHOTS,REQUIRED_POSTCARDS} from '../full-campaign-gate/scope.mjs';
test('new Stage A scope retains the original global budgets and replaces duplicate artifact slots',()=>{assert.deepEqual(CASES['full-chromium'].slice(10).map(([id,,timeout])=>[id,timeout]),[['D11',75000],['D12',90000],['D13',90000],['D14',60000]]);assert.equal(CASES['full-webkit-phone'].length,8);assert.equal(Object.values(CASES).flat().length,22);assert.deepEqual(BUDGETS,{'full-chromium':600000,'full-webkit-phone':420000});assert.deepEqual([JOB_SECONDS,PREFLIGHT_SECONDS,SETUP_SECONDS,RESERVE_SECONDS],[1800,300,300,120]);assert.equal(MAX_SCREENSHOTS,23);assert.equal(MAX_POSTCARDS,2);assert.equal(MAX_ARTIFACT_BYTES,60*1024*1024);assert.deepEqual(REQUIRED_SCREENSHOTS['full-chromium'].filter(n=>/^D1[1-4]-/.test(n)),['D11-entry','D12-camera','D13-competition','D14-new-family']);assert.deepEqual(REQUIRED_POSTCARDS,['full-chromium/postcards/D09-b1.png','full-chromium/postcards/D14-cm5.png']);});
test('Stage A scenarios are present once and sealed artifacts include each new native case',()=>{const source=fs.readFileSync('tests/full-campaign-browser/desktop.spec.mjs','utf8'),indices=[...source.matchAll(/scenario\((\d+),/g)].map(m=>Number(m[1]));assert.deepEqual(indices,Array.from({length:14},(_,i)=>i));for(const text of ['Begin Small Impressions','secondLookRetained','looseEndsCompetition','Original ending',"h.exportCard(page,info,'cm5')"])assert(source.includes(text));const config=fs.readFileSync('playwright.full-campaign.config.mjs','utf8');assert(config.includes('workers:1'));assert(config.includes('retries:0'));assert(config.includes('maxFailures:1'));});

test('D14 retains complete200-card identity traversal as well as selectors and the new postcard',()=>{const source=fs.readFileSync('tests/full-campaign-browser/desktop.spec.mjs','utf8'),d14=source.slice(source.indexOf('scenario(13,'));assert(d14.includes('const gallery=await h.collectionPages(page,200)'));assert(d14.includes("gallery.images.filter(image=>image.location==='collection')).toHaveLength(200)"));assert(d14.includes('h.record(info,{gallery,images,exported'));assert(d14.indexOf('h.collectionPages(page,200)')<d14.indexOf("selectOption('short-measure')"));const helper=fs.readFileSync('tests/full-campaign-browser/helpers.mjs','utf8');assert(helper.includes("await expect(cards.locator('img')).toHaveCount(count)"));assert(helper.includes("proof.filter(image=>image.location==='collection').map(image=>image.pieceId)).toEqual(ids)"));assert(helper.includes('expect(seen).toEqual(C.CATALOG.PIECES.slice(0,total).map(p=>p.id))'));});

test('collection adapter visits all ten pages and rejects absent or misidentified card image proofs',async()=>{
 // Exercise the real adapter with a minimal locator double, not a browser or image renderer.
 const source=fs.readFileSync('tests/full-campaign-browser/helpers.mjs','utf8'),adapter=source.slice(source.indexOf('export async function collectionPages')).replace(/^export /,'');
 const {CATALOG}=await import('../src/career/content.js');
 for(const fault of [null,'missing-image','wrong-image','missing-proof','wrong-page']){
  let index=0,visited=[];
  const ids=()=>CATALOG.PIECES.slice(index*20,index*20+20).map(p=>p.id);
  const page={locator:()=>({count:20,evaluateAll:async()=>ids(),locator:()=>({count:fault==='missing-image'&&index===8?19:20})}),getByRole:(role)=>role==='navigation'?{text:`Page ${fault==='wrong-page'&&index===9?9:index+1} of 10`}:{disabled:index===9,click:async()=>{assert(index<9);index++;}}};
  const expect=value=>({toHaveCount:async n=>assert.equal(value.count,n),toContainText:async text=>assert(value.text.includes(text)),toBeDisabled:async()=>assert(value.disabled),toEqual:other=>assert.deepEqual(value,other)});
  const proof=async()=>{visited.push(index);let pictures=ids().map(pieceId=>({location:'collection',pieceId}));if(fault==='wrong-image'&&index===9)pictures[0].pieceId='b1';if(fault==='missing-proof'&&index===9)pictures.pop();return pictures;};
  const run=new Function('expect','C','imageProof',adapter+';return collectionPages;')(expect,{CATALOG},proof);
  if(fault)await assert.rejects(()=>run(page,200),fault);else{const result=await run(page,200);assert.equal(result.images.length,200);assert.deepEqual(result.seen,CATALOG.PIECES.slice(0,200).map(p=>p.id));assert.deepEqual(visited,[0,1,2,3,4,5,6,7,8,9]);}
 }
});
