import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {validateBasicRoute,validatePurchaseRoutes,validateRouteRecords} from '../full-campaign-gate/stage-route-records.mjs';
const frozen=JSON.parse(fs.readFileSync(new URL('../full-browser-fixtures/stage-a-reviewed-routes.json',import.meta.url))),copy=()=>structuredClone(frozen);
test('exact independently reviewed basic and all11 purchase records satisfy semantic and identity contracts',()=>{const input=copy(),before=JSON.stringify(input);assert.deepEqual(validateRouteRecords(input.basic,input.purchases),{basicLetters:26,purchaseRoutes:11});assert.equal(JSON.stringify(input),before);});
test('route evidence rejects absent null empty primitive array/object confusion and unknown fields',()=>{for(const bad of [undefined,null,{},[],0,true,'passed']){assert.throws(()=>validateBasicRoute(bad));assert.throws(()=>validatePurchaseRoutes(bad));}const b=copy().basic;b.success=true;assert.throws(()=>validateBasicRoute(b));const p=copy().purchases;p[0].success=true;assert.throws(()=>validatePurchaseRoutes(p));});
test('basic evidence rejects missing or duplicate letters wrong chapter order counts rewards provenance and completion',()=>{
 const changes=[b=>delete b.records,b=>b.records.pop(),b=>b.records[1].id=b.records[0].id,b=>b.records.reverse(),b=>b.records[0].id='garden-letter-1',b=>b.records[0].makes++,b=>{b.records[0].makes++;b.records[1].makes--;},b=>b.records[0].makes='6',b=>b.records[0].xp++,b=>b.records[0].coins++,b=>b.state=null,b=>b.state.careerId='other-career',b=>b.state.milestones.pop(),b=>b.state.chapterId='sound-advice',b=>b.state.enteredChapters.pop(),b=>b.state.storyCompletions['garden-letter-1'].contentVersion=5,b=>b.state.coinsSpent=1,b=>b.state.xp++,b=>b.state.sources['rubber-stamp'].cursor=1,b=>b.state.continuationEntries={}];
 for(const [i,change]of changes.entries()){const b=copy().basic;change(b);assert.throws(()=>validateBasicRoute(b),`basic mutation ${i} must fail`);}
});
test('purchase evidence rejects missing policies invalid IDs counters prices balances sources benefits and terminal state',()=>{
 const changes=[p=>p.pop(),p=>p.push(p[0]),p=>p[1]=p[0],p=>p.reverse(),p=>p[0].priority='generic',p=>p[0].buy='true',p=>p[10].retained=false,p=>p[0].records.pop(),p=>p[0].records[1].letter=p[0].records[0].letter,p=>p[0].makes++,p=>{p[0].records[0].makes++;p[0].records[1].makes--;},p=>p[0].records[0].outputs=null,p=>p[0].records[0].outputs.pop(),p=>p[0].records[0].outputs[0].familyId='bird',p=>p[0].records[0].outputs[0].pieceId='unknown',p=>p[0].records[0].outputs[0].tier=5,p=>p[0].records[0].outputs[0].cursor=3,p=>p[0].records[0].balance++,p=>p[0].purchases.pop(),p=>p[0].purchases[0].id='bird-sorter',p=>p[0].purchases[0].price--,p=>p[0].purchases[0].balance++,p=>p[0].purchases[0].milestones++,p=>p[0].purchases[0].revision++,p=>p[0].helpedRequests={},p=>p[0].helpedRequests['rubber-stamp']=['small-impressions-letter-1'],p=>p[9].purchases.push(p[0].purchases[0]),p=>p[0].state=null,p=>p[0].state.coinsSpent--,p=>p[0].state.coinsEarned++,p=>p[0].state.careerId='other-career',p=>p[0].state.purchases['rubber-stamp-sorter'].contentVersion=4,p=>p[0].state.sources['rubber-stamp'].cursor=(p[0].state.sources['rubber-stamp'].cursor+1)%3,p=>p[0].state.milestones.pop()];
 for(const [i,change]of changes.entries()){const p=copy().purchases;change(p);assert.throws(()=>validatePurchaseRoutes(p),`purchase mutation ${i} must fail`);}
});
