import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';import {verifyDispatch,PROPOSED_DESTINATION} from '../full-campaign-gate/dispatch.mjs';import {boundedProcess} from '../full-campaign-gate/bounded-process.mjs';import {eligibleBudget,remainingRunSeconds,JOB_SECONDS,SETUP_SECONDS,PREFLIGHT_SECONDS,MAX_ARTIFACT_BYTES} from '../full-campaign-gate/scope.mjs';
test('proposal push wrapper is isolated, first-attempt, first-failure, bounded, and uploads failure evidence',()=>{const w=JSON.parse(fs.readFileSync('.github/workflows/verify-full-campaign.yml')),j=w.jobs.full_campaign;assert.deepEqual(w.on,{push:{branches:[PROPOSED_DESTINATION.ref.replace('refs/heads/','')]}});assert.equal(j['timeout-minutes'],30);assert.match(j.if,/github.run_attempt == 1/);assert(!JSON.stringify(w).includes('verify/campaign-20261007'));const browser=j.steps.filter(s=>s.run?.startsWith('node full-campaign-gate/run-group.mjs'));assert.equal(browser.length,2);assert(browser.every(s=>s.if===undefined&&!s['continue-on-error']));assert.equal(j.steps.find(s=>s.id==='stage').if,'always()');assert(j.steps.findIndex(s=>s.name==='Require fresh authorization before dependency setup')<j.steps.findIndex(s=>s.uses?.startsWith('actions/setup-node')));const upload=j.steps.find(s=>s.uses?.startsWith('actions/upload-artifact'));assert.equal(upload.with['retention-days'],1);assert.match(upload.if,/always\(\)/);});
test('source build authorization and exact repository ref commit are required before setup',()=>{const env={GITHUB_ACTIONS:'true',GITHUB_REPOSITORY:PROPOSED_DESTINATION.repository,GITHUB_REF:PROPOSED_DESTINATION.ref,GITHUB_EVENT_NAME:'push',GITHUB_RUN_ATTEMPT:'1',GITHUB_RUN_ID:'123456789',GITHUB_SHA:'a'.repeat(40)},message=`Moticos-Reviewed-Source: ${'b'.repeat(64)}\nMoticos-Reviewed-Build: ${'c'.repeat(64)}\nMoticos-Run-Authorization: synthetic-unit-test-only\n`,commit=()=>({head:env.GITHUB_SHA,message}),source=()=>({sourceFingerprint:'b'.repeat(64)});assert.equal(verifyDispatch(env,commit,source).sourceFingerprint,'b'.repeat(64));for(const change of [{GITHUB_RUN_ATTEMPT:'2'},{GITHUB_REF:'refs/heads/main'},{GITHUB_EVENT_NAME:'workflow_dispatch'},{GITHUB_REPOSITORY:'someone/else'}])assert.throws(()=>verifyDispatch({...env,...change},commit,source));assert.throws(()=>verifyDispatch(env,()=>({head:env.GITHUB_SHA,message:message.replace('synthetic-unit-test-only','NOT-AUTHORIZED')}),source));assert.throws(()=>verifyDispatch(env,()=>({head:'d'.repeat(40),message}),source));assert.throws(()=>verifyDispatch(env,()=>({head:env.GITHUB_SHA,message:message.replace(/Moticos-Reviewed-Build:.+\n/,'')}),source));assert.throws(()=>verifyDispatch(env,()=>({head:env.GITHUB_SHA,message:message.replace('b'.repeat(64),'0'.repeat(64))}),source),/does not match verified checkout source/);});
test('both groups cleanup and finalization fit only after bounded setup and preflight',()=>{assert.equal(remainingRunSeconds('full-chromium'),1170);assert.equal(remainingRunSeconds('full-webkit-phone'),555);assert.equal(SETUP_SECONDS+PREFLIGHT_SECONDS+remainingRunSeconds('full-chromium'),1770);assert.equal(JOB_SECONDS,1800);assert.equal(eligibleBudget('full-chromium',630),600000);assert.throws(()=>eligibleBudget('full-chromium',631));assert.throws(()=>eligibleBudget('full-webkit-phone',1246));});
test('bounded child timeout terminates a synthetic process without retry',async()=>{const r=await boundedProcess(process.execPath,['-e','setInterval(()=>{},1000)'],{timeout:100,stdio:'ignore'});assert.equal(r.timedOut,true);assert.notEqual(r.status,0);});
test('failure staging preserves included bytes and enforces artifact and single-failure limits',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'moticos-stage-negative-'));try{const r=path.join(root,'full-browser-results');fs.mkdirSync(r+'/full-chromium/raw',{recursive:true});fs.writeFileSync(r+'/acceptance.json',JSON.stringify({status:'incomplete-or-failed'}));fs.writeFileSync(r+'/full-chromium/raw/failure-one.png','synthetic-original-one');fs.writeFileSync(r+'/full-chromium/raw/failure-two.png','synthetic-original-two');const fd=fs.openSync(r+'/over-cap.log','w');fs.ftruncateSync(fd,MAX_ARTIFACT_BYTES+1);fs.closeSync(fd);const result=spawnSync(process.execPath,[fileURLToPath(new URL('../full-campaign-gate/stage.mjs',import.meta.url))],{cwd:root,encoding:'utf8',timeout:10000});assert.equal(result.status,0,result.stderr);const manifest=JSON.parse(fs.readFileSync(root+'/full-browser-upload/upload-manifest.json'));assert.equal(manifest.status,'incomplete-or-failed');assert.equal(manifest.files.filter(f=>f.included&&f.path.endsWith('.png')).length,1);assert.equal(manifest.files.find(f=>f.path==='over-cap.log').included,false);assert.equal(fs.readFileSync(root+'/full-browser-upload/full-chromium/raw/failure-one.png','utf8'),'synthetic-original-one');assert(fs.statSync(r+'/over-cap.log').size>MAX_ARTIFACT_BYTES);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test('timeout waits for SIGKILL cleanup when the leader exits but a descendant ignores SIGTERM',{timeout:20000},async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'moticos-descendant-negative-')),leaderFile=path.join(root,'leader.pid'),childFile=path.join(root,'child.pid'),termFile=path.join(root,'leader-term');
 const descendant=`const fs=require('node:fs');process.on('SIGTERM',()=>{});fs.writeFileSync(process.argv[1],String(process.pid));setInterval(()=>{},1000);`;
 const leader=`const fs=require('node:fs'),{spawn}=require('node:child_process');fs.writeFileSync(process.argv[1],String(process.pid));process.on('SIGTERM',()=>{fs.writeFileSync(process.argv[3],'leader exited on SIGTERM');process.exit(0);});spawn(process.execPath,['-e',${JSON.stringify(descendant)},process.argv[2]],{stdio:'ignore',detached:false});setInterval(()=>{},1000);`;
 try{
  const started=performance.now(),result=await boundedProcess(process.execPath,['-e',leader,leaderFile,childFile,termFile],{timeout:2000,stdio:'ignore'}),elapsed=performance.now()-started;
  assert.equal(result.timedOut,true);assert.equal(result.status,0,'Leader must exit cleanly on SIGTERM to reproduce the former bug');assert.equal(fs.readFileSync(termFile,'utf8'),'leader exited on SIGTERM');assert(elapsed>=6900,'Leader close must not return before the five-second descendant grace');assert(elapsed<12000,'Cleanup must remain bounded');
  const pid=Number(fs.readFileSync(childFile,'utf8'));let alive=false;try{process.kill(pid,0);alive=true;}catch(error){if(error.code!=='ESRCH')throw error;}if(alive&&process.platform==='linux'){try{const stat=fs.readFileSync(`/proc/${pid}/stat`,'utf8');alive=stat.slice(stat.lastIndexOf(')')+2).split(' ')[0]!=='Z';}catch(error){if(error.code==='ENOENT')alive=false;else throw error;}}assert.equal(alive,false,'SIGTERM-ignoring descendant is still running');assert(['terminated','unconfirmed'].includes(result.groupCleanup));if(result.groupCleanup==='unconfirmed')assert.match(result.error,/could not be confirmed/);
 }finally{
  // Test-owned group only; cleanup also runs if this regression fails early.
  if(fs.existsSync(leaderFile)){const pgid=Number(fs.readFileSync(leaderFile,'utf8'));assert(Number.isSafeInteger(pgid)&&pgid>1,'Invalid test-owned process group');try{process.kill(-pgid,'SIGKILL');}catch(error){if(error.code!=='ESRCH')throw error;}}
  fs.rmSync(root,{recursive:true,force:true});
 }
});

test('well-formed incorrect source trailer fails against the real verified checkout before setup',()=>{const env={GITHUB_ACTIONS:'true',GITHUB_REPOSITORY:PROPOSED_DESTINATION.repository,GITHUB_REF:PROPOSED_DESTINATION.ref,GITHUB_EVENT_NAME:'push',GITHUB_RUN_ATTEMPT:'1',GITHUB_RUN_ID:'123456789',GITHUB_SHA:'a'.repeat(40)},message=`Moticos-Reviewed-Source: ${'0'.repeat(64)}\nMoticos-Reviewed-Build: ${'c'.repeat(64)}\nMoticos-Run-Authorization: synthetic-test-only\n`;assert.throws(()=>verifyDispatch(env,()=>({head:env.GITHUB_SHA,message})),/Reviewed source trailer does not match verified checkout source/);});
