// Exact independently reviewed original-forty visual revisions.
const art = Object.freeze({
  b1: new URL("./art-v1/b1.webp", import.meta.url).href,
  b2: new URL("./art-v1/b2.webp", import.meta.url).href,
  b3: new URL("./art-v1/b3.webp", import.meta.url).href,
  b4: new URL("./art-v1/b4.webp", import.meta.url).href,
  b5: new URL("./art-v1/b5.webp", import.meta.url).href,
  f1: new URL("./art-v1/f1.webp", import.meta.url).href,
  f2: new URL("./art-v1/f2.webp", import.meta.url).href,
  f3: new URL("./art-v1/f3.webp", import.meta.url).href,
  f4: new URL("./art-v1/f4.webp", import.meta.url).href,
  f5: new URL("./art-v1/f5.webp", import.meta.url).href,
  k1: new URL("./art-v1/k1.webp", import.meta.url).href,
  k2: new URL("./art-v1/k2.webp", import.meta.url).href,
  k3: new URL("./art-v1/k3.webp", import.meta.url).href,
  k4: new URL("./art-v1/k4.webp", import.meta.url).href,
  k5: new URL("./art-v1/k5.webp", import.meta.url).href,
  m1: new URL("./art-v1/m1.webp", import.meta.url).href,
  m2: new URL("./art-v1/m2.webp", import.meta.url).href,
  m3: new URL("./art-v1/m3.webp", import.meta.url).href,
  m4: new URL("./art-v1/m4.webp", import.meta.url).href,
  m5: new URL("./art-v1/m5.webp", import.meta.url).href,
  r1: new URL("./art-v1/r1.webp", import.meta.url).href,
  r2: new URL("./art-v1/r2.webp", import.meta.url).href,
  r3: new URL("./art-v1/r3.webp", import.meta.url).href,
  r4: new URL("./art-v1/r4.webp", import.meta.url).href,
  r5: new URL("./art-v1/r5.webp", import.meta.url).href,
  t1: new URL("./art-v1/t1.webp", import.meta.url).href,
  t2: new URL("./art-v1/t2.webp", import.meta.url).href,
  t3: new URL("./art-v1/t3.webp", import.meta.url).href,
  t4: new URL("./art-v1/t4.webp", import.meta.url).href,
  t5: new URL("./art-v1/t5.webp", import.meta.url).href,
  l1: new URL("./art-v1/l1.webp", import.meta.url).href,
  l2: new URL("./art-v1/l2.webp", import.meta.url).href,
  l3: new URL("./art-v1/l3.webp", import.meta.url).href,
  l4: new URL("./art-v1/l4.webp", import.meta.url).href,
  l5: new URL("./art-v1/l5.webp", import.meta.url).href,
  s1: new URL("./art-v1/s1.webp", import.meta.url).href,
  s2: new URL("./art-v1/s2.webp", import.meta.url).href,
  s3: new URL("./art-v1/s3.webp", import.meta.url).href,
  s4: new URL("./art-v1/s4.webp", import.meta.url).href,
  s5: new URL("./art-v1/s5.webp", import.meta.url).href,
});
export const COHESION_REVISIONS = Object.freeze({
  "matching-garden": Object.freeze([
    Object.freeze({ id: "b1", art: art.b1, description: "A black-and-ivory printed bird with a coral chest scrap and teal wing splice.", shortName: "Bird" }),
    Object.freeze({ id: "b2", art: art.b2, description: "The bird’s shifted feather print carries a narrow teal river route.", shortName: "Riverwing" }),
    Object.freeze({ id: "b3", art: art.b3, description: "An offset bird, upright river feather and diagonal key become a wayfinding collage.", shortName: "Wayfinder" }),
    Object.freeze({ id: "b4", art: art.b4, description: "Two printed bird-wing panels slide apart above a key, opening a gate-shaped gap.", shortName: "Gate" }),
    Object.freeze({ id: "b5", art: art.b5, description: "The bird opens into a rising fan of feather slips above its key and a small leafy clipping.", shortName: "Aviary" }),
    Object.freeze({ id: "f1", art: art.f1, description: "An unfurling black-and-ivory printed fern interrupted by a teal paper splice.", shortName: "Fern" }),
    Object.freeze({ id: "f2", art: art.f2, description: "The fern meets the left edge of a printed ivory teacup in an asymmetric collage.", shortName: "Fern Cup" }),
    Object.freeze({ id: "f3", art: art.f3, description: "A sideways fern and a black printed crescent remake the cup as a night garden.", shortName: "Nightgarden" }),
    Object.freeze({ id: "f4", art: art.f4, description: "Offset fern brackets shelter the moon above separated cup-rim and handle fragments.", shortName: "Arbor" }),
    Object.freeze({ id: "f5", art: art.f5, description: "Fern, moon and displaced cup fragments become a wide botanical conservatory collage.", shortName: "Lunar" }),
  ]),
  "moonlit-passage": Object.freeze([
    Object.freeze({ id: "k1", art: art.k1, description: "A black-and-ivory printed round key interrupted by a muted ochre paper splice.", shortName: "Key" }),
    Object.freeze({ id: "k2", art: art.k2, description: "A sideways printed key joins a split botanical frond with a teal splice.", shortName: "Frond Key" }),
    Object.freeze({ id: "k3", art: art.k3, description: "The leafy key lifts its cut shaft like a drawbridge beneath an OVER type scrap.", shortName: "Bridge" }),
    Object.freeze({ id: "k4", art: art.k4, description: "A printed key descends in displaced stair-step sections beside an UP scrap pointing down.", shortName: "Stairkey" }),
    Object.freeze({ id: "k5", art: art.k5, description: "An engraved stair-route threads the key bow and travels from HERE to ELSE.", shortName: "Elsewhere" }),
    Object.freeze({ id: "m1", art: art.m1, description: "A cratered black-and-ivory crescent crossed by a muted cobalt paper splice.", shortName: "Moon" }),
    Object.freeze({ id: "m2", art: art.m2, description: "A printed bird with a coral chest carries a cratered crescent above a BY AIR scrap.", shortName: "Courier" }),
    Object.freeze({ id: "m3", art: art.m3, description: "A split crescent becomes a skiff beneath a printed navigation sail and a tiny coral bird.", shortName: "Skiff" }),
    Object.freeze({ id: "m4", art: art.m4, description: "A displaced crescent balloon hangs above a printed basket while its type scrap says DOWN.", shortName: "Balloon" }),
    Object.freeze({ id: "m5", art: art.m5, description: "An offset crescent sail and orbital strip carry a coral bird across an AIR MAIL sky-vessel.", shortName: "Voyager" }),
  ]),
  "riverside-reverie": Object.freeze([
    Object.freeze({ id: "r1", art: art.r1, description: "Three offset topographic print slips carry a muted cobalt river across ivory paper.", shortName: "Map" }),
    Object.freeze({ id: "r2", art: art.r2, description: "Two unequal map peaks interrupt the river beneath a LOW scrap at the higher summit.", shortName: "Ridge" }),
    Object.freeze({ id: "r3", art: art.r3, description: "Map fragments form a broken crossing while an ACROSS river strip drops through its gap.", shortName: "Crossing" }),
    Object.freeze({ id: "r4", art: art.r4, description: "A cobalt river cascades down four displaced map slips beneath a STILL type scrap.", shortName: "Cascade" }),
    Object.freeze({ id: "r5", art: art.r5, description: "Three stepped map columns gather into a broad river citadel of INLAND and OUT fragments.", shortName: "Citadel" }),
    Object.freeze({ id: "t1", art: art.t1, description: "A black-and-ivory printed teacup carries a geometric diamond band and ochre rim splice.", shortName: "Teacup" }),
    Object.freeze({ id: "t2", art: art.t2, description: "A stepped cup releases one tall printed steam ribbon above a SIP type scrap.", shortName: "Sip" }),
    Object.freeze({ id: "t3", art: art.t3, description: "Two displaced cup halves send opposed steam curls past a HUSH scrap.", shortName: "Chorus" }),
    Object.freeze({ id: "t4", art: art.t4, description: "An upright fan of printed steam opens above the cup’s shifted bowl and handle fragments.", shortName: "Pleats" }),
    Object.freeze({ id: "t5", art: art.t5, description: "Three printed steam ribbons carry DREAM away from an AWAKE cup and its displaced foot and handle.", shortName: "Reverie" }),
  ]),
  "lantern-studio": Object.freeze([
    Object.freeze({ id: "l1", art: art.l1, description: "A squat black-and-ivory lantern print has an open handle, broad cream window and ochre paper splice.", shortName: "Lantern" }),
    Object.freeze({ id: "l2", art: art.l2, description: "The lantern print spreads into a wide accordion of window panels beneath a triangular cap and a FOLD scrap.", shortName: "Glow" }),
    Object.freeze({ id: "l3", art: art.l3, description: "An oversized roof clipping slides left above a four-pane lantern window, with an INSIDE scrap on its outer edge.", shortName: "House" }),
    Object.freeze({ id: "l4", art: art.l4, description: "Two offset lantern windows form a narrow zigzag tower, with an ABOVE scrap on the lower panel.", shortName: "Tower" }),
    Object.freeze({ id: "l5", art: art.l5, description: "Three unequal peaked lantern prints make a broad paper palace with solid ivory windows and paired ROOM scraps.", shortName: "Palace" }),
    Object.freeze({ id: "s1", art: art.s1, description: "A black-and-ivory printed spool carries a broad coral paper band across its engraved thread.", shortName: "Spool" }),
    Object.freeze({ id: "s2", art: art.s2, description: "One tilted engraved ribbon loop rises from a split spool flange, interrupted by teal and an AGAIN scrap.", shortName: "Loop" }),
    Object.freeze({ id: "s3", art: art.s3, description: "Three printed ribbon loops fan above displaced spool parts, with coral and teal splices and a THREE scrap.", shortName: "Bloom" }),
    Object.freeze({ id: "s4", art: art.s4, description: "Broad printed ribbons weave inside an arched loom above split coral spool bases, with an UNDER scrap across the upper band.", shortName: "Loom" }),
    Object.freeze({ id: "s5", art: art.s5, description: "A broad striped ribbon canopy spans two short spool bases and a broken flange, with OVER below and UNDER above.", shortName: "Pavilion" }),
  ]),
});
