import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import * as C from '../src/career/content.js';import * as E from '../src/career/engine.js';import * as C5 from '../src/career/content.v5.js';import * as E5 from '../src/career/engine.v5.js';import {CONTINUATIONS} from '../src/career/volumes.js';import {driver} from '../tests/campaign-browser/save-fixtures.mjs';
const d=driver(),d5=driver(E5,C5),endpoint=JSON.parse(fs.readFileSync(new URL('./v5-complete.frozen.json',import.meta.url))).state;
let old=structuredClone(endpoint);for(const u of C5.UPGRADES)old=d5.act(old,{type:'purchase',upgradeId:u.id,expectedLevel:0});assert.equal(C5.coinBalance(old),110);
const cost=o=>o.requirements.reduce((n,r)=>n+(2*C.CATALOG.pieceOf(r.pieceId).mass-1)*r.quantity,0);
function journey({priority='authored',order='authored',buy=true,late=false,stock=false,conservative=false}={}){
 let s=E.upgradeCareer(conservative?endpoint:old),records=[],purchases=[],benefit=Object.fromEntries(C.FAMILIES.slice(40).map(f=>[f.id,new Set()]));
 if(conservative){s.xp=7810;s.coinsEarned=0;E.validateCareer(s);}
 if(stock){for(const familyId of ['bird','fern'])s=d.act(s,{type:'supply',familyId});[s]=d.acquire(s,'rp2');}
 const purchase=()=>{if(!buy)return;let us=C.availableUpgrades(s).filter(u=>!s.upgrades[u.id]&&u.level<=C.levelDefinition(s).level);if(priority==='cheapest')us.sort((a,b)=>a.price-b.price);if(priority==='reverse')us.reverse();if(priority==='reserve'&&['safe-keeping','paper-duet'].includes(s.chapterId)){const second=s.chapterId==='safe-keeping'?'tied-parcel':'trumpet';if(!s.unlockedSources.includes(second))return;us.sort((a,b)=>(a.familyId===second?-1:b.familyId===second?1:0));}for(const u of us)if(C.coinBalance(s)>=u.price){s=d.act(s,{type:'purchase',upgradeId:u.id,expectedLevel:0});purchases.push({id:u.id,price:u.price,balance:C.coinBalance(s),atLetter:s.milestones.length});}};
 for(const chapter of C.CHAPTERS.slice(20)){s=d.act(s,chapter.number===21?{type:'enter-continuation',boundaryId:CONTINUATIONS[1].id}:{type:'start-next-chapter',chapterId:chapter.id});while(!E.chapterComplete(s)){if(!late)purchase();const available=s.orders.filter(o=>o.origin==='story');if(order==='authored')available.sort((a,b)=>chapter.storyIds.indexOf(a.storyLetterId)-chapter.storyIds.indexOf(b.storyLetterId));else available.sort((a,b)=>(order==='long'?-1:1)*(cost(a)-cost(b)));const o=available[0];assert(o);s=d.act(s,{type:'focus-order',orderId:o.id});let makes=0;while(!E.matchingTiles(s,o)){assert(makes++<100);const h=E.goalHint(s,o.id);if(h.kind==='supply'){const next=E.nextOutput(s,h.familyId);if(next.tier===2&&benefit[h.familyId])benefit[h.familyId].add(o.storyLetterId);s=d.act(s,{type:'supply',familyId:h.familyId});}else if(h.kind==='merge'){const[from,to]=h.pair;s=d.act(s,{type:'move',from,to,tileId:s.board[from].id,targetTileId:s.board[to].id});}else if(h.kind==='cut')s=d.act(s,{type:'cut',at:h.at,tileId:s.board[h.at].id});else assert.fail(h.kind);}s=d.act(s,{type:'complete',orderId:o.id,tileIds:E.matchingTiles(s,o)});records.push({id:o.storyLetterId,makes,balance:C.coinBalance(s)});assert(C.coinBalance(s)>=0);}purchase();}
 return{priority,order,buy,late,stock,conservative,state:s,records,purchases,makes:records.reduce((n,r)=>n+r.makes,0),helpedRequests:Object.fromEntries(Object.entries(benefit).map(([id,set])=>[id,[...set]]))};
}
test('actual runtime purchase priorities and short/long story routes finish without repeat work',()=>{
 const routes=[];for(const [priority,order]of [['authored','authored'],['authored','short'],['authored','long'],['cheapest','short'],['reverse','long'],['reserve','short'],['reserve','long']]){const r=journey({priority,order});assert.equal(r.state.xp,9000);assert.equal(r.state.coinsEarned,3820);assert.equal(r.state.coinsSpent,3690);assert.equal(C.coinBalance(r.state),130);assert.equal(r.purchases.length,8);assert.equal(r.records.length,25);for(const [id,letters]of Object.entries(r.helpedRequests))assert(letters.length>=2,`${priority}/${order}: ${id} benefits only ${letters.length}`);routes.push(r);}
 const noNew=journey({buy:false}),retained=journey({stock:true}),late=journey({late:true}),conservative=journey({buy:false,conservative:true});assert.equal(noNew.makes,314);assert.equal(routes[0].makes,248);assert.equal(late.makes,314);assert.equal(C.coinBalance(late.state),130);assert.equal(C.coinBalance(retained.state),130);assert.equal(conservative.state.xp,8980);assert.equal(conservative.state.coinsEarned,505);assert.equal(conservative.state.coinsSpent,0);assert(E.allAuthoredContentComplete(conservative.state));routes.push(noNew,retained,late,conservative);
 const dir=process.env.MOTICOS_STAGE_B_OUTPUT_ROOT;if(dir){fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/purchase-runtime-routes.json',JSON.stringify(routes,null,2));}console.log(routes.map(r=>({priority:r.priority,order:r.order,buy:r.buy,late:r.late,stock:r.stock,makes:r.makes})));
});
