import test from 'node:test';import assert from 'node:assert/strict';
import {CASES,ORDER,BUDGETS,LIMITS,CONFIG,TARGET,invocation,admit,approval} from './policy.mjs';
import {verifyCombinedCollection} from './collection.mjs';
import {flatten} from '../../gate/results.mjs';
import {validateReports,verifyNodeLog} from './validate.mjs';
import {separatedActions} from './ending-layout.mjs';
import {distinctEndingNote} from '../../src/career/endingPresentation.js';
import {CHAPTER_COPY} from '../../src/career/content.js';import {VOLUMES} from '../../src/career/volumes.js';
const id={sourceFingerprint:'a'.repeat(64),buildFingerprint:'b'.repeat(64),probeFingerprint:'c'.repeat(64),commit:'d'.repeat(40)};
const env={MOTICOS_240_PUBLIC_REPO:'true',GITHUB_ACTIONS:'true',GITHUB_REPOSITORY:TARGET.repository,GITHUB_REF:TARGET.ref,GITHUB_SHA:id.commit,GITHUB_RUN_ATTEMPT:'1',GITHUB_EVENT_NAME:'push',GITHUB_RUN_ID:'123',RUNNER_ENVIRONMENT:'github-hosted',RUNNER_OS:'Linux'};
const accepted=()=>({status:'explicit-owner-approved',scope:'moticos-240-58-cases',...id,profiles:ORDER,limits:LIMITS,authorizationReference:'synthetic-validator-fixture-not-authorization'});
test('58 cases retain historical 22 and all 36 new instances within explicit serial ceiling',()=>{assert.deepEqual(ORDER.map(p=>CASES[p].length),[14,8,18,18]);assert.equal(Object.values(BUDGETS).reduce((a,b)=>a+b,0),5260000);assert.equal(300+600+5260+60+180,6400);assert(LIMITS.jobSeconds>=6400);assert.equal(LIMITS.regularPngs,23+2+16+16);assert.equal(LIMITS.artifactBytes,LIMITS.legacyArtifactBytes+LIMITS.newArtifactBytes);for(const rows of Object.values(CASES))for(const[id,title,ms]of rows){assert(title.length>5);assert(ms>30000);}});
test('exact CLI forbids filtering retries worker changes and unknown profiles',()=>{assert(invocation(['test',`--config=${CONFIG}`,'--list','--reporter=json']).listing);for(const p of ORDER)assert.equal(invocation(['test',`--config=${CONFIG}`,`--project=${p}`]).profile,p);for(const args of [[],['test',`--config=${CONFIG}`,'--grep=B1'],['test',`--config=${CONFIG}`,`--project=${ORDER[0]}`,'--workers=2']])assert.throws(()=>invocation(args));});
test('admission reserves all remaining complete groups and finalization',()=>{assert.equal(admit(ORDER[0],980),600000);assert.throws(()=>admit(ORDER[0],981));assert.throws(()=>admit(ORDER[0],-1));assert.throws(()=>admit('unknown',0));});
test('approval rejects old cycle stale proof wrong target rerun self-hosted and unapproved records',()=>{assert(approval(accepted(),id,env));for(const mutate of [a=>a.status='draft',a=>a.scope='moticos-200',a=>a.sourceFingerprint='f'.repeat(64),a=>a.probeFingerprint='',a=>a.authorizationReference='',a=>a.profiles=[],a=>a.limits={...LIMITS,retries:1}]){const a=structuredClone(accepted());mutate(a);assert.throws(()=>approval(a,id,env));}for(const [k,v]of Object.entries({MOTICOS_240_PUBLIC_REPO:'false',GITHUB_REF:'refs/heads/verify/full-campaign-20261008-r15',GITHUB_RUN_ATTEMPT:'2',RUNNER_ENVIRONMENT:'self-hosted',RUNNER_OS:'macOS',GITHUB_SHA:'e'.repeat(40)}))assert.throws(()=>approval(accepted(),id,{...env,[k]:v}));});
function synthetic(){const config={workers:1,fullyParallel:false,forbidOnly:true,maxFailures:1},reports={},events={},collection={errors:[],config,suites:[]};for(const p of ORDER){const specs=CASES[p].map(([code,title],n)=>({id:'source-spec-'+code,title:code+' '+title,tests:[{projectName:p,expectedStatus:'passed',status:'expected',results:[{status:'passed',retry:0}]}]}));reports[p]={errors:[],config,suites:[{specs}],stats:{unexpected:0,skipped:0,flaky:0,expected:specs.length}};for(const spec of specs){const file=spec.title.startsWith('B')?(Number(spec.title.match(/^B(\d+)/)[1])>=14?'interactions.spec.mjs':'stage-b.spec.mjs'):(p==='full-chromium'?'desktop.spec.mjs':'phone.spec.mjs');let suite=collection.suites.find(s=>s.file===file);if(!suite){suite={title:file,file,column:0,line:0,specs:[],suites:[]};collection.suites.push(suite);}let nested=suite.suites.find(s=>s.specs[0]?.id===spec.id);if(!nested){nested={title:spec.title.split(' ')[0],file,line:1,column:1,specs:[{...structuredClone(spec),file,line:1,column:1,tests:[]}],suites:[]};suite.suites.push(nested);}nested.specs[0].tests.push(...spec.tests.map(t=>({...t,results:[]})));}events[p]=[{event:'begin',workers:1,maxFailures:1,retries:[0],projects:[p]},...specs.flatMap(s=>[{event:'test-begin',id:s.id,project:p,retry:0},{event:'test-end',id:s.id,project:p,retry:0,status:'passed',errors:[]}]),{event:'end',status:'passed',durationMs:10}].map(e=>({...e,...id}));}return{collection,reports,events};}
test('aggregate rejects missing duplicate skipped retried unbound and over-time evidence',()=>{verifyNodeLog('# tests 21\n# pass 21\n# fail 0\n# skipped 0\n# cancelled 0\n# todo 0\n',21);assert.throws(()=>verifyNodeLog('# tests 21\n# fail 1\n',21));const s=synthetic();assert.equal(validateReports(s.collection,s.reports,s.events,id),58);for(const mutate of [s=>s.reports[ORDER[2]].suites[0].specs.pop(),s=>s.events[ORDER[3]].pop(),s=>s.reports[ORDER[0]].stats.skipped=1,s=>s.reports[ORDER[1]].suites[0].specs[0].tests[0].results.push({status:'passed',retry:1}),s=>s.events[ORDER[2]][0].probeFingerprint='wrong',s=>s.events[ORDER[2]].at(-1).durationMs=BUDGETS[ORDER[2]]+1]){const b=structuredClone(s);mutate(b);assert.throws(()=>validateReports(b.collection,b.reports,b.events,id));}});
test('ending actions remain separate on one row or wrapped and reject joined clipped tiny targets',()=>{const button={x:0,y:0,width:150,height:44,scrollWidth:150,clientWidth:150},container={x:0,width:400};assert(separatedActions([button,{...button,x:170}],container));assert(separatedActions([button,{...button,y:56}],container));for(const second of [{...button,x:150},{...button,y:44},{...button,height:20},{...button,x:300},{...button,scrollWidth:200}])assert.throws(()=>separatedActions([button,second],container));});
test('duplicate Stage A ending note is suppressed without suppressing distinct ending or postscript copy',()=>{const ending=CHAPTER_COPY['short-measure'].ending;assert.equal(ending,VOLUMES[1].completionCopy);assert.equal(distinctEndingNote(ending,VOLUMES[1].completionCopy),null);assert.equal(distinctEndingNote(ending,'  '+ending+'  '),null);const different=VOLUMES[2].completionCopy;assert.equal(distinctEndingNote(ending,different),different);assert.equal(distinctEndingNote(ending,'A distinct postscript.'),'A distinct postscript.');});

test('pinned multi-project collection shape accepts shared specs but rejects duplicate project instances and changed coverage',()=>{
 // Synthetic regression fixture follows the pinned reporter structure: nested
 // suites, one source spec, and two project tests under each shared new spec.
 // It is not a claim that this candidate has been collected by Playwright.
 const report=synthetic().collection,rows=flatten(report.suites);assert.equal(rows.length,58);assert.equal(new Set(rows.map(r=>r.id)).size,40);assert.deepEqual(verifyCombinedCollection(report),{kind:'collection-only',cases:58,sourceSpecs:40});
 const shared=r=>r.suites.find(s=>s.file==='stage-b.spec.mjs').suites[0].specs[0];assert.equal(shared(report).tests.length,2);assert.deepEqual(shared(report).tests.map(t=>t.projectName),['stage-b-chromium','stage-b-webkit-phone']);
 for(const mutate of [r=>shared(r).tests.push(structuredClone(shared(r).tests[0])),r=>shared(r).tests.pop(),r=>shared(r).tests[1].projectName='stage-b-chromium',r=>shared(r).title='B1 wrong title',r=>r.suites.find(s=>s.file==='stage-b.spec.mjs').suites[1].specs[0].id=shared(r).id,r=>shared(r).id='',r=>shared(r).tests[0].results=[{status:'passed',retry:0}]]){const broken=structuredClone(report);mutate(broken);assert.throws(()=>verifyCombinedCollection(broken));}
});

test('workflow runner paths are initialized in a step, never unavailable job-env context',async()=>{
 const fs=await import('node:fs'),os=await import('node:os'),path=await import('node:path'),{spawnSync}=await import('node:child_process');
 // GitHub's official workflow schema job-env context excludes runner:
 // https://github.com/actions/languageservices/blob/main/workflow-parser/src/workflow-v1.0.json
 const allowed=new Set(['github','inputs','vars','needs','strategy','matrix','secrets']);
 function jobEnvValid(env){for(const value of Object.values(env))for(const [,expr]of String(value).matchAll(/\$\{\{([\s\S]*?)\}\}/g))for(const [,root]of expr.matchAll(/(?<![\w.])([A-Za-z_][\w-]*)\s*(?:\.|\[)/g))assert(allowed.has(root),`Unavailable job-env context: ${root}`);}
 assert.throws(()=>jobEnvValid({OUTPUT:'${{ runner.temp }}/probe'}));assert.throws(()=>jobEnvValid({OUTPUT:"${{ runner['temp'] }}/probe"}));
 const active=JSON.parse(fs.readFileSync('.github/workflows/verify-full-campaign-240.yml')),proposal=JSON.parse(fs.readFileSync('stage-b-evidence/execution/workflow.proposal.json'));assert.deepEqual({...active,name:proposal.name},proposal);
 for(const w of [active,proposal]){const j=w.jobs.verification;jobEnvValid(j.env);assert(!Object.hasOwn(j.env,'MOTICOS_STAGE_B_PROBE_OUTPUT'));assert(!Object.hasOwn(j.env,'MOTICOS_240_UPLOAD'));assert.equal(j['timeout-minutes'],108);assert.equal(j['runs-on'],'ubuntu-latest');
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'moticos-workflow-env-'));try{const file=path.join(dir,'env'),runner=path.join(dir,'runner with space');const result=spawnSync('bash',['-euo','pipefail','-c',j.steps[0].run],{encoding:'utf8',env:{...process.env,GITHUB_ENV:file,RUNNER_TEMP:runner}});assert.equal(result.status,0,result.stderr);const lines=fs.readFileSync(file,'utf8').trimEnd().split('\n');assert.equal(lines.length,3);assert.match(lines[0],/^MOTICOS_240_EPOCH=\d+$/);assert.equal(lines[1],`MOTICOS_STAGE_B_PROBE_OUTPUT=${runner}/moticos-240-probe`);assert.equal(lines[2],`MOTICOS_240_UPLOAD=${runner}/moticos-240-upload`);}finally{fs.rmSync(dir,{recursive:true,force:true});}}
});

test('nested Playwright config starts the root server and writes only root evidence without a browser',async()=>{
 const fs=await import('node:fs'),os=await import('node:os'),path=await import('node:path'),url=await import('node:url'),net=await import('node:net');
 const {REPO_ROOT,executionPaths,webServerConfig}=await import('./paths.mjs');const {boundedProcess}=await import('../../full-campaign-gate/bounded-process.mjs');
 for(const profile of ORDER){const p=executionPaths(profile),w=webServerConfig();for(const f of [p.raw,p.json,p.progress,p.reporter,p.server,w.cwd])assert(path.isAbsolute(f));assert.equal(w.cwd,REPO_ROOT);assert(p.raw.startsWith(path.join(REPO_ROOT,'full-browser-results')));assert(p.json.startsWith(path.join(REPO_ROOT,'full-browser-results')));assert.equal(w.command,`${JSON.stringify(process.execPath)} ${JSON.stringify(p.server)}`);}
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'moticos-path-fixture-'));let fd;
 try{
  const reserve=net.createServer();await new Promise(ok=>reserve.listen(0,'127.0.0.1',ok));const port=reserve.address().port;await new Promise(ok=>reserve.close(ok));
  const nested=path.join(root,'stage-b-evidence/execution');fs.mkdirSync(nested,{recursive:true});const p=executionPaths('full-chromium',root),server=webServerConfig(root);server.url=`http://127.0.0.1:${port}/career.html`;
  const coreModule=url.pathToFileURL(path.join(REPO_ROOT,'stage-b-evidence/execution/server-core.mjs')).href;const html=path.join(root,'career.html');fs.writeFileSync(html,'<p>synthetic local process fixture, not game evidence</p>');
  fs.writeFileSync(p.server,`import fs from 'node:fs';import{createAssetServer}from ${JSON.stringify(coreModule)};if(process.cwd()!==${JSON.stringify(root)})throw Error('wrong cwd');const s=createAssetServer(new Map([['/career.html',${JSON.stringify(html)}]]));s.listen(${port},'127.0.0.1');process.on('SIGTERM',()=>s.close(()=>process.exit(0)));`);
  const testDir=path.join(root,'fixture-tests');fs.mkdirSync(testDir);const playwright=url.pathToFileURL(path.join(REPO_ROOT,'node_modules/@playwright/test/index.mjs')).href;
  fs.writeFileSync(path.join(testDir,'paths.spec.mjs'),`import{test,expect}from ${JSON.stringify(playwright)};test('synthetic server and paths only; no browser fixture',async()=>{const r=await fetch(${JSON.stringify(server.url)});expect(r.status).toBe(200);expect(await r.text()).toContain('synthetic local process fixture');});`);
  const config={testDir,workers:1,retries:0,globalTimeout:15000,outputDir:p.raw,reporter:[['json',{outputFile:p.json}]],webServer:server};const configFile=path.join(nested,'fixture.config.mjs');fs.writeFileSync(configFile,'export default '+JSON.stringify(config)+';');fd=fs.openSync(path.join(root,'process.log'),'wx');const run=await boundedProcess(process.execPath,[path.join(REPO_ROOT,'node_modules/@playwright/test/cli.js'),'test',`--config=${configFile}`],{cwd:root,timeout:20000,stdio:['ignore',fd,fd]});assert.equal(run.status,0,fs.readFileSync(path.join(root,'process.log'),'utf8'));assert.equal(run.timedOut,false);
  const report=JSON.parse(fs.readFileSync(p.json));assert.equal(report.stats.expected,1);assert.equal(report.stats.unexpected,0);assert(fs.existsSync(path.join(p.raw,'.last-run.json')));assert(!fs.existsSync(path.join(nested,'full-browser-results')));assert.equal(fs.readdirSync(nested).sort().join(','),'fixture.config.mjs,serve.mjs');
 }finally{if(fd!==undefined)fs.closeSync(fd);fs.rmSync(root,{recursive:true,force:true});}
});

test('failed validation preserves diagnostics and safe raw bytes; unsafe evidence never passes',async()=>{
 const fs=await import('node:fs'),os=await import('node:os'),path=await import('node:path');const {finalizeEvidence}=await import('./finalize.mjs');
 for(const unsafe of [false,true]){const root=fs.mkdtempSync(path.join(os.tmpdir(),'moticos-finalizer-fixture-'));try{const results=path.join(root,'results'),execution=path.join(results,'stage-b-execution'),output=path.join(root,'upload');fs.mkdirSync(execution,{recursive:true});const original=Buffer.from('Original startup failure: Cannot find module nested/serve.mjs\n');fs.writeFileSync(path.join(results,'startup.json'),original);if(unsafe)fs.symlinkSync(path.join(root,'outside'),path.join(results,'forbidden-link'));
  const passed=await finalizeEvidence({output,resultsRoot:results,executionRoot:execution,validator:{command:process.execPath,args:['-e',"throw Error('Synthetic Source changed since review checkpoint')"],cwd:root}});assert.equal(passed,false);assert.deepEqual(fs.readFileSync(path.join(results,'startup.json')),original);
  if(unsafe){const summary=JSON.parse(fs.readFileSync(path.join(output,'failure-summary.json')));assert.equal(summary.status,'incomplete-or-failed');assert.match(summary.error,/symlink/i);}else{assert.deepEqual(fs.readFileSync(path.join(output,'startup.json')),original);const summary=JSON.parse(fs.readFileSync(path.join(output,'stage-b-execution/finalizer.json')));assert.equal(summary.status,'incomplete-or-failed');assert.match(summary.validatorOutput,/Source changed/);assert.match(fs.readFileSync(path.join(output,'stage-b-execution/validator.log'),'utf8'),/Source changed/);assert(fs.existsSync(path.join(output,'inventory.json')));}
 }finally{fs.rmSync(root,{recursive:true,force:true});}}
});
