import test from 'node:test';import assert from 'node:assert/strict';
import {CASES,ORDER,BUDGETS,LIMITS,CONFIG,TARGET,invocation,admit,approval} from './policy.mjs';
import {verifyCombinedCollection} from './collection.mjs';
import {flatten} from '../../gate/results.mjs';
import {validateReports,verifyNodeLog} from './validate.mjs';
import {separatedActions} from './ending-layout.mjs';
import {distinctEndingNote} from '../../src/career/endingPresentation.js';
import {CHAPTER_COPY} from '../../src/career/content.js';import {VOLUMES} from '../../src/career/volumes.js';
const id={sourceFingerprint:'a'.repeat(64),buildFingerprint:'b'.repeat(64),probeFingerprint:'c'.repeat(64),commit:'d'.repeat(40)};
const env={MOTICOS_240_PUBLIC_REPO:'true',GITHUB_ACTIONS:'true',GITHUB_REPOSITORY:TARGET.repository,GITHUB_REF:TARGET.ref,GITHUB_SHA:id.commit,GITHUB_RUN_ATTEMPT:'1',GITHUB_EVENT_NAME:'push',GITHUB_RUN_ID:'123',RUNNER_ENVIRONMENT:'github-hosted',RUNNER_OS:'Linux'};
const accepted=()=>({status:'explicit-owner-approved',scope:'moticos-240-58-cases',...id,profiles:ORDER,limits:LIMITS,authorizationReference:'synthetic-validator-fixture-not-authorization'});
test('58 cases retain historical 22 and all 36 new instances within explicit serial ceiling',()=>{assert.deepEqual(ORDER.map(p=>CASES[p].length),[14,8,18,18]);assert.equal(Object.values(BUDGETS).reduce((a,b)=>a+b,0),5260000);assert.equal(300+600+5260+60+180,6400);assert(LIMITS.jobSeconds>=6400);assert.equal(LIMITS.regularPngs,23+2+16+16);assert.equal(LIMITS.artifactBytes,LIMITS.legacyArtifactBytes+LIMITS.newArtifactBytes);for(const rows of Object.values(CASES))for(const[id,title,ms]of rows){assert(title.length>5);assert(ms>30000);}});
test('exact CLI forbids filtering retries worker changes and unknown profiles',()=>{assert(invocation(['test',`--config=${CONFIG}`,'--list','--reporter=json']).listing);for(const p of ORDER)assert.equal(invocation(['test',`--config=${CONFIG}`,`--project=${p}`]).profile,p);for(const args of [[],['test',`--config=${CONFIG}`,'--grep=B1'],['test',`--config=${CONFIG}`,`--project=${ORDER[0]}`,'--workers=2']])assert.throws(()=>invocation(args));});
test('admission reserves all remaining complete groups and finalization',()=>{assert.equal(admit(ORDER[0],980),600000);assert.throws(()=>admit(ORDER[0],981));assert.throws(()=>admit(ORDER[0],-1));assert.throws(()=>admit('unknown',0));});
test('approval rejects old cycle stale proof wrong target rerun self-hosted and unapproved records',()=>{assert(approval(accepted(),id,env));for(const mutate of [a=>a.status='draft',a=>a.scope='moticos-200',a=>a.sourceFingerprint='f'.repeat(64),a=>a.probeFingerprint='',a=>a.authorizationReference='',a=>a.profiles=[],a=>a.limits={...LIMITS,retries:1}]){const a=structuredClone(accepted());mutate(a);assert.throws(()=>approval(a,id,env));}for(const [k,v]of Object.entries({MOTICOS_240_PUBLIC_REPO:'false',GITHUB_REF:'refs/heads/verify/full-campaign-20261008-r15',GITHUB_RUN_ATTEMPT:'2',RUNNER_ENVIRONMENT:'self-hosted',RUNNER_OS:'macOS',GITHUB_SHA:'e'.repeat(40)}))assert.throws(()=>approval(accepted(),id,{...env,[k]:v}));});
function synthetic(){const config={workers:1,fullyParallel:false,forbidOnly:true,maxFailures:1},reports={},events={},collection={errors:[],config,suites:[]};for(const p of ORDER){const specs=CASES[p].map(([code,title],n)=>({id:'source-spec-'+code,title:code+' '+title,tests:[{projectName:p,expectedStatus:'passed',status:'expected',results:[{status:'passed',retry:0}]}]}));reports[p]={errors:[],config,suites:[{specs}],stats:{unexpected:0,skipped:0,flaky:0,expected:specs.length}};for(const spec of specs){const file=spec.title.startsWith('B')?(Number(spec.title.match(/^B(\d+)/)[1])>=14?'interactions.spec.mjs':'stage-b.spec.mjs'):(p==='full-chromium'?'desktop.spec.mjs':'phone.spec.mjs');let suite=collection.suites.find(s=>s.file===file);if(!suite){suite={title:file,file,column:0,line:0,specs:[],suites:[]};collection.suites.push(suite);}let nested=suite.suites.find(s=>s.specs[0]?.id===spec.id);if(!nested){nested={title:spec.title.split(' ')[0],file,line:1,column:1,specs:[{...structuredClone(spec),file,line:1,column:1,tests:[]}],suites:[]};suite.suites.push(nested);}nested.specs[0].tests.push(...spec.tests.map(t=>({...t,results:[]})));}events[p]=[{event:'begin',workers:1,maxFailures:1,retries:[0],projects:[p]},...specs.flatMap(s=>[{event:'test-begin',id:s.id,project:p,retry:0},{event:'test-end',id:s.id,project:p,retry:0,status:'passed',errors:[]}]),{event:'end',status:'passed',durationMs:10}].map(e=>({...e,...id}));}return{collection,reports,events};}
test('aggregate rejects missing duplicate skipped retried unbound and over-time evidence',()=>{verifyNodeLog('# tests 21\n# pass 21\n# fail 0\n# skipped 0\n# cancelled 0\n# todo 0\n',21);assert.throws(()=>verifyNodeLog('# tests 21\n# fail 1\n',21));const s=synthetic();assert.equal(validateReports(s.collection,s.reports,s.events,id),58);for(const mutate of [s=>s.reports[ORDER[2]].suites[0].specs.pop(),s=>s.events[ORDER[3]].pop(),s=>s.reports[ORDER[0]].stats.skipped=1,s=>s.reports[ORDER[1]].suites[0].specs[0].tests[0].results.push({status:'passed',retry:1}),s=>s.events[ORDER[2]][0].probeFingerprint='wrong',s=>s.events[ORDER[2]].at(-1).durationMs=BUDGETS[ORDER[2]]+1]){const b=structuredClone(s);mutate(b);assert.throws(()=>validateReports(b.collection,b.reports,b.events,id));}});
test('ending actions remain separate on one row or wrapped and reject joined clipped tiny targets',()=>{const button={x:0,y:0,width:150,height:44,scrollWidth:150,clientWidth:150},container={x:0,width:400};assert(separatedActions([button,{...button,x:170}],container));assert(separatedActions([button,{...button,y:56}],container));for(const second of [{...button,x:150},{...button,y:44},{...button,height:20},{...button,x:300},{...button,scrollWidth:200}])assert.throws(()=>separatedActions([button,second],container));});
test('duplicate Stage A ending note is suppressed without suppressing distinct ending or postscript copy',()=>{const ending=CHAPTER_COPY['short-measure'].ending;assert.equal(ending,VOLUMES[1].completionCopy);assert.equal(distinctEndingNote(ending,VOLUMES[1].completionCopy),null);assert.equal(distinctEndingNote(ending,'  '+ending+'  '),null);const different=VOLUMES[2].completionCopy;assert.equal(distinctEndingNote(ending,different),different);assert.equal(distinctEndingNote(ending,'A distinct postscript.'),'A distinct postscript.');});

test('pinned multi-project collection shape accepts shared specs but rejects duplicate project instances and changed coverage',()=>{
 // Synthetic regression fixture follows the pinned reporter structure: nested
 // suites, one source spec, and two project tests under each shared new spec.
 // It is not a claim that this candidate has been collected by Playwright.
 const report=synthetic().collection,rows=flatten(report.suites);assert.equal(rows.length,58);assert.equal(new Set(rows.map(r=>r.id)).size,40);assert.deepEqual(verifyCombinedCollection(report),{kind:'collection-only',cases:58,sourceSpecs:40});
 const shared=r=>r.suites.find(s=>s.file==='stage-b.spec.mjs').suites[0].specs[0];assert.equal(shared(report).tests.length,2);assert.deepEqual(shared(report).tests.map(t=>t.projectName),['stage-b-chromium','stage-b-webkit-phone']);
 for(const mutate of [r=>shared(r).tests.push(structuredClone(shared(r).tests[0])),r=>shared(r).tests.pop(),r=>shared(r).tests[1].projectName='stage-b-chromium',r=>shared(r).title='B1 wrong title',r=>r.suites.find(s=>s.file==='stage-b.spec.mjs').suites[1].specs[0].id=shared(r).id,r=>shared(r).id='',r=>shared(r).tests[0].results=[{status:'passed',retry:0}]]){const broken=structuredClone(report);mutate(broken);assert.throws(()=>verifyCombinedCollection(broken));}
});
