import assert from 'node:assert/strict';
import fs from 'node:fs';
import {join,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {identity} from './binding.mjs';
import {CASES,ORDER,ROOT,BUDGETS,LIMITS} from './policy.mjs';
import {verifyStageContracts} from '../../full-campaign-gate/stage-contracts.mjs';
import {verifyCombinedCollection} from './collection.mjs';
import {verifyProfile} from '../../full-campaign-gate/results.mjs';
import {filesUnder,regularBytes,digest,verifyOriginals} from '../../full-campaign-gate/evidence.mjs';
import {expectedOriginals,REQUIRED_SCREENSHOTS} from '../../full-campaign-gate/scope.mjs';
import {verifyPng} from '../../gate/png.mjs';
import {SCREENSHOTS} from '../browser/scope.mjs';
import {CATALOG} from '../../src/career/content.js';
export function verifyNodeLog(log,count){const lines=log.split(String.fromCharCode(10)).map(s=>s.trimEnd());for(const line of ['# tests '+count,'# pass '+count,'# fail 0','# skipped 0','# cancelled 0','# todo 0'])assert.equal(lines.filter(s=>s===line).length,1,'Incomplete or failed Node suite: '+line);}
export function validateReports(collection,reports,events,binding){verifyCombinedCollection(collection);for(const p of ORDER){verifyProfile(p,CASES[p],reports[p],events[p]);for(const event of events[p])for(const k of Object.keys(binding))assert.equal(event[k],binding[k],k);const end=events[p].at(-1);assert(Number.isFinite(end.durationMs)&&end.durationMs<=BUDGETS[p]);}return 58;}
export function validateEvidence(){const id=identity(),json=p=>JSON.parse(fs.readFileSync(p)),reports={},events={};const preflight=json('full-browser-results/preflight.json');assert.equal(preflight.status,'passed');assert.equal(preflight.sourceFingerprint,id.sourceFingerprint);assert.equal(preflight.buildFingerprint,id.buildFingerprint);assert(preflight.elapsedMs<=LIMITS.preflightSeconds*1000);verifyStageContracts('full-browser-results',json('full-browser-results/source.json'),preflight);for(const name of ['stage-b-runtime','stage-b-contracts','collection-240','build-stage-b-probe'])assert.equal(preflight.steps.filter(s=>s.name===name&&s.status===0).length,1);for(const [name,count]of [['stage-b-runtime',17],['stage-b-contracts',23]]){const log=fs.readFileSync('full-browser-results/'+name+'.log','utf8');verifyNodeLog(log,count);}for(const p of ORDER){const root=`${ROOT}/${p}`,launch=json(root+'/launcher.json');assert.equal(launch.status,'passed');assert.equal(launch.exitCode,0);assert.equal(launch.timedOut,false);for(const k of Object.keys(id))assert.equal(launch[k],id[k]);reports[p]=json(root+'/results.json');events[p]=fs.readFileSync(root+'/progress/browser-events.jsonl','utf8').trim().split('\n').map(JSON.parse);}validateReports(json(ROOT+'/collection.json'),reports,events,id);
 const legacy=[];for(const p of ORDER.slice(0,2)){for(const [caseId]of CASES[p]){const record=json(`full-browser-results/${p}/${caseId}.json`);assert.equal(record.caseId,caseId);assert.equal(record.sourceFingerprint,id.sourceFingerprint);assert.equal(record.buildFingerprint,id.buildFingerprint);}legacy.push(...json(`full-browser-results/${p}/screenshots/manifest.json`));}legacy.push(...json('full-browser-results/full-chromium/postcards/manifest.json'));verifyOriginals('full-browser-results',{required:expectedOriginals(),rows:legacy,...id,byteLimit:LIMITS.legacyArtifactBytes,pngLimit:25});
 const expectedPieces=CATALOG.FAMILIES.slice(40).map(f=>f.pieceIds[4]);const receipts=[];
 for(const p of ORDER.slice(2)){const files=filesUnder(`${ROOT}/${p}/raw`),proofs=files.filter(f=>/(^|\/)(proof|interactions)\.json$/.test(f)).map(f=>({path:f,value:JSON.parse(regularBytes(`${ROOT}/${p}/raw`,f))}));assert.equal(proofs.length,18,'Missing native proof');assert.deepEqual(proofs.map(x=>x.value.caseId).sort(),CASES[p].map(x=>x[0]).sort(),'Each case must have its own proof');const postcards=[],screens=[];for(const {path,value:v}of proofs){assert.equal(v.sourceFingerprint,id.sourceFingerprint);assert.equal(v.buildFingerprint,id.buildFingerprint);const dir=path.slice(0,path.lastIndexOf('/')+1);if(v.exported){const r=v.exported;assert(expectedPieces.includes(r.pieceId));const bytes=regularBytes(`${ROOT}/${p}/raw`,dir+r.pieceId+'.png');verifyPng(bytes,[1536,1120]);assert.equal(digest(bytes),r.sha256);assert.equal(bytes.length,r.bytes);assert.deepEqual(v.parity.hashes,[r.sha256,r.sha256,r.sha256]);assert.equal(v.parity.byteEqual,true);assert.equal(v.parity.sameBlob,true);assert.equal(v.parity.sameFilename,true);assert.deepEqual(v.writes,[]);postcards.push(r.pieceId);}for(const r of v.rows??[]){if(r.screenshot){const shot=r.screenshot;assert(SCREENSHOTS.includes(shot.name));const bytes=regularBytes(`${ROOT}/${p}/raw`,dir+shot.name);verifyPng(bytes,shot.dimensions);assert.equal(digest(bytes),shot.sha256);assert.equal(bytes.length,shot.bytes);screens.push(shot.name);}}}assert.deepEqual(postcards.sort(),[...expectedPieces].sort());assert.deepEqual(screens.sort(),[...SCREENSHOTS].sort());receipts.push({profile:p,proofs:proofs.length,postcards,screens});}
 const files=filesUnder('full-browser-results'),rows=files.map(path=>{const b=regularBytes('full-browser-results',path);return{path,bytes:b.length,sha256:digest(b)};});const pngs=rows.filter(r=>r.path.endsWith('.png'));assert.equal(pngs.length,LIMITS.regularPngs,'Missing or unmanifested PNG');assert.equal(rows.filter(r=>r.path.endsWith('trace.zip')).length,0,'Passed run cannot contain failure trace');const total=rows.reduce((n,r)=>n+r.bytes,0);assert(total+65536<=LIMITS.artifactBytes);const fresh=rows.filter(r=>r.path.startsWith('stage-b-execution/')).reduce((n,r)=>n+r.bytes,0);assert(fresh+32768<=LIMITS.newArtifactBytes);assert(total-fresh+32768<=LIMITS.legacyArtifactBytes);return{status:'passed',...id,cases:58,receipts,bytes:total,pngs:pngs.length,inventory:rows};}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){try{const result=validateEvidence();fs.writeFileSync(`${ROOT}/acceptance.json`,JSON.stringify(result,null,2),{flag:'wx'});}catch(error){fs.writeFileSync(`${ROOT}/acceptance.json`,JSON.stringify({status:'incomplete-or-failed',error:error.message}),{flag:'wx'});throw error;}}
