import path from 'node:path';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const evidenceRoot=process.env.MOTICOS_STAGE_A_OUTPUT_ROOT??'../stage-a-r10-review';fs.mkdirSync(evidenceRoot,{recursive:true});
import * as E from '../src/career/engine.js';import * as C from '../src/career/content.js';import * as E4 from '../src/career/engine.v4.js';import * as C4 from '../src/career/content.v4.js';import {CONTINUATION} from '../src/career/volumes.js';import {driver} from '../tests/campaign-browser/save-fixtures.mjs';
const d=driver(),d4=driver(E4,C4),endpoint=JSON.parse(fs.readFileSync(new URL('../campaign-evidence/full-basic-journey.json',import.meta.url))).state;
let old=structuredClone(endpoint);for(const u of C4.UPGRADES)old=d4.act(old,{type:'purchase',upgradeId:u.id,expectedLevel:0});assert.equal(C4.coinBalance(old),190);
const makeCost=o=>o.requirements.reduce((n,r)=>n+(2*C.CATALOG.pieceOf(r.pieceId).mass-1)*r.quantity,0);
function journey({priority='authored',order='authored',buy=true,cursors=false,retained=false}={}){
 let s=E.upgradeCareer(old),records=[],purchases=[],benefit=Object.fromEntries(C.FAMILIES.slice(32).map(f=>[f.id,new Set()]));if(cursors)for(const id of ['bird','fern'])s=d.act(s,{type:'supply',familyId:id});if(retained)[s]=d.acquire(s,'rp2');
 const acquireUpgrades=()=>{if(!buy)return;let us=C.availableUpgrades(s).filter(u=>!s.upgrades[u.id]&&u.level<=C.levelDefinition(s).level);if(priority==='cheapest')us.sort((a,b)=>a.price-b.price);if(priority==='zipper')us.sort((a,b)=>(a.familyId==='zipper'?-1:b.familyId==='zipper'?1:0));for(const u of us)if(C.coinBalance(s)>=u.price){const before=s.revision;s=d.act(s,{type:'purchase',upgradeId:u.id,expectedLevel:0});purchases.push({id:u.id,revision:before+1,milestones:s.milestones.length,price:u.price,balance:C.coinBalance(s)});}};
 for(const chapter of C.CHAPTERS.slice(16)){s=d.act(s,chapter.number===17?{type:'enter-continuation',boundaryId:CONTINUATION.id}:{type:'start-next-chapter',chapterId:chapter.id});while(!E.chapterComplete(s)){acquireUpgrades();let available=s.orders.filter(o=>o.origin==='story');if(order!=='authored')available.sort((a,b)=>(order==='long'?-1:1)*(makeCost(a)-makeCost(b)));const o=available[0];assert(o);s=d.act(s,{type:'focus-order',orderId:o.id});let makes=0,outputs=[];while(!E.matchingTiles(s,o)){assert(makes++<100);const hint=E.goalHint(s,o.id);if(hint.kind==='supply'){const p=E.nextOutput(s,hint.familyId);outputs.push({familyId:hint.familyId,pieceId:p.id,tier:p.tier,cursor:s.sources[hint.familyId].cursor});if(p.tier===2&&benefit[p.familyId])benefit[p.familyId].add(o.storyLetterId);s=d.act(s,{type:'supply',familyId:hint.familyId});}else if(hint.kind==='merge'){const[from,to]=hint.pair;s=d.act(s,{type:'move',from,to,tileId:s.board[from].id,targetTileId:s.board[to].id});}else if(hint.kind==='cut')s=d.act(s,{type:'cut',at:hint.at,tileId:s.board[hint.at].id});else assert.fail(hint.kind);}s=d.act(s,{type:'complete',orderId:o.id,tileIds:E.matchingTiles(s,o)});records.push({letter:o.storyLetterId,makes,outputs,balance:C.coinBalance(s)});assert(C.coinBalance(s)>=0);}acquireUpgrades();}
 return {priority,order,buy,cursors,retained,state:s,records,purchases,helpedRequests:Object.fromEntries(Object.entries(benefit).map(([id,set])=>[id,[...set]])),makes:records.reduce((n,r)=>n+r.makes,0)};
}
test('actual eager purchase priorities and story orders buy all eight from story income without repeats',()=>{
 const routes=[];for(const priority of ['authored','cheapest','zipper'])for(const order of ['authored','short','long']){const r=journey({priority,order});assert.equal(r.state.xp,7830);assert.equal(r.state.coinsEarned,3315);assert.equal(r.state.coinsSpent,3205);assert.equal(C.coinBalance(r.state),110);assert.equal(r.purchases.length,8);for(const [family,letters]of Object.entries(r.helpedRequests))assert(letters.length>=2,`${priority}/${order}: ${family} helps only ${letters.length}`);routes.push(r);}
 const existing=journey({buy:false}),retained=journey({cursors:true,retained:true});assert.equal(existing.state.xp,7830);assert.equal(C.coinBalance(existing.state),760);assert.equal(C.coinBalance(retained.state),110);routes.push(existing,retained);fs.writeFileSync(path.join(evidenceRoot,'purchase-runtime-routes.json'),JSON.stringify(routes,null,2));console.log(routes.map(r=>({priority:r.priority,order:r.order,buy:r.buy,retained:r.retained,makes:r.makes})));});
