// Historical Stage A acceptance remains pinned to its independent v5 reader.
import path from 'node:path';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
const evidenceRoot=process.env.MOTICOS_STAGE_A_OUTPUT_ROOT??'../stage-a-r10-review';fs.mkdirSync(evidenceRoot,{recursive:true});
import * as E from '../src/career/engine.v5.js';import * as C from '../src/career/content.v5.js';import * as E4 from '../src/career/engine.v4.js';import * as C4 from '../src/career/content.v4.js';import * as E3 from '../src/career/engine.v3.js';import * as C3 from '../src/career/content.v3.js';import * as E2 from '../src/career/engine.v2.js';import * as C2 from '../src/career/content.v2.js';
import {createCareerSession} from '../src/career/session.v5.js';import {createCareerSession as oldSession} from '../src/career/session.v4.js';import {CONTINUATION,VOLUMES,collectionScope} from '../src/career/volumes.v5.js';import {progressCue,completedLetter} from '../src/career/feedback.js';
import {driver,storageHarness,legacyFixtures,oldEngine} from '../tests/campaign-browser/save-fixtures.mjs';
const read=name=>JSON.parse(fs.readFileSync(new URL(name,import.meta.url))),proposal=read('./proposal.frozen.json'),original=read('./original-113.frozen.json');
const endpoint=read('../campaign-evidence/full-basic-journey.json').state,d=driver(E,C),d4=driver(E4,C4),clone=structuredClone;
const migrate=()=>E.upgradeCareer(endpoint),enter=s=>d.act(s,{type:'enter-continuation',boundaryId:CONTINUATION.id});
const outstanding=s=>[...s.orders,...s.heldOrders,...(s.suspendedStory?[s.suspendedStory]:[])];
let basic=null,entries=new Map(),ends=new Map(),after=new Map();
function route(){if(basic)return clone(basic);let s=migrate(),records=[];for(const chapter of C.CHAPTERS.slice(16)){s=chapter.number===17?enter(s):d.act(s,{type:'start-next-chapter',chapterId:chapter.id});entries.set(chapter.id,clone(s));for(const id of chapter.storyIds){const o=s.orders.find(o=>o.storyLetterId===id);assert(o,id);const before=s.revision;s=d.ready(s,o);const makes=s.revision-before;s=d.act(s,{type:'complete',orderId:o.id,tileIds:E.matchingTiles(s,o)});records.push({id,makes,xp:s.xp,coins:s.coinsEarned});after.set(id,clone(s));assert(E.originalVolumeComplete(s));}assert(E.chapterComplete(s));ends.set(chapter.id,clone(s));}basic={state:s,records};return clone(basic);}
function unchanged(a,b,keys){for(const key of keys)assert.deepEqual(b[key],a[key],key);}

test('reviewed proposal, original113, all40 asset bytes and original terminal definition remain exact',()=>{
 assert.equal(crypto.createHash('sha256').update(fs.readFileSync(new URL('./proposal.frozen.json',import.meta.url))).digest('hex'),'ab3aec91bda2c3a141cbcd14ed6a6cbc894d8e14d3d1aa7b61f292a81b02aee6');
 assert.equal(C.CATALOG.PIECES.length,200);assert.equal(C.STORY_ORDERS.length,139);assert.deepEqual(C.STORY_ORDERS.slice(0,113),original.story);assert.deepEqual(C.CONTENT_PACKS[4],read('../campaign-evidence/content-pack-4.frozen.json').pack);assert.deepEqual(C.CHAPTERS.slice(0,16),C4.CHAPTERS);assert.equal(C.CHAPTERS[15].nextId,null);assert.deepEqual(C.CHAPTER_COPY['sound-advice'],C4.CHAPTER_COPY['sound-advice']);
 for(const key of ['story','ordinary','levels','upgrades'])assert.deepEqual(C.CONTENT_PACKS[5][key].slice(C.CONTENT_PACKS[4][key].length),proposal.additions[key]);
 assert.equal(C.UPGRADES.find(u=>u.id==='zipper-sorter').price,80);for(const a of read('./art.frozen.json')){const b=fs.readFileSync(fileURLToPath(C.CATALOG.pieceOf(a.pieceId).art));assert.equal(b.length,a.bytes);assert.equal(crypto.createHash('sha256').update(b).digest('hex'),a.sha256);}
});

test('v1-v4 validation precedes pure, idempotent migration; new state and Undo records stay dormant',()=>{
 const legacy=legacyFixtures(),inputs=[...Object.values(legacy),E2.createCareer('stage-v2'),driver(E2,C2).route(5,'stage-v2-progress'),E3.createCareer('stage-v3'),driver(E3,C3).route(5,'stage-v3-progress'),E4.createCareer('stage-v4'),d4.route(5,'stage-v4-progress'),endpoint];
 for(const old of inputs){const before=JSON.stringify(old),s=E.upgradeCareer(old);assert.equal(JSON.stringify(old),before);assert.deepEqual(E.upgradeCareer(s),s);assert.equal(s.schemaVersion,5);assert.deepEqual(s.receipts,E4.upgradeCareer(old).receipts);assert.deepEqual(s.continuationEntries,{});unchanged(old,s,['board','xp','coinsEarned','coinsSpent','revision','nextOrderSeq','nextTileSeq','discoveries','sound','largeText']);if(old.schemaVersion===4)unchanged(old,s,['orders','heldOrders','suspendedStory','resumedOptionalId','focusedOrderId','activeSourceIds','chapterEntryVersions','purchases','storyCompletions']);
 for(const part of [s,...s.history])for(const id of C.FAMILIES.slice(32).map(f=>f.id)){assert.deepEqual(part.sources[id],{sorter:0,cursor:0});assert.deepEqual(part.material[id],{initial:0,generated:0,delivered:0,recycled:0});}assert(s.unlockedSources.every(id=>C4.FAMILIES.some(f=>f.id===id)));}
 const bad=clone(endpoint);bad.material.bird.generated++;assert.throws(()=>E.upgradeCareer(bad));
 const complete=migrate();assert(E.originalVolumeComplete(complete));assert(E.currentVolumeComplete(complete));assert(!E.allAuthoredContentComplete(complete));assert.equal(collectionScope(complete).total,160);assert.match(progressCue(complete).detail,/All 113 original/);
});

test('explicit continuation parks exact promises, retains desk/cursors/stock, and rejects repeated or stale entry',()=>{
 for(const desk of [false,true]){let old=clone(endpoint);if(desk)old=d4.act(old,{type:'purchase',upgradeId:'order-desk',expectedLevel:0});old=d4.act(old,{type:'purchase',upgradeId:'bird-sorter',expectedLevel:0});old=d4.act(old,{type:'supply',familyId:'bird'});const s=E.upgradeCareer(old),orders=clone(s.orders),next=enter(s);unchanged(s,next,['board','material','sources','xp','coinsEarned','coinsSpent','purchases','upgrades','discoveries','storyCompletions','receipts']);assert.equal(next.history.length,0);assert.equal(next.orders.filter(o=>o.origin==='story').length,2);for(const o of orders)assert.deepEqual(outstanding(next).find(n=>n.id===o.id),o);if(desk)assert(next.orders.some(o=>o.slot===2&&orders.some(n=>n.id===o.id)));assert.deepEqual(E.upgradeCareer(next),next);const again=E.reduceCareer(next,E.commandFor(next,{type:'enter-continuation',boundaryId:CONTINUATION.id}));assert(!again.ok);assert.deepEqual(again.state,next);assert(!E.reduceCareer(next,E.commandFor(s,{type:'enter-continuation',boundaryId:CONTINUATION.id})).ok);
 const id=next.heldOrders[0].id,resumed=d.act(next,{type:'resume-optional',orderId:id});assert(resumed.suspendedStory);assert(!E.reduceCareer(resumed,E.commandFor(resumed,{type:'enter-continuation',boundaryId:CONTINUATION.id})).ok);const returned=d.act(E.upgradeCareer(resumed),{type:'return-to-story'});assert.deepEqual(returned.orders,next.orders);}
 assert(!E.reduceCareer(E.createCareer('premature'),E.commandFor(E.createCareer('premature'),{type:'enter-continuation',boundaryId:CONTINUATION.id})).ok);
});

test('actual no-purchase no-repeat route completes26 with exact rewards and operation count',()=>{const r=route();assert.equal(r.state.xp,7830);assert.equal(r.state.coinsEarned,3315);assert.equal(r.state.coinsSpent,0);assert.equal(r.state.milestones.length,139);assert.equal(r.records.length,26);assert.equal(r.records.reduce((n,r)=>n+r.makes,0),356);assert(E.allAuthoredContentComplete(r.state));assert.equal(collectionScope(r.state).total,200);fs.writeFileSync(path.join(evidenceRoot,'basic-runtime-route.json'),JSON.stringify(r,null,2));});

test('source eligibility follows the actual two-letter, one-letter and entry gates despite high XP',()=>{route();for(const [chapter,family,count]of [['small-impressions','fountain-pen',2],['second-look','camera',1],['short-measure','thimble',2]]){let s=clone(entries.get(chapter));s.xp=99999;E.validateCareer(s);assert(!s.unlockedSources.includes(family));assert(!E.reduceCareer(s,E.commandFor(s,{type:'supply',familyId:family})).ok);for(let n=1;n<=count;n++){s=d.complete(s,s.orders.find(o=>o.storyLetterId===`${chapter}-letter-${n}`));assert.equal(s.unlockedSources.includes(family),n===count);}if(count===1)assert.match(progressCue(entries.get(chapter)).cue,/One letter/);}assert(entries.get('loose-ends').unlockedSources.includes('safety-pin'));assert(entries.get('loose-ends').unlockedSources.includes('zipper'));});

test('quantity-versus-merge choices consume distinct actual tiles and leave competing stock',()=>{route();for(const [chapter,stock,leave]of [['small-impressions',['im3','im3','pn2'],'pn2'],['loose-ends',['sp2','sp2','zp3','cj3'],'cj3'],['short-measure',['ru3','ru3','th3'],'th3']]){let s=clone(after.get(`${chapter}-letter-3`));const reserved=new Set();for(const pieceId of stock){let id;[s,id]=d.acquire(s,pieceId,reserved);reserved.add(id);}const a=s.orders.find(o=>o.storyLetterId===`${chapter}-letter-4`),b=s.orders.find(o=>o.storyLetterId===`${chapter}-letter-5`);assert(a&&b);const focused=d.act(s,{type:'focus-order',orderId:b.id});unchanged(s,focused,['board','material','xp','coinsEarned']);const ids=E.matchingTiles(s,a);assert(ids&&new Set(ids).size===ids.length);const sent=d.act(s,{type:'complete',orderId:a.id,tileIds:ids});assert(sent.board.some(t=>t?.pieceId===leave));assert(!E.matchingTiles(sent,b));assert(!E.reduceCareer(sent,E.commandFor(sent,{type:'complete',orderId:a.id,tileIds:ids})).ok);const other=d.complete(clone(s),b);assert(other.milestones.includes(b.storyLetterId));assert(!other.milestones.includes(a.storyLetterId));}});

test('full-board entry and failed supply preserve material/cursors, with free reversible recovery',()=>{route();for(const before of [migrate(),...ends.values()].slice(0,4)){let s=clone(before);while(s.board.includes(null))s=d.act(s,{type:'supply',familyId:'bird',basic:true});const next=s.chapterId==='sound-advice'?enter(s):d.act(s,{type:'start-next-chapter',chapterId:C.chapterDefinition(s).nextId});unchanged(s,next,['board','material','sources']);const failed=E.reduceCareer(next,E.commandFor(next,{type:'supply',familyId:next.activeSourceIds[0]}));assert(!failed.ok);assert.deepEqual(failed.state,next);const recycled=d.act(next,{type:'recycle',at:0,tileId:next.board[0].id,confirmed:true});const undone=d.act(recycled,{type:'undo'});unchanged(next,undone,['board','sources','material','xp','coinsEarned']);}});

test('all40 candidate pictures are reachable; seven optional final postscripts grant no reward',()=>{let s=route().state;for(const p of C.CATALOG.PIECES.slice(160)){[s]=d.acquire(s,p.id);assert(s.discoveries.includes(p.id));for(let i=0;i<25;i++)if(s.board[i])s=d.act(s,{type:'recycle',at:i,tileId:s.board[i].id,confirmed:true});}assert(VOLUMES[1].pieceIds.every(id=>s.discoveries.includes(id)));assert.equal(s.xp,7830);assert.equal(s.coinsEarned,3315);assert.equal(s.milestones.length,139);assert.equal(proposal.additions.postscripts.length,7);const tier5=new Set(proposal.additions.story.flatMap(o=>o.requirements).filter(r=>C.CATALOG.pieceOf(r.pieceId).tier===5).map(r=>r.pieceId));assert.deepEqual([...tier5],['cm5']);});

test('original and continuation replay preserve pinned letter versions and reward zero',()=>{const saved=JSON.stringify(route().state);for(const [id,v]of [['garden-letter-1',1],['sound-advice-letter-8',4],['loose-ends-letter-4',5]]){let replay=E.createReplay(id,'stage-replay-'+v,v);const o=replay.orders[0];assert.deepEqual(o.requirements,C.orderTemplate(id,v).requirements);replay=d.complete(replay,o);assert.equal(replay.xp,0);assert.equal(replay.coinsEarned,0);assert.equal(replay.orders.length,0);}assert.equal(JSON.stringify(route().state),saved);assert.equal(completedLetter(migrate(),'garden-letter-1').id,'garden-letter-1');});

test('single writer races entry exactly once and old v4 reader protects schema5 bytes',async()=>{const h=storageHarness(endpoint),a=createCareerSession(h),b=createCareerSession(h);await Promise.all([a.open(),b.open()]);const before=a.snapshot().state,action=E.commandFor(before,{type:'enter-continuation',boundaryId:CONTINUATION.id});const results=await Promise.all([a.commit(action),b.commit(action)]);assert.equal(results.filter(r=>r.ok).length,1);assert.equal(results.filter(r=>r.code==='stale').length,1);const saved=h.map.get(C.STORAGE_KEY);assert.equal(JSON.parse(saved).chapterId,'small-impressions');const old=oldSession(h),opened=await old.open();assert.equal(opened.status,'practice');assert.equal(h.map.get(C.STORAGE_KEY),saved);const current=createCareerSession(h);assert.equal((await current.open()).status,'saved');});

test('entry write denial, read denial, oversize and future saves preserve the exact prior bytes',async()=>{
 const s=migrate(),h=storageHarness(s),session=createCareerSession(h);await session.open();const bytes=h.map.get(C.STORAGE_KEY);h.flags.failWrite=true;const r=await session.commit(E.commandFor(s,{type:'enter-continuation',boundaryId:CONTINUATION.id}));assert.equal(r.status,'practice');assert.equal(h.map.get(C.STORAGE_KEY),bytes);assert.match(r.warning,/temporary/);
 for(const raw of [' '.repeat(1000001),JSON.stringify({...s,schemaVersion:6})]){const denied=storageHarness(raw),opened=await createCareerSession(denied).open();assert.equal(opened.status,'practice');assert.equal(denied.map.get(C.STORAGE_KEY),raw);}
 const denyRead=storageHarness(s,{failRead:true});assert.equal((await createCareerSession(denyRead).open()).status,'practice');assert.equal(denyRead.map.get(C.STORAGE_KEY),JSON.stringify(s));
 const oversized=clone(s);oversized.padding='x'.repeat(999700-JSON.stringify(oversized).length);const big=storageHarness(oversized),writer=createCareerSession(big);const opened=await writer.open(),old=big.map.get(C.STORAGE_KEY);const tooBig=await writer.commit(E.commandFor(opened.state,{type:'enter-continuation',boundaryId:CONTINUATION.id}));assert.equal(tooBig.status,'practice');assert.equal(big.map.get(C.STORAGE_KEY),old);
});

test('new schema5 careers still earn the unchanged original finale before any continuation claim',()=>{let s=E.createCareer('fresh-volume-contract');for(const chapter of C.CHAPTERS.slice(0,16)){if(chapter.number>1)s=d.act(s,{type:'start-next-chapter',chapterId:chapter.id});for(const id of chapter.storyIds)s=d.complete(s,s.orders.find(o=>o.storyLetterId===id));}assert.equal(s.xp,6495);assert.equal(s.coinsEarned,2745);assert.equal(s.milestones.length,113);assert(E.originalVolumeComplete(s));assert(E.campaignComplete(s));assert(!E.allAuthoredContentComplete(s));assert.deepEqual(s.continuationEntries,{});assert.equal(collectionScope(s).total,160);assert(s.unlockedSources.every(id=>C4.FAMILIES.some(f=>f.id===id)));});

test('concurrent purchase, held selection and delivery each commit once; stale IDs stay dead after receipt pruning',async()=>{
 route();let s=clone(after.get('small-impressions-letter-2'));const upgrade=C.availableUpgrades(s).find(u=>u.id==='rubber-stamp-sorter');assert(upgrade);let h=storageHarness(s),a=createCareerSession(h),b=createCareerSession(h);await Promise.all([a.open(),b.open()]);let command=E.commandFor(s,{type:'purchase',upgradeId:upgrade.id,expectedLevel:0});let results=await Promise.all([a.commit(command),b.commit(command)]);assert.equal(results.filter(r=>r.ok).length,1);let current=JSON.parse(h.map.get(C.STORAGE_KEY));assert.equal(current.purchases[upgrade.id].price,85);
 const held=current.heldOrders[0],staleId=held.id;await Promise.all([a.refresh(),b.refresh()]);command=E.commandFor(current,{type:'resume-optional',orderId:staleId});results=await Promise.all([a.commit(command),b.commit(command)]);assert.equal(results.filter(r=>r.ok).length,1);current=JSON.parse(h.map.get(C.STORAGE_KEY));assert(current.suspendedStory);current=d.ready(current,current.orders.find(o=>o.id===staleId));h=storageHarness(current);a=createCareerSession(h);b=createCareerSession(h);await Promise.all([a.open(),b.open()]);command=E.commandFor(current,{type:'complete',orderId:staleId,tileIds:E.matchingTiles(current,current.orders.find(o=>o.id===staleId))});results=await Promise.all([a.commit(command),b.commit(command)]);assert.equal(results.filter(r=>r.ok).length,1);assert.equal(JSON.parse(h.map.get(C.STORAGE_KEY)).suspendedStory,null);
 let end=route().state;end=d.act(end,{type:'purchase',upgradeId:'order-desk',expectedLevel:0});const id=end.heldOrders[0].id;end=d.act(end,{type:'resume-optional',orderId:id});end=d.complete(end,end.orders.find(o=>o.id===id));for(let n=0;n<41;n++){let o=end.orders.find(o=>o.origin==='ordinary');assert(o);end=d.complete(end,o);}assert(!end.receipts.some(r=>r.id===id));assert(!outstanding(end).some(o=>o.id===id));const failed=E.reduceCareer(end,E.commandFor(end,{type:'resume-optional',orderId:id}));assert(!failed.ok);assert.deepEqual(failed.state,end);
});
