import {it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {runIdentity,currentCatalog} from '../scripts/currentCandidate.mjs';
const env={GITHUB_ACTIONS:'true',GITHUB_REPOSITORY:'BlindAnatomist/moticos-for-cynthia',GITHUB_REF:'refs/heads/verify/current-160-20261006',GITHUB_EVENT_NAME:'push',GITHUB_SHA:'a'.repeat(40),GITHUB_RUN_ID:'123',GITHUB_RUN_ATTEMPT:'1',GITHUB_WORKFLOW_REF:'BlindAnatomist/moticos-for-cynthia/.github/workflows/verify-expansion-160.yml@refs/heads/verify/current-160-20261006'};
it('requires actual complete current-run identity fields',()=>{expect(runIdentity(env).runId).toBe('123');for(const key of Object.keys(env))expect(()=>runIdentity({...env,[key]:''})).toThrow();expect(()=>runIdentity({...env,GITHUB_RUN_ATTEMPT:'2'})).toThrow();});
it('derives 160 unique IDs and hashes from current catalog files',async()=>{const rows=await currentCatalog();expect(rows).toHaveLength(160);expect(new Set(rows.map(r=>r.id)).size).toBe(160);expect(new Set(rows.map(r=>r.sha256)).size).toBe(160);expect(rows.every(r=>r.sourceFile.startsWith('src/')&&r.bytes>0)).toBe(true);});
it('keeps behavior contract free of persisted source and scenario hash pins',()=>{const contract=JSON.parse(readFileSync('tests/verification/expansion160-coverage-contract.json'));expect(contract.sourceFingerprint).toBeUndefined();expect(contract.testFiles.every(r=>Object.keys(r).join()==='path')).toBe(true);expect(contract.cases).toHaveLength(99);});
it('has only one exact branch push trigger with repository/ref/event/attempt guards and one build of each variant',()=>{const w=JSON.parse(readFileSync('.github/workflows/verify-expansion-160.yml'));expect(w.on).toEqual({push:{branches:['verify/current-160-20261006']}});for(const job of Object.values(w.jobs)){expect(job.if).toContain("github.repository == 'BlindAnatomist/moticos-for-cynthia'");expect(job.if).toContain("github.ref == 'refs/heads/verify/current-160-20261006'");expect(job.if).toContain("github.event_name == 'push'");expect(job.if).toContain('github.run_attempt == 1');}const preflight=readFileSync('scripts/preflightExpansion160.sh','utf8');expect(preflight.match(/vite build --outDir /g)).toHaveLength(4);expect(preflight).not.toContain('npm run');expect(preflight).not.toContain('stampCollage');expect(preflight).not.toContain('stampExpansion.mjs');});
it('loads the configured append-only reporter and current validation dependencies',async()=>{const {default:Reporter}=await import('../scripts/expansion160ProgressReporter.mjs');expect(typeof new Reporter().onBegin).toBe('function');expect(typeof (await import('../scripts/validateMatching.mjs')).allFamilyInventories).toBe('function');});

it('retains bounded independent diagnosis and four actual upload-identity receipts',()=>{const w=JSON.parse(readFileSync('.github/workflows/verify-expansion-160.yml'));const steps=w.jobs.browser.steps;expect(steps.find(s=>s.id==='diagnosis').run).toContain('packExpansion160Diagnosis.py');expect(steps.find(s=>s.id==='diagnosis_upload').with.name).toContain('diagnosis');for(const job of Object.values(w.jobs))expect(job.steps.find(s=>s.id==='artifact_receipt')).toBeDefined();expect(readFileSync('scripts/recordCurrentArtifacts.mjs','utf8')).toContain('32768');});

it('rejects wrong repository, ref, event, workflow ref and run attempt before current-run stamping',()=>{for(const [key,value] of [['GITHUB_REPOSITORY','other/repo'],['GITHUB_REF','refs/heads/main'],['GITHUB_EVENT_NAME','workflow_dispatch'],['GITHUB_EVENT_NAME','pull_request'],['GITHUB_EVENT_NAME','schedule'],['GITHUB_WORKFLOW_REF',env.GITHUB_WORKFLOW_REF.replace('current-160','other')],['GITHUB_RUN_ATTEMPT','2']])expect(()=>runIdentity({...env,[key]:value})).toThrow();});
