import {collectionEvents,journeyEvents,geometryFixture} from './expansion160EvidenceFixtures.js';
import {it,expect} from 'vitest';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {verifyVisualEvidence,digest} from '../scripts/verifyExpansion160Coverage.mjs';
import {makePng} from './expansion160PngFixtures.js';
const bytes=fs.readFileSync('tests/verification/expansion160-coverage-contract.json'),contract=JSON.parse(bytes),profile='chromium-desktop',provenance={runCommit:'a'.repeat(40),manifestSha256:'b'.repeat(64),identity:{repository:'fixture/repo',runCommit:'a'.repeat(40),runId:'1',runAttempt:1,workflowRef:'fixture/repo/.github/workflows/verify-expansion-160.yml@refs/heads/test'}};
const nativePng=makePng(1280,720),compactPng=makePng(320,568),exportsById=Object.fromEntries(contract.postcardIds.map((id,i)=>[id,makePng(1536,1120,i)]));
const manifest={identity:provenance.identity,sourceFingerprint:'d'.repeat(64),catalogAssets:contract.envelopePieces.flatMap(e=>e.pieceIds).map(id=>({id,file:`${id}.webp`,sha256:'c'.repeat(64),bytes:10}))};
function fixture(fn){const root=fs.mkdtempSync(path.join(os.tmpdir(),'moticos-160-visual-proof-'));const put=(name,data)=>{fs.mkdirSync(path.dirname(path.join(root,name)),{recursive:true});fs.writeFileSync(path.join(root,name),data);};const png=nativePng;
 try{for(const id of [...contract.pieceIds,...contract.idleFinalIds.map(id=>`idle-${id}`)])for(const size of ['native','320x568']){const prefix=`screenshots/${profile}-matching-layout-${id}-${size}`;put(prefix+'.png',size==='native'?nativePng:compactPng);put(prefix+'.json',JSON.stringify(geometryFixture(size==='native'?{width:1280,height:720}:{width:320,height:568},id.replace(/^idle-/,''))));}for(const envelope of contract.envelopePieces){const events=collectionEvents(envelope,profile);for(const event of events.filter(e=>e.event==='image-decoded')){event.observedSha256='c'.repeat(64);event.observedBytes=10;}for(const e of events.filter(e=>e.state))e.state.viewport={width:1280,height:720};for(const event of events.filter(e=>e.event==='capture-after'||e.event==='chooser-after'))put(event.path.replace('expansion160-test-results/',''),png);put(`progress/${profile}-${envelope.id}-collection.jsonl`,events.map(e=>JSON.stringify(e)).join('\n'));if(contract.journeyEnvelopeIds.includes(envelope.id)){const journey=journeyEvents(envelope,profile);for(const e of journey.filter(e=>e.event==='export-complete')){const bytes=exportsById[e.id];e.sha256=digest(bytes);e.bytes=bytes.length;put(`review/${profile}-${e.id}-export.png`,bytes);}for(const e of journey.filter(e=>e.event==='stage-complete'||e.event==='export-complete'))e.art={source:`http://127.0.0.1:4197/${e.id}.webp`,naturalWidth:768,naturalHeight:768,pieceId:e.id,assetSha256:'c'.repeat(64),observedSha256:'c'.repeat(64),observedBytes:10};put(`progress/${profile}-${envelope.id}-journey.jsonl`,journey.map(e=>JSON.stringify(e)).join('\n'));}}put(`storage-views/${profile}-restored-board.png`,png);for(const name of ['collage','collections'])put(`environment/${profile}-${name}.json`,JSON.stringify({profile,viewport:{width:1280,height:720},deviceScaleFactor:1,browserVersion:'fixture 1',playwrightVersion:'1.61.1',nodeVersion:'v24.19.0',runCommit:'a'.repeat(40),identity:provenance.identity,sourceFingerprint:manifest.sourceFingerprint,caseContractSha256:digest(bytes),buildManifestSha256:'b'.repeat(64),guardedArguments:['test','--config=playwright.expansion160.config.js',`--project=${profile}`],browserBudgetMs:960000}));fn(root,put,png);}finally{fs.rmSync(root,{recursive:true,force:true});}}
it('requires 160 earned PNGs, 160 geometry records, 32 idle views/records, full collections and paired choosers, one legacy view and exact runtime provenance',()=>fixture(root=>{const proof=verifyVisualEvidence(contract,profile,root,provenance,manifest);expect(proof.files).toHaveLength(435);expect(proof.collectionViewports).toBe(32);}));
it.each([`screenshots/${profile}-matching-layout-rc1-native.png`,`screenshots/${profile}-matching-layout-tw5-320x568.json`,`storage-views/${profile}-collection-expansion-fair-weather-0.png`,`environment/${profile}-collage.json`,`screenshots/${profile}-matching-layout-idle-rc5-native.png`])('rejects missing evidence %s',name=>fixture(root=>{fs.unlinkSync(path.join(root,name));expect(()=>verifyVisualEvidence(contract,profile,root,provenance,manifest)).toThrow();}));
it('rejects PNG-header impostors',()=>fixture((root,put)=>{put(`screenshots/${profile}-matching-layout-rc1-native.png`,Buffer.alloc(128));expect(()=>verifyVisualEvidence(contract,profile,root,provenance,manifest)).toThrow();}));
it.each(['sourceFingerprint','caseContractSha256','guardedArguments','browserBudgetMs','runCommit','buildManifestSha256'])('rejects wrong provenance %s',key=>fixture((root,put)=>{const file=`environment/${profile}-collage.json`,record=JSON.parse(fs.readFileSync(path.join(root,file)));record[key]=key==='guardedArguments'?['test','--grep=only']:key==='browserBudgetMs'?960001:'0'.repeat(64);put(file,JSON.stringify(record));expect(()=>verifyVisualEvidence(contract,profile,root,provenance,manifest)).toThrow();}));

it.each([['png',()=>makePng(20,20)],['json',()=>JSON.stringify({fixture:true})],['json',()=>JSON.stringify({...geometryFixture({width:320,height:568},'rc1'),viewport:{width:1280,height:720,scrollX:0,scrollY:0}})]])('rejects wrong screenshot dimensions or malformed geometry %s',(extension,value)=>fixture((root,put)=>{put(`screenshots/${profile}-matching-layout-rc1-320x568.${extension}`,value());expect(()=>verifyVisualEvidence(contract,profile,root,provenance,manifest)).toThrow();}));
