import {it,expect} from 'vitest';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {verifyVisualEvidence} from '../scripts/verifyExpansion120Coverage.mjs';
const contract=JSON.parse(fs.readFileSync('tests/verification/expansion120-coverage-contract.json')),profile='chromium-desktop';
function fixture(fn){const root=fs.mkdtempSync(path.join(os.tmpdir(),'moticos-120-visual-proof-'));const put=(name,bytes)=>{fs.mkdirSync(path.dirname(path.join(root,name)),{recursive:true});fs.writeFileSync(path.join(root,name),bytes);};const png=Buffer.alloc(128);Buffer.from('89504e470d0a1a0a','hex').copy(png);png.writeUInt32BE(390,16);png.writeUInt32BE(844,20);
 try{for(const id of contract.pieceIds)for(const size of ['native','320x568']){const prefix=`screenshots/${profile}-matching-layout-${id}-${size}`;put(prefix+'.png',png);put(prefix+'.json','{"fixture":true}');}for(const id of contract.envelopeIds)put(`storage-views/${profile}-collection-${id}.png`,png);for(const name of ['restored-board','temporary-board-quota-warning'])put(`storage-views/${profile}-${name}.png`,png);for(const name of ['collage','save-capacity'])put(`environment/${profile}-${name}.json`,JSON.stringify({profile,browserVersion:'fixture 1',playwrightVersion:'1.61.1',nodeVersion:'v24.19.0',runCommit:'a'.repeat(40),guardedArguments:['test','--config=playwright.expansion120.config.js',`--project=${profile}`],browserBudgetMs:540000}));fn(root,put,png);}finally{fs.rmSync(root,{recursive:true,force:true});}}
it('requires all 80 earned views, 80 geometry records, twelve collections, two storage views and two runtime records',()=>fixture(root=>{const p=verifyVisualEvidence(contract,profile,root);expect(p.files).toHaveLength(176);expect(p.collectionViewports).toBe(12);}));
it.each(['screenshots/chromium-desktop-matching-layout-hs1-native.png','screenshots/chromium-desktop-matching-layout-sh5-320x568.json','storage-views/chromium-desktop-collection-expansion-return-mail.png','environment/chromium-desktop-collage.json'])('rejects missing required evidence %s',name=>fixture(root=>{fs.unlinkSync(path.join(root,name));expect(()=>verifyVisualEvidence(contract,profile,root)).toThrow();}));
it('rejects invalid image bytes and unbound runtime command metadata',()=>fixture((root,put,png)=>{const p='screenshots/chromium-desktop-matching-layout-hs1-native.png';put(p,'not a PNG');expect(()=>verifyVisualEvidence(contract,profile,root)).toThrow();put(p,png);put('environment/chromium-desktop-collage.json',JSON.stringify({profile,browserVersion:'1',playwrightVersion:'1',nodeVersion:'v24',runCommit:'a'.repeat(40),guardedArguments:['test','--grep=only'],browserBudgetMs:540000}));expect(()=>verifyVisualEvidence(contract,profile,root)).toThrow();}));
