import{it,expect}from'vitest';
import{readFileSync}from'node:fs';
import{verifyFocusedPostcardState}from'../scripts/expansion200FocusedPostcardEvidence.mjs';
import{verifyPostcardState}from'../scripts/expansion200PostcardEvidence.mjs';
import{validateContract,verifyPinnedCases,verifyCollection,verifyCompleted,verifyAggregate}from'../scripts/verifyExpansion200PostcardCoverage.mjs';
import{runIdentity,publicPathAllowed200}from'../scripts/currentCandidate200Postcards.mjs';
import{verifyProfileBudget}from'../scripts/verifyExpansion200PostcardProfileBudget.mjs';
const contract=JSON.parse(readFileSync('tests/verification/expansion200-postcards-contract.json','utf8')),profile='webkit-iphone-13',cases=contract.cases.filter(c=>c.project===profile);
const visual=rect=>({rect,visible:true,unclipped:true,centerHit:true,hitTests:[true,true,true,true,true]});
function fixture(){const rect={x:24,y:130,width:260,height:270};return{viewport:{width:320,height:568},dialogCount:1,modal:true,bodyOverflow:'hidden',pageScrollX:0,pageScrollY:0,documentWidth:320,documentHeight:568,dialog:{x:12,y:12,width:296,height:544},dialogScrollTop:0,title:'Lasting Impression',image:{...visual(rect),complete:true,objectFit:'contain',objectPosition:'50% 50%',naturalWidth:768,naturalHeight:768},caption:{...visual({x:24,y:412,width:260,height:60}),textRect:{x:24,y:412,width:250,height:55},scrollWidth:260,clientWidth:260},header:{x:20,y:20,width:280,height:86},heading:{...visual({x:20,y:20,width:280,height:26}),text:'Your correspondence',textRect:{x:20,y:20,width:210,height:24}},controls:[{name:'Back to board',rect:{x:210,y:54,width:84,height:44}},{name:'Download postcard',rect:{x:20,y:488,width:132,height:44}},{name:'Share postcard',rect:{x:160,y:488,width:140,height:44}}].map(c=>({...c,...visual(c.rect),enabled:true,textRect:{x:c.rect.x+4,y:c.rect.y+10,width:c.rect.width-8,height:20}}))};}
it.each(['art','actions'])('accepts explicit complete heading evidence for %s',view=>expect(verifyFocusedPostcardState(fixture(),{width:320,height:568},'Lasting Impression',view).heading).toBe('Your correspondence'));
it('rejects the old unmeasured heading gap while old art/title/action guards alone pass',()=>{const s=fixture();s.heading.rect.height=75;s.heading.textRect.height=75;expect(()=>verifyPostcardState(s,s.viewport,s.title,'art')).not.toThrow();expect(()=>verifyFocusedPostcardState(s,s.viewport,s.title,'art')).toThrow(/overlaps/);delete s.heading;expect(()=>verifyFocusedPostcardState(s,s.viewport,s.title,'art')).toThrow();});
it.each(['missing','wrong-title','outside-header','clipped-glyphs','covered','offscreen-header','malformed','false-hit','truthy-hit','clipped-action-text'])('rejects bad header or action evidence: %s',kind=>{const s=fixture();({missing:()=>delete s.heading,'wrong-title':()=>s.heading.text='Your corres','outside-header':()=>s.heading.rect.x=0,'clipped-glyphs':()=>s.heading.textRect.width=310,covered:()=>s.heading.centerHit=false,'offscreen-header':()=>s.header.x=-1,malformed:()=>s.heading.rect.height=null,'false-hit':()=>s.heading.hitTests[4]=false,'truthy-hit':()=>s.heading.hitTests[4]='yes','clipped-action-text':()=>s.controls[0].textRect.width=130}[kind])();expect(()=>verifyFocusedPostcardState(s,s.viewport,s.title,'art')).toThrow();});
const report=(items=cases,completed=false)=>({errors:[],stats:{expected:4,unexpected:0,flaky:0,skipped:0},suites:[{specs:items.map(c=>({id:c.id,file:c.file,title:c.title,tests:[{projectName:c.project,expectedStatus:'passed',status:completed?'expected':'skipped',results:completed?[{status:'passed',retry:0,errors:[]}]:[]}]}))}]});
const event=(c,type)=>({...c,event:type,file:'/runner/tests/expansion200-postcards/'+c.file,title:['',c.project,c.file,c.title],retry:0,...(type==='test-end'?{status:'passed',expectedStatus:'passed',errors:[]}: {})});
const events=()=>[{event:'begin',tests:4,workers:1,maxFailures:1,retries:[0],projects:[profile]},...cases.flatMap(c=>[event(c,'test-begin'),event(c,'test-end')]),{event:'end',status:'passed'}];
it('freezes only the12 focused cases and24 cards, not historical99 journeys',()=>{validateContract(contract);verifyPinnedCases(contract);expect(verifyCollection(contract,report(contract.cases),'all').cases).toBe(12);expect(contract.postcardIds).toHaveLength(24);expect(()=>verifyCollection(contract,report(cases.slice(1)),profile)).toThrow();});
it('accepts exactly four terminal zero-retry presentation passes',()=>expect(verifyCompleted(contract,profile,events(),report(cases,true)).uniqueCases).toBe(4));
it.each(['failed','timedOut','interrupted','skipped'])('rejects %s even with a successful report',status=>{const e=events();e[2].status=status;expect(()=>verifyCompleted(contract,profile,e,report(cases,true))).toThrow();});
it('rejects retry, missing result and altered identities',()=>{for(const mutate of [e=>e[2].retry=1,e=>e.splice(2,1),e=>e[2].id='different',e=>e[0].workers=2,e=>e.pop()]){const e=events();mutate(e);expect(()=>verifyCompleted(contract,profile,e,report(cases,true))).toThrow();}});
it('requires all three profiles on one build for a12-case72-export aggregate',()=>{const proofs=['webkit-iphone-13','webkit-iphone-large','chromium-desktop'].map(p=>({profile:p,status:'passed',runCommit:'a'.repeat(40),sourceFingerprint:'b'.repeat(64),uniqueCases:4,retries:0,failed:0,skipped:0,exports:Array(24).fill({}),results:contract.cases.filter(c=>c.project===p).map(c=>event(c,'test-end'))}));expect(verifyAggregate(contract,proofs).uniqueCases).toBe(12);expect(()=>verifyAggregate(contract,proofs.slice(1))).toThrow();expect(()=>verifyAggregate(contract,proofs.map((p,i)=>i?p:{...p,runCommit:'c'.repeat(40)}))).toThrow();});
it.each([['chromium-desktop',2],['webkit-iphone-13',6],['webkit-iphone-large',6]])('retains bounded evidence for %s',(p,n)=>{const proof={kind:'browser',complete:true,partCount:n,uploadUpperBound:n*24*1024*1024,partLimitBytes:24*1024*1024};expect(verifyProfileBudget(p,proof).partCap).toBe(n);expect(()=>verifyProfileBudget(p,{...proof,partCount:n+1})).toThrow();});
it('isolates the new branch and retains50-minute/no-rerun boundaries',()=>{const w=JSON.parse(readFileSync('.github/workflows/verify-expansion-200-postcards.yml','utf8'));expect(w.on).toEqual({push:{branches:['verify/postcards-200-20261007']}});expect(w.permissions).toEqual({contents:'read'});expect(w.jobs.build['timeout-minutes']+3*w.jobs.browser['timeout-minutes']).toBe(50);expect(w.jobs.browser.strategy['fail-fast']).toBe(true);expect(w.jobs.browser.strategy['max-parallel']).toBe(1);for(const job of Object.values(w.jobs)){expect(job.if).toContain('github.run_attempt == 1');for(const s of job.steps.filter(s=>s.uses==='actions/upload-artifact@v4'))expect(s.with['retention-days']).toBe(1);}expect(()=>runIdentity({GITHUB_ACTIONS:'true',GITHUB_REPOSITORY:'BlindAnatomist/moticos-for-cynthia',GITHUB_REF:'refs/heads/verify/current-200-20261007'})).toThrow();expect(publicPathAllowed200('PRIVATE_200_REVIEW.md')).toBe(false);expect(publicPathAllowed200('src/matching/expansion200/matching.css')).toBe(true);});
it('keeps the compact repair within200-only CSS and leaves source images contained',()=>{const css=readFileSync('src/matching/expansion200/matching.css','utf8');expect(css).toContain('@media (max-width: 430px)');expect(css).toContain('@media (max-width: 380px)');expect(css).toContain('grid-template-columns: minmax(0, 1fr)');expect(css).toContain('height: min(52dvh, 570px)');expect(css).not.toContain('object-fit: cover');const e=readFileSync('tests/expansion200-postcards/postcard-evidence.js','utf8');expect(e).toContain('heading:heading?');expect(e).toContain('textRect:textRect(heading)');expect(e).toContain('expect(after).toEqual(state)');});

it.each(['cover','fill','none'])('rejects cropped or distorted image-fit %s',fit=>{const s=fixture();s.image.objectFit=fit;expect(()=>verifyFocusedPostcardState(s,s.viewport,s.title,'art')).toThrow();});
