import {test,expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {verifyPng} from '../../scripts/expansion160Png.mjs';
import {CASES,titleFor} from '../../scripts/careerGateScope.mjs';
import {CATALOG,STORY_ORDERS,STORAGE_KEY,LOCK_NAME} from '../../src/career/content.js';
import {createCareer,matchingTiles,chapterComplete} from '../../src/career/engine.js';
import {act,ready,route,upgraded,threeOrders,allFinal,allArt} from './fixtures.mjs';
import * as h from './helpers.mjs';
const cases=CASES['career-chromium'];
function check(index,fn){const[id,title,timeout]=cases[index];test(titleFor(id,title),async({page,context},info)=>{const args={page,context};test.setTimeout(timeout);await h.instrumentation(args.context);const errors=[];args.context.on('page',p=>p.on('pageerror',e=>errors.push(String(e))));args.page.on('pageerror',e=>errors.push(String(e)));await fn(args,info);expect(errors).toEqual([]);await h.audit(args.page);});}
check(0,async({page},info)=>{
 await h.open(page);let s=await h.read(page);expect([s.xp,s.coinsEarned,s.board.filter(Boolean).length,s.orders.length]).toEqual([0,0,8,1]);
 const xp=[10,20,45,80,140,190,250,370,510],coins=[5,10,20,35,60,80,105,155,215];
 for(let i=0;i<9;i++){s=await h.read(page);const order=s.orders.find(o=>o.storyLetterId===STORY_ORDERS[i].id);expect(order).toBeTruthy();s=await h.send(page,order);expect([s.xp,s.coinsEarned]).toEqual([xp[i],coins[i]]);if(i===3)expect(s.orders.map(o=>o.storyLetterId)).toEqual(['garden-letter-5','garden-letter-6']);if(i===4)s=await h.buy(page,'bird-sorter');if(i===7)s=await h.buy(page,'order-desk');}
 s=await h.buy(page,'fern-sorter');expect([s.xp,s.coinsEarned,s.coinsSpent,s.coinsEarned-s.coinsSpent]).toEqual([510,215,200,15]);expect(chapterComplete(s)).toBe(true);expect(s.orders.some(o=>o.origin==='ordinary'&&o.xp===0)).toBe(true);await expect(page.locator('.career-finished')).toBeVisible();await h.snapshot(page,info,'chapter-finish');
 const saved=await h.bytes(page);await page.getByRole('button',{name:'Open your correspondence'}).click();await h.snapshot(page,info,'correspondence');await page.locator('.career-letter-list article').first().getByRole('button',{name:/Practice/}).click();await expect(page.locator('.career-practice-banner')).toContainText('0 XP · 0 coins');await page.locator('[data-career-cell="0"]').click();await page.locator('[data-career-cell="1"]').click();await page.locator('.career-send').click();await expect(page.getByRole('status').last()).toContainText('Practice letter complete');await page.getByRole('button',{name:'Return to career'}).click();expect(await h.bytes(page)).toBe(saved);await page.reload();expect(await h.bytes(page)).toBe(saved);await h.record(info,'route',{xp,coins,final:await h.read(page)});
});
check(1,async({page},info)=>{
 await h.open(page);await h.seed(page,upgraded());await h.draw(page,'bird');await h.draw(page,'bird');const before=await h.read(page);expect(before.sources.bird.cursor).toBe(2);let[s,id]=await h.draw(page,'bird');expect(CATALOG.pieceOf(s.board.find(t=>t?.id===id).pieceId).tier).toBe(2);s=await h.undo(page);expect(s.board).toEqual(before.board);expect(s.sources).toEqual(before.sources);expect(s.material).toEqual(before.material);await page.reload();expect((await h.read(page)).sources).toEqual(before.sources);
 const cursor=(await h.read(page)).sources.bird.cursor;await h.draw(page,'bird',{basic:true});expect((await h.read(page)).sources.bird.cursor).toBe(cursor);[,id]=await h.make(page,'b2');s=await h.read(page);const at=s.board.findIndex(t=>t?.id===id);await page.locator(`[data-career-cell="${at}"]`).click();const cut=await h.changed(page,s,()=>page.getByRole('button',{name:'Cut',exact:true}).click());expect(cut.material).toEqual(s.material);await h.undo(page);
 await h.seed(page,allFinal());const full=await h.bytes(page);await page.locator('.career-producer.bird .career-supply').click();await expect(page.getByRole('status').last()).toContainText('full');expect(await h.bytes(page)).toBe(full);await page.locator('[data-career-cell="0"]').click();await page.getByRole('button',{name:'Recycle',exact:true}).click();await page.getByRole('button',{name:'Keep picture'}).click();expect(await h.bytes(page)).toBe(full);await page.getByRole('button',{name:'Recycle',exact:true}).click();s=await h.read(page);await h.changed(page,s,()=>page.getByRole('button',{name:'Recycle picture',exact:true}).click());await h.undo(page);expect((await h.read(page)).board).toEqual(JSON.parse(full).board);await page.locator('[data-career-cell="0"]').click();await page.getByRole('button',{name:'Recycle',exact:true}).click();s=await h.read(page);await h.changed(page,s,()=>page.getByRole('button',{name:'Recycle picture',exact:true}).click());await h.draw(page,'fern');s=await h.read(page);expect([s.xp,s.coinsEarned]).toEqual([0,0]);await h.record(info,'cursor-recovery',s);
});
check(2,async({page,context},info)=>{
 await h.open(page);const other=await context.newPage();await h.open(other);const before=await h.read(page);let result=await h.race(page,other,()=>page.locator('.career-producer.bird .career-supply').click(),()=>other.locator('.career-producer.fern .career-supply').click());expect(result.board.filter(Boolean).length).toBe(before.board.filter(Boolean).length+1);
 await page.reload();await other.reload();await page.locator('[data-career-cell="0"]').click();result=await h.race(page,other,()=>page.locator('[data-career-cell="24"]').click(),()=>other.locator('.career-producer.fern .career-supply').click());await h.record(info,'native-races',{revision:result.revision,state:result});
 // Pin a real DOM drag intent, change the committed board in the other tab,
 // then deliver its drop. This specifically tests interrupted drag identity.
 await page.reload();await other.reload();const state=await h.read(page),from=state.board.findIndex(Boolean),to=state.board.findIndex(t=>!t);const transfer=await page.evaluateHandle(()=>new DataTransfer());await page.locator(`[data-career-cell="${from}"]`).dispatchEvent('dragstart',{dataTransfer:transfer});await h.draw(other,'bird');await expect.poll(async()=>(await h.read(page)).revision).toBe(state.revision+1);const changed=await h.bytes(page);await page.locator(`[data-career-cell="${to}"]`).dispatchEvent('drop',{dataTransfer:transfer});expect(await h.bytes(page)).toBe(changed);await h.audit(other);await other.close();
});
check(3,async({page,context},info)=>{
 await h.open(page);const seeded=ready(createCareer('fixture-native-send'));await h.seed(page,seeded);const other=await context.newPage();await h.open(other);const order=seeded.orders[0];const result=await h.race(page,other,()=>page.locator(`[data-order-id="${order.id}"] .career-send`).click(),()=>other.locator(`[data-order-id="${order.id}"] .career-send`).click());expect([result.xp,result.coinsEarned,result.milestones.length,result.receipts.length]).toEqual([10,5,1,1]);expect(result.orders.some(o=>o.id===order.id)).toBe(false);expect(result.board.some(t=>matchingTiles(seeded,order).includes(t?.id))).toBe(false);await page.reload();await other.reload();expect((await h.read(page)).xp).toBe(10);expect((await h.read(other)).xp).toBe(10);
 await h.seed(page,ready(createCareer('fixture-double-send')));const before=await h.read(page);await page.locator('.career-send').dblclick();await expect.poll(async()=>(await h.read(page)).xp).toBe(10);expect((await h.read(page)).receipts.length).toBe(1);expect((await h.read(page)).revision).toBe(before.revision+1);await page.reload();expect((await h.read(page)).xp).toBe(10);await h.record(info,'native-payment',await h.read(page));await h.audit(other);await other.close();
});
check(4,async({page,context},info)=>{
 await h.open(page);await h.seed(page,route(5));const other=await context.newPage();await h.open(other);await page.locator('.career-shop-button').click();await other.locator('.career-shop-button').click();const buyer=p=>p.locator('.career-upgrades article').filter({has:p.getByRole('heading',{name:'Bird sorter I',exact:true})}).getByRole('button',{name:'Buy · 50 coins'});const before=await h.read(page);let result=await h.race(page,other,()=>buyer(page).click(),()=>buyer(other).click());expect(result.coinsSpent).toBe(50);expect(result.upgrades['bird-sorter']).toBe(1);expect(result.sources.bird.cursor).toBe(0);expect(result.board).toEqual(before.board);expect(result.history).toEqual([]);await h.close(page);await h.close(other);await page.reload();await other.reload();
 let fixture=route(5);fixture=ready(fixture,fixture.orders[0]);await h.seed(page,fixture);await other.reload();await page.locator('.career-shop-button').click();result=await h.race(page,other,()=>buyer(page).click(),()=>other.locator(`[data-order-id="${fixture.orders[0].id}"] .career-send`).click());expect(result.revision).toBe(fixture.revision+1);expect(result.coinsSpent===50||result.xp>fixture.xp).toBe(true);expect(result.coinsSpent===50&&result.xp>fixture.xp).toBe(false);await h.close(page);await page.reload();await h.record(info,'native-purchase',result);await h.audit(other);await other.close();
});
check(5,async({page},info)=>{
 await h.open(page);
 const report=[];
 for(const fault of ['quota','read','lock','future']){await page.evaluate(()=>window.name='');await h.seed(page,ready(route(5)));const original=await h.bytes(page);let protectedBytes=original;if(fault==='future'){protectedBytes=JSON.stringify({...JSON.parse(original),schemaVersion:999});await page.evaluate(async({lock,key,value})=>{await navigator.locks.request(lock,()=>{window.__fixtureWrite=true;localStorage.setItem(key,value);window.__fixtureWrite=false;});},{lock:LOCK_NAME,key:STORAGE_KEY,value:protectedBytes});}else await page.evaluate(mode=>window.name=`career-fault:${mode}`,fault);await page.reload();
  if(fault==='quota'){await expect(page.locator('.career-shell')).toHaveAttribute('data-save-status','saved');await page.locator('.career-send').first().click();}
  await expect(page.locator('.career-shell')).toHaveAttribute('data-save-status','practice');await expect(page.locator('.career-save-warning')).toContainText('Unsaved practice');const actual=await page.evaluate(key=>window.__rawStorage.get.call(localStorage,key),STORAGE_KEY);expect(actual).toBe(protectedBytes);report.push({fault,preservedSha256:createHash('sha256').update(actual).digest('hex'),status:'practice'});await page.evaluate(()=>window.name='');if(fault==='future'){await page.evaluate(async({lock,key,value})=>{await navigator.locks.request(lock,()=>{window.__fixtureWrite=true;localStorage.setItem(key,value);window.__fixtureWrite=false;});},{lock:LOCK_NAME,key:STORAGE_KEY,value:original});}await page.reload();await expect(page.locator('.career-shell')).toHaveAttribute('data-save-status','saved');expect(await h.bytes(page)).toBe(original);
 }
 // The same write fault at a purchase boundary preserves both funds and upgrade.
 await h.seed(page,route(5));const purchaseBytes=await h.bytes(page);await page.evaluate(()=>window.name='career-fault:quota');await page.reload();await page.locator('.career-shop-button').click();await page.locator('.career-upgrades article').first().getByRole('button',{name:'Buy · 50 coins'}).click();await expect(page.locator('.career-shell')).toHaveAttribute('data-save-status','practice');expect(await h.bytes(page)).toBe(purchaseBytes);await page.evaluate(()=>window.name='');await page.reload();await h.record(info,'failure-modes',report);
});
check(6,async({page},info)=>{
 await h.open(page);const start=await h.read(page);await page.locator('[data-career-cell="0"]').focus();await page.keyboard.press('Space');await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');await expect.poll(async()=>(await h.read(page)).revision).toBe(start.revision+1);await page.keyboard.press('Escape');await expect(page.locator('[aria-pressed="true"][data-career-cell]')).toHaveCount(0);await page.getByRole('button',{name:'Undo',exact:true}).focus();await page.keyboard.press('Enter');await expect.poll(async()=>(await h.read(page)).revision).toBe(start.revision+2);
 for(const selector of ['.career-collection-button','.career-shop-button','button[aria-label="How to play"]']){const opener=page.locator(selector);await opener.focus();await page.keyboard.press('Enter');await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Shift+Tab');expect(await page.evaluate(()=>document.querySelector('dialog').contains(document.activeElement))).toBe(true);await page.keyboard.press('Escape');await expect(opener).toBeFocused();}
 await page.getByRole('button',{name:'How to play'}).click();let s=await h.read(page);await h.changed(page,s,()=>page.getByRole('button',{name:'Use larger text'}).click());await h.close(page);await page.reload();await expect(page.locator('.career-shell')).toHaveClass(/is-large-text/);expect((await h.read(page)).sound).toBe(false);await page.emulateMedia({reducedMotion:'reduce'});expect(await page.locator('.career-cell').first().evaluate(el=>getComputedStyle(el).transitionDuration)).toBe('0s');await h.record(info,'large-text',await h.noOverflow(page));await h.snapshot(page,info,'large-text');
});
check(7,async({page},info)=>{
 await h.open(page);const layouts=[];for(const size of [{width:1366,height:768},{width:1440,height:900}]){await page.setViewportSize(size);for(const kind of ['fresh','three']){await h.seed(page,kind==='fresh'?createCareer(`fixture-desktop-${size.width}`):threeOrders());if(kind==='three'){expect((await h.read(page)).orders.length).toBe(3);await expect(page.locator('.career-order')).toHaveCount(3);}layouts.push({size,kind,...await h.noOverflow(page,{desktop:true})});await h.snapshot(page,info,`${size.width}-${kind}`);}}
 await h.seed(page,allArt());const images=await h.imageProof(page);await page.locator('.career-collection-button').click();await expect(page.locator('.career-collection-grid button:enabled')).toHaveCount(10);const collectionImages=await h.imageProof(page);await h.close(page);await page.locator('[data-career-cell="0"]').click();await page.getByRole('button',{name:'View art',exact:true}).click();await expect(page.locator('.career-postcard img')).toBeVisible();await expect(page.getByRole('button',{name:'Download postcard'})).toBeEnabled();await h.snapshot(page,info,'postcard');const postcardImages=await h.imageProof(page);const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download postcard'}).click()]);expect(await download.failure()).toBe(null);const path=await download.path(),png=readFileSync(path);verifyPng(png,[1536,1120]);expect(png.subarray(1,4).toString()).toBe('PNG');expect([png.readUInt32BE(16),png.readUInt32BE(20)]).toEqual([1536,1120]);expect(png.length).toBeGreaterThan(20000);await h.record(info,'art-layout-postcard',{layouts,images,collectionImages,postcardImages,postcard:{filename:download.suggestedFilename(),bytes:png.length,sha256:createHash('sha256').update(png).digest('hex'),dimensions:[1536,1120]}});await h.close(page);
});
