import assert from 'node:assert/strict';
import {createCareer,commandFor,reduceCareer,validateCareer,matchingTiles} from '../../src/career/engine.js';
import {CATALOG,STORY_ORDERS,UPGRADES,coinBalance} from '../../src/career/content.js';
export function act(s,a){const r=reduceCareer(s,commandFor(s,a));assert(r.ok,r.message);return r.state;}
function make(s,id){const p=CATALOG.pieceOf(id);if(p.tier===1){const ids=new Set(s.board.filter(Boolean).map(t=>t.id));s=act(s,{type:'supply',familyId:p.familyId,basic:true});return[s,s.board.find(t=>t&&!ids.has(t.id)).id];}let a,b;[s,a]=make(s,CATALOG.previousPiece(id).id);[s,b]=make(s,CATALOG.previousPiece(id).id);const from=s.board.findIndex(t=>t?.id===a),to=s.board.findIndex(t=>t?.id===b);s=act(s,{type:'move',from,to,tileId:a,targetTileId:b});return[s,s.board[to].id];}
export function ready(s,order=s.orders[0]){const reserved=new Set();for(const r of order.requirements)for(let q=0;q<r.quantity;q++){let tile=s.board.find(t=>t?.pieceId===r.pieceId&&!reserved.has(t.id));if(!tile){let id;[s,id]=make(s,r.pieceId);tile=s.board.find(t=>t?.id===id);}reserved.add(tile.id);}validateCareer(s);return s;}
export function route(n){let s=createCareer(`fixture-route-${n}`);for(let i=0;i<n;i++){const o=s.orders.find(o=>o.storyLetterId===STORY_ORDERS[i].id);assert(o);s=ready(s,o);s=act(s,{type:'complete',orderId:o.id,tileIds:matchingTiles(s,o)});}validateCareer(s);return s;}
export function upgraded(){return act(route(5),{type:'purchase',upgradeId:'bird-sorter',expectedLevel:0});}
export function threeOrders(){let s=act(route(7),{type:'purchase',upgradeId:'order-desk',expectedLevel:0});for(const upgradeId of ['bird-sorter','fern-sorter']){let attempts=0;while(coinBalance(s)<50){assert(attempts++<8);const order=s.orders.find(o=>o.slot===2&&o.origin==='ordinary');assert(order);s=ready(s,order);s=act(s,{type:'complete',orderId:order.id,tileIds:matchingTiles(s,order)});}s=act(s,{type:'purchase',upgradeId,expectedLevel:0});}assert.equal(s.orders.length,3);assert(s.upgrades['bird-sorter']&&s.upgrades['fern-sorter']);validateCareer(s);return s;}
export function allFinal(){let s=createCareer('fixture-full-finals');s.board=s.board.map((_,i)=>({id:`${s.careerId}:tile:${s.nextTileSeq++}`,pieceId:i%2?'f5':'b5'}));s.discoveries=[...new Set([...s.discoveries,'b5','f5'])];for(const f of CATALOG.FAMILIES){const live=s.board.filter(t=>CATALOG.pieceOf(t.pieceId).familyId===f.id).length*16;s.material[f.id].generated=live-4;}s.history=[];validateCareer(s);return s;}
export function allArt(){let s=route(9);for(let i=0;i<25;i++)if(s.board[i])s=act(s,{type:'recycle',at:i,tileId:s.board[i].id,confirmed:true});for(const p of CATALOG.PIECES)[s]=make(s,p.id);validateCareer(s);return s;}
export function fixtureNamed(name){return({fresh:()=>createCareer('fixture-fresh'),ready:()=>ready(createCareer('fixture-ready')),funded:()=>route(5),upgraded,threeOrders,allFinal,allArt})[name]();}
export function emptyBoard(){let s=createCareer('geometry-empty');for(let i=0;i<25;i++)if(s.board[i])s=act(s,{type:'recycle',at:i,tileId:s.board[i].id});return s;}
export function mixedBoard(){let s=emptyBoard();for(const p of CATALOG.PIECES)[s]=make(s,p.id);validateCareer(s);return s;}
