import {expect} from '@playwright/test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdirSync,writeFileSync,readdirSync,readFileSync} from 'node:fs';
import {join} from 'node:path';
import {verifyPng} from '../../scripts/expansion160Png.mjs';
import {CATALOG,STORY_ORDERS,STORAGE_KEY,LOCK_NAME} from '../../src/career/content.js';
import {validateCareer,nextOutput} from '../../src/career/engine.js';
import {ORIGIN,MAX_SCREENSHOTS} from '../../scripts/careerGateScope.mjs';
const contextAudits=new WeakMap();
export const OLD_KEYS=['moticos.matching.garden.v1','moticos.collection.garden.v1'];
export async function instrumentation(context){
 const observed=[];contextAudits.set(context,observed);await context.exposeBinding('__recordCareerWrite',(_,event)=>observed.push(event));
 await context.route('**/*',route=>new URL(route.request().url()).origin===ORIGIN?route.continue():route.abort('blockedbyclient'));
 await context.addInitScript(({keys,key})=>{const proto=Storage.prototype,original={get:proto.getItem,set:proto.setItem,remove:proto.removeItem,clear:proto.clear};window.__careerAudit=[];window.__rawStorage=original;window.__fixtureWrite=false;proto.setItem=function(k,v){if(this===localStorage){const event={op:'set',key:k,fixture:window.__fixtureWrite};window.__careerAudit.push(event);void window.__recordCareerWrite(event);}return original.set.call(this,k,v);};proto.removeItem=function(k){if(this===localStorage){const event={op:'remove',key:k,fixture:window.__fixtureWrite};window.__careerAudit.push(event);void window.__recordCareerWrite(event);}return original.remove.call(this,k);};proto.clear=function(){if(this===localStorage){const event={op:'clear',fixture:window.__fixtureWrite};window.__careerAudit.push(event);void window.__recordCareerWrite(event);}return original.clear.call(this);};const mode=window.name;if(mode.startsWith('career-fault:')){const fault=mode.slice(13);if(fault==='read'){const get=proto.getItem;proto.getItem=function(k){if(this===localStorage&&k===key)throw new DOMException('Synthetic read denial','SecurityError');return get.call(this,k);};}if(fault==='quota'){const set=proto.setItem;proto.setItem=function(k,v){if(this===localStorage&&k===key)throw new DOMException('Synthetic quota failure','QuotaExceededError');return set.call(this,k,v);};}if(fault==='lock')Object.defineProperty(navigator,'locks',{configurable:true,value:undefined});}},{keys:OLD_KEYS,key:STORAGE_KEY});
}
export async function open(page){await page.goto('/career.html');await expect(page.locator('.career-shell')).toHaveAttribute('data-save-status','saved');await expect(page.locator('[data-career-cell]')).toHaveCount(25);await seedSentinels(page);}
export async function seedSentinels(page){await page.evaluate(async({keys,lock})=>{await navigator.locks.request(lock,{mode:'exclusive'},()=>{window.__fixtureWrite=true;for(const k of keys)localStorage.setItem(k,'protected synthetic sentinel');window.__fixtureWrite=false;});},{keys:OLD_KEYS,lock:LOCK_NAME});}
export async function read(page){return page.evaluate(key=>JSON.parse(localStorage.getItem(key)),STORAGE_KEY);}
export async function bytes(page){return page.evaluate(key=>localStorage.getItem(key),STORAGE_KEY);}
export async function seed(page,state){validateCareer(state);await page.evaluate(async({key,lock,state})=>{await navigator.locks.request(lock,{mode:'exclusive'},()=>{window.__fixtureWrite=true;localStorage.setItem(key,JSON.stringify(state));window.__fixtureWrite=false;});},{key:STORAGE_KEY,lock:LOCK_NAME,state});await page.reload();await expect(page.locator('.career-shell')).toHaveAttribute('data-save-status','saved');await expect.poll(async()=>(await read(page)).careerId).toBe(state.careerId);}
export async function audit(page){const result=await page.evaluate(({keys,key})=>({sentinels:keys.map(k=>window.__rawStorage.get.call(localStorage,k)),bad:window.__careerAudit.filter(e=>!e.fixture&&(e.op==='clear'||e.key!==key))}),{keys:OLD_KEYS,key:STORAGE_KEY});expect(result.sentinels).toEqual(OLD_KEYS.map(()=>'protected synthetic sentinel'));expect(result.bad).toEqual([]);expect((contextAudits.get(page.context())??[]).filter(e=>!e.fixture&&(e.op==='clear'||e.key!==STORAGE_KEY))).toEqual([]);validateCareer(await read(page));}
export async function press(locator,touch=false){return touch?locator.tap():locator.click();}
export async function changed(page,before,fn){await fn();await expect.poll(async()=>(await read(page)).revision).toBe(before.revision+1);await expect(page.locator('.career-cell').first()).toBeEnabled();return read(page);}
export async function draw(page,familyId,{basic=false,to=null,touch=false}={}){const s=await read(page),family=CATALOG.FAMILIES.find(f=>f.id===familyId);if(to!==null)await press(page.locator(`[data-career-cell="${to}"]`),touch);const loc=basic&&s.sources[familyId].sorter?page.locator(`.career-producer.${familyId} .career-basic-supply`):page.getByRole('button',{name:new RegExp(`^Add free ${family.shortName} supply:`)});const next=await changed(page,s,()=>press(loc,touch));const old=new Set(s.board.filter(Boolean).map(t=>t.id));return[next,next.board.find(t=>t&&!old.has(t.id)).id];}
export async function merge(page,a,b,touch=false){const s=await read(page),from=s.board.findIndex(t=>t?.id===a),to=s.board.findIndex(t=>t?.id===b);expect(from).toBeGreaterThanOrEqual(0);expect(to).toBeGreaterThanOrEqual(0);await press(page.locator(`[data-career-cell="${from}"]`),touch);const next=await changed(page,s,()=>press(page.locator(`[data-career-cell="${to}"]`),touch));return[next,next.board[to].id];}
export async function make(page,id,touch=false){const p=CATALOG.pieceOf(id);if(p.tier===1)return draw(page,p.familyId,{basic:true,touch});let a,b;[,a]=await make(page,CATALOG.previousPiece(id).id,touch);[,b]=await make(page,CATALOG.previousPiece(id).id,touch);return merge(page,a,b,touch);}
export async function readyUI(page,order,touch=false){const reserved=new Set();for(const r of order.requirements)for(let n=0;n<r.quantity;n++){let s=await read(page),tile=s.board.find(t=>t?.pieceId===r.pieceId&&!reserved.has(t.id));if(!tile){let id;[s,id]=await make(page,r.pieceId,touch);tile=s.board.find(t=>t?.id===id);}reserved.add(tile.id);}return read(page);}
export async function send(page,order,touch=false){const s=await readyUI(page,order,touch);const next=await changed(page,s,()=>press(page.locator(`[data-order-id="${order.id}"] .career-send`),touch));await expect(page.getByRole('status').last()).toContainText('saved');return next;}
export async function buy(page,id,touch=false){await press(page.locator('.career-shop-button'),touch);await expect(page.getByRole('dialog')).toBeVisible();const s=await read(page);const article=page.locator('.career-upgrades article').filter({has:page.getByRole('heading',{name:id==='order-desk'?'Order desk':id==='bird-sorter'?'Bird sorter I':'Fern sorter I',exact:true})});const next=await changed(page,s,()=>press(article.getByRole('button',{name:/^Buy/}),touch));await expect(article.getByRole('button',{name:'Owned ✓'})).toBeDisabled();await close(page,touch);return next;}
export async function close(page,touch=false){await press(page.getByRole('button',{name:'Close and return to board'}),touch);await expect(page.getByRole('dialog')).toHaveCount(0);}
export async function undo(page,touch=false){const s=await read(page);return changed(page,s,()=>press(page.getByRole('button',{name:'Undo',exact:true}),touch));}
export async function snapshot(page,info,label){const root=join('career-results',info.project.name,'screenshots');mkdirSync(root,{recursive:true});const total=['career-chromium','career-webkit-phone'].reduce((n,p)=>{try{return n+readdirSync(join('career-results',p,'screenshots')).filter(n=>n.endsWith('.png')).length;}catch{return n;}},0);assert(total<MAX_SCREENSHOTS,'Screenshot cap exceeded');const path=join(root,`${info.title.slice(0,3)}-${label}.png`);const dimensions=await page.evaluate(()=>[Math.round(innerWidth*devicePixelRatio),Math.round(Math.max(document.documentElement.scrollHeight,innerHeight)*devicePixelRatio)]);await page.screenshot({path,fullPage:true});const png=readFileSync(path);verifyPng(png,dimensions);let captures=[];try{captures=JSON.parse(readFileSync(join(root,'manifest.json'),'utf8'));}catch{}captures.push({caseId:info.title.slice(0,3),label,path,bytes:png.length,sha256:createHash('sha256').update(png).digest('hex'),dimensions});writeFileSync(join(root,'manifest.json'),JSON.stringify(captures,null,2)+'\n');info.annotations.push({type:'screenshot',description:path});}
export async function record(info,label,data){const path=join('career-results',info.project.name,`${info.title.slice(0,3)}-${label}.json`);mkdirSync(join('career-results',info.project.name),{recursive:true});writeFileSync(path,JSON.stringify(data,null,2)+'\n');await info.attach(label,{path,contentType:'application/json'});}
export async function holdLock(page){await page.evaluate(async lock=>{window.__gateReady=new Promise(resolve=>{navigator.locks.request(lock,{mode:'exclusive'},async()=>{window.__releaseGate=null;const blocked=new Promise(r=>window.__releaseGate=r);resolve();await blocked;});});await window.__gateReady;},LOCK_NAME);}
export async function releaseLock(page){await page.evaluate(()=>window.__releaseGate());}
export async function race(page,other,clickA,clickB){const before=await read(page);await holdLock(page);await Promise.all([clickA(),clickB()]);await expect.poll(()=>page.evaluate(async lock=>(await navigator.locks.query()).pending.filter(x=>x.name===lock).length,LOCK_NAME)).toBe(2);await releaseLock(page);await expect.poll(async()=>(await read(page)).revision).toBe(before.revision+1);await expect.poll(async()=>(await read(other)).revision).toBe(before.revision+1);await expect(page.locator('.career-cell').first()).toBeEnabled();await expect(other.locator('.career-cell').first()).toBeEnabled();return read(page);}
export async function noOverflow(page,{desktop=false,touch=false}={}){const result=await page.evaluate(({desktop,touch})=>{const rect=el=>{const r=el.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom};};const visible=el=>el.getClientRects().length&&getComputedStyle(el).visibility!=='hidden';const selectors=['.career-header','.career-chapter-row','.career-board','.career-order-list','.career-progress','.career-producers','.career-tools','.career-status','.career-footer'];const bounds=Object.fromEntries(selectors.map(s=>[s,rect(document.querySelector(s))]));const activeRoot=document.querySelector('dialog[open]')??document.querySelector('.career-shell');const controls=[...activeRoot.querySelectorAll('button')].filter(visible).map(el=>({label:el.getAttribute('aria-label')||el.textContent,box:rect(el),rail:!!el.closest('.career-order-list')}));return{width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,bounds,controls,clipped:controls.filter(({box:b,rail})=>!rail&&(b.x<-.5||b.right>innerWidth+.5)),small:touch?controls.filter(({box:b})=>b.width<43.5||b.height<43.5):[]};},{desktop,touch});expect(result.scrollWidth).toBeLessThanOrEqual(result.width+1);expect(result.clipped).toEqual([]);expect(result.small).toEqual([]);if(desktop)expect(result.scrollHeight,'Whole desktop page exceeds one ordinary screen').toBeLessThanOrEqual(result.height+1);if(desktop)for(const [name,b] of Object.entries(result.bounds)){expect(b.y,`${name} above screen`).toBeGreaterThanOrEqual(-1);expect(b.bottom,`${name} below screen`).toBeLessThanOrEqual(result.height+1);}const hitProof=await page.evaluate(()=>{const x=scrollX,y=scrollY,rails=[...document.querySelectorAll('.career-order-list')].map(el=>[el,el.scrollLeft]);const bad=[],clippedText=[];for(const el of (document.querySelector('dialog[open]')??document.querySelector('.career-shell')).querySelectorAll('button')){if(!el.getClientRects().length)continue;el.scrollIntoView({block:'nearest',inline:'nearest',behavior:'instant'});const r=el.getBoundingClientRect(),cx=r.x+r.width/2,cy=r.y+r.height/2;const points=[[cx,cy],[r.x+r.width*.2,cy],[r.x+r.width*.8,cy],[cx,r.y+r.height*.2],[cx,r.y+r.height*.8]];if(points.some(([px,py])=>{const hit=document.elementFromPoint(px,py);return !hit||!(hit===el||el.contains(hit));}))bad.push(el.getAttribute('aria-label')||el.textContent);}for(const el of document.querySelectorAll('.career-cell-label,.career-target strong,.career-supply small,.career-rewards'))if(el.getClientRects().length&&(el.scrollWidth>el.clientWidth+1||el.scrollHeight>el.clientHeight+1))clippedText.push(el.textContent);for(const[el,left]of rails)el.scrollLeft=left;scrollTo(x,y);return{bad,clippedText};});expect(hitProof.bad).toEqual([]);expect(hitProof.clippedText).toEqual([]);return{...result,hitProof};}
export async function imageProof(page){await expect.poll(()=>page.locator('.career-shell img').evaluateAll(nodes=>nodes.every(img=>img.complete&&img.naturalWidth>0))).toBe(true);const state=await read(page),sources=Object.fromEntries(CATALOG.FAMILIES.map(f=>[f.id,nextOutput(state,f.id).id])),names=Object.fromEntries(CATALOG.PIECES.map(p=>[p.name,p.id]));const records=await page.locator('.career-shell img').evaluateAll((nodes,{sources,names})=>nodes.map(img=>{const cell=img.closest('[data-piece-id]'),target=img.closest('.career-target'),producer=img.closest('.career-producer'),collection=img.closest('.career-collection-grid button'),postcard=img.closest('.career-postcard');const pieceId=cell?.dataset.pieceId??(target?names[target.querySelector('strong').textContent]:producer?sources[producer.classList.contains('bird')?'bird':'fern']:collection?names[collection.querySelector('strong').textContent]:postcard?names[document.querySelector('#career-dialog-title').textContent]:null);return{pieceId,src:img.currentSrc,loaded:img.complete,width:img.naturalWidth,height:img.naturalHeight,display:img.getBoundingClientRect().width};}),{sources,names});expect(records.length).toBeGreaterThan(0);const proof=[];for(const r of records){expect(r.loaded).toBe(true);expect(r.width).toBeGreaterThan(0);expect(r.height).toBeGreaterThan(0);expect(r.display).toBeGreaterThan(8);expect(new URL(r.src).origin).toBe(ORIGIN);const response=await page.request.get(r.src);expect(response.ok()).toBe(true);const body=await response.body();proof.push({...r,bytes:body.length,sha256:createHash('sha256').update(body).digest('hex')});}const assets=JSON.parse(readFileSync('career-build-proof.json','utf8')).art;for(const r of proof){expect(r.pieceId,'Rendered image has an explicit game identity').toBeTruthy();expect(assets.find(a=>a.id===r.pieceId)?.sha256).toBe(r.sha256);}return proof;}
