import {test,expect} from '@playwright/test';
import {CASES,titleFor} from '../../scripts/careerGateScope.mjs';
import {createCareer} from '../../src/career/engine.js';
import {CATALOG} from '../../src/career/content.js';
import {route,threeOrders,ready} from './fixtures.mjs';
import * as h from './helpers.mjs';
const cases=CASES['career-webkit-phone'];
function check(index,fn){const[id,title,timeout]=cases[index];test(titleFor(id,title),async({page,context},info)=>{const args={page,context};test.setTimeout(timeout);await h.instrumentation(args.context);const errors=[];args.page.on('pageerror',e=>errors.push(String(e)));await fn(args,info);expect(errors).toEqual([]);await h.audit(args.page);});}
check(0,async({page},info)=>{await h.open(page);let s=await h.read(page);s=await h.send(page,s.orders[0],true);expect([s.xp,s.coinsEarned]).toEqual([10,5]);expect(s.discoveries).toContain('b2');await page.getByRole('button',{name:'View postcard',exact:true}).tap();await expect(page.locator('.career-postcard img')).toBeVisible();await h.snapshot(page,info,'first-postcard');await h.noOverflow(page,{touch:true});await h.close(page,true);const before=await h.bytes(page);await page.reload();expect(await h.bytes(page)).toBe(before);await h.record(info,'first-delivery',s);});
check(1,async({page},info)=>{await h.open(page);await h.seed(page,route(5));await h.buy(page,'bird-sorter',true);for(const tier of [1,1,2]){let s=await h.read(page),to=s.board.findIndex(t=>!t);let id;[s,id]=await h.draw(page,'bird',{to,touch:true});expect(s.board[to].id).toBe(id);expect(CATALOG.pieceOf(s.board[to].pieceId).tier).toBe(tier);}const before=await h.read(page);await h.draw(page,'bird',{basic:true,touch:true});expect((await h.read(page)).sources).toEqual(before.sources);await h.undo(page,true);await page.reload();expect((await h.read(page)).board).toEqual(before.board);let s=await h.read(page);const valuable=s.board.findIndex(t=>CATALOG.pieceOf(t?.pieceId)?.tier>=3);if(valuable<0){const made=await h.make(page,'b3',true);s=made[0];}else s=await h.read(page);const at=s.board.findIndex(t=>CATALOG.pieceOf(t?.pieceId)?.tier>=3);await page.locator(`[data-career-cell="${at}"]`).tap();await page.getByRole('button',{name:'Recycle',exact:true}).tap();await page.getByRole('button',{name:'Keep picture'}).tap();expect((await h.read(page)).board).toEqual(s.board);await page.getByRole('button',{name:'Recycle',exact:true}).tap();await h.changed(page,s,()=>page.getByRole('button',{name:'Recycle picture',exact:true}).tap());const fixture=ready(route(5));await h.seed(page,fixture);await h.send(page,fixture.orders[0],true);const sent=await h.bytes(page);await page.reload();expect(await h.bytes(page)).toBe(sent);await h.record(info,'touch-operations',await h.read(page));});
check(2,async({page},info)=>{await h.open(page);const records=[];for(const size of [{width:320,height:568},{width:390,height:844},{width:430,height:932}]){await page.setViewportSize(size);for(const kind of ['fresh','three']){await h.seed(page,kind==='fresh'?createCareer(`fixture-phone-${size.width}`):threeOrders());if(kind==='three'){expect((await h.read(page)).orders.length).toBe(3);await expect(page.locator('.career-order')).toHaveCount(3);}records.push({size,kind,...await h.noOverflow(page,{touch:true})});await h.snapshot(page,info,`${size.width}-${kind}`);}}await h.record(info,'phone-geometry',records);});
check(3,async({page},info)=>{await h.open(page);await page.getByRole('button',{name:'How to play'}).tap();const before=await h.read(page);await h.changed(page,before,()=>page.getByRole('button',{name:'Use larger text'}).tap());await h.close(page,true);await page.reload();await expect(page.locator('.career-shell')).toHaveClass(/is-large-text/);await h.record(info,'phone-large-text',await h.noOverflow(page,{touch:true}));await h.snapshot(page,info,'large-text');for(const selector of ['.career-collection-button','.career-shop-button']){const opener=page.locator(selector);await opener.tap();await expect(page.getByRole('dialog')).toBeVisible();await h.noOverflow(page,{touch:true});await h.close(page,true);await expect(opener).toBeFocused();}expect((await h.read(page)).sound).toBe(false);await page.emulateMedia({reducedMotion:'reduce'});expect(await page.locator('.career-cell').first().evaluate(el=>getComputedStyle(el).transitionDuration)).toBe('0s');await page.reload();await expect(page.locator('.career-shell')).toHaveClass(/is-large-text/);});
