import {test,expect} from '@playwright/test';
import {readFileSync,mkdirSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {CASES,titleFor} from '../../gate/scope.mjs';
import {verifyPng} from '../../gate/png.mjs';
import {gridViolations} from '../../gate/layout.mjs';
import * as h from './helpers.mjs';
import * as f from './fixtures.mjs';
import * as adopted from './adopted-journeys.mjs';
const {C,E}=f, cases=CASES['campaign-chromium'];
function check(index,fn){const[id,title,timeout]=cases[index];test(titleFor(id,title),async({page,context},info)=>{test.setTimeout(timeout);await h.instrumentation(context);const errors=[];context.on('page',p=>p.on('pageerror',e=>errors.push(String(e))));page.on('pageerror',e=>errors.push(String(e)));await fn({page,context},info);expect(errors).toEqual([]);await h.audit(page);});}
check(0,async({page},info)=>{
 await h.open(page);const journey=[];
 for(const letter of C.CHAPTERS[0].storyIds){let s=await h.read(page);const order=s.orders.find(o=>o.storyLetterId===letter);expect(order).toBeTruthy();const before={xp:s.xp,coins:s.coinsEarned};s=await h.send(page,order);expect([s.xp,s.coinsEarned]).toEqual([before.xp+order.xp,before.coins+order.coins]);journey.push({letter,revision:s.revision,xp:s.xp,coins:s.coinsEarned});if(letter==='garden-letter-5')await h.buy(page,'bird-sorter');if(letter==='garden-letter-8')await h.buy(page,'order-desk');if(letter==='garden-letter-4'){const chosen=s.orders.at(-1);await h.focusOrder(page,chosen.id);const saved=await h.bytes(page);await page.reload();expect(await h.bytes(page)).toBe(saved);}}
 await h.buy(page,'fern-sorter');const s=await h.read(page);expect([s.xp,s.coinsEarned,s.coinsSpent]).toEqual([510,215,200]);expect(E.chapterComplete(s)).toBe(true);await h.visibleNotice(page,/sorter/i);await h.snapshot(page,info,'garden-complete');const saved=await h.bytes(page);await page.reload();expect(await h.bytes(page)).toBe(saved);await expect(page.locator('.career-postmark')).toHaveCount(1);await expect(page.locator('.career-postmark')).toContainText('SENT & SAVED');await expect(page.locator('.career-postmark')).not.toHaveClass(/is-new-delivery/);await h.record(info,'garden-ui-route',{kind:'Every story crafting and Send action above used visible UI; no story fixture injection.',journey,state:s});
});
check(1,async({page},info)=>{
 await h.open(page);let s=f.transition();[s]=f.acquire(s,'b3');await h.seed(page,s);const original=s;await h.startChapter(page);s=await h.read(page);for(const key of['board','material','discoveries','purchases','coinsEarned','coinsSpent'])expect(s[key]).toEqual(original[key]);expect(s.unlockedSources).toEqual(['bird','fern','key']);const journey=[];
 for(const letter of C.CHAPTERS[1].storyIds){s=await h.read(page);const order=s.orders.find(o=>o.storyLetterId===letter);expect(order).toBeTruthy();const before={xp:s.xp,coins:s.coinsEarned};s=await h.send(page,order);expect([s.xp,s.coinsEarned]).toEqual([before.xp+order.xp,before.coins+order.coins]);if(letter==='moon-letter-1')expect(s.unlockedSources).not.toContain('moon');if(letter==='moon-letter-2'){expect(s.unlockedSources).toContain('moon');expect(s.material.moon.generated).toBe(0);}if(letter==='moon-letter-3')await h.buy(page,'key-sorter');if(letter==='moon-letter-6')await h.buy(page,'moon-sorter');journey.push({letter,revision:s.revision,unlocked:s.unlockedSources});const bytes=await h.bytes(page);await page.reload();expect(await h.bytes(page)).toBe(bytes);}
 s=await h.read(page);expect([s.xp,s.coinsEarned,s.coinsSpent]).toEqual([1020,430,300]);expect(E.campaignComplete(s)).toBe(true);expect(s.milestones).toHaveLength(16);await h.panel(page,'letters');await expect(page.locator('.career-next-chapter')).toContainText('Extra coins have no further use');await expect(page.getByRole('dialog')).toContainText('Further chapters are still being developed');await h.close(page);await h.selectSource(page,'moon',0);await h.draw(page,'moon');await h.undo(page);await page.reload();await h.snapshot(page,info,'authored-finale');await h.record(info,'moon-ui-route',{kind:'Prepared Garden-complete start; all seven Moon letters crafted and delivered through visible UI.',journey,state:await h.read(page)});
});
check(2,async(args,info)=>{
 await adopted.choice(args,info);const {page}=args;await h.seed(page,f.route(11));const before=await h.read(page),chosen=before.orders.at(-1);await h.focusOrder(page,chosen.id);const focused=await h.read(page);expect(focused.activeSourceIds).toEqual(expect.arrayContaining([...new Set(chosen.requirements.map(r=>C.CATALOG.pieceOf(r.pieceId).familyId))]));await h.selectSource(page,'bird',0);const next=await h.read(page);for(const k of['board','material','sources','orders'])expect(next[k]).toEqual(focused[k]);expect(next.activeSourceIds).toHaveLength(2);expect(new Set(next.activeSourceIds).size).toBe(2);await page.reload();expect(await h.read(page)).toEqual(next);await h.record(info,'chosen-source-return',next);
 // Real queued writes must not dismiss a newer panel, even the same panel type.
 await page.setViewportSize({width:390,height:664});const holder=await args.context.newPage();await h.open(holder);const lateResults=[];
 for(const type of['collection','orders']){await h.panel(page,'orders');const current=await h.read(page),pending=current.orders.find(o=>o.id!==current.focusedOrderId);expect(pending).toBeTruthy();await h.holdLock(holder);await page.locator('.career-order-choices>section').filter({has:page.locator(`[data-order-id="${pending.id}"]`)}).locator('.career-focus-order').click();await expect.poll(()=>holder.evaluate(async name=>(await navigator.locks.query()).pending.filter(x=>x.name===name).length,C.LOCK_NAME)).toBeGreaterThanOrEqual(1);await h.close(page);await h.panel(page,type);await h.releaseLock(holder);await expect.poll(async()=>(await h.read(page)).focusedOrderId).toBe(pending.id);await expect(page.getByRole('dialog')).toHaveAccessibleName(type==='collection'?'Your collected pictures':'Choose a request');await h.close(page);lateResults.push({type,pendingOrderId:pending.id,newerPanelPreserved:true});}
 await h.audit(holder);await holder.close();await page.setViewportSize({width:1366,height:768});await h.record(info,'late-goal-preserves-newer-panel',{lateResults});
});
check(3,async(args,info)=>{
 await adopted.full(args,info);const {page}=args;await h.seed(page,f.act(f.route(5),{type:'purchase',upgradeId:'bird-sorter',expectedLevel:0}));await h.draw(page,'bird');await h.draw(page,'bird');const before=await h.read(page);let[s,id]=await h.draw(page,'bird');expect(C.CATALOG.pieceOf(s.board.find(t=>t?.id===id).pieceId).tier).toBe(2);s=await h.undo(page);for(const k of['board','sources','material'])expect(s[k]).toEqual(before[k]);await page.reload();expect((await h.read(page)).sources).toEqual(before.sources);await h.draw(page,'bird',{basic:true});expect((await h.read(page)).sources.bird.cursor).toBe(before.sources.bird.cursor);
 await h.seed(page,f.allFinal());const bytes=await h.bytes(page);const full=await h.read(page),pair=full.board.flatMap((t,i)=>t?.pieceId==='b5'?[i]:[]).slice(0,2);expect(pair).toHaveLength(2);await page.locator(`[data-career-cell="${pair[0]}"]`).click();await page.locator(`[data-career-cell="${pair[1]}"]`).click();await h.visibleNotice(page,/final|highest|last|cannot/i);expect(await h.bytes(page)).toBe(bytes);await h.record(info,'sorter-final-errors',{state:await h.read(page)});
});
check(4,async({page,context},info)=>{
 await h.open(page);const other=await context.newPage();await h.open(other);const before=await h.read(page);let next=await h.race(page,other,()=>page.locator('.career-producer.bird .career-supply').click(),()=>other.locator('.career-producer.fern .career-supply').click());expect(next.board.filter(Boolean)).toHaveLength(before.board.filter(Boolean).length+1);await page.reload();await other.reload();await page.locator('[data-career-cell="0"]').click();next=await h.race(page,other,()=>page.locator('[data-career-cell="24"]').click(),()=>other.locator('.career-producer.fern .career-supply').click());await page.reload();await other.reload();const state=await h.read(page),from=state.board.findIndex(Boolean),to=state.board.findIndex(t=>!t),transfer=await page.evaluateHandle(()=>new DataTransfer());await page.locator(`[data-career-cell="${from}"]`).dispatchEvent('dragstart',{dataTransfer:transfer});await h.draw(other,'bird');await expect.poll(async()=>(await h.read(page)).revision).toBe(state.revision+1);const saved=await h.bytes(page);await page.locator(`[data-career-cell="${to}"]`).dispatchEvent('drop',{dataTransfer:transfer});expect(await h.bytes(page)).toBe(saved);await h.audit(other);await other.close();await h.record(info,'native-board-races',next);
});
check(5,adopted.nativeSend);
check(6,async({page,context},info)=>{
 await h.open(page);await h.seed(page,f.route(5));const other=await context.newPage();await h.open(other);await h.panel(page,'shop');await h.panel(other,'shop');const buyer=p=>p.locator('.career-upgrades article').filter({has:p.getByRole('heading',{name:'Bird sorter I',exact:true})}).getByRole('button',{name:'Buy · 50 coins'});const before=await h.read(page);let next=await h.race(page,other,()=>buyer(page).click(),()=>buyer(other).click());expect(next.coinsSpent).toBe(50);expect(next.purchases['bird-sorter']).toEqual({price:50,contentVersion:C.CONTENT_VERSION});expect(next.board).toEqual(before.board);await h.close(page);await h.close(other);let fixture=f.ready(f.route(5));await h.seed(page,fixture);await other.reload();await h.panel(page,'shop');next=await h.race(page,other,()=>buyer(page).click(),()=>h.sendControl(other,fixture.orders[0].id).click());expect((next.coinsSpent===50)!==(next.xp>fixture.xp)).toBe(true);await h.close(page);await h.audit(other);await other.close();await h.record(info,'native-purchase-races',next);
});
check(7,async(args,info)=>{
 await adopted.chapter(args,info);const {page,context}=args;await h.seed(page,f.transition());const other=await context.newPage();await h.open(other);for(const p of[page,other])await p.getByRole('button',{name:'Open Moonlit Correspondence',exact:true}).click();const before=await h.read(page);const next=await h.race(page,other,()=>page.getByRole('button',{name:'Begin Moonlit Correspondence',exact:true}).click(),()=>other.getByRole('button',{name:'Begin Moonlit Correspondence',exact:true}).click());expect(next.enteredChapters.filter(id=>id==='moonlit-correspondence')).toHaveLength(1);expect(next.board).toEqual(before.board);expect(next.material.key.generated).toBe(0);await page.reload();await other.reload();
 const legacy=f.legacyFixtures().pendingChangedLetters;const holder=await context.newPage();await h.open(holder);await h.holdLock(holder);await holder.evaluate(({key,value})=>{window.__fixtureWrite=true;localStorage.setItem(key,value);window.__fixtureWrite=false;},{key:C.STORAGE_KEY,value:JSON.stringify(legacy)});const navigations=[page,other].map(p=>p.reload({waitUntil:'domcontentloaded'}));await Promise.all(navigations);await expect.poll(()=>holder.evaluate(async name=>(await navigator.locks.query()).pending.filter(x=>x.name===name).length,C.LOCK_NAME)).toBe(2);await h.releaseLock(holder);await holder.close();
 await expect(page.locator('.career-shell')).toHaveAttribute('data-save-status','saved');await expect(other.locator('.career-shell')).toHaveAttribute('data-save-status','saved');expect(await h.read(page)).toEqual(await h.read(other));expect((await h.read(page)).schemaVersion).toBe(C.SCHEMA_VERSION);await h.audit(other);await other.close();await h.record(info,'native-entry-conversion',await h.read(page));
});
check(8,async({page},info)=>{
 await h.open(page);const rows=[];for(const fault of['quota','read','lock','future']){await page.evaluate(()=>window.name='');await h.seed(page,f.ready(f.route(5)));const original=await h.bytes(page);let protectedBytes=original;if(fault==='future'){protectedBytes=JSON.stringify({...JSON.parse(original),contentVersion:999});await page.evaluate(({key,bytes})=>{window.__fixtureWrite=true;localStorage.setItem(key,bytes);window.__fixtureWrite=false;},{key:C.STORAGE_KEY,bytes:protectedBytes});}else await page.evaluate(fault=>window.name=`career-fault:${fault}`,fault);await page.reload();if(fault==='quota')await h.sendControl(page,JSON.parse(original).orders[0].id).click();await expect(page.locator('.career-shell')).toHaveAttribute('data-save-status','practice');await expect(page.locator('.career-save-warning')).toContainText('unsaved practice');expect(await page.evaluate(key=>window.__rawStorage.get.call(localStorage,key),C.STORAGE_KEY)).toBe(protectedBytes);if(fault==='quota'){await expect(page.locator('.career-postmark')).toHaveCount(1);await expect(page.locator('.career-postmark')).toContainText('PRACTICE ONLY');}else await expect(page.locator('.career-postmark')).toHaveCount(0);await expect(page.locator('.career-postmark').filter({hasText:'SENT & SAVED'})).toHaveCount(0);rows.push({fault,sha256:createHash('sha256').update(protectedBytes).digest('hex')});await page.evaluate(({key,bytes})=>{window.name='';window.__rawStorage.set.call(localStorage,key,bytes);},{key:C.STORAGE_KEY,bytes:original});await page.reload();await expect(page.locator('.career-shell')).toHaveAttribute('data-save-status','saved');expect(await h.bytes(page)).toBe(original);}await h.record(info,'protected-faults',rows);
});
check(9,async({page},info)=>{
 await h.open(page);const legacy=f.legacyFixtures().pendingChangedLetters,states=[legacy,f.sameSchemaPreviousPack(legacy)],rows=[];for(const state of states){await page.evaluate(({key,state})=>{window.__fixtureWrite=true;localStorage.setItem(key,JSON.stringify(state));window.__fixtureWrite=false;},{key:C.STORAGE_KEY,state});await page.reload();await expect(page.locator('.career-shell')).toHaveAttribute('data-save-status','saved');const next=await h.read(page);for(const order of state.orders){const kept=next.orders.find(o=>o.id===order.id);expect(kept.requirements).toEqual(order.requirements);expect([kept.xp,kept.coins]).toEqual([order.xp,order.coins]);}expect(next.board).toEqual(state.board);expect(next.sources.key.sorter).toBe(0);expect(next.unlockedSources).not.toContain('key');expect(next.coinsSpent).toBe(state.coinsSpent);const saved=await h.bytes(page);await page.reload();expect(await h.bytes(page)).toBe(saved);rows.push({inputSchema:state.schemaVersion,inputContent:state.contentVersion,output:next});}const pruned=f.legacyFixtures().prunedPurchaseReceipts;await page.evaluate(({key,state})=>{window.__fixtureWrite=true;localStorage.setItem(key,JSON.stringify(state));window.__fixtureWrite=false;},{key:C.STORAGE_KEY,state:pruned});await page.reload();await expect(page.locator('.career-shell')).toHaveAttribute('data-save-status','saved');await h.panel(page,'letters');const oldLetter=page.locator('.career-letter-list article').filter({has:page.getByRole('heading',{name:'Between bird and moon',exact:true})});await expect(oldLetter).toHaveCount(1);await oldLetter.getByRole('button',{name:'View sent letter',exact:true}).click();await expect(page.locator('.career-sent-pictures button')).toHaveCount(2);await expect(page.locator('.career-sent-pictures')).toContainText('Wayfinder');await expect(page.locator('.career-sent-pictures')).toContainText('Nightgarden');await h.close(page);const original=await h.bytes(page);await h.panel(page,'letters');await page.locator('.career-letter-list article').filter({has:page.getByRole('heading',{name:'Between bird and moon',exact:true})}).getByRole('button',{name:/Practice/}).click();await expect(page.locator('.career-practice-banner')).toContainText('0 XP');const visibleTargets=page.locator('.career-order:visible .career-target strong');await expect(visibleTargets).toHaveText(['Wayfinder','Nightgarden']);await page.getByRole('button',{name:'Return to career',exact:true}).click();expect(await h.bytes(page)).toBe(original);await h.record(info,'compatible-browser-saves',{rows,historicalPrunedPair:true,isolatedOriginalRecipe:true});
});
check(10,async(args,info)=>{
 const {page,context}=args;await page.addInitScript(()=>{window.__audioStarts=[];for(const name of['AudioBufferSourceNode','OscillatorNode','ConstantSourceNode']){const prototype=window[name]?.prototype,original=prototype?.start;if(typeof original==='function')prototype.start=function(...args){window.__audioStarts.push({node:name,at:performance.now()});return original.apply(this,args);};}});
 await adopted.keyboard(args,info);let s=await h.read(page);await h.changed(page,s,()=>page.getByRole('button',{name:'Turn sound on',exact:true}).click());await page.reload();expect((await h.read(page)).sound).toBe(true);await h.draw(page,'bird');s=await h.read(page);await h.changed(page,s,()=>page.getByRole('button',{name:'Turn sound off',exact:true}).click());expect((await h.read(page)).sound).toBe(false);
 await h.seed(page,f.ready(f.route(1)));s=await h.read(page);const startsBeforeOptIn=await page.evaluate(()=>window.__audioStarts.length);await h.changed(page,s,()=>page.getByRole('button',{name:'Turn sound on',exact:true}).click());await expect.poll(()=>page.evaluate(()=>window.__audioStarts.length)).toBeGreaterThan(startsBeforeOptIn);const holder=await context.newPage();await h.open(holder);await h.holdLock(holder);const before=await h.read(page);await h.sendControl(page,before.focusedOrderId).click();await expect.poll(()=>holder.evaluate(async name=>(await navigator.locks.query()).pending.filter(x=>x.name===name).length,C.LOCK_NAME)).toBeGreaterThanOrEqual(1);await h.panel(page,'letters');await page.locator('.career-letter-list article').first().getByRole('button',{name:/Practice/}).click();await expect(page.locator('.career-practice-banner')).toBeVisible();await page.getByRole('button',{name:'Turn sound off',exact:true}).click();await expect(page.getByRole('button',{name:'Turn sound on',exact:true})).toHaveAttribute('aria-pressed','false');const startsBeforeRelease=await page.evaluate(()=>window.__audioStarts.length);await h.releaseLock(holder);await expect.poll(async()=>(await h.read(page)).receipts.length).toBe(before.receipts.length+1);await page.evaluate(()=>new Promise(resolve=>setTimeout(resolve,250))); // 200ms documented deferred-cue horizon + 50ms margin, not a perceptual timing claim.
const startsAfterRelease=await page.evaluate(()=>window.__audioStarts.length);expect(startsAfterRelease).toBe(startsBeforeRelease);await expect(page.locator('.career-practice-banner')).toBeVisible();await page.getByRole('button',{name:'Return to career',exact:true}).click();await h.audit(holder);await holder.close();await h.record(info,'optional-audio-setting',{optInPersists:true,optOutPersists:true,startsBeforeOptIn,observationWindowMs:250,startsBeforeRelease,startsAfterRelease,noCareerCueScheduledInMutedReplay:true,audibleVerification:false,caveat:'Native Web Audio start-call audit and saved setting only. It does not establish heard output, loudness, timing comfort, or physical-device quality.'});
});
check(11,async({page},info)=>{
 await h.open(page);const layouts=[];for(const size of[{width:1366,height:768},{width:1440,height:900}]){await page.setViewportSize(size);for(const kind of['fresh','moon']){await h.seed(page,kind==='fresh'?E.createCareer('browser-desktop'):f.allArt());const proof=await h.noOverflow(page,{desktop:true});expect(gridViolations(proof.controls.filter(c=>c.kind==='cell').map(c=>c.box))).toEqual([]);layouts.push({size,kind,...proof});if(kind==='moon'){await h.snapshot(page,info,`${size.width}-moon`);const ending=page.locator('.career-finished button');await ending.scrollIntoViewIfNeeded();await expect(ending).toBeInViewport({ratio:1});await ending.click();await expect(page.getByRole('dialog')).toBeVisible();await h.close(page);await page.evaluate(()=>scrollTo(0,0));}}}
 const images=await h.imageProof(page);await h.panel(page,'collection');await expect(page.locator('.career-collection-grid button:enabled')).toHaveCount(20);await h.snapshot(page,info,'all-collected-art');await h.close(page);await h.record(info,'desktop-art-layout',{layouts,images});
});
check(12,async({page},info)=>{
 await page.addInitScript(()=>{window.__encodes=0;const original=HTMLCanvasElement.prototype.toBlob;HTMLCanvasElement.prototype.toBlob=function(...a){window.__encodes++;return original.apply(this,a);};});await h.open(page);await h.seed(page,f.allArt());const timings=[];let started=Date.now();await h.panel(page,'postcard');const targets=page.locator('.career-sent-pictures button');await expect(targets).toHaveCount(2);await expect(targets.nth(0)).toContainText(C.CATALOG.pieceOf('k5').name);await expect(targets.nth(1)).toContainText(C.CATALOG.pieceOf('m4').name);await targets.first().click();await expect(page.locator('.career-postcard')).toContainText('MOONLIT CORRESPONDENCE');await expect(page.getByRole('button',{name:'Download postcard'})).toBeEnabled();expect(await page.evaluate(()=>window.__encodes)).toBe(1);timings.push({phase:'cache-empty-ui',elapsedMs:Date.now()-started});const rows=[];
 async function download(label){const[d]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Download postcard'}).click()]);expect(await d.failure()).toBe(null);const png=readFileSync(await d.path());verifyPng(png,[1536,1120]);const file=`campaign-results/campaign-chromium/postcards/C13-${label}.png`;mkdirSync('campaign-results/campaign-chromium/postcards',{recursive:true});writeFileSync(file,png);rows.push({file,filename:d.suggestedFilename(),bytes:png.length,sha256:createHash('sha256').update(png).digest('hex'),dimensions:[1536,1120]});}
 await download('moon');await h.snapshot(page,info,'moon-postcard');await h.close(page);started=Date.now();await h.panel(page,'collection');await page.getByRole('button',{name:new RegExp(C.CATALOG.pieceOf('k5').name)}).click();await expect(page.getByRole('button',{name:'Download postcard'})).toBeEnabled();expect(await page.evaluate(()=>window.__encodes)).toBe(1);timings.push({phase:'repeat-ui',elapsedMs:Date.now()-started});await h.close(page);started=Date.now();await h.panel(page,'collection');await page.getByRole('button',{name:new RegExp(C.CATALOG.pieceOf('b1').name)}).click();await expect(page.locator('.career-postcard')).toContainText('GARDEN CORRESPONDENCE');await expect(page.getByRole('button',{name:'Download postcard'})).toBeEnabled();expect(await page.evaluate(()=>window.__encodes)).toBe(2);await download('garden');await h.snapshot(page,info,'garden-postcard');await h.close(page);await h.record(info,'paired-labels-original-exports',{postcards:rows,timings,encodes:2,caveat:'UI readiness and repeat encode count; not physical input latency or audible quality.'});
});
check(13,async({page},info)=>{
 await page.goto('/probe/index.html');await page.waitForFunction(()=>Boolean(window.postcardProbe));const results=[];for(const id of['b1','k5']){const row=await page.evaluate(id=>window.postcardProbe.compare(id),id);expect(row.byteEqual).toBe(true);expect(row.sameBlob).toBe(true);expect(row.sameFilename).toBe(true);expect([row.width,row.height]).toEqual([1536,1120]);expect(row.first.encodeMs).toHaveLength(1);expect(row.repeat.encodeMs).toHaveLength(0);expect(row.repeat.decodeMs).toHaveLength(0);expect(row.stats.retainedBytes).toBeLessThanOrEqual(row.stats.maxBytes);const exports=JSON.parse(readFileSync('campaign-results/campaign-chromium/C13-paired-labels-original-exports.json')).postcards;expect(row.sha256).toBe(exports.find(e=>e.filename===row.filename)?.sha256);results.push({...row,actualDownloadBytesMatch:true});}await h.record(info,'bounded-cache-byte-comparison',{results,realEncodes:4,claim:'Two representative cache-empty/repeat/reference byte comparisons. Cache correctness is broader in Node tests. No 20-piece browser re-encode loop.'});await h.open(page);
});
