import {expect} from '@playwright/test';
import {compactSurface} from '../../gate/responsive-surface.mjs';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdirSync,writeFileSync,readdirSync,readFileSync} from 'node:fs';
import {join} from 'node:path';
import {verifyPng} from '../../gate/png.mjs';
import {CATALOG,STORY_ORDERS,STORAGE_KEY,LOCK_NAME} from '../../src/career/content.js';
import {validateCareer,nextOutput} from '../../src/career/engine.js';
import {layoutViolations,MOBILE_CORE,DESKTOP_CORE} from '../../gate/layout.mjs';
import {BOARD_ART_BOUNDS} from '../../src/matching/cohesion/boardArt.js';
import {ORIGIN,MAX_PNG_FILES} from '../../gate/scope.mjs';
const contextAudits=new WeakMap();
export const OLD_KEYS=['moticos.career.garden.v1','moticos.matching.garden.v1','moticos.collection.garden.v1'];
export async function instrumentation(context){
 const observed=[];contextAudits.set(context,observed);await context.exposeBinding('__recordCareerWrite',(_,event)=>observed.push(event));
 await context.route('**/*',route=>new URL(route.request().url()).origin===ORIGIN?route.continue():route.abort('blockedbyclient'));
 await context.addInitScript(({keys,key})=>{const proto=Storage.prototype,original={get:proto.getItem,set:proto.setItem,remove:proto.removeItem,clear:proto.clear};window.__careerAudit=[];window.__rawStorage=original;window.__fixtureWrite=false;proto.setItem=function(k,v){if(this===localStorage){const event={op:'set',key:k,fixture:window.__fixtureWrite};window.__careerAudit.push(event);void window.__recordCareerWrite(event);}return original.set.call(this,k,v);};proto.removeItem=function(k){if(this===localStorage){const event={op:'remove',key:k,fixture:window.__fixtureWrite};window.__careerAudit.push(event);void window.__recordCareerWrite(event);}return original.remove.call(this,k);};proto.clear=function(){if(this===localStorage){const event={op:'clear',fixture:window.__fixtureWrite};window.__careerAudit.push(event);void window.__recordCareerWrite(event);}return original.clear.call(this);};const mode=window.name;if(mode.startsWith('career-fault:')){const fault=mode.slice(13);if(fault==='read'){const get=proto.getItem;proto.getItem=function(k){if(this===localStorage&&k===key)throw new DOMException('Synthetic read denial','SecurityError');return get.call(this,k);};}if(fault==='quota'){const set=proto.setItem;proto.setItem=function(k,v){if(this===localStorage&&k===key)throw new DOMException('Synthetic quota failure','QuotaExceededError');return set.call(this,k,v);};}if(fault==='lock')Object.defineProperty(navigator,'locks',{configurable:true,value:undefined});}},{keys:OLD_KEYS,key:STORAGE_KEY});
}
export async function open(page){await page.goto('/career.html');await expect(page.locator('.career-shell')).toHaveAttribute('data-save-status','saved');await expect(page.locator('[data-career-cell]')).toHaveCount(25);await seedSentinels(page);}
export async function seedSentinels(page){await page.evaluate(async({keys,lock})=>{await navigator.locks.request(lock,{mode:'exclusive'},()=>{window.__fixtureWrite=true;for(const k of keys)localStorage.setItem(k,'protected synthetic sentinel');window.__fixtureWrite=false;});},{keys:OLD_KEYS,lock:LOCK_NAME});}
export async function read(page){return page.evaluate(key=>JSON.parse(localStorage.getItem(key)),STORAGE_KEY);}
export async function bytes(page){return page.evaluate(key=>localStorage.getItem(key),STORAGE_KEY);}
export async function seed(page,state){validateCareer(state);await page.evaluate(async({key,lock,state})=>{await navigator.locks.request(lock,{mode:'exclusive'},()=>{window.__fixtureWrite=true;localStorage.setItem(key,JSON.stringify(state));window.__fixtureWrite=false;});},{key:STORAGE_KEY,lock:LOCK_NAME,state});await page.reload();await expect(page.locator('.career-shell')).toHaveAttribute('data-save-status','saved');await expect.poll(async()=>(await read(page)).careerId).toBe(state.careerId);}
export async function audit(page){const result=await page.evaluate(({keys,key})=>({sentinels:keys.map(k=>window.__rawStorage.get.call(localStorage,k)),bad:window.__careerAudit.filter(e=>!e.fixture&&(e.op==='clear'||e.key!==key))}),{keys:OLD_KEYS,key:STORAGE_KEY});expect(result.sentinels).toEqual(OLD_KEYS.map(()=>'protected synthetic sentinel'));expect(result.bad).toEqual([]);expect((contextAudits.get(page.context())??[]).filter(e=>!e.fixture&&(e.op==='clear'||e.key!==STORAGE_KEY))).toEqual([]);validateCareer(await read(page));}
export async function press(locator,touch=false){return touch?locator.tap():locator.click();}
export async function changed(page,before,fn){await fn();await expect.poll(async()=>(await read(page)).revision).toBe(before.revision+1);await expect(page.locator('.career-cell').first()).toBeEnabled();return read(page);}
export async function draw(page,familyId,{basic=false,to=null,touch=false}={}){const s=await read(page),family=CATALOG.FAMILIES.find(f=>f.id===familyId);if(to!==null)await press(page.locator(`[data-career-cell="${to}"]`),touch);const loc=basic&&s.sources[familyId].sorter?page.locator(`.career-producer.${familyId} .career-basic-supply`):page.getByRole('button',{name:new RegExp(`^Add free ${family.shortName} supply:`)});const next=await changed(page,s,()=>press(loc,touch));const old=new Set(s.board.filter(Boolean).map(t=>t.id));return[next,next.board.find(t=>t&&!old.has(t.id)).id];}
export async function merge(page,a,b,touch=false){const s=await read(page),from=s.board.findIndex(t=>t?.id===a),to=s.board.findIndex(t=>t?.id===b);expect(from).toBeGreaterThanOrEqual(0);expect(to).toBeGreaterThanOrEqual(0);await press(page.locator(`[data-career-cell="${from}"]`),touch);const next=await changed(page,s,()=>press(page.locator(`[data-career-cell="${to}"]`),touch));return[next,next.board[to].id];}
export async function make(page,id,touch=false){const p=CATALOG.pieceOf(id);if(p.tier===1)return draw(page,p.familyId,{basic:true,touch});let a,b;[,a]=await make(page,CATALOG.previousPiece(id).id,touch);[,b]=await make(page,CATALOG.previousPiece(id).id,touch);return merge(page,a,b,touch);}
export async function readyUI(page,order,touch=false){const reserved=new Set();for(const r of order.requirements)for(let n=0;n<r.quantity;n++){let s=await read(page),tile=s.board.find(t=>t?.pieceId===r.pieceId&&!reserved.has(t.id));if(!tile){let id;[s,id]=await make(page,r.pieceId,touch);tile=s.board.find(t=>t?.id===id);}reserved.add(tile.id);}return read(page);}
// Responsive layouts intentionally keep both controls in the DOM. Match the
// currently rendered surface, never DOM position or the first hidden match.
export function sendControl(page,orderId=null){return page.locator(orderId?`[data-order-id="${orderId}"] .career-send:visible`:'.career-send:visible');}
export async function send(page,order,touch=false){await focusOrder(page,order.id,touch);const s=await readyUI(page,order,touch);const next=await changed(page,s,()=>press(sendControl(page,order.id),touch));await expect(page.locator('.career-status')).toContainText('saved');return next;}
export async function buy(page,id,touch=false){await panel(page,'shop',touch);const s=await read(page);const article=page.getByRole('dialog').locator('.career-upgrades article').filter({has:page.getByRole('heading',{name:id==='order-desk'?'Order desk':`${id.split('-')[0][0].toUpperCase()}${id.split('-')[0].slice(1)} sorter I`,exact:true})});const next=await changed(page,s,()=>press(article.getByRole('button',{name:/^Buy/}),touch));await expect(article.getByRole('button',{name:'Owned ✓'})).toBeDisabled();await close(page,touch);return next;}
export async function compact(page){return compactSurface(page);}
export async function panel(page,type,touch=false){if(await compact(page)){if(type==='sources'){await press(page.locator('.career-source-picker'),touch);}else if(type==='progress')await press(page.locator('.career-mobile-progress-button'),touch);else if(type==='orders')await press(page.locator('.career-mobile-orders-button'),touch);else{await press(page.locator('.career-mobile-more-button'),touch);const names={shop:'Upgrades',collection:/^Collection/,help:'How to play',postcard:'Last letter',letters:/^Correspondence/};if(type!=='more')await press(page.getByRole('dialog').getByRole('button',{name:names[type],exact:typeof names[type]==='string'}),touch);}}else{const selectors={shop:'.career-shop-button',collection:'.career-collection-button',help:'button[aria-label="How to play"]',postcard:'.career-receipt-postcard',letters:'.career-correspondence-link',orders:'.career-correspondence-link',sources:'.career-source-picker'};await press(page.locator(selectors[type]),touch);}await expect(page.getByRole('dialog')).toBeVisible();}
export async function focusOrder(page,orderId,touch=false){if(!await compact(page)){if((await read(page)).focusedOrderId!==orderId){const before=await read(page);await changed(page,before,()=>press(page.locator(`.career-order[data-order-id="${orderId}"] .career-order-title`),touch));}return;}if(await page.locator('.career-mobile-order-strip').getAttribute('data-order-id')===orderId)return;await panel(page,'orders',touch);const choice=page.getByRole('dialog').locator('.career-order-choices>section').filter({has:page.locator(`[data-order-id="${orderId}"]`)});await press(choice.locator('.career-focus-order'),touch);await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('.career-mobile-order-strip')).toHaveAttribute('data-order-id',orderId);await expect.poll(async()=>(await read(page)).focusedOrderId).toBe(orderId);}
export async function close(page,touch=false){await press(page.getByRole('dialog').getByRole('button',{name:'Close and return to board'}),touch);await expect(page.getByRole('dialog')).toHaveCount(0);}
export async function undo(page,touch=false){const s=await read(page);return changed(page,s,()=>press(page.getByRole('button',{name:'Undo',exact:true}),touch));}
export async function snapshot(page,info,label){const root=join('campaign-results',info.project.name,'screenshots');mkdirSync(root,{recursive:true});const total=['campaign-chromium','campaign-webkit-phone'].reduce((n,p)=>{try{return n+readdirSync(join('campaign-results',p,'screenshots')).filter(n=>n.endsWith('.png')).length;}catch{return n;}},0);assert(total<MAX_PNG_FILES,'Screenshot cap exceeded');const path=join(root,`${info.title.slice(0,3)}-${label}.png`);const dimensions=await page.evaluate(()=>[Math.round(innerWidth*devicePixelRatio),Math.round(Math.max(document.documentElement.scrollHeight,innerHeight)*devicePixelRatio)]);await page.screenshot({path,fullPage:true});const png=readFileSync(path);verifyPng(png,dimensions);let captures=[];try{captures=JSON.parse(readFileSync(join(root,'manifest.json'),'utf8'));}catch{}captures.push({sourceFingerprint:JSON.parse(readFileSync('campaign-build.json','utf8')).sourceFingerprint,caseId:info.title.slice(0,3),label,path,bytes:png.length,sha256:createHash('sha256').update(png).digest('hex'),dimensions});writeFileSync(join(root,'manifest.json'),JSON.stringify(captures,null,2)+'\n');info.annotations.push({type:'screenshot',description:path});}
export async function record(info,label,data){const path=join('campaign-results',info.project.name,`${info.title.slice(0,3)}-${label}.json`);mkdirSync(join('campaign-results',info.project.name),{recursive:true});const binding={sourceFingerprint:JSON.parse(readFileSync('campaign-build.json','utf8')).sourceFingerprint,caseId:info.title.slice(0,3)};writeFileSync(path,JSON.stringify(Array.isArray(data)?{rows:data,...binding}:{...data,...binding},null,2)+'\n');await info.attach(label,{path,contentType:'application/json'});}
export async function holdLock(page){await page.evaluate(async lock=>{window.__gateReady=new Promise(resolve=>{navigator.locks.request(lock,{mode:'exclusive'},async()=>{window.__releaseGate=null;const blocked=new Promise(r=>window.__releaseGate=r);resolve();await blocked;});});await window.__gateReady;},LOCK_NAME);}
export async function releaseLock(page){await page.evaluate(()=>window.__releaseGate());}
export async function race(page,other,clickA,clickB){const before=await read(page);await holdLock(page);await Promise.all([clickA(),clickB()]);await expect.poll(()=>page.evaluate(async lock=>(await navigator.locks.query()).pending.filter(x=>x.name===lock).length,LOCK_NAME)).toBe(2);await releaseLock(page);await expect.poll(async()=>(await read(page)).revision).toBe(before.revision+1);await expect.poll(async()=>(await read(other)).revision).toBe(before.revision+1);await expect(page.locator('.career-cell').first()).toBeEnabled();await expect(other.locator('.career-cell').first()).toBeEnabled();return read(page);}
export async function noOverflow(page,{desktop=false,touch=false,mode=desktop?'desktop':touch?'standard-phone':'large-text'}={}){
 const state=await read(page),selectors=mode==='standard-phone'?MOBILE_CORE:DESKTOP_CORE;
 const result=await page.evaluate(({selectors})=>{const rect=el=>{if(!el)return null;const r=el.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom};};const visible=el=>el.getClientRects().length&&getComputedStyle(el).visibility!=='hidden';const activeRoot=document.querySelector('dialog[open]')??document.querySelector('.career-shell');const kind=el=>el.matches('[data-career-cell]')?'cell':el.matches('.career-supply')?'supply':el.matches('.career-basic-supply')?'basic-supply':el.matches('.career-mobile-send')?'send':el.closest('.career-tools')&&el.textContent.trim()==='Undo'?'undo':'other';const controls=[...activeRoot.querySelectorAll('button')].filter(visible).map(el=>({label:el.getAttribute('aria-label')||el.textContent.trim(),kind:kind(el),box:rect(el)}));return{width:innerWidth,height:innerHeight,scrollY,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,largeText:document.querySelector('.career-shell').classList.contains('is-large-text'),modal:!!document.querySelector('dialog[open]'),bounds:Object.fromEntries(selectors.map(s=>[s,rect(document.querySelector(s))])),controls};},{selectors});
 const expectedBasicSources=state.activeSourceIds.filter(id=>state.sources[id].sorter>0).length;
 expect(layoutViolations(result,{mode,expectedBasicSources,expectedSend:state.orders.length?1:0})).toEqual([]);
 // Geometry is checked before any scroll-to-hit inspection. Standard mode may
 // not rescue offscreen controls by scrolling them into view.
 const hitProof=await page.evaluate(({mode,core})=>{const x=scrollX,y=scrollY,rails=[...document.querySelectorAll('.career-order-list,.career-board')].map(el=>[el,el.scrollLeft]);const bad=[],clippedText=[];for(const el of (document.querySelector('dialog[open]')??document.querySelector('.career-shell')).querySelectorAll('button')){if(!el.getClientRects().length)continue;if(mode==='desktop'&&!el.closest(core.join(',')))continue;if(mode==='large-text'||mode==='panel')el.scrollIntoView({block:'nearest',inline:'nearest',behavior:'instant'});const r=el.getBoundingClientRect(),cx=r.x+r.width/2,cy=r.y+r.height/2;const points=[[cx,cy],[r.x+r.width*.2,cy],[r.x+r.width*.8,cy],[cx,r.y+r.height*.2],[cx,r.y+r.height*.8]];if(points.some(([px,py])=>{const hit=document.elementFromPoint(px,py);return !hit||!(hit===el||el.contains(hit));}))bad.push(el.getAttribute('aria-label')||el.textContent);}for(const el of document.querySelectorAll('.career-cell-label,.career-target strong,.career-mobile-target strong,.career-supply small,.career-rewards,.career-mobile-progress-button strong,.career-mobile-progress-button>span,.career-status-short'))if(el.getClientRects().length&&(el.scrollWidth>el.clientWidth+1||el.scrollHeight>el.clientHeight+1))clippedText.push(el.textContent);for(const[el,left]of rails)el.scrollLeft=left;scrollTo(x,y);return{bad,clippedText,scrollY};},{mode,core:DESKTOP_CORE});
 expect(hitProof.bad).toEqual([]);expect(hitProof.clippedText).toEqual([]);if(mode==='standard-phone')expect(hitProof.scrollY).toBe(0);return{...result,mode,hitProof};
}
export async function imageProof(page){await expect.poll(()=>page.locator('.career-shell img:visible').evaluateAll(nodes=>nodes.every(img=>img.complete&&img.naturalWidth>0))).toBe(true);const state=await read(page),sources=Object.fromEntries(CATALOG.FAMILIES.filter(f=>state.unlockedSources.includes(f.id)).map(f=>[f.id,nextOutput(state,f.id).id])),names=Object.fromEntries(CATALOG.PIECES.map(p=>[p.name,p.id]));const records=await page.locator('.career-shell img:visible').evaluateAll((nodes,{sources,names})=>nodes.map(img=>{const cell=img.closest('[data-piece-id]'),mobileTarget=img.closest('[data-target-piece-id]'),target=img.closest('.career-target'),producer=img.closest('.career-producer'),collection=img.closest('.career-collection-grid button'),postcard=img.closest('.career-postcard');const pieceId=cell?.dataset.pieceId??mobileTarget?.dataset.targetPieceId??(target?names[target.querySelector('strong').textContent]:producer?sources[Object.keys(sources).find(id=>producer.classList.contains(id))]:collection?names[collection.querySelector('strong').textContent]:postcard?names[document.querySelector('#career-dialog-title').textContent]:null);return{pieceId,board:!!cell,src:img.currentSrc,loaded:img.complete,width:img.naturalWidth,height:img.naturalHeight,display:img.getBoundingClientRect().width,displayHeight:img.getBoundingClientRect().height};}),{sources,names});expect(records.length).toBeGreaterThan(0);if(!await page.getByRole('dialog').count())expect(records.filter(r=>r.board).map(r=>r.pieceId).sort(),'Every occupied board cell must expose its actual visible artwork').toEqual(state.board.filter(Boolean).map(t=>t.pieceId).sort());const proof=[];for(const r of records){expect(r.loaded).toBe(true);expect(r.width).toBeGreaterThan(0);expect(r.height).toBeGreaterThan(0);expect(r.display).toBeGreaterThan(8);expect(new URL(r.src).origin).toBe(ORIGIN);const response=await page.request.get(r.src);expect(response.ok()).toBe(true);const body=await response.body();proof.push({...r,bytes:body.length,sha256:createHash('sha256').update(body).digest('hex')});}const assets=JSON.parse(readFileSync('campaign-build.json','utf8')).art;for(const r of proof){expect(Math.abs(r.display/r.displayHeight-r.width/r.height),'Artwork must retain its natural aspect ratio').toBeLessThan(.03);if(r.board&&await compact(page)){const b=BOARD_ART_BOUNDS[r.pieceId];const ink=Math.max(b.ink[2]/b.source[0]*r.display,b.ink[3]/b.source[1]*r.displayHeight);expect(ink,'Board art must not be made tiny to force fit').toBeGreaterThanOrEqual(28);}expect(r.pieceId,'Rendered image has an explicit game identity').toBeTruthy();expect(assets.find(a=>a.id===r.pieceId)?.sha256).toBe(r.sha256);}return proof;}
export async function visibleNotice(page, text, {large=false}={}) {
 const loc=page.locator(large?'.career-status-long':await compact(page)?'.career-status-short':'.career-status-long');
 await expect(loc).toContainText(text);if(large)await loc.scrollIntoViewIfNeeded();await expect(loc).toBeInViewport({ratio:1});
 const clipped=await loc.evaluate(el=>el.scrollWidth>el.clientWidth+1||el.scrollHeight>el.clientHeight+1);expect(clipped).toBe(false);
}
export async function selectSource(page,familyId,slot=0,touch=false){
 const s=await read(page);if(s.activeSourceIds[slot]===familyId)return s;
 await panel(page,'sources',touch);const name=CATALOG.FAMILIES.find(f=>f.id===familyId).shortName;
 const next=await changed(page,s,()=>press(page.getByRole('dialog').locator('.career-source-panel').getByRole('button',{name:new RegExp(`^${name}, ${slot?'right':'left'} source`)}),touch));await close(page,touch);return next;
}
export async function startChapter(page,touch=false){
 const before=await read(page);const openButton=await compact(page)?page.locator('.career-mobile-order-details'):page.locator('.career-finished').getByRole('button',{name:'Open Moonlit Correspondence',exact:true});
 await press(openButton,touch);await expect(page.getByRole('dialog')).toBeVisible();const next=await changed(page,before,()=>press(page.getByRole('dialog').getByRole('button',{name:'Begin Moonlit Correspondence',exact:true}),touch));await expect(page.getByRole('dialog')).toHaveCount(0);return next;
}

export function collectionPiece(page,pieceId){const piece=CATALOG.pieceOf(pieceId);if(!piece)throw Error('Unknown collection piece');return page.getByRole('dialog').locator('.career-collection-grid').getByRole('button',{name:`${piece.name} Level ${piece.tier} · collected`,exact:true});}
