import {test,expect} from '@playwright/test';
import {CASES,titleFor} from '../../gate/scope.mjs';
import {PHONE_VIEWPORTS,gridViolations} from '../../gate/layout.mjs';
import * as h from './helpers.mjs';
import * as f from './fixtures.mjs';
import * as adopted from './adopted-journeys.mjs';
const {C,E}=f,cases=CASES['campaign-webkit-phone'];
function check(index,fn){const[id,title,timeout]=cases[index];test(titleFor(id,title),async({page,context},info)=>{test.setTimeout(timeout);await h.instrumentation(context);const errors=[];context.on('page',p=>p.on('pageerror',e=>errors.push(String(e))));page.on('pageerror',e=>errors.push(String(e)));await fn({page,context},info);expect(errors).toEqual([]);await h.audit(page);});}
check(0,(args,info)=>adopted.fresh(args,info,true));
check(1,async(args,info)=>{await adopted.chapter(args,info,true);const{page}=args;await h.seed(page,f.route(11));const state=await h.read(page),chosen=state.orders.at(-1);await h.focusOrder(page,chosen.id,true);const focused=await h.read(page);await h.selectSource(page,'bird',0,true);await page.reload();let next=await h.read(page);expect(next.focusedOrderId).toBe(chosen.id);expect(next.activeSourceIds[0]).toBe('bird');for(const k of['board','material','sources','orders'])expect(next[k]).toEqual(focused[k]);await h.panel(page,'sources',true);await expect(page.getByRole('button',{name:/Moon, left source/})).toHaveCount(1);await h.close(page,true);await h.record(info,'touch-goal-return',next);});
check(2,async({page},info)=>{
 await h.open(page);const rows=[],moon=f.allArt();for(const size of PHONE_VIEWPORTS){await page.setViewportSize(size);for(const kind of['fresh','moon']){await h.seed(page,kind==='fresh'?E.createCareer(`browser-phone-${size.width}`):moon);const proof=await h.noOverflow(page,{touch:true});expect(gridViolations(proof.controls.filter(c=>c.kind==='cell').map(c=>c.box))).toEqual([]);rows.push({size,kind,...proof});if(kind==='moon')await h.snapshot(page,info,`${size.width}x${size.height}-moon`);}}const images=await h.imageProof(page);await h.record(info,'phone-core-geometry',{rows,images});
});
check(3,async({page},info)=>{
 await h.open(page);await h.seed(page,f.route(5));await h.panel(page,'help',true);let s=await h.read(page);await h.changed(page,s,()=>page.getByRole('button',{name:'Use larger text',exact:true}).tap());await h.close(page,true);await h.buy(page,'bird-sorter',true);await h.visibleNotice(page,/Bird sorter I is yours/,{large:true});await h.draw(page,'bird',{touch:true});await h.visibleNotice(page,/added for free/,{large:true});await h.undo(page,true);await h.visibleNotice(page,/Undone/,{large:true});await page.reload();await expect(page.locator('.career-shell')).toHaveClass(/is-large-text/);await h.record(info,'larger-text-geometry',await h.noOverflow(page,{mode:'large-text'}));
 s=f.act(f.full(),{type:'large-text',enabled:true});await h.seed(page,s);const bytes=await h.bytes(page);await page.locator('.career-supply').first().tap();await h.visibleNotice(page,/table is full/,{large:true});expect(await h.bytes(page)).toBe(bytes);const at=s.board.findIndex(t=>t?.pieceId==='b3');await page.locator(`[data-career-cell="${at}"]`).tap();await page.getByRole('button',{name:'Cut',exact:true}).tap();await h.visibleNotice(page,/one empty space/,{large:true});expect(await h.bytes(page)).toBe(bytes);await h.snapshot(page,info,'large-error-feedback');let moon=f.act(f.route(11),{type:'large-text',enabled:true});await h.seed(page,moon);await h.panel(page,'sources',true);await h.record(info,'larger-text-source-panel',await h.noOverflow(page,{mode:'panel'}));const small=page.locator('.career-source-options button small').first();expect(await small.evaluate(el=>parseFloat(getComputedStyle(el).fontSize))).toBeGreaterThanOrEqual(14.99);await h.snapshot(page,info,'large-source-panel');await h.close(page,true);expect(await page.evaluate(()=>document.activeElement!==document.body)).toBe(true);
});
check(4,(args,info)=>adopted.replay(args,info,true));
check(5,async(args,info)=>{
 await adopted.full(args,info,true);const{page}=args;let s=f.route(3),order=s.orders[0];[s]=f.acquire(s,order.requirements[0].pieceId);await h.seed(page,s);const protectedIds=s.board.filter(t=>t?.pieceId===order.requirements[0].pieceId).slice(0,order.requirements[0].quantity).map(t=>t.id);await expect(page.locator('[data-needed-for-goal="true"]')).toHaveCount(protectedIds.length);const guidance=E.goalHint(s);await page.getByRole('button',{name:'Hint',exact:true}).tap();if(guidance.pair){for(const at of guidance.pair)expect(protectedIds).not.toContain(s.board[at].id);await expect(page.locator('.career-cell.is-hint')).toHaveCount(2);}expect(await h.read(page)).toEqual(s);s=f.ready(s,order);await h.seed(page,s);await page.getByRole('button',{name:'Hint',exact:true}).tap();await h.visibleNotice(page,/ready.*Send/);await expect(h.sendControl(page,order.id)).toBeFocused();await h.snapshot(page,info,'ready-hint');await h.record(info,'protected-goal-hints',{guidance,protectedIds,ready:s});
});
check(6,async({page},info)=>{
 await h.open(page);const rows=[];for(const kind of['delivery','purchase']){await page.evaluate(()=>window.name='');const fixture=f.act(kind==='delivery'?f.ready(f.route(5)):f.route(5),{type:'large-text',enabled:true});await h.seed(page,fixture);const original=await h.bytes(page);await page.evaluate(()=>window.name='career-fault:quota');await page.reload();if(kind==='delivery'){await h.sendControl(page,fixture.focusedOrderId).tap();await h.visibleNotice(page,/temporary, not saved/,{large:true});await expect(page.locator('.career-postmark')).toHaveCount(1);await expect(page.locator('.career-postmark')).toContainText('PRACTICE ONLY');await expect(page.locator('.career-postmark').filter({hasText:'SENT & SAVED'})).toHaveCount(0);}else{await h.panel(page,'shop',true);await page.locator('.career-upgrades article').filter({has:page.getByRole('heading',{name:'Bird sorter I',exact:true})}).getByRole('button',{name:'Buy · 50 coins'}).tap();const notice=page.locator('.career-purchase-feedback');await expect(notice).toContainText('not saved');await notice.scrollIntoViewIfNeeded();await expect(notice).toBeInViewport({ratio:1});await expect(page.locator('.career-shop-balance')).toContainText('temporary practice coins');await h.close(page,true);await h.visibleNotice(page,/not saved/,{large:true});}await expect(page.locator('.career-shell')).toHaveAttribute('data-save-status','practice');expect(await h.bytes(page)).toBe(original);rows.push({kind,statePreserved:true});if(kind==='purchase')await h.snapshot(page,info,'unsaved-purchase');await page.evaluate(()=>window.name='');await page.reload();await expect(page.locator('.career-shell')).toHaveAttribute('data-save-status','saved');expect(await h.bytes(page)).toBe(original);}await h.record(info,'temporary-feedback',rows);
});
