// Only generated by assemble_candidate.py after exact independent art acceptance.
const art = Object.freeze({
  wr1: new URL("./art/wr1.webp", import.meta.url).href,
  wr2: new URL("./art/wr2.webp", import.meta.url).href,
  wr3: new URL("./art/wr3.webp", import.meta.url).href,
  wr4: new URL("./art/wr4.webp", import.meta.url).href,
  wr5: new URL("./art/wr5.webp", import.meta.url).href,
  wa1: new URL("./art/wa1.webp", import.meta.url).href,
  wa2: new URL("./art/wa2.webp", import.meta.url).href,
  wa3: new URL("./art/wa3.webp", import.meta.url).href,
  wa4: new URL("./art/wa4.webp", import.meta.url).href,
  wa5: new URL("./art/wa5.webp", import.meta.url).href,
  ec1: new URL("./art/ec1.webp", import.meta.url).href,
  ec2: new URL("./art/ec2.webp", import.meta.url).href,
  ec3: new URL("./art/ec3.webp", import.meta.url).href,
  ec4: new URL("./art/ec4.webp", import.meta.url).href,
  ec5: new URL("./art/ec5.webp", import.meta.url).href,
  ce1: new URL("./art/ce1.webp", import.meta.url).href,
  ce2: new URL("./art/ce2.webp", import.meta.url).href,
  ce3: new URL("./art/ce3.webp", import.meta.url).href,
  ce4: new URL("./art/ce4.webp", import.meta.url).href,
  ce5: new URL("./art/ce5.webp", import.meta.url).href,
  pp1: new URL("./art/pp1.webp", import.meta.url).href,
  pp2: new URL("./art/pp2.webp", import.meta.url).href,
  pp3: new URL("./art/pp3.webp", import.meta.url).href,
  pp4: new URL("./art/pp4.webp", import.meta.url).href,
  pp5: new URL("./art/pp5.webp", import.meta.url).href,
  ss1: new URL("./art/ss1.webp", import.meta.url).href,
  ss2: new URL("./art/ss2.webp", import.meta.url).href,
  ss3: new URL("./art/ss3.webp", import.meta.url).href,
  ss4: new URL("./art/ss4.webp", import.meta.url).href,
  ss5: new URL("./art/ss5.webp", import.meta.url).href,
  cj1: new URL("./art/cj1.webp", import.meta.url).href,
  cj2: new URL("./art/cj2.webp", import.meta.url).href,
  cj3: new URL("./art/cj3.webp", import.meta.url).href,
  cj4: new URL("./art/cj4.webp", import.meta.url).href,
  cj5: new URL("./art/cj5.webp", import.meta.url).href,
  bh1: new URL("./art/bh1.webp", import.meta.url).href,
  bh2: new URL("./art/bh2.webp", import.meta.url).href,
  bh3: new URL("./art/bh3.webp", import.meta.url).href,
  bh4: new URL("./art/bh4.webp", import.meta.url).href,
  bh5: new URL("./art/bh5.webp", import.meta.url).href,
});
const definitions = [
  {
    "envelope": {
      "id": "batch-wrong-address",
      "contentRevision": 1,
      "saveSchemaVersion": 1,
      "title": "Wrong Address",
      "subtitle": "Wrong Address",
      "description": "Two routes argue gently about where an image belongs.",
      "storageKey": "moticos.matching.batch-wrong-address.v1"
    },
    "catalog": {
      "id": "batch-wrong-address",
      "rows": [
        [
          "wr1",
          "wing",
          1,
          "Bird",
          "Bird",
          "A right-facing black print bird on ivory, with a blue river bend and red underline.",
          "wr1"
        ],
        [
          "wr2",
          "wing",
          2,
          "River Wing",
          "Wing",
          "A broad upraised map-wing turns feather lines into roads around a blue river.",
          "wr2"
        ],
        [
          "wr3",
          "wing",
          3,
          "Address Window",
          "Window",
          "A tall notched map clipping holds a bird head inside a round transparent window.",
          "wr3"
        ],
        [
          "wr4",
          "wing",
          4,
          "Here and There",
          "Across",
          "Unequal map-wings face across a deep transparent cleft, joined by a red route.",
          "wr4"
        ],
        [
          "wr5",
          "wing",
          5,
          "Arrival",
          "Arrival",
          "A rising angular route links a printed bird to a bird-shaped transparent window.",
          "wr5"
        ],
        [
          "wa1",
          "shoe",
          1,
          "Shoe",
          "Shoe",
          "A flat black lace-up shoe with three ivory eyelets and a red arch tab.",
          "wa1"
        ],
        [
          "wa2",
          "shoe",
          2,
          "Route",
          "Route",
          "A tall footprint-shaped map places a red route between a black toe cap and heel.",
          "wa2"
        ],
        [
          "wa3",
          "shoe",
          3,
          "Go",
          "Go",
          "Unequal shoe fragments and a curved sole form an open arch above a red GO route.",
          "wa3"
        ],
        [
          "wa4",
          "shoe",
          4,
          "Stay",
          "Stay",
          "A long diagonal shoe-strip crosses a small upright door-shaped map marker.",
          "wa4"
        ],
        [
          "wa5",
          "shoe",
          5,
          "Walkaway",
          "Walkaway",
          "Four angular shoe fragments form an open X with a shoe-shaped transparent absence.",
          "wa5"
        ]
      ],
      "families": [
        {
          "id": "wing",
          "name": "Wing Routes",
          "shortName": "Wing",
          "color": "#486977",
          "pieceIds": [
            "wr1",
            "wr2",
            "wr3",
            "wr4",
            "wr5"
          ]
        },
        {
          "id": "shoe",
          "name": "Walkaway",
          "shortName": "Shoe",
          "color": "#9c4d40",
          "pieceIds": [
            "wa1",
            "wa2",
            "wa3",
            "wa4",
            "wa5"
          ]
        }
      ]
    }
  },
  {
    "envelope": {
      "id": "batch-quiet-company",
      "contentRevision": 1,
      "saveSchemaVersion": 1,
      "title": "Quiet Company",
      "subtitle": "Quiet Company",
      "description": "Seats, cups and absences keep one another company.",
      "storageKey": "moticos.matching.batch-quiet-company.v1"
    },
    "catalog": {
      "id": "batch-quiet-company",
      "rows": [
        [
          "ec1",
          "chair",
          1,
          "Chair",
          "Chair",
          "A front-facing black print chair with three back slats and an off-center red seat patch.",
          "ec1"
        ],
        [
          "ec2",
          "chair",
          2,
          "Window",
          "Window",
          "The chair back spreads into a wide low frame with three transparent window openings.",
          "ec2"
        ],
        [
          "ec3",
          "chair",
          3,
          "Invitation",
          "Invite",
          "A tall slanted chair-back clipping surrounds a large empty seat aperture above SIT.",
          "ec3"
        ],
        [
          "ec4",
          "chair",
          4,
          "Wait",
          "Wait",
          "Unequal chair-back fragments face across a deep empty cleft joined by a red strip.",
          "ec4"
        ],
        [
          "ec5",
          "chair",
          5,
          "Company",
          "Company",
          "Offset chair-back and seat-rail fragments share a long red seat across an open corner.",
          "ec5"
        ],
        [
          "ce1",
          "cup",
          1,
          "Cup",
          "Cup",
          "A low ivory printed cup with a dark circular handle, bold rim and small red tab.",
          "ce1"
        ],
        [
          "ce2",
          "cup",
          2,
          "Full",
          "Full",
          "An enlarged upright handle loop is crossed by a rim bar carrying a small cup fragment.",
          "ce2"
        ],
        [
          "ce3",
          "cup",
          3,
          "Empty",
          "Empty",
          "Upright and inverted cup fragments meet at a narrow red waist between two handle arcs.",
          "ce3"
        ],
        [
          "ce4",
          "cup",
          4,
          "Answer",
          "Answer",
          "Two angled bowl fragments face across a large round gap edged by split handle arcs.",
          "ce4"
        ],
        [
          "ce5",
          "cup",
          5,
          "Echo",
          "Echo",
          "A wide shallow bowl holds the former handle as a circular empty space within a red band.",
          "ce5"
        ]
      ],
      "families": [
        {
          "id": "chair",
          "name": "Empty Chair",
          "shortName": "Chair",
          "color": "#486977",
          "pieceIds": [
            "ec1",
            "ec2",
            "ec3",
            "ec4",
            "ec5"
          ]
        },
        {
          "id": "cup",
          "name": "Cup Echo",
          "shortName": "Cup",
          "color": "#9c4d40",
          "pieceIds": [
            "ce1",
            "ce2",
            "ce3",
            "ce4",
            "ce5"
          ]
        }
      ]
    }
  },
  {
    "envelope": {
      "id": "batch-namesakes",
      "contentRevision": 1,
      "saveSchemaVersion": 1,
      "title": "Namesakes",
      "subtitle": "Namesakes",
      "description": "A pear and a fish find meanings hidden in their names.",
      "storageKey": "moticos.matching.batch-namesakes.v1"
    },
    "catalog": {
      "id": "batch-namesakes",
      "rows": [
        [
          "pp1",
          "pear",
          1,
          "Crooked Pear",
          "Pear",
          "A black printed pear with a left-hooking stem, large veined leaf and a dark teardrop seed, caught by a red strip.",
          "pp1"
        ],
        [
          "pp2",
          "pear",
          2,
          "Pair Hinge",
          "Pair",
          "Two unequal pear-shaped lobes part above a red PAIR hinge; one retains the stem and the other the leaf and seed.",
          "pp2"
        ],
        [
          "pp3",
          "pear",
          3,
          "Seed Leaf",
          "Seedleaf",
          "The leaf and pear curve make a horizontal open frame around the inherited seed, with PEAR along its low edge.",
          "pp3"
        ],
        [
          "pp4",
          "pear",
          4,
          "Split",
          "Split",
          "A crooked pear curve and an upright veined leaf stand apart, joined by a red bridge with a seed suspended below.",
          "pp4"
        ],
        [
          "pp5",
          "pear",
          5,
          "Namesake",
          "Namesake",
          "Two unequal pear-shaped transparent spaces sit beneath a diagonal veined leaf, with the seed extending into the larger opening.",
          "pp5"
        ],
        [
          "ss1",
          "fish",
          1,
          "Fish",
          "Fish",
          "A black-and-ivory woodcut fish has a bold round eye, three gill cuts, a pointed fin and a deeply notched tail.",
          "ss1"
        ],
        [
          "ss2",
          "fish",
          2,
          "Tide",
          "Tide",
          "A faded-blue wave slices across an angular pennant, separating an upturned fish head from its tail and scale-printed lower edge.",
          "ss2"
        ],
        [
          "ss3",
          "fish",
          3,
          "Lookout",
          "Lookout",
          "An open circular eye-ring sits above a narrow scale-printed column ending in a forked tail, with SEE at the red crosspiece.",
          "ss3"
        ],
        [
          "ss4",
          "fish",
          4,
          "Facing",
          "Facing",
          "A large curved fish head faces a smaller tail-and-ring fragment across a broad open gap, joined below by blue waves.",
          "ss4"
        ],
        [
          "ss5",
          "fish",
          5,
          "Seesaw",
          "Seesaw",
          "A broad low wave band surrounds a fish-shaped transparent opening, with the eye at left and the notched tail projecting at right.",
          "ss5"
        ]
      ],
      "families": [
        {
          "id": "pear",
          "name": "Pear / Pair",
          "shortName": "Pear/Pair",
          "color": "#486977",
          "pieceIds": [
            "pp1",
            "pp2",
            "pp3",
            "pp4",
            "pp5"
          ]
        },
        {
          "id": "fish",
          "name": "Sea / See",
          "shortName": "Sea/See",
          "color": "#9c4d40",
          "pieceIds": [
            "ss1",
            "ss2",
            "ss3",
            "ss4",
            "ss5"
          ]
        }
      ]
    }
  },
  {
    "envelope": {
      "id": "batch-useful-gaps",
      "contentRevision": 1,
      "saveSchemaVersion": 1,
      "title": "Useful Gaps",
      "subtitle": "Useful Gaps",
      "description": "Cuts and openings turn practical fragments into correspondence.",
      "storageKey": "moticos.matching.batch-useful-gaps.v1"
    },
    "catalog": {
      "id": "batch-useful-gaps",
      "rows": [
        [
          "cj1",
          "scissors",
          1,
          "Scissors",
          "Scissors",
          "A nearly closed printed pair of scissors angles upward, with unequal open handle rings, a round rivet and a red offcut.",
          "cj1"
        ],
        [
          "cj2",
          "scissors",
          2,
          "Loops",
          "Loops",
          "The unequal rings spread into a low sideways double loop with a short blade and rivet crossing the waist.",
          "cj2"
        ],
        [
          "cj3",
          "scissors",
          3,
          "Join",
          "Join",
          "Two offset vertical blade-and-handle strips stand across a rectangular gap, joined by a red bar at the rivet.",
          "cj3"
        ],
        [
          "cj4",
          "scissors",
          4,
          "Overcut",
          "Overcut",
          "A long shallow blade-slash carries two unequal open handle curls underneath it.",
          "cj4"
        ],
        [
          "cj5",
          "scissors",
          5,
          "Crossjoin",
          "Crossjoin",
          "A spread X separates the oval and round handle fragments from a red-joined diagonal of two blunt blades.",
          "cj5"
        ],
        [
          "bh1",
          "button",
          1,
          "Button",
          "Button",
          "A dark printed four-hole button sits inside an uneven ivory rim, with red thread passing through its left holes.",
          "bh1"
        ],
        [
          "bh2",
          "button",
          2,
          "Clasp",
          "Clasp",
          "Two opposed half-button clippings sit above and below a transparent slit, held at the left by a red stitch.",
          "bh2"
        ],
        [
          "bh3",
          "button",
          3,
          "Threadway",
          "Threadway",
          "Four large round transparent windows line up in a low black strip, crossed by blue thread and a red end stitch.",
          "bh3"
        ],
        [
          "bh4",
          "button",
          4,
          "Open",
          "Open",
          "Two curved button halves surround a slanted diamond-shaped opening, joined by blue and red stitches.",
          "bh4"
        ],
        [
          "bh5",
          "button",
          5,
          "Unfold",
          "Unfold",
          "Unequal openwork button wings spread like a flat bow, connected by crossing red and blue stitches.",
          "bh5"
        ]
      ],
      "families": [
        {
          "id": "scissors",
          "name": "Cut / Join",
          "shortName": "Cut/Join",
          "color": "#486977",
          "pieceIds": [
            "cj1",
            "cj2",
            "cj3",
            "cj4",
            "cj5"
          ]
        },
        {
          "id": "button",
          "name": "Buttonhole",
          "shortName": "Button",
          "color": "#9c4d40",
          "pieceIds": [
            "bh1",
            "bh2",
            "bh3",
            "bh4",
            "bh5"
          ]
        }
      ]
    }
  }
];
export const BATCH_DEFINITIONS = Object.freeze(definitions.map(item => Object.freeze({ ...item, catalog: { ...item.catalog, artUrl: asset => art[asset] } })));
