import test from 'node:test';
import assert from 'node:assert/strict';
import {retainedV5,retainedEntry,newChapterEntry,occupiedNewBoard} from './interaction-fixtures.mjs';
import {retainedTransition,occupiedProof,noViewWrites,exactScope} from './interaction-proofs.mjs';
import {C,E,d} from './fixtures.mjs';
import {inventory} from '../../full-campaign-gate/binding.mjs';
import {stageBSuites,RUNTIME_SUITES,BROWSER_CONTRACT_SUITES,EXECUTION_CONTRACT_SUITES} from '../suite-inventory.mjs';
import {CASE_LIMITS,PROFILE_MS,PROPOSAL,scenarioFor,verifyFilename,SCREENSHOTS,screenshotAllowed} from './scope.mjs';
import {createCareerSession as oldSession} from '../../src/career/session.v5.js';
import {commandFor as oldCommand} from '../../src/career/engine.v5.js';
import {storageHarness} from '../../tests/campaign-browser/save-fixtures.mjs';
test('preflight inventory separates runtime and browser contracts without omissions',()=>{const files=inventory('stage-b-evidence');assert.deepEqual(stageBSuites(files),{runtime:[...RUNTIME_SUITES],browserContracts:[...BROWSER_CONTRACT_SUITES],executionContracts:[...EXECUTION_CONTRACT_SUITES]});for(const file of [...RUNTIME_SUITES,...BROWSER_CONTRACT_SUITES,...EXECUTION_CONTRACT_SUITES])assert.throws(()=>stageBSuites(files.filter(f=>f.file!==file)));assert.throws(()=>stageBSuites([...files,{file:'stage-b-evidence/unregistered.test.mjs'}]));assert.throws(()=>stageBSuites([...files,{file:RUNTIME_SUITES[0]}]));});
test('paid-desk entry proof catches stock cursor payment promise and double-entry defects',()=>{const before=E.upgradeCareer(retainedV5()),after=retainedEntry();assert(before.sources.bird.cursor>0);assert(before.board.some(t=>t?.pieceId==='b5'));assert(retainedTransition(before,after));for(const mutate of [s=>s.board.fill(null),s=>s.sources.bird.cursor++,s=>s.coinsSpent++,s=>s.orders=s.orders.filter(o=>o.slot!==2),s=>s.heldOrders.push(s.heldOrders[0]),s=>s.revision++]){const broken=structuredClone(after);mutate(broken);assert.throws(()=>retainedTransition(before,broken));}});
test('all eight new families occupy real board tiles; layout proof rejects empty missing duplicate unloaded or zero-area images',()=>{const s=occupiedNewBoard(),ids=s.board.filter(Boolean).map(t=>t.pieceId);E.validateCareer(s);assert.deepEqual(ids.map(id=>C.CATALOG.pieceOf(id).familyId),C.FAMILIES.slice(40).map(f=>f.id));const proof={ready:true,missing:[],images:ids.map((pieceId,cell)=>({pieceId,cell:String(cell),ready:true,complete:true,natural:[100,100],display:[44,44]}))};assert(occupiedProof(proof,ids));for(const mutate of [p=>p.images=[],p=>p.images.pop(),p=>p.images[0]=p.images[1],p=>p.images[0].complete=false,p=>p.images[0].display=[0,44],p=>p.missing=['0']]){const broken=structuredClone(proof);mutate(broken);assert.throws(()=>occupiedProof(broken,ids));}});
test('new source gate fixtures retain paid desk and unlock only after the actual first delivery',()=>{for(const [number,family]of [[22,'tied-parcel'],[24,'trumpet']]){const s=newChapterEntry(number),o=s.orders.find(o=>o.storyLetterId===C.CHAPTERS[number-1].storyIds[0]),desk=s.orders.find(o=>o.slot===2);assert(desk);assert(!s.unlockedSources.includes(family));const high=structuredClone(s);high.xp=99999;assert(!E.reduceCareer(high,E.commandFor(high,{type:'supply',familyId:family})).ok);const next=d.complete(s,o);assert(next.unlockedSources.includes(family));assert.equal(next.material[family].generated,0);assert.deepEqual(next.orders.find(o=>o.slot===2),desk);}});

test('each authored draft case receives its explicit proposed timeout, never inherited200 limits',()=>{const declarations=[];let current;const fake=(title,fn)=>declarations.push({title,timeout:current});fake.describe=(id,fn)=>fn();fake.describe.configure=({timeout})=>current=timeout;const scenario=scenarioFor(fake);for(const [id,ms]of Object.entries(CASE_LIMITS)){scenario(id+' unit declaration',()=>{});assert.equal(declarations.at(-1).timeout,ms);}assert.equal(declarations.length,18);assert.equal(PROFILE_MS,2120000);assert.equal(PROPOSAL.totalSeconds,4720);assert.equal(PROPOSAL.approved,false);assert.throws(()=>scenario('B19 unregistered',()=>{}));});
 test('wrong actual download filename fails independently of cache parity',()=>{assert(verifyFilename('moticos-a-note-kept.png','moticos-a-note-kept.png'));for(const wrong of ['',undefined,'moticos-wrong.png','moticos-a-note-kept (1).png'])assert.throws(()=>verifyFilename(wrong,'moticos-a-note-kept.png'));});

test('view-only proof rejects redundant/transient career writes and wrong scoped grids',()=>{assert(noViewWrites([],C.STORAGE_KEY));assert(noViewWrites([{fixture:true,op:'set',key:C.STORAGE_KEY}],C.STORAGE_KEY));for(const op of ['set','remove','clear'])assert.throws(()=>noViewWrites([{fixture:false,op,key:C.STORAGE_KEY}],C.STORAGE_KEY));const ids=C.CATALOG.PIECES.slice(200).map(p=>p.id);assert(exactScope(ids,ids));for(const wrong of [[],ids.slice(1),C.CATALOG.PIECES.slice(160,200).map(p=>p.id),[...ids.slice(0,39),ids[0]]])assert.throws(()=>exactScope(wrong,ids));});
 test('a real frozen v5 session refuses v6 bytes and keeps repeated practice writes isolated',async()=>{const old=retainedV5(),h=storageHarness(old),session=oldSession(h);assert.equal((await session.open()).status,'saved');const v6=JSON.stringify(E.upgradeCareer(old));h.map.set(C.STORAGE_KEY,v6);const count=h.audit.filter(x=>x[0]==='set').length;const result=await session.commit(oldCommand(old,{type:'supply',familyId:old.activeSourceIds[0]}));assert.equal(result.status,'practice');assert.equal(result.ok,false);assert.equal(h.map.get(C.STORAGE_KEY),v6);assert.equal(h.audit.filter(x=>x[0]==='set').length,count);const again=await session.commit(oldCommand(old,{type:'supply',familyId:old.activeSourceIds[0]}));assert.equal(again.status,'practice');assert.equal(h.map.get(C.STORAGE_KEY),v6);assert.equal(h.audit.filter(x=>x[0]==='set').length,count);});

test('new screenshot inventory includes 360px and enlarged text and rejects undeclared captures',()=>{assert.equal(SCREENSHOTS.length,8);for(const name of SCREENSHOTS)assert(screenshotAllowed(name));assert(SCREENSHOTS.includes('B16-360-normal.png'));assert(SCREENSHOTS.includes('B16-360-large.png'));assert.equal(PROPOSAL.routineScreenshots,16);assert.throws(()=>screenshotAllowed('D14-new-family.png'));assert.throws(()=>screenshotAllowed('B16-375-normal.png'));});
