import { BOARD_ART_BOUNDS as PREVIOUS_BOUNDS, COMPACT_BOARD_LABELS as PREVIOUS_LABELS } from '../cohesion/boardArt.js';
import { EXPANSION200_BOUNDS, EXPANSION200_LABELS } from './bounds.js';
export const BOARD_ART_BOUNDS = Object.freeze({ ...PREVIOUS_BOUNDS, ...EXPANSION200_BOUNDS });
export const COMPACT_BOARD_LABELS = Object.freeze({ ...PREVIOUS_LABELS, ...EXPANSION200_LABELS });
