// Offline reconstructed fixture invariants; not native browser acceptance.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {gunzipSync} from 'node:zlib';import {createHash} from 'node:crypto';import {C,E,V,fixture} from './fixtures.mjs';
const data=JSON.parse(gunzipSync(fs.readFileSync(new URL('./fixtures.generated.json.gz',import.meta.url)))),sha=b=>createHash('sha256').update(b).digest('hex');
test('fixture inputs bind current product bytes and historical archive',()=>{assert.equal(data.schema,2);assert(data.inputFiles.length>100);for(const row of data.inputFiles){const bytes=fs.readFileSync(row.file);assert.equal(bytes.length,row.bytes);assert.equal(sha(bytes),row.sha256,row.file);}});
test('all fixture states validate through actual current upgrade',()=>{for(const[name,s]of Object.entries(data.fixtures)){const upgraded=E.upgradeCareer(s);E.validateCareer(upgraded);assert.equal(upgraded.schemaVersion,8,name);assert.equal(upgraded.contentVersion,8,name);assert.equal(upgraded.rulesVersion,2,name);}});
test('conservative final route adds19 stories455XP200coins and no purchases',()=>{const before=fixture('v8-before-entry'),after=fixture('completed320');assert.equal(before.xp,9375);assert.equal(after.xp,9830);assert.equal(after.milestones.length-before.milestones.length,19);assert.equal(after.coinsEarned-before.coinsEarned,200);assert.equal(after.coinsSpent,0);assert.deepEqual(after.purchases,{});assert(E.allAuthoredContentComplete(after));assert.equal(V.collectionScope(after,'all').total,320);assert.equal(C.levelDefinition(after).level,58);for(const id of before.milestones)assert.deepEqual(after.storyCompletions[id],before.storyCompletions[id]);});
test('all forty ordered crop-fixture pictures are truly earned',()=>{for(const[name,from]of [['stock-first20',280],['stock-last20',300]]){const s=fixture(name),ids=C.CATALOG.PIECES.slice(from,from+20).map(p=>p.id);assert.deepEqual(s.board.filter(Boolean).map(t=>t.pieceId),ids);assert.equal(s.board.filter(t=>!t).length,5);for(const id of ids)assert(s.discoveries.includes(id));}});
test('isolated tier-five discovery neither awards nor completes companions',()=>{for(const f of C.FAMILIES.slice(56)){const id=f.pieceIds[4],before=fixture(`postcard-${id}-before`),after=fixture(`postcard-${id}-after`);assert(!before.discoveries.includes(id));assert(after.discoveries.includes(id));for(const key of ['xp','coinsEarned','coinsSpent','milestones','storyCompletions'])assert.deepEqual(after[key],before[key]);assert(!E.chapterComplete(after));for(const other of C.FAMILIES.slice(56).filter(x=>x!==f))assert(!after.discoveries.includes(other.pieceIds[4]));}});
test('negative fixtures encode real highXP and exact duplicate-ID counterexample',()=>{const high=fixture('high-xp-before-mushroom');assert(high.xp>=9445);assert(!high.unlockedSources.includes('paper-mushroom'));assert(!E.canStartNextChapter(high));const s=fixture('post-cut-violin3'),o=s.orders.find(o=>o.storyLetterId==='room-for-rhythm-letter-3'),v=s.board.find(t=>t?.pieceId==='d320-vn3'),d=s.board.find(t=>t?.pieceId==='d320-dr2');const bad=E.reduceCareer(s,E.commandFor(s,{type:'complete',orderId:o.id,tileIds:[v.id,d.id,d.id]}));assert(!bad.ok);const good=E.reduceCareer(s,E.commandFor(s,{type:'complete',orderId:o.id,tileIds:E.matchingTiles(s,o)}));assert(good.ok);assert.equal(fixture('full-board-violin').board.filter(Boolean).length,25);});
test('fixture callers cannot mutate frozen shared payload',()=>{const s=fixture('completed320');s.xp=0;assert.equal(fixture('completed320').xp,9830);assert.throws(()=>fixture('not-authored'));});
