import {layoutOptionsForSurface} from './layout-mode.mjs';
// Newly reconstructed from accepted280; requires independent320 review.
import {inspectHudReadability,hudReadabilityViolations} from '../../tests/full-campaign-browser/hud-readability.mjs';
import {inspectImageReadiness} from '../../tests/full-campaign-browser/image-readiness.mjs';
import {expect} from '@playwright/test';import assert from 'node:assert/strict';import fs from 'node:fs';import {join} from 'node:path';
import * as base from '../../tests/campaign-browser/helpers.mjs';export * from '../../tests/campaign-browser/helpers.mjs';
import {C,E} from './fixtures.mjs';import {gridViolations} from '../../gate/layout.mjs';import {compactInkViolations} from '../../full-campaign-gate/geometry.mjs';import {digest} from '../../full-campaign-gate/evidence.mjs';import {verifyPng} from '../../gate/png.mjs';
import {ORIGIN} from '../../full-campaign-gate/scope.mjs';
import {screenshotAllowed} from './scope.mjs';
import {captureFullPage,captureViewportModal} from './capture-geometry.mjs';
import {waitSaved} from '../../stage-b-evidence/browser/reload.mjs';
import {preparedIdentity} from '../execution/binding.mjs';
let checkedBinding;const binding=()=>checkedBinding??=preparedIdentity();
const captures=new Map();
export async function stateProof(page){const bytes=await base.bytes(page),state=JSON.parse(bytes);E.validateCareer(state);return{sha256:digest(bytes),schema:state.schemaVersion,content:state.contentVersion,revision:state.revision,chapter:state.chapterId,focus:state.focusedOrderId,sources:state.activeSourceIds,board:state.board,orders:state.orders,held:state.heldOrders,suspended:state.suspendedStory,xp:state.xp,coinsEarned:state.coinsEarned,coinsSpent:state.coinsSpent};}
export async function record(info,data){const path=info.outputPath('proof.json');fs.mkdirSync(info.outputDir,{recursive:true});const proof={testId:info.testId,testTitle:info.title,project:info.project.name,caseId:info.title.split(' ')[0],...binding(),setup:'Reducer-generated fixtures; only reported native gestures are browser evidence.',...data,screenshots:captures.get(info.outputDir)??[]};const bytes=Buffer.from(JSON.stringify(proof,null,2)+'\n');fs.writeFileSync(path,bytes,{flag:'wx'});await info.attach('proof-reference',{body:Buffer.from(JSON.stringify({file:'proof.json',caseId:proof.caseId,...binding(),bytes:bytes.length,sha256:digest(bytes)})),contentType:'application/json'});return proof;}
export async function shot(page,info,name,options={}){assert(['full-page','viewport-modal'].includes(options.captureKind??'full-page'),'Unknown screenshot capture kind');assert(Object.keys(options).every(key=>['captureKind','modal','frame'].includes(key)),'Unknown screenshot option');if((options.captureKind??'full-page')==='full-page')assert(!options.modal&&!options.frame,'Modal framing requires viewport-modal capture');screenshotAllowed(name);assert(name.startsWith(info.title.split(' ')[0]+'-'));await captureImageReadiness(page);const path=info.outputPath(name);fs.mkdirSync(info.outputDir,{recursive:true});const {dimensions,geometry}=options.captureKind==='viewport-modal'?await captureViewportModal(page,path,options):await captureFullPage(page,path);const bytes=fs.readFileSync(path);const row={name,path,bytes:bytes.length,sha256:digest(bytes),dimensions,captureKind:geometry.captureKind??'full-page',geometry,...binding()};const rows=captures.get(info.outputDir)??[];assert(!rows.some(r=>r.name===name));rows.push(row);captures.set(info.outputDir,rows);return row;}
export async function seedStable(page,state){await base.seed(page,state);await waitSaved(page,state);expect(await base.read(page)).toEqual(state);return state;}
export async function noViewWrites(page,start){const events=await page.evaluate(start=>window.__careerAudit.slice(start),start);expect(events.filter(e=>!e.fixture&&(e.op==='clear'||e.key===C.STORAGE_KEY))).toEqual([]);return events;}
export async function seedRaw(page,stateOrBytes){const bytes=typeof stateOrBytes==='string'?stateOrBytes:JSON.stringify(stateOrBytes);await page.evaluate(async({key,lock,bytes})=>navigator.locks.request(lock,{mode:'exclusive'},()=>{window.__fixtureWrite=true;window.__rawStorage.set.call(localStorage,key,bytes);window.__fixtureWrite=false;}),{key:C.STORAGE_KEY,lock:C.LOCK_NAME,bytes});return digest(bytes);}
export async function startChapter(page,touch=false){const before=await base.read(page),chapter=C.chapterDefinition(before);expect(E.canStartNextChapter(before)).toBe(true);const control=await base.compact(page)?page.locator('.career-mobile-progress-button'):page.locator('.career-finished').getByRole('button',{name:`Open ${chapter.nextTitle}`,exact:true});await base.press(control,touch);await expect(page.getByRole('dialog')).toBeVisible();const next=await base.changed(page,before,()=>base.press(page.getByRole('dialog').getByRole('button',{name:`Begin ${chapter.nextTitle}`,exact:true}),touch));await expect(page.getByRole('dialog')).toHaveCount(0);return next;}
export async function chooseHeld(page,id,touch=false){await base.panel(page,'orders',touch);const before=await base.read(page),held=before.heldOrders.find(o=>o.id===id);expect(held).toBeTruthy();const name=`Resume optional letter: ${held.requirements.map(r=>`${r.quantity} ${C.CATALOG.pieceOf(r.pieceId).name}`).join(' and ')}`;const next=await base.changed(page,before,()=>base.press(page.getByRole('dialog').getByRole('button',{name,exact:true}),touch));await expect(page.getByRole('dialog')).toHaveCount(0);return next;}
export async function returnStory(page,touch=false){await base.panel(page,'orders',touch);const before=await base.read(page);const next=await base.changed(page,before,()=>base.press(page.getByRole('dialog').getByRole('button',{name:'Return to story · free',exact:true}),touch));await expect(page.getByRole('dialog')).toHaveCount(0);return next;}
export async function imageProof(page){
 await expect.poll(()=>page.locator('.career-shell img:visible').evaluateAll(nodes=>nodes.every(img=>img.complete&&img.naturalWidth>0))).toBe(true);
 const state=await base.read(page),names=Object.fromEntries(C.CATALOG.PIECES.map(p=>[p.name,p.id])),sources=Object.fromEntries(state.unlockedSources.map(id=>[id,E.nextOutput(state,id).id]));
 const next=C.CHAPTERS.find(c=>c.id===C.chapterDefinition(state).nextId),preview=(next?.entrySources??[]).map(id=>C.FAMILIES.find(f=>f.id===id).pieceIds[0]);
 const images=await page.locator('.career-shell img:visible').evaluateAll((nodes,{state,names,sources,preview,pieces,families,upgrades})=>nodes.map(img=>{
  const cell=img.closest('[data-career-cell]'),mobile=img.closest('[data-target-piece-id]'),target=img.closest('.career-target'),producer=img.closest('.career-producer'),collection=img.closest('.career-collection-grid button'),picker=img.closest('.career-source-options button'),entry=img.closest('.career-chapter-preview-art'),postcard=img.closest('.career-postcard'),sent=img.closest('.career-sent-pictures button'),recycle=img.closest('.career-recycle-confirm'),upgrade=img.closest('.career-upgrades article');
  let pieceId=null,location=null;
  if(cell){location='board';pieceId=state.board[Number(cell.dataset.careerCell)]?.pieceId;if(pieceId!==cell.dataset.pieceId)throw Error('Board identity differs from saved tile');}
  else if(mobile||target){location='target';const el=mobile??target,orderRoot=el.closest('[data-order-id]'),order=state.orders.find(o=>o.id===orderRoot?.dataset.orderId),siblings=[...el.parentElement.querySelectorAll(mobile?'.career-mobile-target':'.career-target')];pieceId=order?.requirements[siblings.indexOf(el)]?.pieceId;if(mobile&&pieceId!==mobile.dataset.targetPieceId)throw Error('Chosen target identity differs from saved requirement');if(target&&names[target.querySelector('strong')?.textContent]!==pieceId)throw Error('Target label differs from saved requirement');}
  else if(producer){location='source';pieceId=sources[Object.keys(sources).find(id=>producer.classList.contains(id))];}
  else if(collection){location='collection';pieceId=collection.dataset.collectionPieceId??pieces[[...collection.parentElement.children].indexOf(collection)]?.id;if(pieces.find(p=>p.id===pieceId)?.name!==collection.querySelector('strong')?.textContent)throw Error('Collection label differs from piece identity');}
  else if(picker){location='source-picker';pieceId=families.find(f=>f.shortName===picker.querySelector('strong')?.textContent)?.pieceIds[0];}
  else if(entry){location='entry-preview';pieceId=preview[[...entry.querySelectorAll('img')].indexOf(img)];}
  else if(postcard){location='postcard';pieceId=names[document.querySelector('#career-dialog-title')?.textContent];}
  else if(sent){location='sent-letter';pieceId=names[sent.querySelector('strong')?.textContent.replace(/^\d+ × /,'')];}
  else if(recycle){location='recycle';pieceId=names[recycle.querySelector('b')?.textContent];}
  else if(upgrade){location='upgrade';const u=upgrades.find(u=>u.name===upgrade.querySelector('h3')?.textContent);pieceId=families.find(f=>f.id===u?.familyId)?.pieceIds[1];}
  if(!pieceId)throw Error('Unmapped rendered artwork context');const r=img.getBoundingClientRect();return{pieceId,location,src:img.currentSrc,natural:[img.naturalWidth,img.naturalHeight],display:[r.width,r.height]};
 }),{state,names,sources,preview,pieces:C.CATALOG.PIECES,families:C.FAMILIES,upgrades:C.UPGRADES});
 expect(images.length).toBeGreaterThan(0);expect(images.filter(img=>img.location==='board').map(img=>img.pieceId).sort(),'Each occupied tile must render its own original art').toEqual(state.board.filter(Boolean).map(tile=>tile.pieceId).sort());const art=JSON.parse(fs.readFileSync('stage-d-build.json')).art,proof=[];
 const compact=await base.compact(page);for(const img of images){if(compact&&img.location==='board')expect(compactInkViolations(img),'Compact board art must retain at least 28px of measured ink').toEqual([]);expect(new URL(img.src).origin).toBe(ORIGIN);expect(img.display[0]).toBeGreaterThan(8);expect(Math.abs(img.display[0]/img.display[1]-img.natural[0]/img.natural[1])).toBeLessThan(.03);const response=await page.request.get(img.src);expect(response.ok()).toBe(true);const bytes=await response.body(),sha256=digest(bytes),expected=art.find(a=>a.id===img.pieceId);expect(expected,'Expected piece must be in sealed registry').toBeTruthy();expect(sha256,`Wrong original artwork for ${img.location} ${img.pieceId}`).toBe(expected.sha256);proof.push({...img,sha256,bytes:bytes.length});}
 return proof;
}
export async function exportCard(page,info,pieceId){const [download]=await Promise.all([page.waitForEvent('download'),page.getByRole('dialog').getByRole('button',{name:'Download postcard',exact:true}).click()]);expect(await download.failure()).toBe(null);const path=info.outputPath(pieceId+'.png');fs.mkdirSync(info.outputDir,{recursive:true});assert(!fs.existsSync(path));await download.saveAs(path);const bytes=fs.readFileSync(path);verifyPng(bytes,[1536,1120]);return{path,pieceId,filename:pieceId+'.png',suggestedFilename:download.suggestedFilename(),...binding(),bytes:bytes.length,sha256:digest(bytes),dimensions:[1536,1120]};}

export async function noOverflow(page,{expectedMode}={}){const state=await base.read(page);await expect(page.locator('.career-shell')).toHaveClass(state.largeText?/is-large-text/:/^(?!.*is-large-text)/);const compact=await base.compact(page),surface=await page.evaluate(()=>({width:innerWidth,renderedLargeText:document.querySelector('.career-shell').classList.contains('is-large-text')}));const options=layoutOptionsForSurface({...surface,compact,largeText:state.largeText});if(expectedMode)expect(options.mode,'Actual rendered layout must match the explicitly requested test surface').toBe(expectedMode);const proof=await base.noOverflow(page,options);const cells=await page.locator('[data-career-cell]').evaluateAll(nodes=>nodes.map(node=>{const r=node.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height};}));expect(gridViolations(cells),'The actual 25-cell board must retain equal aligned rows and 44px hit targets').toEqual([]);return{...proof,grid:cells,surface:{...surface,compact,largeText:state.largeText}};}

// Wait for actual DOM images, not persisted state: quota failures deliberately
// leave the practice board ahead of the last saved career.
export async function captureImageReadiness(page){
 await expect.poll(async()=>(await page.evaluate(inspectImageReadiness)).ready,{message:'Rendered artwork must load and have a nonzero crop before capture'}).toBe(true);
 await page.evaluate(async()=>{const images=[...document.querySelectorAll('.career-shell img')].filter(img=>img.getClientRects().length&&img.getBoundingClientRect().width>0);await Promise.all(images.map(img=>img.decode()));await Promise.all(document.querySelector('.career-shell').getAnimations({subtree:true}).filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{})));await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));});
 const proof=await page.evaluate(inspectImageReadiness);expect(proof.ready,'Artwork stayed ready after decode, animation and two layout frames').toBe(true);return proof;
}
export async function hudReadability(page){
 const hud=page.locator('.career-mobile-hud');await expect(hud).toHaveCount(1);
 const proof=await hud.evaluate(inspectHudReadability),violations=hudReadabilityViolations(proof);
 expect(violations,'Every HUD control and required label must be visible, nonoverlapping and contained').toEqual([]);
 return {...proof,violations};
}
export async function wayfinderLines(page){
 const label=page.locator('[data-piece-id="b3"] .career-cell-name-full');expect(await label.textContent()).toBe('Wayfinder');
 const lines=await label.evaluate(el=>{const chars=[],walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);while(walker.nextNode()){const n=walker.currentNode;for(let i=0;i<n.length;i++){const r=document.createRange();r.setStart(n,i);r.setEnd(n,i+1);chars.push({text:n.textContent[i],y:r.getBoundingClientRect().y});}}const lines=[];for(const c of chars){let row=lines.find(r=>Math.abs(r.y-c.y)<1);if(!row){row={y:c.y,text:''};lines.push(row);}row.text+=c.text;}return lines.map(r=>r.text);});
 expect(lines).toEqual(['Wayfinder']);await expect(page.locator('[data-piece-id="b3"]')).toHaveAttribute('aria-label',/^Wayfinder,/);return lines;
}

// Collection adapters use stable IDs; a card may be on another filtered page.
export function collectionPiece(page,pieceId){assert(C.CATALOG.pieceOf(pieceId),'Unknown collection piece');return page.getByRole('dialog').locator(`[data-collection-piece-id="${pieceId}"]`);}
export async function revealCollectionPiece(page,pieceId){const p=C.CATALOG.pieceOf(pieceId);assert(p);const volume=page.getByRole('combobox',{name:'Collection volume',exact:true});if(await volume.count())await volume.selectOption('all');await page.getByRole('combobox',{name:'Collection chapter',exact:true}).selectOption('all');await page.getByRole('combobox',{name:'Picture family',exact:true}).selectOption(p.familyId);await expect(collectionPiece(page,pieceId)).toBeVisible();return collectionPiece(page,pieceId);}
export async function collectionPages(page,total){const seen=[],images=[];for(let pageNumber=1;pageNumber<=Math.ceil(total/20);pageNumber++){await expect(page.getByRole('navigation',{name:'Collection pages'})).toContainText(`Page ${pageNumber} of ${Math.ceil(total/20)}`);const cards=page.locator('[data-collection-piece-id]'),count=Math.min(20,total-seen.length);await expect(cards).toHaveCount(count);await expect(cards.locator('img')).toHaveCount(count);const ids=await cards.evaluateAll(nodes=>nodes.map(n=>n.dataset.collectionPieceId)),proof=await imageProof(page);expect(proof.filter(image=>image.location==='collection').map(image=>image.pieceId)).toEqual(ids);seen.push(...ids);images.push(...proof);const next=page.getByRole('button',{name:'Next pictures',exact:true});if(seen.length<total)await next.click();else await expect(next).toBeDisabled();}expect(seen).toEqual(C.CATALOG.PIECES.slice(0,total).map(p=>p.id));return{seen,images};}
// Durable test-side write journal survives every navigation and fixture reload.
const journals=new WeakMap();
export async function instrumentation(context){await base.instrumentation(context);const rows=[];journals.set(context,rows);await context.exposeBinding('__stageDRecordWrite',(_,row)=>rows.push(row));await context.addInitScript(()=>{window.__stageDWriteAcks=[];const p=Storage.prototype;for(const name of ['setItem','removeItem','clear']){const original=p[name];p[name]=function(...args){if(this===localStorage)window.__stageDWriteAcks.push(window.__stageDRecordWrite({operation:name,key:args[0]??null,fixture:Boolean(window.__fixtureWrite),url:location.href}));return original.apply(this,args);};}});}
export async function flushWrites(page){expect(journals.has(page.context()),'Context must be instrumented before auditing').toBe(true);await page.evaluate(async()=>{if(!Array.isArray(window.__stageDWriteAcks))throw Error('Write journal missing');await Promise.all(window.__stageDWriteAcks);});}
export async function writeCheckpoint(page){await flushWrites(page);return journals.get(page.context()).length;}
export async function durableNoWrites(page,start){expect(Number.isSafeInteger(start)&&start>=0).toBe(true);await flushWrites(page);const rows=journals.get(page.context()).slice(start).filter(r=>!r.fixture&&(r.operation==='clear'||r.key===C.STORAGE_KEY));expect(rows,'No game save writes across acknowledged navigations and views').toEqual([]);return rows;}
