// NEW320 browser evidence suite. Native assertions still require independent review.
import {test,expect} from '@playwright/test';import * as h from './helpers.mjs';import {C,E,V,fixture} from './fixtures.mjs';import {scenarioFor,PROPOSAL,failureState} from './scope.mjs';import {wholeWordBoardProof,boardScrollProof,postcardFontProof} from './text-polish.mjs';import {postcardSubtitle} from '../../src/career/feedback.js';
const scenario=scenarioFor(test),title=id=>{const c=PROPOSAL.cases.find(c=>c.id===id);return c.id+' '+c.title;},touch=i=>Boolean(i.project.use.hasTouch);test.beforeEach(async({page,context})=>{await h.instrumentation(context);await h.open(page);});test.afterEach(async({page},info)=>{if(info.status!==info.expectedStatus)await failureState(page,info,info.error??Error('Setup or case failed'),{phase:'afterEach'});try{await h.audit(page);}catch(error){await failureState(page,info,error,{phase:'afterEach-audit'});throw error;}});
scenario(title('D06'),async({page},info)=>{await h.seedStable(page,fixture('all-new-discovered'));const saved=await h.bytes(page),state=await h.read(page),checkpoint=await h.writeCheckpoint(page);await h.panel(page,'collection',touch(info));await page.getByRole('combobox',{name:'Collection volume',exact:true}).selectOption('all');await page.getByRole('combobox',{name:'Collection chapter',exact:true}).selectOption('all');await page.getByRole('combobox',{name:'Picture family',exact:true}).selectOption('all');const seen=[];for(let n=0;n<16;n++){const cards=page.locator('[data-collection-piece-id]');await expect(cards).toHaveCount(20);const rows=await cards.evaluateAll(nodes=>nodes.map(node=>({id:node.dataset.collectionPieceId,images:node.querySelectorAll('img').length,disabled:node.disabled})));for(const row of rows){expect(row.disabled).toBe(!state.discoveries.includes(row.id));expect(row.images).toBe(state.discoveries.includes(row.id)?1:0);}seen.push(...rows.map(r=>r.id));if(n===0||n===15)await h.shot(page,info,n===0?'D06-page-first.png':'D06-page-last.png');if(n<15)await page.getByRole('button',{name:'Next pictures',exact:true}).click();}expect(seen).toEqual(C.CATALOG.PIECES.map(p=>p.id));const scopes=[],filters=[],volume=page.getByRole('combobox',{name:'Collection volume',exact:true}),chapter=page.getByRole('combobox',{name:'Collection chapter',exact:true}),family=page.getByRole('combobox',{name:'Picture family',exact:true});for(const v of V.VOLUMES){await volume.selectOption(v.id);await expect(chapter).toHaveValue('all');await expect(family).toHaveValue('all');const ids=[];for(let i=0;i<Math.ceil(v.pieceIds.length/20);i++){const actual=await page.locator('[data-collection-piece-id]').evaluateAll(nodes=>nodes.map(n=>n.dataset.collectionPieceId));expect(actual).toEqual(v.pieceIds.slice(i*20,i*20+20));ids.push(...actual);if(i+1<Math.ceil(v.pieceIds.length/20))await page.getByRole('button',{name:'Next pictures',exact:true}).click();}scopes.push({volume:v.id,ids});}await volume.selectOption('all');for(const ch of C.CHAPTERS.slice(28)){await chapter.selectOption(ch.id);const families=C.FAMILIES.slice(56).filter(f=>C.CONTENT_PACKS[8].sourceRules.find(r=>r.id===f.id).chapterId===ch.id);expect(await page.locator('[data-collection-piece-id]').evaluateAll(nodes=>nodes.map(n=>n.dataset.collectionPieceId))).toEqual(families.flatMap(f=>f.pieceIds));for(const f of families){await family.selectOption(f.id);const actual=await page.locator('[data-collection-piece-id]').evaluateAll(nodes=>nodes.map(n=>n.dataset.collectionPieceId));expect(actual).toEqual(f.pieceIds);filters.push({chapter:ch.id,family:f.id,ids:actual});}}expect(await h.bytes(page)).toBe(saved);await h.durableNoWrites(page,checkpoint);await h.record(info,{seen,scopes,filters,savedState:state});});
const boardIds=page=>page.locator('[data-career-cell]').evaluateAll(nodes=>nodes.map(n=>n.dataset.pieceId||null));
async function playReplay(page, letterId, version, touch) {
  let mirror = E.createReplay(letterId, 'stage-c-replay-mirror', version);
  const order = mirror.orders[0], template = C.orderTemplate(letterId, version, 'story');
  expect(order.contentVersion).toBe(version);
  expect(order.requirements).toEqual(template.requirements);
  await expect(page.locator('.career-shell')).toHaveAttribute('data-save-status', 'replay');
  await expect(page.locator('.career-practice-banner strong')).toHaveText('Isolated letter practice · 0 XP · 0 coins');
  await expect.poll(() => boardIds(page)).toEqual(mirror.board.map(t => t?.pieceId ?? null));
  const compact = await h.compact(page);
  const targets = compact ? page.locator('.career-mobile-target') : page.locator('.career-order-list .career-target');
  const targetProof = await targets.evaluateAll(nodes => nodes.map(node => ({id: node.dataset.targetPieceId ?? null, name: node.querySelector('strong')?.textContent, count: node.querySelector('small')?.textContent, text: node.textContent})));
  expect(targetProof.map(row => row.name)).toEqual(template.requirements.map(r => {
    const p = C.CATALOG.pieceOf(r.pieceId); return compact ? p.shortName : p.name;
  }));
  if (compact) expect(targetProof.map(row => row.id)).toEqual(template.requirements.map(r => r.pieceId));
  for (const [index, requirement] of template.requirements.entries()) expect(targetProof[index].text).toContain(`/${requirement.quantity}`);
  const actions = [];
  while (mirror.orders.length) {
    const hint = E.goalHint(mirror), before = mirror;
    let action;
    if (hint.kind === 'send') {
      action = {type: 'complete', orderId: order.id, tileIds: E.matchingTiles(mirror, order)};
      await h.press(h.sendControl(page), touch);
    } else if (hint.kind === 'merge') {
      const [from, to] = hint.pair;
      action = {type: 'move', from, to, tileId: mirror.board[from].id, targetTileId: mirror.board[to].id};
      await h.press(page.locator(`[data-career-cell="${from}"]`), touch);
      await expect(page.locator(`[data-career-cell="${from}"]`)).toHaveAttribute('aria-pressed', 'true');
      await h.press(page.locator(`[data-career-cell="${to}"]`), touch);
    } else if (hint.kind === 'supply') {
      action = {type: 'supply', familyId: hint.familyId};
      await h.press(page.locator(`.career-producer.${hint.familyId} .career-supply`), touch);
    } else if (hint.kind === 'cut') {
      action = {type: 'cut', at: hint.at, tileId: mirror.board[hint.at].id};
      await h.press(page.locator(`[data-career-cell="${hint.at}"]`), touch);
      await h.press(page.getByRole('button', {name: 'Cut', exact: true}), touch);
    } else throw Error(`Unexpected replay gesture ${hint.kind}`);
    const reduced = E.reduceCareer(before, E.commandFor(before, action));
    expect(reduced.ok).toBe(true);
    mirror = reduced.state;
    await expect(page.locator('.career-board')).toHaveAttribute('aria-busy', 'false');
    await expect.poll(() => boardIds(page)).toEqual(mirror.board.map(t => t?.pieceId ?? null));
    actions.push({type: action.type, familyId: action.familyId, from: action.from, to: action.to, board: mirror.board.map(t => t?.pieceId ?? null)});
    expect(actions.length).toBeLessThan(100);
  }
  await expect(page.locator('.career-postmark small')).toHaveText('0 XP · 0 coins');
  await expect(page.locator('.career-status-long')).toContainText('Practice letter complete. 0 XP and 0 coins; your career is unchanged.');
  expect(mirror.receipts.at(-1)).toMatchObject({type: 'practice', contentVersion: version, xp: 0, coins: 0});
  return {letterId, contentVersion: version, requirements: template.requirements, targetProof, actions, receipt: mirror.receipts.at(-1)};
}

scenario(title('D07'),async({page},info)=>{await h.seedStable(page,fixture('completed320'));const saved=await h.bytes(page),state=await h.read(page),endings=[],endingsCheckpoint=await h.writeCheckpoint(page);await h.panel(page,'letters',touch(info));for(const [i,id]of ['sound-advice','short-measure','paper-duet','next-move','along-the-grain'].entries()){await page.getByRole('combobox',{name:'Chapter',exact:true}).selectOption(id);const el=page.getByRole('dialog').locator('.career-chapter-ending');await expect(el).toHaveText(C.CHAPTER_COPY[id].ending);await el.scrollIntoViewIfNeeded();await expect(el).toBeInViewport({ratio:1});if(i===4)await h.shot(page,info,'D07-five-endings.png');endings.push({id,text:await el.textContent()});expect(await h.bytes(page)).toBe(saved);}expect(V.VOLUMES).toHaveLength(5);for(const volume of V.VOLUMES)expect(E.volumeComplete(state,volume.id)).toBe(true);expect(E.canEnterContinuation(state)).toBe(false);await h.close(page,touch(info));await h.durableNoWrites(page,endingsCheckpoint);const replays=[];const legacy=E.upgradeCareer(fixture('legacy-v1')),v1=Object.entries(legacy.storyCompletions).find(([id,r])=>r.contentVersion===1);expect(v1).toBeTruthy();for(const [letterId,version]of [[v1[0],1],['paper-duet-letter-6',6],['next-move-letter-5',7],['along-the-grain-letter-5',8]]){await h.seedStable(page,version===1?legacy:state);const checkpoint=await h.writeCheckpoint(page),raw=await h.bytes(page),chapter=C.CHAPTERS.find(c=>c.storyIds.includes(letterId));await h.panel(page,'letters',touch(info));await page.getByRole('combobox',{name:'Chapter',exact:true}).selectOption(chapter.id);await h.press(page.locator('.career-letter-list > article').nth(chapter.storyIds.indexOf(letterId)).getByRole('button',{name:/^Practice/}),touch(info));replays.push(await playReplay(page,letterId,version,touch(info)));expect(await h.bytes(page)).toBe(raw);await h.press(await h.compact(page)?page.locator('.career-mobile-return'):page.getByRole('button',{name:'Return to career',exact:true}),touch(info));await expect(page.locator('.career-shell')).toHaveAttribute('data-save-status','saved');expect(await h.bytes(page)).toBe(raw);await h.durableNoWrites(page,checkpoint);}await h.record(info,{state,endings,replays,screenshotScope:'D07-five-endings.png shows only the selected final ending. All five ending texts are separately asserted and recorded above; this is not five visual captures.'});});
async function failedFontRecovery(context,info){const page=await context.newPage();let denied=0;const block=route=>{denied++;return route.abort('failed');};await page.route('**/*.ttf',block);try{await h.open(page);await h.seedStable(page,fixture('all-new-discovered'));const saved=await h.bytes(page),checkpoint=await h.writeCheckpoint(page);await h.panel(page,'collection',touch(info));await h.revealCollectionPiece(page,'d320-rb5');await h.collectionPiece(page,'d320-rb5').click();const download=page.getByRole('button',{name:'Download postcard',exact:true}),retry=page.getByRole('button',{name:'Try preparing again',exact:true});await expect(retry).toBeVisible();await expect(download).toBeDisabled();expect(denied).toBeGreaterThan(0);await page.unroute('**/*.ttf',block);await retry.click();await expect(download).toBeEnabled();const typography=await postcardFontProof(page);expect(await h.bytes(page)).toBe(saved);await h.durableNoWrites(page,checkpoint);return{deniedRequests:denied,failedDownloadDisabled:true,retryEnabledDownload:true,typography};}catch(error){await failureState(page,info,error,{phase:'D08-native-failed-font-recovery'});throw error;}finally{await page.close();}}
scenario(title('D08'),async({page,context},info)=>{const exports=[],fontRecovery=await failedFontRecovery(context,info),p=await context.newPage();await p.goto('/stage-d-probe/stage-d-evidence/browser/probe/current/index.html');try{for(const spec of PROPOSAL.postcardOutputsPerProfile){const id=spec.pieceId,piece=C.CATALOG.pieceOf(id);expect(spec.expectedSuggestedDownloadFilename).toBe('moticos-'+piece.name.toLowerCase().replaceAll(' ','-')+'.png');await h.seedStable(page,fixture('all-new-discovered'));const saved=await h.bytes(page),checkpoint=await h.writeCheckpoint(page);await h.panel(page,'collection',touch(info));await h.revealCollectionPiece(page,id);await h.collectionPiece(page,id).click();await expect(page.getByRole('heading',{name:piece.name,exact:true})).toBeVisible();await expect(page.locator('.career-postcard figcaption small')).toHaveText('MOTICOS · '+postcardSubtitle(id).toUpperCase());if(id==='d320-rb5'||id==='d320-mu5')await h.shot(page,info,id==='d320-rb5'?'D08-rabbit-postcard.png':'D08-mushroom-window-postcard.png');const typography=await postcardFontProof(page),art=await h.imageProof(page),out=await h.exportCard(page,info,id);expect(out.suggestedFilename).toBe(spec.expectedSuggestedDownloadFilename);const parity=await p.evaluate(id=>window.stageDProbe.compare(id),id);expect(parity.byteEqual).toBe(true);expect(parity.sameBlob).toBe(true);expect(parity.sameFilename).toBe(true);expect(parity.hashes).toEqual([out.sha256,out.sha256,out.sha256]);expect(parity.dimensions).toEqual([1536,1120]);expect(await h.bytes(page)).toBe(saved);await h.durableNoWrites(page,checkpoint);exports.push({...out,typography,art,parity});}}finally{await p.close();}expect(exports).toHaveLength(12);await h.record(info,{exports,fontRecovery,visualAcceptance:'Pending independent review of actual output PNGs'});});
async function setLarge(page,large,t){const before=await h.read(page);if(Boolean(before.largeText)===large)return before;await h.panel(page,'help',t);const after=await h.changed(page,before,()=>page.getByRole('button',{name:large?'Use larger text':'Use standard text',exact:true}).click());await h.close(page,t);for(const key of ['board','xp','coinsEarned','coinsSpent','purchases','milestones'])expect(after[key]).toEqual(before[key]);return after;}
scenario(title('D09'),async({page},info)=>{const rows=[];async function inspect(name,desktop=false,large=false){const before=await h.bytes(page),checkpoint=await h.writeCheckpoint(page),state=await h.read(page);const words=large?await wholeWordBoardProof(page):null,scroll=large?await boardScrollProof(page,touch(info)):null,layout=await h.noOverflow(page,desktop?{desktop:true}:large?{mode:'large-text'}:{touch:true}),images=await h.imageProof(page),hud=desktop?null:await h.hudReadability(page);await h.shot(page,info,name);expect(await h.bytes(page)).toBe(before);await h.durableNoWrites(page,checkpoint);rows.push({name,state,words,scroll,layout,images,hud});}
for(const [w,hgt]of [[320,568],[390,664],[390,844],[430,932]]){await page.setViewportSize({width:w,height:hgt});await h.seedStable(page,fixture('occupied-active'));await setLarge(page,false,touch(info));await inspect(`D09-${w}x${hgt}-standard.png`);await setLarge(page,true,touch(info));await page.locator('.career-board').evaluate(el=>el.scrollLeft=0);await inspect(`D09-${w}x${hgt}-large-left.png`,false,true);await page.locator('[data-career-cell="24"]').focus();await page.keyboard.press('Control+End');await h.shot(page,info,`D09-${w}x${hgt}-large-right.png`);}
await page.setViewportSize({width:1366,height:768});await h.seedStable(page,fixture('occupied-active'));await setLarge(page,false,touch(info));await inspect('D09-desktop-standard.png',true);await setLarge(page,true,touch(info));await inspect('D09-desktop-large.png',true,true);
await page.setViewportSize({width:320,height:568});await h.seedStable(page,fixture('occupied-complete'));await setLarge(page,true,touch(info));await inspect('D09-ending-320x568-large-left.png',false,true);await page.locator('[data-career-cell="24"]').focus();await page.keyboard.press('Control+End');await h.shot(page,info,'D09-ending-320x568-large-right.png');await h.record(info,{rows});});

import {registerStressCases} from './stress.spec-cases.mjs';
registerStressCases();
