import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,statSync,openSync,closeSync,ftruncateSync,rmSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {deflateSync} from 'node:zlib';
import {stageDiagnostic,scanSizes,DIAGNOSTIC_CAP,diagnosticOutcome,hashFile} from '../../gate/package.mjs';
import {MAX_ARTIFACT_BYTES,CASES} from '../../gate/scope.mjs';
function tmp(){const root=mkdtempSync(join(tmpdir(),'campaign-failure-evidence-')),input=join(root,'input'),output=join(root,'upload');mkdirSync(input);return{root,input,output};}
function write(root,path,bytes){const at=join(root,path);mkdirSync(at.slice(0,at.lastIndexOf('/')),{recursive:true});writeFileSync(at,bytes);return at;}
function report(){return{suites:[{specs:CASES['campaign-chromium'].map(([id,title],i)=>({id,title:`${id} ${title}`,tests:[{projectName:'campaign-chromium',expectedStatus:'passed',status:i<8?'expected':i===8?'unexpected':'skipped',results:[{status:i<8?'passed':i===8?'failed':'skipped',retry:0,errors:i===8?[{message:'Element not found in valid fresh fallback'}]:[]}]}]}))}],errors:[]};}
function png(){const crc=bytes=>{let c=0xffffffff;for(const byte of bytes){c^=byte;for(let i=0;i<8;i++)c=c&1?0xedb88320^(c>>>1):c>>>1;}return(c^0xffffffff)>>>0;};const chunk=(type,data)=>{const b=Buffer.alloc(12+data.length);b.writeUInt32BE(data.length);b.write(type,4);data.copy(b,8);b.writeUInt32BE(crc(b.subarray(4,8+data.length)),8+data.length);return b;};const h=Buffer.alloc(13);h.writeUInt32BE(2);h.writeUInt32BE(2,4);h[8]=8;h[9]=6;return Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',h),chunk('IDAT',deflateSync(Buffer.alloc(18))),chunk('IEND',Buffer.alloc(0))]);}
test('actual over-cap trace preserves bounded honest diagnostics and leaves raw files untouched',()=>{const t=tmp();try{write(t.input,'campaign-chromium/results.json',JSON.stringify(report()));write(t.input,'campaign-chromium/progress/browser-events.jsonl','{"event":"end","status":"failed"}\n');write(t.input,'campaign-source.json','{"source":"synthetic identity"}');write(t.input,'campaign-chromium/raw/failed/error-context.md','C09 absent postmark');const picture=write(t.input,'campaign-chromium/raw/failed/test-failed-1.png',png());const trace=write(t.input,'campaign-chromium/raw/failed/trace.zip','');const fd=openSync(trace,'r+');ftruncateSync(fd,MAX_ARTIFACT_BYTES+1024);closeSync(fd);const before=scanSizes(t.input),traceHash=hashFile(trace),pictureHash=hashFile(picture);assert(before.reduce((n,r)=>n+r.bytes,0)>MAX_ARTIFACT_BYTES);const m=stageDiagnostic({inputRoot:t.input,outputRoot:t.output,reason:'Synthetic full bundle exceeds60MiB',binding:{status:'verified',sourceFingerprint:'synthetic'}});assert.equal(m.status,'incomplete');assert.equal(m.fullEvidenceAvailable,false);assert.deepEqual([m.outcome.passed,m.outcome.failed,m.outcome.incompleteCases],[8,1,12]);assert(scanSizes(t.output).reduce((n,r)=>n+r.bytes,0)<=DIAGNOSTIC_CAP);assert.deepEqual(scanSizes(t.input),before);assert.equal(hashFile(trace),traceHash);assert.equal(hashFile(picture),pictureHash);assert.equal(hashFile(join(t.output,'campaign-chromium/raw/failed/test-failed-1.png')),pictureHash);assert(existsSync(join(t.output,'campaign-chromium/raw/failed/error-context.md')));const omitted=m.omittedFiles.find(x=>x.file.endsWith('trace.zip'));assert.equal(omitted.bytes,MAX_ARTIFACT_BYTES+1024);assert.equal(omitted.sha256,traceHash);assert(!existsSync(join(t.output,omitted.file)));}finally{rmSync(t.root,{recursive:true,force:true});}});
test('missing and corrupt raw reports survive as explicit incomplete evidence with binding failure',()=>{for(const corrupt of[false,true]){const t=tmp();try{if(corrupt)write(t.input,'campaign-chromium/results.json','not JSON');const m=stageDiagnostic({inputRoot:t.input,outputRoot:t.output,reason:'Verifier rejected raw report',binding:{status:'failed',error:'Source identity changed'}});assert.equal(m.status,'incomplete');assert.equal(m.binding.status,'failed');assert.equal(m.binding.error,'Source identity changed');assert.equal(m.outcome.passed,0);assert.equal(m.outcome.notObserved,21);assert(m.outcome.groups.some(x=>x.status==='evidence-unreadable'&&x.reportError));assert(existsSync(join(t.output,'diagnostic-outcome.json')));assert(scanSizes(t.output).reduce((n,r)=>n+r.bytes,0)<=DIAGNOSTIC_CAP);}finally{rmSync(t.root,{recursive:true,force:true});}}});
test('oversized raw report is omitted honestly but still produces bounded case summary',()=>{const t=tmp();try{const r=report();r.padding='x'.repeat(300*1024);write(t.input,'campaign-chromium/results.json',JSON.stringify(r));const m=stageDiagnostic({inputRoot:t.input,outputRoot:t.output,reason:'Oversized report fixture'});assert.deepEqual([m.outcome.passed,m.outcome.failed,m.outcome.incompleteCases],[8,1,12]);assert(!existsSync(join(t.output,'campaign-chromium/results.json')));assert(m.omittedFiles.some(x=>x.file.endsWith('results.json')&&x.sha256));assert(scanSizes(t.output).reduce((n,r)=>n+r.bytes,0)<=DIAGNOSTIC_CAP);}finally{rmSync(t.root,{recursive:true,force:true});}});
test('corrupt small failure PNG is not called verified or uploaded',()=>{const t=tmp();try{write(t.input,'campaign-chromium/raw/failed/test-failed-1.png','corrupt');const m=stageDiagnostic({inputRoot:t.input,outputRoot:t.output,reason:'Corrupt evidence'});assert.equal(m.status,'incomplete');assert(!existsSync(join(t.output,'campaign-chromium/raw/failed/test-failed-1.png')));assert(m.omittedFiles.some(x=>/PNG validation failed/.test(x.reason)));}finally{rmSync(t.root,{recursive:true,force:true});}});
test('absent false-bank indicator is valid while quota and replay postmarks have positive checks',()=>{for(const file of['chromium.spec.mjs','phone.spec.mjs','adopted-journeys.mjs']){const source=readFileSync(`tests/campaign-browser/${file}`,'utf8');assert(!source.includes(".not.toContainText('SENT & SAVED')"));assert(source.includes("filter({hasText:'SENT & SAVED'})).toHaveCount(0)"));}const chromium=readFileSync('tests/campaign-browser/chromium.spec.mjs','utf8');assert(chromium.includes("if(fault==='quota')"));assert(chromium.includes("else await expect(page.locator('.career-postmark')).toHaveCount(0)"));});


test('duplicate unknown or malformed report rows cannot inflate observed counts',()=>{for(const type of['duplicate-title','duplicate-id','unknown-title','bad-results']){const t=tmp();try{const r=report();if(type==='duplicate-title')r.suites[0].specs[1].title=r.suites[0].specs[0].title;if(type==='duplicate-id')r.suites[0].specs[1].id=r.suites[0].specs[0].id;if(type==='unknown-title')r.suites[0].specs[1].title='C99 unapproved';if(type==='bad-results')r.suites[0].specs[1].tests[0].results={bad:true};write(t.input,'campaign-chromium/results.json',JSON.stringify(r));const outcome=diagnosticOutcome(t.input);assert.deepEqual([outcome.passed,outcome.failed,outcome.notObserved],[0,0,21]);assert.equal(outcome.passed+outcome.failed+outcome.skipped+outcome.notObserved,21);}finally{rmSync(t.root,{recursive:true,force:true});}}});

test('corrupt raw report retains observed8/1/12 through a bounded valid progress ledger',()=>{const t=tmp();try{write(t.input,'campaign-chromium/results.json','not json');const events=CASES['campaign-chromium'].slice(0,9).map(([id,title],i)=>({event:'test-end',id:`opaque-${id}`,project:'campaign-chromium',title:['campaign-chromium',`${id} ${title}`],status:i<8?'passed':'failed',retry:0,errors:i===8?['Actual failure']:[]}));write(t.input,'campaign-chromium/progress/browser-events.jsonl',events.map(x=>JSON.stringify(x)).join('\n'));const m=stageDiagnostic({inputRoot:t.input,outputRoot:t.output,reason:'Corrupt raw report'});assert.deepEqual([m.outcome.passed,m.outcome.failed,m.outcome.incompleteCases],[8,1,12]);assert.equal(m.outcome.groups[0].status,'progress-only-observed-not-accepted');assert(m.outcome.groups[0].reportError);}finally{rmSync(t.root,{recursive:true,force:true});}});

test('actual over-cap package entry point stages diagnostics and never upgrades the failed status',async()=>{const {packageEvidence}=await import('../../gate/package.mjs');const t=tmp(),cwd=process.cwd();try{const input=join(t.root,'campaign-results');mkdirSync(input);write(input,'campaign-chromium/results.json',JSON.stringify(report()));const trace=write(input,'campaign-chromium/raw/failed/trace.zip',''),fd=openSync(trace,'r+');ftruncateSync(fd,MAX_ARTIFACT_BYTES+1024);closeSync(fd);process.chdir(t.root);const m=packageEvidence();assert.equal(m.status,'incomplete');assert.equal(m.kind,'bounded-diagnostic-only');assert(scanSizes('campaign-upload').reduce((n,r)=>n+r.bytes,0)<=DIAGNOSTIC_CAP);assert.equal(statSync(trace).size,MAX_ARTIFACT_BYTES+1024);assert.equal(m.binding.status,'failed');}finally{process.chdir(cwd);rmSync(t.root,{recursive:true,force:true});}});
