import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {deflateSync} from 'node:zlib';
import {CASES,validateInvocation,eligibleBudget,MAX_ARTIFACT_BYTES} from '../../gate/scope.mjs';
import {gridViolations,layoutViolations} from '../../gate/layout.mjs';
import {verifyCaps,validateOriginalPng} from '../../gate/package.mjs';
import {digest} from '../../gate/binding.mjs';
import {verifyCollection} from '../../gate/results.mjs';
import * as f from '../campaign-browser/fixtures.mjs';
const list=['test','--config=playwright.campaign.config.mjs','--list','--reporter=json'];
test('read-only collection is the only unapproved invocation',()=>{assert.equal(validateInvocation(list).listing,true);assert.throws(()=>validateInvocation(['test','--config=playwright.campaign.config.mjs','--project=campaign-chromium']));for(const extra of['--headed','--debug','--repeat-each=2','--workers=2','--retries=1','--grep=C01'])assert.throws(()=>validateInvocation([...list,extra],true));});
test('one exact approved group admits no duplicate or filtering flags',()=>{for(const project of Object.keys(CASES)){assert.equal(validateInvocation(['test','--config=playwright.campaign.config.mjs',`--project=${project}`],true).profile,project);}assert.throws(()=>validateInvocation(['test','--config=playwright.campaign.config.mjs','--project=unknown'],true));});
test('full group time plus cleanup reserve is required',()=>{assert.equal(eligibleBudget('campaign-chromium',630),360000);assert.throws(()=>eligibleBudget('campaign-chromium',631));assert.equal(eligibleBudget('campaign-webkit-phone',750),240000);assert.throws(()=>eligibleBudget('campaign-webkit-phone',751));for(const n of[-1,NaN,0.5])assert.throws(()=>eligibleBudget('campaign-chromium',n));});
test('exactly 21 bounded focused cases have unique IDs and no 120-second default',()=>{const entries=Object.values(CASES).flat();assert.equal(entries.length,21);assert.equal(new Set(entries.map(x=>x[0])).size,21);for(const row of entries)assert(row[2]>=25000&&row[2]<=75000);});
test('grid rejects unequal rows small targets and missing cells',()=>{const cells=Array.from({length:25},(_,i)=>({x:i%5*44,y:Math.floor(i/5)*44,width:44,height:44}));assert.deepEqual(gridViolations(cells),[]);assert(gridViolations(cells.slice(1)).length);assert(gridViolations(cells.map((x,i)=>i===0?{...x,height:42}:x)).length);assert(gridViolations(cells.map((x,i)=>i===0?{...x,height:48}:x)).length);});
test('artifact caps cannot be bypassed by failed or empty test status',()=>{assert.throws(()=>verifyCaps([{file:'huge',bytes:MAX_ARTIFACT_BYTES+1}]));assert.throws(()=>verifyCaps(Array.from({length:27},(_,i)=>({file:`raw/${i}.png`,bytes:1}))));assert.throws(()=>verifyCaps([{file:'x/raw/one.png',bytes:1},{file:'x/raw/two.png',bytes:1}]));assert.throws(()=>verifyCaps([{file:'one.zip',bytes:1},{file:'two.zip',bytes:1}]));assert.throws(()=>verifyCaps(Array.from({length:3},(_,i)=>({file:`x/postcards/${i}.png`,bytes:1}))));});
test('original PNG validation rejects changed bytes hash dimensions and corrupt stream',()=>{const crc=bytes=>{let c=0xffffffff;for(const byte of bytes){c^=byte;for(let i=0;i<8;i++)c=c&1?0xedb88320^(c>>>1):c>>>1;}return (c^0xffffffff)>>>0;};const chunk=(type,data)=>{const b=Buffer.alloc(12+data.length);b.writeUInt32BE(data.length);b.write(type,4);data.copy(b,8);b.writeUInt32BE(crc(b.subarray(4,8+data.length)),8+data.length);return b;};const ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(2);ihdr.writeUInt32BE(2,4);ihdr[8]=8;ihdr[9]=6;const png=Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',ihdr),chunk('IDAT',deflateSync(Buffer.alloc(18))),chunk('IEND',Buffer.alloc(0))]);const row={bytes:png.length,sha256:digest(png),dimensions:[2,2]};validateOriginalPng(png,row);assert.throws(()=>validateOriginalPng(png,{...row,bytes:row.bytes+1}));assert.throws(()=>validateOriginalPng(png,{...row,sha256:'0'.repeat(64)}));assert.throws(()=>validateOriginalPng(png,{...row,dimensions:[3,2]}));const corrupt=Buffer.from(png);corrupt[corrupt.length-1]^=1;assert.throws(()=>validateOriginalPng(corrupt,{...row,sha256:digest(corrupt)}));});
test('fixtures are legal and explicitly distinguish setup from actual UI routes',()=>{const set=f.fixtures();for(const state of Object.values(set))f.E.validateCareer(state);assert.equal(set.full.board.filter(Boolean).length,25);assert.equal(set.finals.board.filter(t=>f.C.CATALOG.pieceOf(t?.pieceId)?.tier===5).length,21);assert.equal(set.allArt.discoveries.length,20);assert.equal(f.threeOrders().orders.length,3);assert.equal(set.finished.xp,1020);assert.equal(set.finished.coinsEarned,430);assert.equal(set.finished.coinsSpent,300);});
test('transition fixtures retain non-story promises and do not imply Key focus',()=>{let s=f.transition();const prior=s.orders.map(o=>o.id);s=f.act(s,{type:'start-next-chapter',chapterId:f.C.CHAPTERS[1].id});for(const id of prior)assert(s.orders.some(o=>o.id===id));assert.equal(s.material.key.generated,0);assert(!s.unlockedSources.includes('moon'));});
test('workflow proposal is exact-branch push-only standard bounded synthetic evidence',()=>{const w=JSON.parse(readFileSync('gate/workflow.proposal.json'));assert.deepEqual(w.on,{push:{branches:['verify/campaign-20261007']}});assert(!w.on.workflow_dispatch);const j=w.jobs.campaign;assert.equal(j['runs-on'],'ubuntu-latest');assert.equal(j['timeout-minutes'],18);assert.match(j.if,/run_attempt == 1/);assert.match(j.if,/github.repository == 'BlindAnatomist\/moticos-for-cynthia'/);assert.match(j.if,/github.ref == 'refs\/heads\/verify\/campaign-20261007'/);const upload=j.steps.find(s=>s.uses?.startsWith('actions/upload-artifact'));assert.equal(upload.with['retention-days'],1);assert.equal(upload.with['include-hidden-files'],true);assert(!JSON.stringify(w).match(/deploy|paid.overage|budget.update/i));});
test('collection report is checked against exact configured scope',()=>{const report=JSON.parse(readFileSync('campaign-results/collection.json'));const proof=verifyCollection(report);assert.equal(proof.cases,21);const broken=structuredClone(report);broken.suites[0].specs.pop();assert.throws(()=>verifyCollection(broken));});

test('terminal acceptance rejects skipped retried or partial raw results and ledgers',async()=>{const {verifyCompleted,flatten}=await import('../../gate/results.mjs');const report=JSON.parse(readFileSync('campaign-results/collection.json')),rows=flatten(report.suites).filter(r=>r.project==='campaign-chromium');const result={...report,suites:[{specs:rows.map(r=>({title:r.title,id:r.id,file:r.file,line:r.line,tests:[{projectName:r.project,expectedStatus:'passed',status:'expected',results:[{status:'passed',retry:0}]}]}))}],stats:{unexpected:0,skipped:0,flaky:0,expected:rows.length}};const events=[{event:'begin',workers:1,maxFailures:1,retries:[0],projects:['campaign-chromium']},...rows.flatMap(r=>[{event:'test-begin',id:r.id},{event:'test-end',id:r.id,project:r.project,status:'passed',retry:0,errors:[]}]),{event:'end',status:'passed'}];assert.equal(verifyCompleted('campaign-chromium',result,events).cases,14);for(const type of['skip','retry','missing']){const bad=structuredClone(result);if(type==='skip')bad.suites[0].specs[0].tests[0].results[0].status='skipped';if(type==='retry')bad.suites[0].specs[0].tests[0].results[0].retry=1;if(type==='missing')bad.suites[0].specs.pop();assert.throws(()=>verifyCompleted('campaign-chromium',bad,events));}assert.throws(()=>verifyCompleted('campaign-chromium',result,events.slice(1)));});

test('source inventory rejects unreviewed root files and symlinks',async()=>{const fs=await import('node:fs'),os=await import('node:os'),path=await import('node:path');const {assertProjectionRoots,inventory}=await import('../../gate/binding.mjs');const extra='UNREVIEWED-ROOT.txt',cwd=process.cwd(),root=fs.mkdtempSync(path.join(os.tmpdir(),'campaign-root-check-'));try{process.chdir(root);fs.writeFileSync(extra,'synthetic source inventory rejection test');assert.throws(()=>assertProjectionRoots());fs.unlinkSync(extra);assertProjectionRoots();}finally{process.chdir(cwd);fs.rmSync(root,{recursive:true,force:true});}const dir=fs.mkdtempSync(path.join(os.tmpdir(),'campaign-inventory-'));try{fs.writeFileSync(path.join(dir,'regular.txt'),'synthetic');fs.symlinkSync('regular.txt',path.join(dir,'symlink.txt'));assert.throws(()=>inventory(dir));}finally{fs.rmSync(dir,{recursive:true,force:true});}});


test('passing artifacts require every original screenshot manifest download and case record',async()=>{const {verifyRequiredEvidence}=await import('../../gate/package.mjs');const {REQUIRED_SCREENSHOTS,REQUIRED_POSTCARDS,REQUIRED_RECORDS}=await import('../../gate/scope.mjs');const originals=Object.entries(REQUIRED_SCREENSHOTS).flatMap(([profile,names])=>names.map(name=>({path:`campaign-results/${profile}/screenshots/${name}.png`}))).concat(REQUIRED_POSTCARDS.map(file=>({file})));const files=originals.map(row=>({file:row.path??row.file,bytes:1})).concat(Object.keys(REQUIRED_SCREENSHOTS).map(profile=>({file:`campaign-results/${profile}/screenshots/manifest.json`,bytes:1})),Object.entries(REQUIRED_RECORDS).flatMap(([profile,names])=>names.map(name=>({file:`campaign-results/${profile}/${name}.json`,bytes:1}))));verifyRequiredEvidence(files,originals);for(const kind of['screenshot','manifest','postcard','record']){const target=kind==='screenshot'?files.find(x=>x.file.includes('/screenshots/')&&x.file.endsWith('.png')):kind==='manifest'?files.find(x=>x.file.endsWith('/manifest.json')):kind==='postcard'?files.find(x=>x.file.includes('/postcards/')):files.find(x=>x.file.endsWith('C01-garden-ui-route.json'));assert.throws(()=>verifyRequiredEvidence(files.filter(x=>x!==target),originals));}assert.throws(()=>verifyRequiredEvidence(files,originals.slice(1)));});


test('UI-route upgrade milestones are affordable without optional farming',()=>{let s=f.C.CHAPTERS[0].storyIds.reduce((state,id)=>{const order=state.orders.find(o=>o.storyLetterId===id);state=f.act(f.ready(state,order),{type:'complete',orderId:order.id,tileIds:f.E.matchingTiles(f.ready(state,order),order)});const upgrade=id==='garden-letter-5'?'bird-sorter':id==='garden-letter-8'?'order-desk':id==='garden-letter-9'?'fern-sorter':null;return upgrade?f.act(state,{type:'purchase',upgradeId:upgrade,expectedLevel:0}):state;},f.E.createCareer('browser-route-purchases'));s=f.act(s,{type:'start-next-chapter',chapterId:f.C.CHAPTERS[1].id});for(const id of f.C.CHAPTERS[1].storyIds){const order=s.orders.find(o=>o.storyLetterId===id);s=f.ready(s,order);s=f.act(s,{type:'complete',orderId:order.id,tileIds:f.E.matchingTiles(s,order)});const upgrade=id==='moon-letter-3'?'key-sorter':id==='moon-letter-6'?'moon-sorter':null;if(upgrade)s=f.act(s,{type:'purchase',upgradeId:upgrade,expectedLevel:0});}assert.equal(s.coinsSpent,300);assert.equal(s.coinsEarned,430);assert.equal(s.milestones.length,16);});
