import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,mkdtempSync,mkdirSync,writeFileSync,openSync,ftruncateSync,closeSync,rmSync,existsSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {collectionPiece} from '../campaign-browser/helpers.mjs';
import {CATALOG} from '../../src/career/content.js';
import {isWorkingTrace} from '../../gate/evidence-policy.mjs';
import {inventory} from '../../gate/binding.mjs';
import {packageEvidence,scanSizes} from '../../gate/package.mjs';
import {MAX_ARTIFACT_BYTES} from '../../gate/scope.mjs';

test('every collection piece resolves through active dialog and collection grid with exact accessible name',()=>{for(const piece of CATALOG.PIECES){const calls=[],target={id:piece.id};const page={getByRole(role){calls.push(role);assert.equal(role,'dialog');return{locator(selector){assert.equal(selector,'.career-collection-grid');return{getByRole(role,options){assert.equal(role,'button');assert.equal(options.name,`${piece.name} Level ${piece.tier} · collected`);assert.equal(options.exact,true);return target;}}}}}};assert.equal(collectionPiece(page,piece.id),target);assert.deepEqual(calls,['dialog']);}assert.throws(()=>collectionPiece({},'unknown'));});

test('modal-only controls never use an unscoped page or other-page button query',()=>{const names=['Close and return to board','Download postcard','Keep picture','Recycle picture','Stay at my table','Begin Moonlit Correspondence','Use larger text','Use standard text','Back to my board','View sent letter'];for(const file of['helpers.mjs','adopted-journeys.mjs','chromium.spec.mjs','phone.spec.mjs']){const source=readFileSync(`tests/campaign-browser/${file}`,'utf8');for(const name of names)assert(!source.includes(`page.getByRole('button',{name:'${name}'`)&&!source.includes(`other.getByRole('button',{name:'${name}'`)&&!source.includes(`p.getByRole('button',{name:'${name}'`),`${file}: ${name}`);assert(!source.includes("p.locator('.career-upgrades article')"));assert(!/page\.getByRole\('button',\{name:new RegExp\(C\.CATALOG/.test(source));assert(!source.includes("page.getByRole('button',{name:/Moon, left source/}"));}});

test('postcard download is journaled before later UI actions can fail',()=>{const source=readFileSync('tests/campaign-browser/chromium.spec.mjs','utf8'),start=source.indexOf('async function download(label)'),end=source.indexOf("await download('moon')",start),body=source.slice(start,end);assert(body.includes("h.record(info,'postcard-download-journal',{postcards:rows})"));assert(body.includes('expectedFilename'));assert(body.indexOf("h.record(info,'postcard-download-journal'")<body.indexOf('expect(d.suggestedFilename()).toBe(expectedFilename)'),'Journal must flush before a filename assertion can fail');assert(source.includes("await expect(h.collectionPiece(page,'k5')).toHaveCount(1)"));const pack=readFileSync('gate/package-full.mjs','utf8');assert(pack.includes('C13-postcard-download-journal.json'));assert(pack.includes("assert.equal(journal.caseId,'C13')"));assert(pack.includes('journal.sourceFingerprint,binding.sourceFingerprint'));});

test('only exact disposable recorder trace paths are excluded; canonical evidence is retained',()=>{const stem='campaign-chromium/raw/.playwright-artifacts-0/traces/';assert(isWorkingTrace(stem+'abc-recording1.trace'));assert(isWorkingTrace('campaign-results/'+stem+'abc.network'));for(const path of['campaign-chromium/raw/failed/trace.zip','campaign-chromium/raw/.last-run.json',stem+'test-failed-1.png',stem+'metadata.json','campaign-chromium/results.json','campaign-webkit-phone/progress/browser-events.jsonl','src/career/engine.trace'])assert.equal(isWorkingTrace(path),false,path);});

test('measured large working traces do not prevent canonical failure evidence upload',()=>{const root=mkdtempSync(join(tmpdir(),'campaign-working-traces-')),cwd=process.cwd();try{mkdirSync(join(root,'campaign-results/campaign-chromium/raw/.playwright-artifacts-0/traces'),{recursive:true});const work=join(root,'campaign-results/campaign-chromium/raw/.playwright-artifacts-0/traces/synthetic.trace'),fd=openSync(work,'w');ftruncateSync(fd,MAX_ARTIFACT_BYTES+1024);closeSync(fd);mkdirSync(join(root,'campaign-results/campaign-chromium/raw/failed'),{recursive:true});writeFileSync(join(root,'campaign-results/campaign-chromium/raw/failed/trace.zip'),'synthetic canonical trace for selection check');process.chdir(root);const m=packageEvidence();assert.equal(m.status,'incomplete');assert(existsSync('campaign-upload/working-trace-omissions.json'));const omitted=JSON.parse(readFileSync('campaign-upload/working-trace-omissions.json'));assert.equal(omitted.files.length,1);assert.equal(omitted.files[0].bytes,MAX_ARTIFACT_BYTES+1024);assert.match(omitted.files[0].sha256,/^[a-f0-9]{64}$/);assert.equal(omitted.originalsModified,false);assert(existsSync('campaign-upload/campaign-chromium/raw/failed/trace.zip'));assert(!existsSync('campaign-upload/campaign-chromium/raw/.playwright-artifacts-0/traces/synthetic.trace'));assert(scanSizes('campaign-upload').reduce((n,row)=>n+row.bytes,0)<MAX_ARTIFACT_BYTES);assert.equal(inventory('campaign-results',file=>!isWorkingTrace(file)).some(row=>row.file===work),false);}finally{process.chdir(cwd);rmSync(root,{recursive:true,force:true});}});

test('a first downloaded postcard survives a later failed case before its final aggregate record',async()=>{const {inspectFullEvidence}=await import('../../gate/package-full.mjs');const {deflateSync}=await import('node:zlib');const {createHash}=await import('node:crypto');const root=mkdtempSync(join(tmpdir(),'campaign-partial-export-')),cwd=process.cwd();try{const crc=b=>{let c=0xffffffff;for(const byte of b){c^=byte;for(let i=0;i<8;i++)c=c&1?0xedb88320^(c>>>1):c>>>1;}return(c^0xffffffff)>>>0;};const chunk=(type,data)=>{const b=Buffer.alloc(12+data.length);b.writeUInt32BE(data.length);b.write(type,4);data.copy(b,8);b.writeUInt32BE(crc(b.subarray(4,8+data.length)),8+data.length);return b;};const header=Buffer.alloc(13);header.writeUInt32BE(1536);header.writeUInt32BE(1120,4);header[8]=8;header[9]=6;const png=Buffer.concat([Buffer.from('89504e470d0a1a0a','hex'),chunk('IHDR',header),chunk('IDAT',deflateSync(Buffer.alloc((1536*4+1)*1120))),chunk('IEND',Buffer.alloc(0))]);mkdirSync(join(root,'campaign-results/campaign-chromium/postcards'),{recursive:true});const file='campaign-results/campaign-chromium/postcards/C13-moon.png';writeFileSync(join(root,file),png);const row={file,pieceId:'k5',filename:'unexpected-file.png',bytes:png.length,sha256:createHash('sha256').update(png).digest('hex'),dimensions:[1536,1120]};writeFileSync(join(root,'campaign-results/campaign-chromium/C13-postcard-download-journal.json'),JSON.stringify({caseId:'C13',sourceFingerprint:'synthetic',postcards:[row]}));process.chdir(root);const m=inspectFullEvidence();assert.equal(m.status,'incomplete');assert(m.originals.some(x=>x.kind==='postcard'&&x.file===file&&x.filename==='unexpected-file.png'));assert(m.files.some(x=>x.file===file));assert(!existsSync('campaign-results/campaign-chromium/C13-paired-labels-original-exports.json'));assert.equal(createHash('sha256').update(readFileSync(file)).digest('hex'),row.sha256);}finally{process.chdir(cwd);rmSync(root,{recursive:true,force:true});}});


test('source inventory still works after adding evidence-only filtering',async()=>{const {currentFiles}=await import('../../gate/binding.mjs');const files=currentFiles();assert(files.length>250);assert(files.some(row=>row.file==='src/career/CareerGarden.jsx'));assert(files.some(row=>row.file==='gate/evidence-policy.mjs'));});
