import * as V6 from './volumes.v6.js';
const freeze=v=>{if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}return v;};
const FIRST=V6.CONTINUATION;
export const CONTINUATION=FIRST;
export const CONTINUATIONS=freeze([...V6.CONTINUATIONS,{
  "id": "after-cross-currents-correspondences",
  "fromChapterId": "paper-duet",
  "toChapterId": "sideways-company",
  "fromVolumeId": "cross-currents-correspondences",
  "toVolumeId": "sideways-correspondences",
  "requiredPreviousStoryIds": [
    "garden-letter-1",
    "garden-letter-2",
    "garden-letter-3",
    "garden-letter-4",
    "garden-letter-5",
    "garden-letter-6",
    "garden-letter-7",
    "garden-letter-8",
    "garden-letter-9",
    "moon-letter-1",
    "moon-letter-2",
    "moon-letter-3",
    "moon-letter-4",
    "moon-letter-5",
    "moon-letter-6",
    "moon-letter-7",
    "riverside-letter-1",
    "riverside-letter-2",
    "riverside-letter-3",
    "riverside-letter-4",
    "riverside-letter-5",
    "riverside-letter-6",
    "riverside-letter-7",
    "lantern-letter-1",
    "lantern-letter-2",
    "lantern-letter-3",
    "lantern-letter-4",
    "lantern-letter-5",
    "lantern-letter-6",
    "lantern-letter-7",
    "wrong-address-letter-1",
    "wrong-address-letter-2",
    "wrong-address-letter-3",
    "wrong-address-letter-4",
    "wrong-address-letter-5",
    "wrong-address-letter-6",
    "wrong-address-letter-7",
    "quiet-company-letter-1",
    "quiet-company-letter-2",
    "quiet-company-letter-3",
    "quiet-company-letter-4",
    "quiet-company-letter-5",
    "quiet-company-letter-6",
    "namesakes-letter-1",
    "namesakes-letter-2",
    "namesakes-letter-3",
    "namesakes-letter-4",
    "namesakes-letter-5",
    "namesakes-letter-6",
    "namesakes-letter-7",
    "useful-gaps-letter-1",
    "useful-gaps-letter-2",
    "useful-gaps-letter-3",
    "useful-gaps-letter-4",
    "useful-gaps-letter-5",
    "useful-gaps-letter-6",
    "useful-gaps-letter-7",
    "small-talk-letter-1",
    "small-talk-letter-2",
    "small-talk-letter-3",
    "small-talk-letter-4",
    "small-talk-letter-5",
    "small-talk-letter-6",
    "hello-again-letter-1",
    "hello-again-letter-2",
    "hello-again-letter-3",
    "hello-again-letter-4",
    "hello-again-letter-5",
    "hello-again-letter-6",
    "hello-again-letter-7",
    "off-beat-letter-1",
    "off-beat-letter-2",
    "off-beat-letter-3",
    "off-beat-letter-4",
    "off-beat-letter-5",
    "off-beat-letter-6",
    "off-beat-letter-7",
    "return-mail-letter-1",
    "return-mail-letter-2",
    "return-mail-letter-3",
    "return-mail-letter-4",
    "return-mail-letter-5",
    "return-mail-letter-6",
    "return-mail-letter-7",
    "return-mail-letter-8",
    "fair-weather-letter-1",
    "fair-weather-letter-2",
    "fair-weather-letter-3",
    "fair-weather-letter-4",
    "fair-weather-letter-5",
    "fair-weather-letter-6",
    "fair-weather-letter-7",
    "double-meaning-letter-1",
    "double-meaning-letter-2",
    "double-meaning-letter-3",
    "double-meaning-letter-4",
    "double-meaning-letter-5",
    "double-meaning-letter-6",
    "double-meaning-letter-7",
    "fine-print-letter-1",
    "fine-print-letter-2",
    "fine-print-letter-3",
    "fine-print-letter-4",
    "fine-print-letter-5",
    "fine-print-letter-6",
    "sound-advice-letter-1",
    "sound-advice-letter-2",
    "sound-advice-letter-3",
    "sound-advice-letter-4",
    "sound-advice-letter-5",
    "sound-advice-letter-6",
    "sound-advice-letter-7",
    "sound-advice-letter-8",
    "small-impressions-letter-1",
    "small-impressions-letter-2",
    "small-impressions-letter-3",
    "small-impressions-letter-4",
    "small-impressions-letter-5",
    "small-impressions-letter-6",
    "small-impressions-letter-7",
    "second-look-letter-1",
    "second-look-letter-2",
    "second-look-letter-3",
    "second-look-letter-4",
    "second-look-letter-5",
    "second-look-letter-6",
    "loose-ends-letter-1",
    "loose-ends-letter-2",
    "loose-ends-letter-3",
    "loose-ends-letter-4",
    "loose-ends-letter-5",
    "loose-ends-letter-6",
    "loose-ends-letter-7",
    "short-measure-letter-1",
    "short-measure-letter-2",
    "short-measure-letter-3",
    "short-measure-letter-4",
    "short-measure-letter-5",
    "short-measure-letter-6",
    "cross-currents-letter-1",
    "cross-currents-letter-2",
    "cross-currents-letter-3",
    "cross-currents-letter-4",
    "cross-currents-letter-5",
    "cross-currents-letter-6",
    "safe-keeping-letter-1",
    "safe-keeping-letter-2",
    "safe-keeping-letter-3",
    "safe-keeping-letter-4",
    "safe-keeping-letter-5",
    "safe-keeping-letter-6",
    "give-and-take-letter-1",
    "give-and-take-letter-2",
    "give-and-take-letter-3",
    "give-and-take-letter-4",
    "give-and-take-letter-5",
    "give-and-take-letter-6",
    "paper-duet-letter-1",
    "paper-duet-letter-2",
    "paper-duet-letter-3",
    "paper-duet-letter-4",
    "paper-duet-letter-5",
    "paper-duet-letter-6",
    "paper-duet-letter-7"
  ],
  "minimumXP": 8980,
  "explicitEntryRequired": true,
  "action": "enter-continuation",
  "entryButton": "Open the next four correspondences",
  "deferButton": "Stay at my table",
  "entryCopy": "The first twenty-four chapters are complete. Four more envelopes bring forty new pictures. Open them when you want to continue; your finished letters and saved table stay with you.",
  "terminalPreviousChapterNextIdRemainsNull": true
}]);
export const VOLUMES=freeze([...V6.VOLUMES,{
  "id": "sideways-correspondences",
  "title": "Sideways Company and three more",
  "chapterIds": [
    "sideways-company",
    "a-little-tending",
    "warm-regards",
    "next-move"
  ],
  "storyIds": [
    "sideways-company-letter-1",
    "sideways-company-letter-2",
    "sideways-company-letter-3",
    "sideways-company-letter-4",
    "a-little-tending-letter-1",
    "a-little-tending-letter-2",
    "a-little-tending-letter-3",
    "a-little-tending-letter-4",
    "a-little-tending-letter-5",
    "warm-regards-letter-1",
    "warm-regards-letter-2",
    "warm-regards-letter-3",
    "warm-regards-letter-4",
    "warm-regards-letter-5",
    "next-move-letter-1",
    "next-move-letter-2",
    "next-move-letter-3",
    "next-move-letter-4",
    "next-move-letter-5"
  ],
  "pieceIds": [
    "c280-cr1",
    "c280-cr2",
    "c280-cr3",
    "c280-cr4",
    "c280-cr5",
    "c280-sn1",
    "c280-sn2",
    "c280-sn3",
    "c280-sn4",
    "c280-sn5",
    "c280-wc1",
    "c280-wc2",
    "c280-wc3",
    "c280-wc4",
    "c280-wc5",
    "c280-gt1",
    "c280-gt2",
    "c280-gt3",
    "c280-gt4",
    "c280-gt5",
    "c280-fi1",
    "c280-fi2",
    "c280-fi3",
    "c280-fi4",
    "c280-fi5",
    "c280-mi1",
    "c280-mi2",
    "c280-mi3",
    "c280-mi4",
    "c280-mi5",
    "c280-kn1",
    "c280-kn2",
    "c280-kn3",
    "c280-kn4",
    "c280-kn5",
    "c280-cg1",
    "c280-cg2",
    "c280-cg3",
    "c280-cg4",
    "c280-cg5"
  ],
  "completionCopy": "These four correspondences are complete. There are now 280 pictures available across the opened collections; discovering them all is optional. The earlier endings remain yours. This is the 280-picture checkpoint on the way to 320."
}]);
export const boundariesForVersion=version=>version>=7?CONTINUATIONS:V6.boundariesForVersion(version);
export const boundaryById=(id,version=7)=>boundariesForVersion(version).find(b=>b.id===id)??null;
export const boundaryAt=s=>boundariesForVersion(s.contentVersion).find(b=>b.fromChapterId===s.chapterId)??null;
export const volumeOf=s=>VOLUMES.find(v=>v.chapterIds.includes(s.chapterId))??VOLUMES[0];
export const continuationEntered=(s,boundaryId=FIRST.id)=>{const b=boundaryById(boundaryId,s.contentVersion);return !!b&&s.enteredChapters.includes(b.toChapterId);};
export const availableVolumes=s=>VOLUMES.filter((v,i)=>i===0||s.enteredChapters.includes(v.chapterIds[0]));
export function collectionScope(s,id=availableVolumes(s).length>1?'all':VOLUMES[0].id){const available=availableVolumes(s),v=available.find(v=>v.id===id),all=available.length>1&&id==='all',chosen=v??available[0],ids=all?available.flatMap(v=>v.pieceIds):chosen.pieceIds;return{id:all?'all':chosen.id,title:all?'All available pictures':chosen.title,pieceIds:ids,collected:ids.filter(id=>s.discoveries.includes(id)).length,total:ids.length};}
