import {CONTINUATION as FIRST,VOLUMES as OLD} from './volumes.v5.js';
const freeze=v=>{if(v&&typeof v==='object'){Object.values(v).forEach(freeze);Object.freeze(v);}return v;};
export const CONTINUATION=FIRST;
export const CONTINUATIONS=freeze([FIRST,{
  "id": "after-four-more-correspondences",
  "fromChapterId": "short-measure",
  "toChapterId": "cross-currents",
  "fromVolumeId": "four-more-correspondences",
  "toVolumeId": "cross-currents-correspondences",
  "requiredPreviousStoryIds": [
    "garden-letter-1",
    "garden-letter-2",
    "garden-letter-3",
    "garden-letter-4",
    "garden-letter-5",
    "garden-letter-6",
    "garden-letter-7",
    "garden-letter-8",
    "garden-letter-9",
    "moon-letter-1",
    "moon-letter-2",
    "moon-letter-3",
    "moon-letter-4",
    "moon-letter-5",
    "moon-letter-6",
    "moon-letter-7",
    "riverside-letter-1",
    "riverside-letter-2",
    "riverside-letter-3",
    "riverside-letter-4",
    "riverside-letter-5",
    "riverside-letter-6",
    "riverside-letter-7",
    "lantern-letter-1",
    "lantern-letter-2",
    "lantern-letter-3",
    "lantern-letter-4",
    "lantern-letter-5",
    "lantern-letter-6",
    "lantern-letter-7",
    "wrong-address-letter-1",
    "wrong-address-letter-2",
    "wrong-address-letter-3",
    "wrong-address-letter-4",
    "wrong-address-letter-5",
    "wrong-address-letter-6",
    "wrong-address-letter-7",
    "quiet-company-letter-1",
    "quiet-company-letter-2",
    "quiet-company-letter-3",
    "quiet-company-letter-4",
    "quiet-company-letter-5",
    "quiet-company-letter-6",
    "namesakes-letter-1",
    "namesakes-letter-2",
    "namesakes-letter-3",
    "namesakes-letter-4",
    "namesakes-letter-5",
    "namesakes-letter-6",
    "namesakes-letter-7",
    "useful-gaps-letter-1",
    "useful-gaps-letter-2",
    "useful-gaps-letter-3",
    "useful-gaps-letter-4",
    "useful-gaps-letter-5",
    "useful-gaps-letter-6",
    "useful-gaps-letter-7",
    "small-talk-letter-1",
    "small-talk-letter-2",
    "small-talk-letter-3",
    "small-talk-letter-4",
    "small-talk-letter-5",
    "small-talk-letter-6",
    "hello-again-letter-1",
    "hello-again-letter-2",
    "hello-again-letter-3",
    "hello-again-letter-4",
    "hello-again-letter-5",
    "hello-again-letter-6",
    "hello-again-letter-7",
    "off-beat-letter-1",
    "off-beat-letter-2",
    "off-beat-letter-3",
    "off-beat-letter-4",
    "off-beat-letter-5",
    "off-beat-letter-6",
    "off-beat-letter-7",
    "return-mail-letter-1",
    "return-mail-letter-2",
    "return-mail-letter-3",
    "return-mail-letter-4",
    "return-mail-letter-5",
    "return-mail-letter-6",
    "return-mail-letter-7",
    "return-mail-letter-8",
    "fair-weather-letter-1",
    "fair-weather-letter-2",
    "fair-weather-letter-3",
    "fair-weather-letter-4",
    "fair-weather-letter-5",
    "fair-weather-letter-6",
    "fair-weather-letter-7",
    "double-meaning-letter-1",
    "double-meaning-letter-2",
    "double-meaning-letter-3",
    "double-meaning-letter-4",
    "double-meaning-letter-5",
    "double-meaning-letter-6",
    "double-meaning-letter-7",
    "fine-print-letter-1",
    "fine-print-letter-2",
    "fine-print-letter-3",
    "fine-print-letter-4",
    "fine-print-letter-5",
    "fine-print-letter-6",
    "sound-advice-letter-1",
    "sound-advice-letter-2",
    "sound-advice-letter-3",
    "sound-advice-letter-4",
    "sound-advice-letter-5",
    "sound-advice-letter-6",
    "sound-advice-letter-7",
    "sound-advice-letter-8",
    "small-impressions-letter-1",
    "small-impressions-letter-2",
    "small-impressions-letter-3",
    "small-impressions-letter-4",
    "small-impressions-letter-5",
    "small-impressions-letter-6",
    "small-impressions-letter-7",
    "second-look-letter-1",
    "second-look-letter-2",
    "second-look-letter-3",
    "second-look-letter-4",
    "second-look-letter-5",
    "second-look-letter-6",
    "loose-ends-letter-1",
    "loose-ends-letter-2",
    "loose-ends-letter-3",
    "loose-ends-letter-4",
    "loose-ends-letter-5",
    "loose-ends-letter-6",
    "loose-ends-letter-7",
    "short-measure-letter-1",
    "short-measure-letter-2",
    "short-measure-letter-3",
    "short-measure-letter-4",
    "short-measure-letter-5",
    "short-measure-letter-6"
  ],
  "minimumXP": 7810,
  "explicitEntryRequired": true,
  "action": "enter-continuation",
  "entryButton": "Open the next four correspondences",
  "deferButton": "Stay at my table",
  "entryCopy": "The first twenty chapters are complete. Four new envelopes bring forty more pictures. Open them when you want another reply; your completed correspondences and saved table stay with you.",
  "terminalPreviousChapterNextIdRemainsNull": true
}]);
export const VOLUMES=freeze([...OLD,{
  "id": "cross-currents-correspondences",
  "title": "Cross Currents and three more",
  "chapterIds": [
    "cross-currents",
    "safe-keeping",
    "give-and-take",
    "paper-duet"
  ],
  "storyIds": [
    "cross-currents-letter-1",
    "cross-currents-letter-2",
    "cross-currents-letter-3",
    "cross-currents-letter-4",
    "cross-currents-letter-5",
    "cross-currents-letter-6",
    "safe-keeping-letter-1",
    "safe-keeping-letter-2",
    "safe-keeping-letter-3",
    "safe-keeping-letter-4",
    "safe-keeping-letter-5",
    "safe-keeping-letter-6",
    "give-and-take-letter-1",
    "give-and-take-letter-2",
    "give-and-take-letter-3",
    "give-and-take-letter-4",
    "give-and-take-letter-5",
    "give-and-take-letter-6",
    "paper-duet-letter-1",
    "paper-duet-letter-2",
    "paper-duet-letter-3",
    "paper-duet-letter-4",
    "paper-duet-letter-5",
    "paper-duet-letter-6",
    "paper-duet-letter-7"
  ],
  "pieceIds": [
    "b240-cp1",
    "b240-cp2",
    "b240-cp3",
    "b240-cp4",
    "b240-cp5",
    "b240-kt1",
    "b240-kt2",
    "b240-kt3",
    "b240-kt4",
    "b240-kt5",
    "b240-vb1",
    "b240-vb2",
    "b240-vb3",
    "b240-vb4",
    "b240-vb5",
    "b240-pa1",
    "b240-pa2",
    "b240-pa3",
    "b240-pa4",
    "b240-pa5",
    "b240-bs1",
    "b240-bs2",
    "b240-bs3",
    "b240-bs4",
    "b240-bs5",
    "b240-mg1",
    "b240-mg2",
    "b240-mg3",
    "b240-mg4",
    "b240-mg5",
    "b240-ac1",
    "b240-ac2",
    "b240-ac3",
    "b240-ac4",
    "b240-ac5",
    "b240-tr1",
    "b240-tr2",
    "b240-tr3",
    "b240-tr4",
    "b240-tr5"
  ],
  "completionCopy": "These four correspondences are complete. The first sixteen and the four that followed remain complete too. Your table, pictures and earlier letters are here to revisit."
}]);
export const boundariesForVersion=version=>version>=6?CONTINUATIONS:version===5?[FIRST]:[];
export const boundaryById=(id,version=6)=>boundariesForVersion(version).find(b=>b.id===id)??null;
export const boundaryAt=s=>boundariesForVersion(s.contentVersion).find(b=>b.fromChapterId===s.chapterId)??null;
export const volumeOf=s=>VOLUMES.find(v=>v.chapterIds.includes(s.chapterId))??VOLUMES[0];
export const continuationEntered=(s,boundaryId=FIRST.id)=>{const b=boundaryById(boundaryId,s.contentVersion);return !!b&&s.enteredChapters.includes(b.toChapterId);};
export const availableVolumes=s=>VOLUMES.filter((v,i)=>i===0||s.enteredChapters.includes(v.chapterIds[0]));
export function collectionScope(s,id=availableVolumes(s).length>1?'all':VOLUMES[0].id){const available=availableVolumes(s),v=available.find(v=>v.id===id),all=available.length>1&&id==='all',chosen=v??available[0],ids=all?available.flatMap(v=>v.pieceIds):chosen.pieceIds;return{id:all?'all':chosen.id,title:all?'All available pictures':chosen.title,pieceIds:ids,collected:ids.filter(id=>s.discoveries.includes(id)).length,total:ids.length};}
