import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import * as E from '../src/career/engine.js';import * as C from '../src/career/content.js';import * as E2 from '../src/career/engine.v2.js';import * as C2 from '../src/career/content.v2.js';import * as E3 from '../src/career/engine.v3.js';import * as C3 from '../src/career/content.v3.js';
import {driver,storageHarness} from '../tests/campaign-browser/save-fixtures.mjs';import {createCareerSession} from '../src/career/session.js';const d=driver(),d2=driver(E2,C2),d3=driver(E3,C3);

test('a suspended schema-3 story and held optional promises migrate intact under the single session writer',async()=>{
 let old=E2.createCareer('suspended-v3');for(const c of C2.CHAPTERS){if(c.number>1)old=d2.act(old,{type:'start-next-chapter',chapterId:c.id});while(!E2.chapterComplete(old))old=d2.complete(old,old.orders.find(o=>o.origin==='story'));}old=E3.upgradeCareer(old);old=d3.act(old,{type:'start-next-chapter',chapterId:'riverside-correspondence'});old=d3.act(old,{type:'resume-optional',orderId:old.heldOrders[0].id});old=d3.act(old,{type:'supply',familyId:old.activeSourceIds[0]});
 const h=storageHarness(old),session=createCareerSession(h);const result=await session.open();assert(result.saved);for(const k of ['heldOrders','suspendedStory','resumedOptionalId','orders','focusedOrderId','activeSourceIds','board','nextOrderSeq','purchases','receipts','milestones'])assert.deepEqual(result.state[k],old[k]);for(let i=0;i<old.history.length;i++)for(const f of C3.FAMILIES){assert.deepEqual(result.state.history[i].material[f.id],old.history[i].material[f.id]);assert.deepEqual(result.state.history[i].sources[f.id],old.history[i].sources[f.id]);}
 assert.deepEqual(E.upgradeCareer(result.state),result.state);assert.throws(()=>E3.upgradeCareer(result.state));const restored=await session.commit(E.commandFor(result.state,{type:'return-to-story'}));assert(restored.saved);assert.deepEqual(restored.state.orders.find(o=>o.id===old.suspendedStory.id),old.suspendedStory);
 const failed=storageHarness(old,{failWrite:true});const before=failed.map.get(C.STORAGE_KEY);assert.equal((await createCareerSession(failed).open()).saved,false);assert.equal(failed.map.get(C.STORAGE_KEY),before);
});
test('a full table of distinct retained pictures has free reversible recovery and keeps discoveries',()=>{
 let s=E.upgradeCareer(JSON.parse(fs.readFileSync(new URL('full-basic-journey.json',import.meta.url))).state);for(let i=0;i<25;i++)if(s.board[i])s=d.act(s,{type:'recycle',at:i,tileId:s.board[i].id,confirmed:true});const kept=new Set;
 for(const [i,f] of C.FAMILIES.slice(0,25).entries()){let id;[s,id]=d.acquire(s,f.pieceIds[i<5?4:0],kept);kept.add(id);}assert(!s.board.includes(null));assert.equal(E.goalHint(s).kind,'recover');const before=structuredClone(s);s=d.act(s,{type:'recycle',at:0,tileId:s.board[0].id,confirmed:true});assert(s.board.includes(null));assert.equal(s.xp,before.xp);assert.equal(s.coinsEarned,before.coinsEarned);assert.equal(s.coinsSpent,0);assert.deepEqual(s.discoveries,before.discoveries);s=d.act(s,{type:'undo'});assert.deepEqual(s.board,before.board);assert.deepEqual(s.material,before.material);assert.deepEqual(s.sources,before.sources);
});
