import fs from 'node:fs';import assert from 'node:assert/strict';import {resolve,relative,isAbsolute} from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';
import {CATALOG} from '../../src/career/content.js';import {digest,regularBytes,filesUnder} from '../../full-campaign-gate/evidence.mjs';import {gitRead} from './git-read.mjs';import {LIMITS,ROOT,ORDER,approval} from './policy.mjs';import {REPO_ROOT,requireRepoCwd} from './paths.mjs';
export const SOURCE_ROOTS=['src','public','gate','tests','full-campaign-gate','full-campaign-probe','full-browser-fixtures','full-browser-evidence','campaign-evidence','stage-a-evidence','stage-b-evidence','stage-c-evidence','stage-d-evidence','.github','docs'];
export const SOURCE_FILES=['career.html','career.vite.config.js','package.json','package-lock.json','playwright.full-campaign.config.mjs','playwright.campaign.config.mjs'];
export const inventory=root=>filesUnder(root).map(file=>{const b=regularBytes(root,file);return{file,bytes:b.length,sha256:digest(b)};});
export const sourceFiles=()=>SOURCE_ROOTS.filter(fs.existsSync).flatMap(root=>inventory(root).map(r=>({...r,file:root+'/'+r.file}))).concat(SOURCE_FILES.map(file=>{const b=regularBytes(REPO_ROOT,file);return{file,bytes:b.length,sha256:digest(b)};})).sort((a,b)=>a.file<b.file?-1:a.file>b.file?1:0);
export function verifyVersions(){assert.equal(Number(process.versions.node.split('.')[0]),24);const lock=JSON.parse(fs.readFileSync('package-lock.json'));for(const name of ['@playwright/test','playwright','playwright-core','vite','@vitejs/plugin-react','react','react-dom'])assert.equal(JSON.parse(fs.readFileSync(`node_modules/${name}/package.json`)).version,lock.packages[`node_modules/${name}`].version);assert.equal(lock.packages['node_modules/@playwright/test'].version,'1.61.1');}
export function prepareSource(){requireRepoCwd();const payload={schemaVersion:1,status:'PROVISIONAL_PREPARATION_NOT_ACCEPTED_OR_AUTHORIZED',files:sourceFiles()};fs.writeFileSync('stage-d-source.preparation.json',JSON.stringify(payload,null,2)+'\n');return verifySource();}
export function validateAcceptedBaseline(a,b){for(const x of [a.commit,a.tree])assert.match(x,/^[a-f0-9]{40}$/);for(const x of [a.sourceFingerprint,a.buildFingerprint,a.probeFingerprint,a.sourceReceiptSha256])assert.match(x,/^[a-f0-9]{64}$/);assert(Number.isSafeInteger(a.runId)&&a.runId>0);assert.equal(a.status,'accepted-corrected-280-native-artifact-and-scoped-visual-evidence');assert.equal(a.commit,b.commit);assert.equal(a.tree,b.tree);assert.equal(a.trackedFiles,b.files.length);assert.equal(a.trackedFiles,616);assert.equal(a.nativeCases,20);assert.equal(a.pngs,82);assert.equal(a.allOriginalsVisuallyInspected,82);assert.equal(a.journalsComplete,true);assert.equal(a.cleanup,'confirmed-clean-both-profiles');return{commit:a.commit,tree:a.tree,runId:a.runId,sourceFingerprint:a.sourceFingerprint,buildFingerprint:a.buildFingerprint,probeFingerprint:a.probeFingerprint,acceptanceReceiptSha256:a.sourceReceiptSha256};}
export function acceptedBaseline(){return validateAcceptedBaseline(JSON.parse(fs.readFileSync('stage-d-evidence/baseline-acceptance.frozen.json')),JSON.parse(fs.readFileSync('stage-d-evidence/baseline-files.frozen.json')));}
export function bindSource(){requireRepoCwd();const payload={schemaVersion:1,status:'ACCEPTED_SOURCE_FOR_AUTHORIZED_RUN',meaning:'Reviewed local320source on accepted280baseline; native320acceptance remains pending',baseline:acceptedBaseline(),files:sourceFiles()};fs.writeFileSync('stage-d-source.json',JSON.stringify(payload,null,2)+'\n',{flag:'wx'});return verifySource();}
export function verifySource(){requireRepoCwd();const file=fs.existsSync('stage-d-source.json')?'stage-d-source.json':'stage-d-source.preparation.json',bytes=fs.readFileSync(file),manifest=JSON.parse(bytes);assert.equal(manifest.schemaVersion,1);assert(['PROVISIONAL_PREPARATION_NOT_ACCEPTED_OR_AUTHORIZED','ACCEPTED_SOURCE_FOR_AUTHORIZED_RUN'].includes(manifest.status));if(manifest.status==='ACCEPTED_SOURCE_FOR_AUTHORIZED_RUN')assert.deepEqual(manifest.baseline,acceptedBaseline());assert.deepEqual(manifest.files,sourceFiles(),'StageD source differs from its current preparation/binding');return{sourceFingerprint:digest(bytes),manifest,file};}
export const canonicalFingerprint=value=>digest(Buffer.from(JSON.stringify(value)));
export function buildProof(){const{sourceFingerprint}=verifySource(),files=inventory('dist-stage-d').map(r=>({...r,file:'dist-stage-d/'+r.file}));assert(files.some(r=>r.file==='dist-stage-d/career.html'));const art=CATALOG.PIECES.map(p=>{const path=relative(REPO_ROOT,fileURLToPath(p.art)),bytes=regularBytes(REPO_ROOT,path),sha256=digest(bytes),builtPaths=files.filter(f=>f.sha256===sha256).map(f=>f.file);assert(builtPaths.length,`Missing built art ${p.id}`);return{id:p.id,path,sha256,bytes:bytes.length,builtPaths};});assert.equal(art.length,320);return{schemaVersion:1,sourceFingerprint,files,art};}
export function prepareBuild(){const payload=buildProof(),proof={...payload,buildFingerprint:canonicalFingerprint(payload)};fs.writeFileSync('stage-d-build.json',JSON.stringify(proof,null,2)+'\n');return proof;}
export function verifyBuild(){const proof=JSON.parse(fs.readFileSync('stage-d-build.json')),{buildFingerprint,...payload}=proof;assert.equal(buildFingerprint,canonicalFingerprint(payload));assert.deepEqual(payload,buildProof());return proof;}
export function probeRoot(){const root=process.env.MOTICOS_STAGE_D_PROBE_OUTPUT;assert(root&&isAbsolute(root)&&resolve(root)!==resolve(REPO_ROOT)&&!resolve(root).startsWith(resolve(REPO_ROOT)+'/'),'External current/v7 probe output required');return resolve(root);}
export function prepareProbe(){const build=verifyBuild(),proof={schemaVersion:1,status:'PROVISIONAL_PREPARATION_NOT_NATIVE_EVIDENCE',sourceFingerprint:build.sourceFingerprint,buildFingerprint:build.buildFingerprint,files:inventory(probeRoot())};for(const file of ['stage-d-evidence/browser/probe/current/index.html','stage-d-evidence/browser/probe/v7/index.html'])assert(proof.files.some(r=>r.file===file),file);fs.writeFileSync('stage-d-probe.preparation.json',JSON.stringify(proof,null,2)+'\n');return proof;}
export function preparedIdentity(){const b=verifyBuild(),bytes=fs.readFileSync('stage-d-probe.preparation.json'),p=JSON.parse(bytes);assert.equal(p.sourceFingerprint,b.sourceFingerprint);assert.equal(p.buildFingerprint,b.buildFingerprint);assert.deepEqual(p.files,inventory(probeRoot()));return{sourceFingerprint:b.sourceFingerprint,buildFingerprint:b.buildFingerprint,probeFingerprint:digest(bytes)};}
export function commitIdentity(){const{manifest}=verifySource();assert.equal(manifest.status,'ACCEPTED_SOURCE_FOR_AUTHORIZED_RUN','Final accepted baseline has not been bound');const git=(...args)=>gitRead(...args).trim(),commit=git('rev-parse','HEAD'),parent=manifest.baseline.commit,parentTree=manifest.baseline.tree;assert.match(commit,/^[a-f0-9]{40}$/);assert.match(parent,/^[a-f0-9]{40}$/);assert.match(parentTree,/^[a-f0-9]{40}$/);assert.equal(git('rev-parse',`${parent}^{tree}`),parentTree);git('merge-base','--is-ancestor',parent,'HEAD');return{commit,parent,parentTree};}
export function identity(){return{...preparedIdentity(),...commitIdentity()};}
export function requireApproval(){const id=identity(),file=process.env.MOTICOS_STAGE_D_APPROVAL;assert(file&&resolve(file)===resolve(ROOT,'approval.json')&&fs.existsSync(file),'Fresh bounded320 approval required');approval(JSON.parse(fs.readFileSync(file)),id,process.env);return id;}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){requireRepoCwd();verifyVersions();const command=process.argv[2];assert.equal(process.argv.length,3);assert(['prepare-source','bind-source','prepare-build','prepare-probe','verify-source'].includes(command));const result=({'prepare-source':prepareSource,'bind-source':bindSource,'prepare-build':prepareBuild,'prepare-probe':prepareProbe,'verify-source':verifySource})[command]();console.log(JSON.stringify({command,sourceFingerprint:result.sourceFingerprint,buildFingerprint:result.buildFingerprint,status:'PREPARATION_ONLY'}));}
