import test from 'node:test';import assert from 'node:assert/strict';
import {responseMetadata,errorResponseSummary,withinDeadline} from './clock-response.mjs';
const signal=()=>new AbortController().signal;
test('clock response records only allowlisted capped headers',()=>{const r=new Response('{}',{status:403,headers:{date:'today','x-github-request-id':'r'.repeat(300),'x-ratelimit-remaining':'0','set-cookie':'private','authorization':'secret','server':'ignored'}});const out=responseMetadata(r);assert.equal(out.status,403);assert.equal(out.headers['x-github-request-id'].length,128);assert.deepEqual(Object.keys(out.headers).sort(),['date','x-github-request-id','x-ratelimit-remaining'].sort());assert(!JSON.stringify(out).includes('private'));});
test('clock error summary caps selected message and reports category without retry',async()=>{for(const [message,classification]of [['API rate limit exceeded','rate-limit-reported'],['Resource not accessible by integration','access-denial-reported'],['Forbidden','unclassified']]){const out=await errorResponseSummary(new Response(JSON.stringify({message,unused:'never retain'})),signal());assert.equal(out.classification,classification);assert.equal(out.message,message);assert(!JSON.stringify(out).includes('never retain'));}const out=await errorResponseSummary(new Response(JSON.stringify({message:'x'.repeat(700)})),signal());assert.equal(out.message.length,512);});
test('clock body size and invalid JSON fail closed without retaining raw bytes',async()=>{const big=await errorResponseSummary(new Response('x'.repeat(10000)),signal());assert.deepEqual(big,{status:'truncated',limitBytes:2048});assert.equal((await errorResponseSummary(new Response('<html>private</html>'),signal())).status,'unavailable');});
test('same request abort deadline also bounds body and unresolved fetch promises',async()=>{const controller=new AbortController();const pending=withinDeadline(new Promise(()=>{}),controller.signal);controller.abort();await assert.rejects(pending,/deadline/);const c=new AbortController(),response={body:{getReader:()=>({read:()=>new Promise(()=>{}),releaseLock(){}})}};const body=errorResponseSummary(response,c.signal);c.abort();assert.deepEqual(await body,{status:'unavailable',reason:'Original request deadline reached'});});

test('failed clock request persists bounded classification and never writes an epoch',async()=>{const fs=await import('node:fs'),os=await import('node:os'),{join}=await import('node:path');const {establishClock}=await import('./job-clock.mjs');const {TARGET}=await import('./policy.mjs');const dir=fs.mkdtempSync(join(os.tmpdir(),'clock-response-'));try{let calls=0;const env={GITHUB_ACTIONS:'true',MOTICOS_320_PUBLIC_REPO:'true',GITHUB_REPOSITORY:TARGET.repository,GITHUB_REF:TARGET.ref,GITHUB_SHA:'a'.repeat(40),GITHUB_RUN_ATTEMPT:'1',GITHUB_EVENT_NAME:'push',GITHUB_RUN_ID:'123',RUNNER_ENVIRONMENT:'github-hosted',RUNNER_OS:'Linux',GITHUB_ENV:join(dir,'env'),RUNNER_TEMP:dir};await assert.rejects(establishClock({env,root:join(dir,'setup'),fetcher:async(url,options)=>{calls++;assert(!('Authorization' in options.headers));return new Response(JSON.stringify({message:'API rate limit exceeded',other:'omit'}),{status:403,headers:{'x-ratelimit-remaining':'0','set-cookie':'omit'}});}}),/HTTP 403/);const saved=JSON.parse(fs.readFileSync(join(dir,'setup/job-clock.json')));assert.equal(calls,1);assert.equal(fs.existsSync(env.GITHUB_ENV),false);assert.equal(saved.response.errorBody.classification,'rate-limit-reported');assert.equal(saved.response.headers['x-ratelimit-remaining'],'0');assert(!JSON.stringify(saved).includes('omit'));}finally{fs.rmSync(dir,{recursive:true,force:true});}});

test('pre-aborted deadline still observes an already rejected operation',async()=>{const controller=new AbortController();controller.abort();await assert.rejects(withinDeadline(Promise.reject(Error('operation aborted')),controller.signal),/deadline/);await new Promise(resolve=>setImmediate(resolve));});
