import test from 'node:test';import assert from 'node:assert/strict';
import {resourceSnapshot,resourceDiagnostics,observeBoundedProcess} from './resource-diagnostics.mjs';
function operations(files,pids=['1','7','8']){return{readdirSync:()=>pids,openSync(p){if(!(p in files))throw Object.assign(Error('missing'),{code:'ENOENT'});return p;},readSync(fd,b){return b.write(files[fd]);},closeSync(){}};}
const files={'/sys/fs/cgroup/memory.current':'1234','/sys/fs/cgroup/memory.peak':'5678','/sys/fs/cgroup/memory.max':'max','/sys/fs/cgroup/memory.events':'low 0\noom 1\noom_kill 0\nsecret private','/proc/1/stat':'1 (docker-init) S 0 1','/proc/7/stat':'7 (WebKitWebProcess) S 1 7','/proc/7/status':'Name: WebKitWebProcess\nVmRSS: 2048 kB\nSECRET: private','/proc/8/stat':'8 (node) R 1 7','/proc/8/status':'VmRSS: 1024 kB'};
test('resource snapshot retains only bounded process and numeric memory fields',()=>{const r=resourceSnapshot({operations:operations(files),now:()=>0});assert.equal(r.status,'complete');assert.equal(r.rssKiB,3072);assert.equal(r.processes.length,2);assert.deepEqual(r.cgroup['memory.events'].values,{low:'0',oom:'1',oom_kill:'0'});assert(!JSON.stringify(r).includes('private'));assert.deepEqual(r.processes[0],{pid:7,ppid:1,pgid:7,state:'S',family:'webkit',rssKiB:2048});});
test('unavailable counters and truncated scans remain explicit observations',()=>{const r=resourceSnapshot({operations:operations({}),now:()=>0});assert.equal(r.cgroup['memory.current'].status,'unavailable');assert.equal(r.vanished,3);const pids=Array.from({length:300},(_,i)=>String(i+1));assert.equal(resourceSnapshot({operations:operations({},pids),now:()=>0}).status,'truncated');let n=0;assert.equal(resourceSnapshot({operations:operations(files),now:()=>n+=51}).status,'truncated');});
test('resource monitor keeps last twelve samples and peak, retires timer and stays under byte cap',()=>{let tick,cleared=false,count=0;const writes=[];const m=resourceDiagnostics({path:'unused',binding:{sourceFingerprint:'x'},profile:'webkit',snapshot:()=>({status:'complete',rssKiB:++count,processes:[]}),now:()=>123,schedule:(fn,ms)=>{assert.equal(ms,10000);tick=fn;return 9;},cancel:id=>{assert.equal(id,9);cleared=true;},write:(p,b)=>writes.push(JSON.parse(b))});for(let i=0;i<30;i++)tick();m.stop();const r=writes.at(-1);assert.equal(r.samples.length,12);assert.equal(r.totalSamples,32);assert.equal(r.maxObservedRssKiB,32);assert.equal(r.samples.at(-1).phase,'after-profile');assert(cleared);tick();assert.equal(writes.length,32);assert(Buffer.byteLength(JSON.stringify(r))<65536);});
test('resource sampler and file failures cannot replace native process result',()=>{let tick;const m=resourceDiagnostics({snapshot:()=>{throw Error('unavailable');},schedule:fn=>(tick=fn,1),cancel(){},write(){throw Error('disk');}});assert.doesNotThrow(()=>{tick();m.stop();});});

test('diagnostic initialization failure still awaits native process and preserves its verdict',async()=>{let resolve;const launched=new Promise(r=>resolve=r);let done=false;const observed=observeBoundedProcess(launched,{},()=>{throw Error('scheduler');}).then(r=>(done=true,r));await Promise.resolve();assert.equal(done,false);resolve({status:1,error:'original native failure',groupCleanup:'terminated'});assert.deepEqual(await observed,{status:1,error:'original native failure',groupCleanup:'terminated',resourceObserver:{status:'unavailable-or-partial',errors:['initialization-failed']}});});
test('diagnostic retirement failure preserves native result or original rejection',async()=>{const create=()=>({stop(){throw Error('retirement');}});const r=await observeBoundedProcess(Promise.resolve({status:0,groupCleanup:'not-required'}),{},create);assert.equal(r.status,0);assert.equal(r.groupCleanup,'not-required');assert.deepEqual(r.resourceObserver.errors,['retirement-failed']);const original=Error('native rejection');await assert.rejects(observeBoundedProcess(Promise.reject(original),{},create),e=>e===original);});
