import test from 'node:test';import assert from 'node:assert/strict';
import {assertReconstructionReviewed} from './fixture-closure.mjs';
const baseline={commit:'a'.repeat(40),tree:'b'.repeat(40),runId:123},source={sourceFingerprint:'c'.repeat(64),manifest:{status:'ACCEPTED_SOURCE_FOR_AUTHORIZED_RUN',baseline}};
test('review predicate requires freshly verified accepted source and exact accepted baseline',()=>{assert.deepEqual(assertReconstructionReviewed({readSource:()=>source,readBaseline:()=>baseline}),source);for(const status of ['PROVISIONAL_PREPARATION_NOT_ACCEPTED_OR_AUTHORIZED','passed',undefined])assert.throws(()=>assertReconstructionReviewed({readSource:()=>({...source,manifest:{...source.manifest,status}}),readBaseline:()=>baseline}));assert.throws(()=>assertReconstructionReviewed({readSource:()=>source,readBaseline:()=>({...baseline,commit:'d'.repeat(40)})}),/baseline/);assert.throws(()=>assertReconstructionReviewed({readSource:()=>({...source,sourceFingerprint:'unsealed'}),readBaseline:()=>baseline}));});
test('review predicate propagates stale source and tampered baseline integrity failures',()=>{for(const message of ['Source bytes changed','Historical baseline manifest tampered'])assert.throws(()=>assertReconstructionReviewed({readSource:()=>{throw Error(message);},readBaseline:()=>baseline}),new RegExp(message));assert.throws(()=>assertReconstructionReviewed({readSource:()=>source,readBaseline:()=>{throw Error('Baseline verification failed');}}),/Baseline verification failed/);});

import {verifyScreenshotCapture} from './validate.mjs';
import {SCREENSHOTS} from './policy.mjs';
function captureRow(name,kind){const metrics={scrollWidth:320,scrollHeight:1000,offsetWidth:320,offsetHeight:1000,clientWidth:320,clientHeight:568},before={viewport:{width:320,height:568,dpr:1},fonts:'loaded',body:{...metrics},root:{...metrics}};if(kind==='viewport-modal')before.modal={selector:'.career-dialog',rect:{left:10,top:10,right:310,bottom:558},scrollport:{left:11,top:11,right:309,bottom:557},scrollLeft:0,scrollTop:10,scrollWidth:298,scrollHeight:900,clientWidth:298,clientHeight:546,overflowY:'auto',documentScroll:{x:0,y:0},targets:[{selector:'.card',rect:{left:20,top:40,right:290,bottom:100}}]};return{name,captureKind:kind,dimensions:[320,kind==='viewport-modal'?568:1000],geometry:{schemaVersion:1,captureKind:kind,before,after:structuredClone(before)}};}
test('only the four D06/D11 captures require viewport modal scope; all other planned screenshots stay full-page',()=>{
 const names=['D06-page-first.png','D06-page-last.png','D11-all-sources-first.png','D11-all-sources-last.png'];
 assert.equal(SCREENSHOTS.length,32);
 for(const name of SCREENSHOTS){const kind=names.includes(name)?'viewport-modal':'full-page',row=captureRow(name,kind);assert.deepEqual(verifyScreenshotCapture(row),row.dimensions);assert.throws(()=>verifyScreenshotCapture(captureRow(name,kind==='full-page'?'viewport-modal':'full-page')),/planned scope/);}
 const legacy=captureRow('D09-desktop-standard.png','full-page');delete legacy.captureKind;delete legacy.geometry.captureKind;assert.deepEqual(verifyScreenshotCapture(legacy),[320,1000]);
 const wrong=captureRow(names[0],'viewport-modal');wrong.dimensions=[320,1000];assert.throws(()=>verifyScreenshotCapture(wrong),/dimensions must match/);
 const dishonest=captureRow(names[0],'viewport-modal');dishonest.captureKind='full-page';assert.throws(()=>verifyScreenshotCapture(dishonest),/row capture kind/);
});
