import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {planBoardFocusReveal,focusBoardCell} from '../src/career/boardFocus.js';
import {nextBoardIndex} from '../src/career/feedback.js';
function rig(width=374){const calls=[],document={activeElement:null},board={scrollLeft:0,scrollTop:19,scrollWidth:554,clientWidth:width,clientLeft:1,getBoundingClientRect:()=>({left:7}),scrollTo(options){calls.push(['scroll',options]);this.scrollLeft=options.left;this.scrollTop=options.top;}};const cells=Array.from({length:25},(_,index)=>({ownerDocument:document,focus(){calls.push(['focus',index]);document.activeElement=this;},closest(selector){assert.equal(selector,'.career-board');return board;},getBoundingClientRect(){return{left:15+(index%5)*108-board.scrollLeft,right:119+(index%5)*108-board.scrollLeft};}}));return{calls,document,board,cells};}
function fullyVisible(r,index){const b=r.board,t=r.cells[index].getBoundingClientRect(),left=8;assert(t.left>=left&&t.right<=left+b.clientWidth);assert(b.scrollLeft>=0&&b.scrollLeft<=b.scrollWidth-b.clientWidth);assert.equal(b.scrollTop,19);assert.equal(r.document.activeElement,r.cells[index]);}
test('partly visible fourth column is revealed after native focus, preserving vertical scroll',()=>{const r=rig();const before=r.cells[3].getBoundingClientRect();assert(before.left<382&&before.right>382);focusBoardCell(r.cells[3]);fullyVisible(r,3);assert.deepEqual(r.calls,[['focus',3],['scroll',{left:64,top:19,behavior:'instant'}]]);assert.equal(planBoardFocusReveal({scrollLeft:0,scrollWidth:554,clientWidth:374,left:8,targetLeft:340,targetRight:444}),65);});
test('all columns and rows are revealed through actual arrow/Home/End/Ctrl navigation semantics',()=>{for(const width of [284,304,374,474]){const r=rig(width);for(let at=0;at<25;at++){focusBoardCell(r.cells[at]);fullyVisible(r,at);}let index=0;focusBoardCell(r.cells[index]);fullyVisible(r,index);for(const key of ['ArrowRight','ArrowRight','ArrowRight','ArrowRight','ArrowLeft','ArrowLeft','ArrowLeft','ArrowLeft','ArrowDown','ArrowDown','ArrowDown','ArrowDown','ArrowRight','ArrowRight','ArrowRight','ArrowRight','ArrowUp','ArrowUp','ArrowUp','ArrowUp']){index=nextBoardIndex(index,key);focusBoardCell(r.cells[index]);fullyVisible(r,index);}for(const [key,ctrl] of [['End',false],['End',true],['Home',false],['Home',true]]){index=ctrl?(key==='Home'?0:24):Math.floor(index/5)*5+(key==='End'?4:0);focusBoardCell(r.cells[index]);fullyVisible(r,index);}}});
test('both legal horizontal ends clamp and reverse traversal reveals each cell',()=>{const r=rig();focusBoardCell(r.cells[4]);fullyVisible(r,4);const end=r.board.scrollLeft;assert(end>0);for(let i=3;i>=0;i--){focusBoardCell(r.cells[i]);fullyVisible(r,i);}assert.equal(r.board.scrollLeft,4);assert(r.board.scrollLeft<end);assert.equal(planBoardFocusReveal({scrollLeft:0,scrollWidth:554,clientWidth:374,left:8,targetLeft:7,targetRight:111}),0);assert.equal(planBoardFocusReveal({scrollLeft:180,scrollWidth:554,clientWidth:374,left:8,targetLeft:285,targetRight:389}),180);});
test('fully visible cells and a standard-width board do not introduce horizontal scroll',()=>{const r=rig();focusBoardCell(r.cells[0]);assert.deepEqual(r.calls,[['focus',0]]);const standard=rig(554);for(const cell of standard.cells)focusBoardCell(cell);assert.equal(standard.board.scrollLeft,0);assert(standard.calls.every(c=>c[0]==='focus'));});
test('geometry is measured after native focus already scrolls; document and board vertical positions are retained',()=>{const r=rig(),focus=r.cells[3].focus;r.document.scrollY=0;r.cells[3].focus=()=>{focus.call(r.cells[3]);r.board.scrollLeft=100;r.document.scrollY=240;};focusBoardCell(r.cells[3]);fullyVisible(r,3);assert.deepEqual(r.calls,[['focus',3]]);assert.equal(r.document.scrollY,240);assert.equal(r.board.scrollLeft,100);});
test('failed or absent native focus cannot trigger board scrolling',()=>{focusBoardCell(null);const r=rig();r.cells[3].focus=()=>r.calls.push(['focus-disabled']);focusBoardCell(r.cells[3]);assert.deepEqual(r.calls,[['focus-disabled']]);});
test('fractional positions stay bounded and invalid geometry cannot write scroll state',()=>{const base={scrollLeft:12.5,scrollWidth:554,clientWidth:374,left:8.125,targetLeft:8.09375,targetRight:112.09375};assert.equal(planBoardFocusReveal(base),9.46875);for(const key of Object.keys(base))assert.equal(planBoardFocusReveal({...base,[key]:NaN}),null);assert.equal(planBoardFocusReveal({...base,clientWidth:0}),null);assert.equal(planBoardFocusReveal({...base,targetRight:0}),null);});
test('all four production focus paths use the reveal helper without changing key dispatch or standard reset',()=>{const source=fs.readFileSync(new URL('../src/career/CareerGarden.jsx',import.meta.url),'utf8');assert.equal((source.match(/focusBoardCell\(cells\.current/g)??[]).length,4);assert(!source.includes('cells.current[next]?.focus()'));assert(source.includes('nextBoardIndex(index, event.key)'));const viewport=fs.readFileSync(new URL('../src/career/BoardViewport.jsx',import.meta.url),'utf8');assert(viewport.includes('if (!largeText) board.scrollLeft = 0;'));const native=fs.readFileSync(new URL('./browser/text-polish.mjs',import.meta.url),'utf8');assert(native.includes("['ArrowRight',2],['ArrowRight',3],['ArrowRight',4],['ArrowLeft',3],['ArrowLeft',2],['ArrowLeft',1]"));});
