import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import * as model from '../src/career/boardDrag.js';
const source=fs.readFileSync(new URL('../src/career/useBoardDrag.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace('export default function useBoardDrag','function useBoardDrag');
function harness() {
  let visual=null,cleanup,frameId=0; const listeners=new Map(),frames=new Map(),calls=[];
  const stateRef={current:{careerId:'one',revision:1,board:[{id:'a',pieceId:'bird-1'},null,{id:'b',pieceId:'bird-1'},{id:'c',pieceId:'fern-1'}]}},busyRef={current:false};
  const board={scrollLeft:0,getBoundingClientRect:()=>({left:0,right:400,top:0,bottom:100}),contains:cell=>cells.includes(cell)};
  const cells=stateRef.current.board.map((_,index)=>({dataset:{careerCell:String(index)},held:false,closest:selector=>selector==='.career-board'?board:cells[index],getBoundingClientRect:()=>({width:100}),setPointerCapture(){this.held=true;},hasPointerCapture(){return this.held;},releasePointerCapture(){this.held=false;}}));
  const target={hidden:false,elementFromPoint:(x,y)=>y>=0&&y<100?cells[Math.floor(x/100)]??null:null,addEventListener:(type,fn)=>listeners.set(type,fn),removeEventListener:type=>listeners.delete(type)};
  const hooks={useRef:value=>({current:value}),useState:()=>[visual,value=>{visual=value;}],useEffect:fn=>{cleanup=fn();}};
  const create=new Function('useEffect','useRef','useState','dragMoved','dragIsCurrent','dragDestination','dragEdgeStep','document','window','requestAnimationFrame','cancelAnimationFrame',`${source}\nreturn useBoardDrag;`);
  const hook=create(hooks.useEffect,hooks.useRef,hooks.useState,model.dragMoved,model.dragIsCurrent,model.dragDestination,model.dragEdgeStep,target,target,fn=>{frames.set(++frameId,fn);return frameId;},id=>frames.delete(id));
  const api=hook({stateRef,busyRef,nextPiece:id=>id.endsWith('-1')?'bird-2':null,move:(from,to)=>calls.push({from,to})});
  const event=(x=50,y=50,extra={})=>({pointerId:1,pointerType:'touch',isPrimary:true,button:0,clientX:x,clientY:y,currentTarget:cells[0],prevented:false,stopped:false,preventDefault(){this.prevented=true;},stopPropagation(){this.stopped=true;},...extra});
  return {api,event,calls,stateRef,busyRef,cells,board,document:target,listeners,frames,visual:()=>visual,cleanup:()=>cleanup(),drag:(x=150)=>{api.down(event(),0);api.update(event(x));}};
}
test('touch drop commits once only on release, then compatibility click is blocked',()=>{const h=harness();h.drag();assert.equal(h.calls.length,0);assert.equal(h.visual().to,1);h.api.up(h.event(150));h.api.up(h.event(150));h.api.cancel();assert.deepEqual(h.calls,[{from:0,to:1}]);assert.equal(h.visual(),null);const click=h.event(150,50,{detail:1});assert(h.api.click(click));assert(click.prevented&&click.stopped);assert(!h.api.click(h.event(150,50,{detail:0,nativeEvent:{pointerType:'touch'}})));});
test('matching merge releases the same single move path',()=>{const h=harness();h.drag(250);h.api.up(h.event(250));assert.deepEqual(h.calls,[{from:0,to:2}]);});
test('stationary and jitter taps remain unsuppressed and never call move',()=>{const h=harness();h.api.down(h.event(),0);h.api.update(h.event(53,53));h.api.up(h.event(53,53));assert.equal(h.visual(),null);assert.equal(h.calls.length,0);assert(!h.api.click(h.event(53,53,{detail:1})));});
test('invalid, self and outside releases never commit',()=>{for(const [x,y] of [[350,50],[50,50],[450,50],[150,150]]){const h=harness();h.drag();h.api.up(h.event(x,y));assert.deepEqual(h.calls,[]);assert.equal(h.visual(),null);assert(h.api.click(h.event(x,y,{detail:1})));}});
test('cancel and lost capture clear presentation and permit the next independent tap',()=>{const h=harness();h.drag();h.api.cancel();h.api.up(h.event(150));assert.deepEqual(h.calls,[]);assert.equal(h.frames.size,0);h.api.down(h.event(),0);h.api.up(h.event());assert(!h.api.click(h.event(50,50,{detail:1})));});
test('busy, revision, career and source changes cannot commit stale pickups',()=>{for(const change of [h=>h.busyRef.current=true,h=>h.stateRef.current.revision++,h=>h.stateRef.current.careerId='two',h=>h.stateRef.current.board[0].id='replacement']){const h=harness();h.drag();change(h);h.api.up(h.event(150));assert.deepEqual(h.calls,[]);assert.equal(h.visual(),null);}});
test('mouse stays native and pen uses pointer dragging',()=>{const h=harness();h.api.down(h.event(50,50,{pointerType:'mouse'}),0);h.api.update(h.event(150,50,{pointerType:'mouse'}));assert.equal(h.visual(),null);assert(h.api.nativeStart(h.event()));h.api.down(h.event(50,50,{pointerType:'pen'}),0);assert(!h.api.nativeStart(h.event()));h.api.update(h.event(150,50,{pointerType:'pen'}));h.api.up(h.event(150,50,{pointerType:'pen'}));assert.equal(h.calls.length,1);});
test('second pointer, Escape, blur, hidden page and unmount cancel without writes',()=>{for(const interrupt of [h=>h.listeners.get('pointerdown')(h.event(20,20,{pointerId:2,isPrimary:false})),h=>h.listeners.get('keydown')({key:'Escape'}),h=>h.listeners.get('blur')(),h=>{h.document.hidden=true;h.listeners.get('visibilitychange')();},h=>h.cleanup()]){const h=harness();h.drag();interrupt(h);h.api.up(h.event(150));assert.deepEqual(h.calls,[]);assert.equal(h.frames.size,0);assert(!h.cells[0].held);}});
test('edge frames reveal horizontally without committing before drop',()=>{const h=harness();h.drag(399);const [id,fn]=[...h.frames][0];h.frames.delete(id);fn(16);assert(h.board.scrollLeft>0&&h.board.scrollLeft<=12);assert.deepEqual(h.calls,[]);h.api.cancel();assert.equal(h.frames.size,0);});

test('empty cells and nonprimary pointers never capture or activate dragging',()=>{const h=harness();h.api.down(h.event(150,50,{currentTarget:h.cells[1]}),1);assert(!h.cells[1].held);h.api.update(h.event(250));h.api.up(h.event(250));assert.equal(h.visual(),null);h.api.down(h.event(50,50,{isPrimary:false,pointerId:2}),0);assert(!h.cells[0].held);assert.deepEqual(h.calls,[]);});
test('a new completed drag is independent and a post-cancel second finger cannot restart it',()=>{const h=harness();h.drag();h.listeners.get('pointerdown')(h.event(50,50,{pointerId:2,isPrimary:false}));h.api.down(h.event(50,50,{pointerId:2,isPrimary:false}),0);h.api.update(h.event(150));h.api.up(h.event(150));assert.deepEqual(h.calls,[]);h.drag();h.api.up(h.event(150));assert.deepEqual(h.calls,[{from:0,to:1}]);});
