import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import {join} from 'node:path';import {createHash} from 'node:crypto';
import {cleanupPassedTraces} from './passed-traces.mjs';import {artifactUsage,enforceUsage} from './bounded-process.mjs';import {CASES,ORDER,LIMITS} from './policy.mjs';
const id='a'.repeat(20)+'-'+'b'.repeat(20),other='c'.repeat(20)+'-'+'d'.repeat(20),profile=ORDER[0],title=CASES[profile][2].slice(0,2).join(' ');
const pass={testId:id,title,profile,status:'passed',expectedStatus:'passed',retry:0,errors:[]};
const hash=b=>createHash('sha256').update(b).digest('hex');
const body=name=>JSON.stringify({type:'context-options',origin:'library',version:8,playwrightVersion:'1.61.1',title:'scope.mjs:30 › '+name})+'\n'+JSON.stringify({type:'after',result:'unchanged synthetic native event'})+'\n';
function fixture(){const root=fs.mkdtempSync(join(os.tmpdir(),'c280-trace-lifecycle-')),rawRoot=join(root,'raw'),traces=join(rawRoot,'.playwright-artifacts-0','traces');fs.mkdirSync(traces,{recursive:true});const files=new Map();const add=(path,b)=>{const p=join(rawRoot,path);fs.mkdirSync(join(p,'..'),{recursive:true});fs.writeFileSync(p,b);files.set(path,fs.readFileSync(p));};
 for(const n of [`${id}.trace`,`${id}-recording1.trace`])add('.playwright-artifacts-0/traces/'+n,body(title));
 for(const n of [`${id}.network`,`${id}-recording1.network`,`${id}-recording1-pwnetcopy-1.network`])add('.playwright-artifacts-0/traces/'+n,'closed passed network event\n');
 add('.playwright-artifacts-0/traces/'+other+'-recording2.trace',body(CASES[profile][5].slice(0,2).join(' ')));add('.playwright-artifacts-0/traces/resources/shared','shared resource required by any later failure');add('.playwright-artifacts-0/traces/'+id+'-unknown.trace','unknown untouched');add('C03/proof.json','native proof');add('C03/C03-crab-zero.png','native PNG unchanged');add('C08/c280-cr5.png','native download unchanged');add('failure/trace.zip','failure ZIP unchanged');return{root,rawRoot,traces,files};}
test('terminal expected pass removes only exact owned closed raw chunks with full audit',()=>{const f=fixture();try{const before=artifactUsage(f.rawRoot);const result=cleanupPassedTraces({...pass,rawRoot:f.rawRoot});assert.equal(result.files.length,5);assert.equal(result.removedBytes,result.files.reduce((n,r)=>n+r.bytes,0));for(const row of result.files){assert.equal(row.sha256,hash(f.files.get(row.path)));assert.equal(row.bytes,f.files.get(row.path).length);assert(!fs.existsSync(join(f.rawRoot,row.path)));}for(const [path,bytes]of f.files)if(!result.files.some(r=>r.path===path))assert.deepEqual(fs.readFileSync(join(f.rawRoot,path)),bytes);const after=artifactUsage(f.rawRoot);assert.equal(before.bytes-after.bytes,result.removedBytes);assert.equal(before.pngs,after.pngs);assert.equal(before.traces,after.traces);assert.equal(cleanupPassedTraces({...pass,rawRoot:f.rawRoot}).removedBytes,0);assert.equal(LIMITS.artifactBytes,128*1024*1024);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});
test('active failed interrupted retried skipped or errorful cases are never cleaned',()=>{const f=fixture();try{for(const mutation of [{status:'failed'},{status:'interrupted'},{status:'timedOut'},{status:'skipped'},{status:'running'},{expectedStatus:'failed'},{retry:1},{errors:[{message:'assertion failure'}]}]){const r=cleanupPassedTraces({...pass,...mutation,rawRoot:f.rawRoot});assert.equal(r.status,'preserved-nonpass');assert.equal(r.files.length,0);}for(const [path,bytes]of f.files)assert.deepEqual(fs.readFileSync(join(f.rawRoot,path)),bytes);}finally{fs.rmSync(f.root,{recursive:true,force:true});}});
test('wrong ownership headers and symlinks fail closed before deleting planned chunks',()=>{for(const kind of ['header','version','malformed','symlink']){const f=fixture();try{const path=join(f.traces,id+'-recording1.trace');if(kind==='header')fs.writeFileSync(path,body('C06 Wrong case'));else if(kind==='version')fs.writeFileSync(path,body(title).replace('1.61.1','1.62.0'));else if(kind==='malformed')fs.writeFileSync(path,'not-json\n');else{fs.unlinkSync(path);fs.symlinkSync(join(f.traces,other+'-recording2.trace'),path);}assert.throws(()=>cleanupPassedTraces({...pass,rawRoot:f.rawRoot}));assert(fs.existsSync(join(f.traces,id+'.trace')));assert(fs.existsSync(join(f.traces,other+'-recording2.trace')));assert(fs.existsSync(join(f.rawRoot,'failure/trace.zip')));}finally{fs.rmSync(f.root,{recursive:true,force:true});}}});
test('total watchdog still counts all temporary active traces, with unchanged byte ceiling',()=>{const f=fixture();try{const trace=join(f.traces,other+'-recording2.trace');fs.truncateSync(trace,LIMITS.artifactBytes);assert.throws(()=>enforceUsage(artifactUsage(f.rawRoot)),/Artifact byte safety ceiling/);cleanupPassedTraces({...pass,rawRoot:f.rawRoot});assert.equal(fs.statSync(trace).size,LIMITS.artifactBytes);assert.throws(()=>enforceUsage(artifactUsage(f.rawRoot)),/Artifact byte safety ceiling/);const source=fs.readFileSync(new URL('./reporter.mjs',import.meta.url),'utf8'),config=fs.readFileSync(new URL('./playwright.config.mjs',import.meta.url),'utf8');
 // Native tracing is disabled. The current reporter preserves terminal results
 // and journals every case instead of deleting any active/passed trace files.
 assert(config.includes("trace:'off'"));assert(!source.includes('cleanupPassedTraces'));assert(!source.includes('passed-trace-cleanup'));assert(!/\b(unlink|rm|rmdir)(Sync)?\b/.test(source));
 assert(source.includes("import {StepJournal} from './step-journal.mjs'"));
 const terminal=source.indexOf('super.onTestEnd(test,result)'),accounting=source.indexOf("this.journalCall('testEnd',test,result)");assert(terminal>=0&&accounting>terminal,'Terminal reporting must precede journal accounting');
 assert(source.includes("event:'step-journal'"));assert(source.includes("phase:'step-journal'"));assert(source.includes("return{status:'failed'}"));}finally{fs.rmSync(f.root,{recursive:true,force:true});}});
test('watchdog tolerates only vanished temporary traces during synchronous pass cleanup',()=>{const f=fixture();try{
 const vanished=join(f.traces,id+'.trace'),enoent=()=>Object.assign(Error('Concurrent closed-trace removal'),{code:'ENOENT'}),ops={existsSync:fs.existsSync,readdirSync:fs.readdirSync,lstatSync:path=>{if(path===vanished)throw enoent();return fs.lstatSync(path);}};
 const normal=artifactUsage(f.rawRoot);assert.equal(artifactUsage(f.rawRoot,ops).bytes,normal.bytes-fs.statSync(vanished).size);
 const missingDirectory={...ops,readdirSync:path=>{if(path===f.traces)throw enoent();return fs.readdirSync(path);}};assert(artifactUsage(f.rawRoot,missingDirectory).bytes<normal.bytes);
 const required=join(f.rawRoot,'C03/proof.json');assert.throws(()=>artifactUsage(f.rawRoot,{...ops,lstatSync:path=>{if(path===required)throw enoent();return fs.lstatSync(path);}}),/Concurrent/);
 assert.throws(()=>artifactUsage(f.rawRoot,{...ops,lstatSync:path=>{if(path===vanished)throw Object.assign(Error('Permission failure'),{code:'EACCES'});return fs.lstatSync(path);}}),/Permission/);
 }finally{fs.rmSync(f.root,{recursive:true,force:true});}});
