import fs from 'node:fs';
import assert from 'node:assert/strict';
import {resolve,relative,isAbsolute} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {CATALOG} from '../../src/career/content.js';
import {digest,regularBytes,filesUnder} from '../../full-campaign-gate/evidence.mjs';
import {gitRead} from './git-read.mjs';
import {ROOT,approval} from './policy.mjs';
import {REPO_ROOT,requireRepoCwd} from './paths.mjs';
export const SOURCE_ROOTS=['src','public','gate','tests','full-campaign-gate','full-campaign-probe','full-browser-fixtures','full-browser-evidence','campaign-evidence','stage-a-evidence','stage-b-evidence','stage-c-evidence','stage-d-evidence','stage-e-evidence','.github','docs'];
export const SOURCE_FILES=['stage-d-source.json','career.html','career.vite.config.js','package.json','package-lock.json','playwright.full-campaign.config.mjs','playwright.campaign.config.mjs'];
export const inventory=root=>filesUnder(root).map(file=>{const bytes=regularBytes(root,file);return{file,bytes:bytes.length,sha256:digest(bytes)};});
export const sourceFiles=()=>SOURCE_ROOTS.filter(fs.existsSync).flatMap(root=>inventory(root).map(r=>({...r,file:root+'/'+r.file}))).concat(SOURCE_FILES.map(file=>{const b=regularBytes(REPO_ROOT,file);return{file,bytes:b.length,sha256:digest(b)};})).sort((a,b)=>a.file<b.file?-1:a.file>b.file?1:0);
export function verifyVersions(){assert.equal(Number(process.versions.node.split('.')[0]),24);const lock=JSON.parse(fs.readFileSync('package-lock.json'));for(const name of ['@playwright/test','playwright','playwright-core','vite','@vitejs/plugin-react','react','react-dom'])assert.equal(JSON.parse(fs.readFileSync(`node_modules/${name}/package.json`)).version,lock.packages[`node_modules/${name}`].version);assert.equal(lock.packages['node_modules/@playwright/test'].version,'1.61.1');}
export function acceptedBaseline(){
 const ref=JSON.parse(fs.readFileSync('stage-e-evidence/baseline-reference.frozen.json'));
 const finalBytes=fs.readFileSync('stage-e-evidence/baseline-final-acceptance.frozen.json'),nativeBytes=fs.readFileSync('stage-e-evidence/baseline-native-acceptance.frozen.json');
 assert.equal(ref.runId,38016449234);assert.equal(ref.commit,'c5c7714588d0eff5b2a9a3c16de1c9467aa6d508');assert.equal(ref.tree,'3280796d6b95050ee8d7ca3508aded4aaac32c06');
 assert.equal(digest(regularBytes(REPO_ROOT,'stage-d-source.json')),ref.binding.sourceFingerprint,'Accepted320 source manifest changed');
 assert.equal(digest(finalBytes),ref.finalReceiptSha256);assert.equal(digest(nativeBytes),ref.nativeReceiptSha256);
 const final=JSON.parse(finalBytes),native=JSON.parse(nativeBytes);assert.equal(final.status,'ACCEPTED_320_NATIVE_ARTIFACT_AND_SCOPED_ORIGINAL_VISUAL_EVIDENCE');assert.equal(native.status,'passed');assert.equal(final.runId,ref.runId);assert.equal(final.commit,ref.commit);assert.equal(final.tree,ref.tree);assert.deepEqual(final.binding,ref.binding);assert.deepEqual(native.binding,ref.binding);assert.equal(final.nativeCases,22);assert.equal(final.pngs,88);assert.equal(final.allOriginalsIndividuallyVisuallyInspected,88);assert.equal(final.cleanup,'confirmed-clean-both-profiles');
 return{commit:ref.commit,tree:ref.tree,runId:ref.runId,finalReceiptSha256:ref.finalReceiptSha256,nativeReceiptSha256:ref.nativeReceiptSha256};
}
export function prepareSource(){requireRepoCwd();const payload={schemaVersion:1,status:'PROVISIONAL_PREPARATION_NOT_ACCEPTED_OR_AUTHORIZED',baseline:acceptedBaseline(),files:sourceFiles()};fs.writeFileSync('stage-e-source.preparation.json',JSON.stringify(payload,null,2)+'\n');return verifySource();}
export function bindSource(){requireRepoCwd();const payload={schemaVersion:1,status:'ACCEPTED_SOURCE_FOR_AUTHORIZED_RUN',meaning:'Reviewed local touch-drag source on the accepted320 baseline. Stage E native acceptance is pending.',baseline:acceptedBaseline(),files:sourceFiles()};fs.writeFileSync('stage-e-source.json',JSON.stringify(payload,null,2)+'\n',{flag:'wx'});return verifySource();}
export function verifySource(){requireRepoCwd();const file=fs.existsSync('stage-e-source.json')?'stage-e-source.json':'stage-e-source.preparation.json',bytes=fs.readFileSync(file),manifest=JSON.parse(bytes);assert.equal(manifest.schemaVersion,1);assert(['PROVISIONAL_PREPARATION_NOT_ACCEPTED_OR_AUTHORIZED','ACCEPTED_SOURCE_FOR_AUTHORIZED_RUN'].includes(manifest.status));assert.deepEqual(manifest.baseline,acceptedBaseline());assert.deepEqual(manifest.files,sourceFiles(),'Stage E source differs from its exact preparation/binding');return{sourceFingerprint:digest(bytes),manifest,file};}
export const canonicalFingerprint=value=>digest(Buffer.from(JSON.stringify(value)));
export function buildProof(){const{sourceFingerprint}=verifySource(),files=inventory('dist-stage-e').map(r=>({...r,file:'dist-stage-e/'+r.file}));assert(files.some(r=>r.file==='dist-stage-e/career.html'));const art=CATALOG.PIECES.map(p=>{const path=relative(REPO_ROOT,fileURLToPath(p.art)),bytes=regularBytes(REPO_ROOT,path),sha256=digest(bytes),builtPaths=files.filter(f=>f.sha256===sha256).map(f=>f.file);assert(builtPaths.length,`Missing built art ${p.id}`);return{id:p.id,path,sha256,bytes:bytes.length,builtPaths};});assert.equal(art.length,320);return{schemaVersion:1,sourceFingerprint,files,art};}
export function prepareBuild(){const payload=buildProof(),proof={...payload,buildFingerprint:canonicalFingerprint(payload)};fs.writeFileSync('stage-e-build.json',JSON.stringify(proof,null,2)+'\n');return proof;}
export function verifyBuild(){const proof=JSON.parse(fs.readFileSync('stage-e-build.json')),{buildFingerprint,...payload}=proof;assert.equal(buildFingerprint,canonicalFingerprint(payload));assert.deepEqual(payload,buildProof());return proof;}
export function probeRoot(){const root=process.env.MOTICOS_STAGE_E_PROBE_OUTPUT;assert(root&&isAbsolute(root)&&resolve(root)!==resolve(REPO_ROOT)&&!resolve(root).startsWith(resolve(REPO_ROOT)+'/'),'External fresh current-session probe output required');return resolve(root);}
export function prepareProbe(){const build=verifyBuild(),proof={schemaVersion:1,status:'PROVISIONAL_PREPARATION_NOT_NATIVE_EVIDENCE',sourceFingerprint:build.sourceFingerprint,buildFingerprint:build.buildFingerprint,files:inventory(probeRoot())};assert(proof.files.some(r=>r.file==='stage-e-evidence/browser/probe/current/index.html'));fs.writeFileSync('stage-e-probe.preparation.json',JSON.stringify(proof,null,2)+'\n');return proof;}
export function preparedIdentity(){const b=verifyBuild(),bytes=fs.readFileSync('stage-e-probe.preparation.json'),p=JSON.parse(bytes);assert.equal(p.sourceFingerprint,b.sourceFingerprint);assert.equal(p.buildFingerprint,b.buildFingerprint);assert.deepEqual(p.files,inventory(probeRoot()));return{sourceFingerprint:b.sourceFingerprint,buildFingerprint:b.buildFingerprint,probeFingerprint:digest(bytes)};}
export function commitIdentity(){const{manifest}=verifySource();assert.equal(manifest.status,'ACCEPTED_SOURCE_FOR_AUTHORIZED_RUN','Reviewed source has not been bound');const git=(...args)=>gitRead(...args).trim(),commit=git('rev-parse','HEAD'),parent=manifest.baseline.commit,parentTree=manifest.baseline.tree;assert.match(commit,/^[a-f0-9]{40}$/);assert.equal(git('rev-parse',`${parent}^{tree}`),parentTree);git('merge-base','--is-ancestor',parent,'HEAD');return{commit,parent,parentTree};}
export function identity(){return{...preparedIdentity(),...commitIdentity()};}
export function requireApproval(){const id=identity(),file=process.env.MOTICOS_STAGE_E_APPROVAL;assert(file&&resolve(file)===resolve(ROOT,'approval.json')&&fs.existsSync(file),'Fresh bounded touch-drag approval required');approval(JSON.parse(fs.readFileSync(file)),id,process.env);return id;}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){requireRepoCwd();verifyVersions();const command=process.argv[2];assert.equal(process.argv.length,3);assert(['prepare-source','bind-source','prepare-build','prepare-probe','verify-source'].includes(command));const result=({'prepare-source':prepareSource,'bind-source':bindSource,'prepare-build':prepareBuild,'prepare-probe':prepareProbe,'verify-source':verifySource})[command]();console.log(JSON.stringify({command,sourceFingerprint:result.sourceFingerprint,buildFingerprint:result.buildFingerprint,status:'PREPARATION_ONLY'}));}
