import test from 'node:test';
import assert from 'node:assert/strict';
import {verifyInputEvidence} from './validate.mjs';
import {verifyLauncher} from './validate-all.mjs';
import {EVIDENCE_SCOPES,ORDER,PROFILE_SCREENSHOTS,ACCEPTANCE_MEANING} from './policy.mjs';
const event=(type,{trusted=true,touch=true,primary=true}={})=>({type,isTrusted:trusted,pointerType:touch?'touch':null,isPrimary:primary});
function proof(profile,caseId,events){return{scope:EVIDENCE_SCOPES[profile],caseId,events,steps:[{label:profile===ORDER[1]?'synthetic-webkit-pointer-handler-with-capture-shim test':'trusted-chromium-cdp-touch test',eventStart:0,eventEnd:events.length}]};}
test('Chromium accepted drag requires trusted down move and up while WebKit handler proof stays synthetic',()=>{const native=proof(ORDER[0],'E01',['pointerdown','pointermove','pointerup'].map(t=>event(t)));assert(verifyInputEvidence(native,ORDER[0]));for(const i of [0,1,2]){const p=structuredClone(native);p.events[i].isTrusted=false;assert.throws(()=>verifyInputEvidence(p,ORDER[0]),/trusted/);}const synthetic=proof(ORDER[1],'E01',['pointerdown','pointermove','pointerup'].map(t=>event(t,{trusted:false})));assert(verifyInputEvidence(synthetic,ORDER[1]));for(const change of [{scope:EVIDENCE_SCOPES[ORDER[0]]},{steps:[]},{events:synthetic.events.map(e=>({...e,isTrusted:true}))}])assert.throws(()=>verifyInputEvidence({...synthetic,...change},ORDER[1]));assert(ACCEPTANCE_MEANING.includes('labeled synthetic handler checks'));});
test('cancellation requires trusted cancellation capture loss and second touch',()=>{const p=proof(ORDER[0],'E04',[event('pointercancel'),event('lostpointercapture'),event('pointerdown',{primary:false})]);assert(verifyInputEvidence(p,ORDER[0]));for(let i=0;i<3;i++){const q=structuredClone(p);q.events[i].isTrusted=false;assert.throws(()=>verifyInputEvidence(q,ORDER[0]));}});
test('both browsers native mouse and keyboard and WebKit tap proof require trusted events',()=>{for(const profile of ORDER){for(const [caseId,names]of [['E07',['dragstart','drop']],['E08',['keydown']]]){const p=proof(profile,caseId,names.map(t=>event(t,{touch:false})));assert(verifyInputEvidence(p,profile));assert.throws(()=>verifyInputEvidence({...p,events:p.events.map(e=>({...e,isTrusted:false}))},profile));}}const p=proof(ORDER[1],'E03',[event('pointerdown'),event('pointerdown',{trusted:false}),event('pointermove',{trusted:false})]);assert(verifyInputEvidence(p,ORDER[1]));assert.throws(()=>verifyInputEvidence({...p,steps:[{label:'synthetic-webkit-pointer-handler-with-capture-shim',eventStart:0,eventEnd:99}]},ORDER[1]));});
test('launcher requires exact profile counts limits identities and confirmed cleanup',()=>{for(const profile of ORDER){const binding={commit:'a'.repeat(40)},r={status:'passed',profile,...binding,exitCode:0,signal:null,error:null,timedOut:false,groupCleanup:'not-required',budget:900000,receipt:{status:'passed',cases:8,screenshots:PROFILE_SCREENSHOTS[profile].length,postcards:0}};assert(verifyLauncher(r,profile,binding));for(const change of [{groupCleanup:'unconfirmed'},{exitCode:1},{timedOut:true},{budget:900001},{commit:'b'.repeat(40)},{receipt:{...r.receipt,cases:11}},{receipt:{...r.receipt,screenshots:5}}])assert.throws(()=>verifyLauncher({...r,...change},profile,binding));}});
