import assert from 'node:assert/strict';import fs from 'node:fs';import {resolve,relative} from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';
import {CATALOG} from '../src/career/content.js';import {digest} from './evidence.mjs';import {CASES,BUDGETS,JOB_SECONDS,RESERVE_SECONDS,MAX_ARTIFACT_BYTES} from './scope.mjs';
const roots=['src','public','gate','tests/campaign-browser','tests/campaign-contract','tests/full-campaign-browser','full-campaign-gate','full-campaign-probe','full-browser-fixtures','stage-a-evidence','stage-b-evidence','.github'];
const singles=['career.html','career.vite.config.js','package.json','package-lock.json','playwright.full-campaign.config.mjs','playwright.campaign.config.mjs','campaign-evidence/full-campaign.test.mjs','campaign-evidence/full-recovery.test.mjs','campaign-evidence/content-pack-2.frozen.json','campaign-evidence/content-pack-3.frozen.json','campaign-evidence/content-pack-4.frozen.json','campaign-evidence/full-basic-journey.json'];
export function guardSources(){return inventory('full-browser-evidence').filter(row=>/\.(mjs|js)$/.test(row.file)||['full-browser-evidence/PREPARATION.md','full-browser-evidence/RUN-PROPOSAL.md','full-browser-evidence/legacy-harness-preservation.json'].includes(row.file));}
export function sealedGuardTests(manifest){const files=manifest.files.filter(row=>row.file.startsWith('full-browser-evidence/')&&row.file.endsWith('.test.mjs')).map(row=>row.file);assert(files.length>0);return files;}
export function inventory(root){const rows=[];const walk=p=>{const st=fs.lstatSync(p);assert(!st.isSymbolicLink(),`Symlink: ${p}`);if(st.isDirectory())for(const name of fs.readdirSync(p).sort())walk(p+'/'+name);else{assert(st.isFile());const b=fs.readFileSync(p);rows.push({file:p,bytes:b.length,sha256:digest(b)});}};walk(root);return rows;}
export function assertRoots(){const allowed=new Set(['stage-b-evidence','stage-a-evidence','.git','.github','CONTINUATION-CHECKPOINT.md','FULL-CAMPAIGN-CHECKPOINT-R2.md','FULL-BROWSER-CHECKPOINT-R3.md','FULL-BROWSER-CHECKPOINT-R4.md','FULL-BROWSER-CHECKPOINT-R5.md','README.txt','TRANSITION-COPY-R1.md','application-provisional.json','campaign-source.json','campaign-evidence','career.html','career.vite.config.js','gate','probe','public','src','tests','package.json','package-lock.json','playwright.campaign.config.mjs','playwright.full-campaign.config.mjs','full-browser-evidence','full-browser-inputs','full-browser-fixtures','full-browser-upload','full-campaign-gate','full-campaign-probe','full-campaign-source.json','full-campaign-build.json','full-campaign-run-approval.json','node_modules','dist-career','dist-full-probe','full-browser-results']);for(const name of fs.readdirSync('.'))assert(allowed.has(name),'Unreviewed root: '+name);}
export function sourceFiles(){assertRoots();return roots.flatMap(inventory).concat(guardSources()).concat(singles.map(file=>{const b=fs.readFileSync(file);return{file,bytes:b.length,sha256:digest(b)};})).sort((a,b)=>a.file.localeCompare(b.file));}
export function seal(){const manifest={schemaVersion:1,status:'private-provisional-not-run-approved',files:sourceFiles()};fs.writeFileSync('full-campaign-source.json',JSON.stringify(manifest,null,2)+'\n');return manifest;}
export function verifySource(){const bytes=fs.readFileSync('full-campaign-source.json'),manifest=JSON.parse(bytes);assert.equal(manifest.status,'private-provisional-not-run-approved');assert.deepEqual(manifest.files,sourceFiles(),'Source changed since review checkpoint');return{sourceFingerprint:digest(bytes),manifest};}
export function verifyVersions(){assert.equal(JSON.parse(fs.readFileSync('node_modules/@playwright/test/package.json')).version,'1.61.1','Pinned Playwright required');const lock=JSON.parse(fs.readFileSync('package-lock.json'));assert.equal(JSON.parse(fs.readFileSync('node_modules/vite/package.json')).version,lock.packages['node_modules/vite'].version);}
export function buildProof(){verifyVersions();const source=verifySource(),files=inventory('dist-career').concat(inventory('dist-full-probe'));assert(files.some(f=>f.file==='dist-career/career.html'));const art=CATALOG.PIECES.map(p=>{const bytes=fs.readFileSync(fileURLToPath(p.art)),sha256=digest(bytes);assert(files.some(f=>f.sha256===sha256),`Missing original built art ${p.id}`);return{id:p.id,sha256,bytes:bytes.length};});return{schemaVersion:1,sourceFingerprint:source.sourceFingerprint,files,art};}
export function freezeBuild(){const proof=buildProof();fs.writeFileSync('full-campaign-build.json',JSON.stringify(proof,null,2)+'\n');return proof;}
export function verifyBuild(){const bytes=fs.readFileSync('full-campaign-build.json'),proof=JSON.parse(bytes);assert.deepEqual(proof,buildProof(),'Build changed');return{...proof,buildFingerprint:digest(bytes)};}
export function verifyApproval(profile){const proof=verifyBuild(),approval=JSON.parse(fs.readFileSync('full-campaign-run-approval.json'));assert.equal(approval.status,'explicit-user-approved');assert.equal(approval.sourceFingerprint,proof.sourceFingerprint);assert.equal(approval.buildFingerprint,proof.buildFingerprint);assert.deepEqual(approval.profiles,Object.keys(CASES));assert(approval.profiles.includes(profile));assert.deepEqual(approval.limits,{jobSeconds:JOB_SECONDS,profileMilliseconds:BUDGETS,reserveSeconds:RESERVE_SECONDS,artifactBytes:MAX_ARTIFACT_BYTES});assert(typeof approval.authorizationReference==='string'&&approval.authorizationReference.trim().length>0,'Record the actual new user authorization');return proof;}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){const mode=process.argv[2];if(mode==='seal')seal();else if(mode==='source')verifySource();else if(mode==='freeze')freezeBuild();else if(mode==='verify')verifyBuild();else if(mode==='approval')verifyApproval(process.argv[3]);else throw Error('Unknown binding command');console.log(`full-campaign ${mode}: checked`);}
