import assert from 'node:assert/strict';import {verifySource} from './binding.mjs';import {execFileSync} from 'node:child_process';
export const PROPOSED_DESTINATION=Object.freeze({repository:'BlindAnatomist/moticos-for-cynthia',ref:'refs/heads/verify/full-campaign-20261008-r15',status:'proposed-not-user-approved'});
export function verifyDispatch(env=process.env,commit=()=>({head:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),message:execFileSync('git',['log','-1','--format=%B'],{encoding:'utf8'})}),source=verifySource){
 assert.equal(env.GITHUB_ACTIONS,'true');assert.equal(env.GITHUB_REPOSITORY,PROPOSED_DESTINATION.repository);assert.equal(env.GITHUB_REF,PROPOSED_DESTINATION.ref);assert.equal(env.GITHUB_EVENT_NAME,'push');assert.equal(env.GITHUB_RUN_ATTEMPT,'1');assert.match(env.GITHUB_RUN_ID??'',/^\d+$/);assert.match(env.GITHUB_SHA??'',/^[a-f0-9]{40}$/);const actual=commit();assert.equal(actual.head,env.GITHUB_SHA);
 const field=name=>{const rows=actual.message.split('\n').filter(s=>s.startsWith(name+': '));assert.equal(rows.length,1,'Missing or duplicate reviewed run trailer: '+name);return rows[0].slice(name.length+2).trim();};
 const sourceFingerprint=field('Moticos-Reviewed-Source'),buildFingerprint=field('Moticos-Reviewed-Build'),authorizationReference=field('Moticos-Run-Authorization');assert.match(sourceFingerprint,/^[a-f0-9]{64}$/);assert.match(buildFingerprint,/^[a-f0-9]{64}$/);assert(authorizationReference.length>0&&!/pending|proposed|not.authorized/i.test(authorizationReference),'A real fresh user authorization reference must be recorded; a proposal is not approval');
 const verified=source();assert.equal(sourceFingerprint,verified.sourceFingerprint,'Reviewed source trailer does not match verified checkout source');
 return{repository:env.GITHUB_REPOSITORY,ref:env.GITHUB_REF,commit:env.GITHUB_SHA,runId:env.GITHUB_RUN_ID,attempt:1,sourceFingerprint,buildFingerprint,authorizationReference};
}
