import fs from 'node:fs';import {filesUnder,regularBytes,digest} from './evidence.mjs';import {RESULTS,MAX_ARTIFACT_BYTES,MAX_PNG_FILES,MAX_TRACE_FILES,expectedOriginals} from './scope.mjs';
const out='full-browser-upload';if(fs.existsSync(out))throw Error('Never overwrite existing staged evidence');fs.mkdirSync(out);let errors=[],rows=[];
try{rows=filesUnder(RESULTS).map(path=>{const b=regularBytes(RESULTS,path);return{path,bytes:b.length,sha256:digest(b),included:false};});}catch(e){errors.push(e.message);}
let acceptance=null;try{acceptance=JSON.parse(regularBytes(RESULTS,'acceptance.json'));}catch(e){errors.push('Missing readable acceptance result: '+e.message);}
const manifest={status:'incomplete-or-failed',originalsUnmodified:true,acceptanceStatus:acceptance?.status??null,errors,files:rows};let bytes=0,pngs=0,traces=0,failures=0;
// Small diagnostic records first; never replace originals with thumbnails.
rows.sort((a,b)=>(/\.(json|jsonl)$/.test(b.path)?1:0)-(/\.(json|jsonl)$/.test(a.path)?1:0)||a.path.localeCompare(b.path));
for(const row of rows){const png=row.path.endsWith('.png'),trace=row.path.endsWith('.zip');if(png&&!expectedOriginals().includes(row.path)){if(!row.path.includes('/raw/')||failures>=1){errors.push('Omitted unexpected or extra failure PNG: '+row.path);continue;}failures++;}if((png&&pngs>=MAX_PNG_FILES)||(trace&&traces>=MAX_TRACE_FILES)){errors.push('Omitted over-count original: '+row.path);continue;}if(bytes+row.bytes+Buffer.byteLength(JSON.stringify(manifest,null,2))+8192>MAX_ARTIFACT_BYTES){errors.push('Omitted over-size original: '+row.path);continue;}const data=regularBytes(RESULTS,row.path),target=out+'/'+row.path;fs.mkdirSync(target.slice(0,target.lastIndexOf('/')),{recursive:true});fs.writeFileSync(target,data,{flag:'wx'});row.included=true;bytes+=data.length;if(png)pngs++;if(trace)traces++;}
manifest.status=acceptance?.status==='passed'&&errors.length===0&&rows.every(r=>r.included)?'passed':'incomplete-or-failed';manifest.payloadBytes=bytes;manifest.pngs=pngs;manifest.traces=traces;const encoded=JSON.stringify(manifest,null,2)+'\n';if(bytes+Buffer.byteLength(encoded)>MAX_ARTIFACT_BYTES)throw Error('Staged metadata exceeds cap');fs.writeFileSync(out+'/upload-manifest.json',encoded,{flag:'wx'});console.log(JSON.stringify({status:manifest.status,bytes:bytes+Buffer.byteLength(encoded),files:rows.filter(r=>r.included).length}));
