import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,readdirSync,lstatSync,existsSync} from 'node:fs';
import {join,relative,resolve} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {CATALOG} from '../src/career/content.js';
export const digest=b=>createHash('sha256').update(b).digest('hex');
export function regularFile(file){const stat=lstatSync(file);assert(stat.isFile()&&!stat.isSymbolicLink(),`Not a regular bound file: ${file}`);return readFileSync(file);}
export function inventory(root,include=()=>true){assert(lstatSync(root).isDirectory()&&!lstatSync(root).isSymbolicLink(),`Invalid inventory root: ${root}`);const out=[];function walk(path){for(const name of readdirSync(path).sort()){const p=join(path,name),s=lstatSync(p);assert(!s.isSymbolicLink(),`Symlink forbidden: ${p}`);if(s.isDirectory())walk(p);else{assert(s.isFile());if(!include(p.replaceAll('\\','/')))continue;const b=readFileSync(p);out.push({file:p.replaceAll('\\','/'),bytes:b.length,sha256:digest(b)});}}}walk(root);return out;}
export function assertProjectionRoots(){const allowed=new Set(['career.html','career.vite.config.js','package.json','package-lock.json','application-provisional.json','playwright.campaign.config.mjs','README.txt','campaign-source.json','campaign-provisional-seal.json','campaign-build.json','src','public','gate','tests','probe','node_modules','dist-career','dist-probe','campaign-results','campaign-upload','.git','.github']);for(const name of readdirSync('.'))assert(allowed.has(name),`Unreviewed projection root: ${name}`);}
export function currentFiles(){assertProjectionRoots();const app=JSON.parse(readFileSync('application-provisional.json')).files;const rest=['gate','tests','probe'].flatMap(root=>inventory(root)).concat(['playwright.campaign.config.mjs','application-provisional.json','README.txt'].map(file=>{const b=regularFile(file);return{file,bytes:b.length,sha256:digest(b)};}));const files=app.map(({file})=>{const b=regularFile(file);return{file,bytes:b.length,sha256:digest(b)};}).concat(rest).sort((a,b)=>a.file.localeCompare(b.file));assert.equal(new Set(files.map(x=>x.file)).size,files.length);return files;}
export function validateManifest(manifest,{final=false}={}){assert.equal(manifest.schemaVersion,1);if(final)assert.equal(manifest.status,'reviewed-frozen');assert.deepEqual(manifest.files,currentFiles(),'Source or gate changed since seal');const app=JSON.parse(readFileSync('application-provisional.json')).files;for(const row of app){const actual=manifest.files.find(x=>x.file===row.file);assert.deepEqual(actual,row,'Runtime differs from source-import closure');}for(const root of['src','public'])assert.deepEqual(inventory(root).map(x=>x.file).sort(),app.filter(x=>x.file.startsWith(root+'/')).map(x=>x.file).sort(),'Extra unreviewed source');if(existsSync('.github')){const actual=inventory('.github');const proposal=readFileSync('gate/workflow.proposal.json');assert.deepEqual(actual,[{file:'.github/workflows/verify-campaign.yml',bytes:proposal.length,sha256:digest(proposal)}],'Only the byte-identical reviewed workflow may be materialized after separate authorization');}return manifest;}
export function verifySource(final=true){const path=final?'campaign-source.json':'campaign-provisional-seal.json';const manifest=validateManifest(JSON.parse(regularFile(path)),{final});return {manifest,sourceFingerprint:digest(readFileSync(path))};}
export function identity(){if(process.env.GITHUB_ACTIONS!=='true')return {kind:'local-preparation'};assert.equal(process.env.GITHUB_RUN_ATTEMPT,'1');assert.equal(process.env.GITHUB_REPOSITORY,'BlindAnatomist/moticos-for-cynthia');assert.equal(process.env.GITHUB_REF,'refs/heads/verify/campaign-20261007');assert.equal(process.env.GITHUB_EVENT_NAME,'push');assert.match(process.env.GITHUB_SHA??'',/^[a-f0-9]{40}$/);assert.match(process.env.GITHUB_RUN_ID??'',/^\d+$/);const commit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();assert.equal(commit,process.env.GITHUB_SHA);return {kind:'github',commit,repository:process.env.GITHUB_REPOSITORY,ref:process.env.GITHUB_REF,runId:process.env.GITHUB_RUN_ID,attempt:1};}
export function freezeBuild(final=true){const source=verifySource(final),files=inventory('dist-career').concat(inventory('dist-probe'));assert(files.some(f=>f.file==='dist-career/career.html'));assert(files.some(f=>f.file==='dist-probe/probe/index.html'));const art=CATALOG.PIECES.map(piece=>{const p=fileURLToPath(piece.art),b=readFileSync(p),sha256=digest(b),matches=files.filter(f=>f.sha256===sha256);assert(matches.length,`Missing original built art ${piece.id}`);return{id:piece.id,source:relative(process.cwd(),p).replaceAll('\\','/'),bytes:b.length,sha256,buildPaths:matches.map(x=>x.file.startsWith('dist-career/')?x.file.slice('dist-career/'.length):x.file)};});return {schemaVersion:1,identity:identity(),status:final?'sealed-build':'provisional-build-not-browser-accepted',sourceFingerprint:source.sourceFingerprint,files,art,versions:{node:process.version,vite:JSON.parse(readFileSync('node_modules/vite/package.json')).version,playwright:JSON.parse(readFileSync('node_modules/@playwright/test/package.json')).version}};}
export function verifyBuild(final=true){const proof=JSON.parse(readFileSync('campaign-build.json'));assert.deepEqual(proof,freezeBuild(final),'Build/source changed');return proof;}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){const [mode,flag]=process.argv.slice(2),final=flag!=='--provisional';if(mode==='seal'){assert(!final,'Final seal requires independent approval via parent-controlled finalization');writeFileSync('campaign-provisional-seal.json',JSON.stringify({schemaVersion:1,status:'provisional-not-browser-accepted',files:currentFiles()},null,2)+'\n');}else if(mode==='source')verifySource(final);else if(mode==='freeze')writeFileSync('campaign-build.json',JSON.stringify(freezeBuild(final),null,2)+'\n');else{assert.equal(mode,'verify');verifyBuild(final);}console.log(`campaign ${mode}: ${final?'final':'provisional'} source binding verified`);}
