import {readFileSync,writeFileSync,mkdirSync,copyFileSync,existsSync} from 'node:fs';
import assert from 'node:assert/strict';
import {inventory,verifyBuild,digest} from './binding.mjs';
import {verifyPng} from './png.mjs';
import {verifyCompleted} from './results.mjs';
import {CASES,MAX_SCREENSHOTS,MAX_POSTCARDS,MAX_PNG_FILES,MAX_TRACE_FILES,MAX_ARTIFACT_BYTES,REQUIRED_SCREENSHOTS,REQUIRED_POSTCARDS,REQUIRED_RECORDS} from './scope.mjs';
export function verifyCaps(files){assert(files.reduce((n,f)=>n+f.bytes,0)<=MAX_ARTIFACT_BYTES,'Artifact byte cap exceeded');assert(files.filter(f=>f.file.endsWith('.png')).length<=MAX_PNG_FILES,'PNG cap exceeded');assert(files.filter(f=>f.file.includes('/raw/')&&f.file.endsWith('.png')).length<=1,'Failure screenshot cap exceeded');assert(files.filter(f=>f.file.endsWith('.zip')).length<=MAX_TRACE_FILES,'Trace cap exceeded');assert(files.filter(f=>/\/screenshots\/.*\.png$/.test(f.file)).length<=MAX_SCREENSHOTS,'Screenshot cap exceeded');assert(files.filter(f=>/\/postcards\/.*\.png$/.test(f.file)).length<=MAX_POSTCARDS,'Export cap exceeded');}
export function validateOriginalPng(bytes,row){assert.equal(bytes.length,row.bytes);assert.equal(digest(bytes),row.sha256);verifyPng(bytes,row.dimensions);}
export function verifyRequiredEvidence(files,originals){const paths=new Set(files.map(row=>row.file)),originalPaths=new Set(originals.map(row=>row.path??row.file));for(const [profile,names] of Object.entries(REQUIRED_SCREENSHOTS)){assert(paths.has(`campaign-results/${profile}/screenshots/manifest.json`),'Missing screenshot manifest');for(const name of names){const path=`campaign-results/${profile}/screenshots/${name}.png`;assert(paths.has(path)&&originalPaths.has(path),`Missing required original screenshot: ${name}`);}}for(const path of REQUIRED_POSTCARDS)assert(paths.has(path)&&originalPaths.has(path),`Missing required original download: ${path}`);for(const [profile,names] of Object.entries(REQUIRED_RECORDS))for(const name of names)assert(paths.has(`campaign-results/${profile}/${name}.json`),`Missing required case record: ${name}`);}
export function inspectFullEvidence(){mkdirSync('campaign-results',{recursive:true});let binding,status='passed',error=null;try{binding={status:'verified',sourceFingerprint:verifyBuild(true).sourceFingerprint};}catch(e){status='incomplete';error=e.message;binding={status:'failed'};}for(const file of['campaign-source.json','campaign-build.json'])if(existsSync(file))copyFileSync(file,`campaign-results/${file}`);const groups=[];
 for(const profile of Object.keys(CASES)){try{const root=`campaign-results/${profile}`,raw=JSON.parse(readFileSync(`${root}/results.json`)),events=readFileSync(`${root}/progress/browser-events.jsonl`,'utf8').trim().split('\n').map(JSON.parse);groups.push(verifyCompleted(profile,raw,events));}catch(e){status='incomplete';groups.push({profile,status:'incomplete',error:e.message});}}
 const originals=[];for(const profile of Object.keys(CASES)){const root=`campaign-results/${profile}`,path=`${root}/screenshots/manifest.json`;if(existsSync(path))for(const row of JSON.parse(readFileSync(path))){assert(row.path.startsWith(`${root}/screenshots/`)&&!row.path.split('/').includes('..'));if(binding.status==='verified')assert.equal(row.sourceFingerprint,binding.sourceFingerprint);validateOriginalPng(readFileSync(row.path),row);originals.push({kind:'screenshot',...row});}}
 const exportPath='campaign-results/campaign-chromium/C13-paired-labels-original-exports.json';if(existsSync(exportPath))for(const row of JSON.parse(readFileSync(exportPath)).postcards){assert(/^campaign-results\/campaign-chromium\/postcards\/C13-(garden|moon)\.png$/.test(row.file));validateOriginalPng(readFileSync(row.file),row);originals.push({kind:'postcard',...row});}
 for(const profile of Object.keys(CASES))for(const [id] of CASES[profile]){const candidates=existsSync(`campaign-results/${profile}`)?inventory(`campaign-results/${profile}`).filter(row=>row.file.match(new RegExp(`/`+id+`-[^/]+\\.json$`))):[];if(status==='passed')assert(candidates.length,`Missing actual case evidence ${id}`);for(const row of candidates){const record=JSON.parse(readFileSync(row.file));assert.equal(record.caseId,id);if(binding.status==='verified')assert.equal(record.sourceFingerprint,binding.sourceFingerprint);}}
 const files=inventory('campaign-results').filter(f=>!f.file.endsWith('/evidence-manifest.json'));for(const row of files.filter(f=>f.file.endsWith('.png'))){const bytes=readFileSync(row.file);const expected=originals.find(r=>(r.path??r.file)===row.file);if(!expected){assert(row.file.includes('/raw/'),'Unmanifested original PNG');verifyPng(bytes,[bytes.readUInt32BE(16),bytes.readUInt32BE(20)]);}}
 const known=new Set(originals.map(r=>r.path??r.file));assert.equal(known.size,originals.length,'Duplicate original records');verifyCaps(files);if(status==='passed')verifyRequiredEvidence(files,originals);
 const manifest={schemaVersion:1,status,binding,error,groups,originals,files,retentionDays:1,caveat:'Automated browser evidence only. Human screenshot review, physical-device audio/input/assistive technology and uncoached player acceptance remain required.'};let bytes;for(let n=0;n<3;n++){bytes=Buffer.from(JSON.stringify(manifest,null,2)+'\n');manifest.totalBytes=files.reduce((s,f)=>s+f.bytes,0)+bytes.length;}bytes=Buffer.from(JSON.stringify(manifest,null,2)+'\n');assert(files.reduce((s,f)=>s+f.bytes,0)+bytes.length<=MAX_ARTIFACT_BYTES,'Final manifest exceeds artifact cap');writeFileSync('campaign-results/evidence-manifest.json',bytes);console.log(JSON.stringify({status,files:files.length,bytes:manifest.totalBytes}));return manifest;}

