import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const sha=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
const source=[...walk('src'),...walk('public'),'package.json','package-lock.json','vite.config.js','index.html'].sort().map(file=>({file,sha256:sha(file)}));
const sourceFingerprint=createHash('sha256').update(JSON.stringify(source)).digest('hex');
const receipt=JSON.parse(fs.readFileSync('evidence/expansion-assets/asset-receipt.json'));
const emitted=walk('dist-expansion/assets').map(file=>({file:file.slice('dist-expansion/'.length),sha256:sha(file)}));
const assets=receipt.records.map(r=>{const matches=emitted.filter(a=>a.sha256===r.canonicalWebpSha256);assert.equal(matches.length,1,`Exact emitted new art: ${r.id}`);return {id:r.id,...matches[0]};});
assert.equal(assets.length,40);
const prior=JSON.parse(fs.readFileSync('evidence/collage-batch/asset-receipt.json'));
for(const r of prior.records)assert.equal(emitted.filter(a=>a.sha256===r.canonicalWebpSha256).length,1,`Preserved prior art: ${r.id}`);
let index=fs.readFileSync('dist-expansion/index.html','utf8');
assert(!index.includes('moticos-private-expansion-source'));
index=index.replace('</head>',`<meta name="moticos-private-expansion-source" content="${sourceFingerprint}" />\n</head>`);
fs.writeFileSync('dist-expansion/index.html',index);
fs.writeFileSync('dist-expansion/expansion-manifest.json',JSON.stringify({kind:'private-120-piece-expansion',baselineCommit:'cf172905dc3fec335d4117e86bb9847149b01122',totalPieces:120,newPieces:40,envelopes:12,sourceFingerprint,entryScripts:[...index.matchAll(/<script[^>]*src="([^"]+)"/g)].map(m=>m[1]),assets,entryFiles:emitted.filter(a=>/\.(js|css)$/.test(a.file)),source},null,2)+'\n');
console.log(`Private 120-piece source fingerprint: ${sourceFingerprint}`);
