import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,readdirSync,lstatSync,existsSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {join,relative,resolve} from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import {CATALOG} from '../src/career/content.js';
export const digest=bytes=>createHash('sha256').update(bytes).digest('hex');
export function inventory(root){const result=[];function walk(p){for(const name of readdirSync(p).sort()){const q=join(p,name),s=lstatSync(q);assert(!s.isSymbolicLink(),'No symlink in bound evidence/source');if(s.isDirectory())walk(q);else if(s.isFile()){const bytes=readFileSync(q);result.push({file:q.replaceAll('\\','/'),bytes:bytes.length,sha256:digest(bytes)});}else throw Error('Unexpected special file');}}walk(root);return result;}
export function verifySource(){const manifest=JSON.parse(readFileSync('career-gate-source.json','utf8'));assert.equal(manifest.schemaVersion,1);assert.equal(manifest.publicBase,'e3583203731eb256c14e75e7cb9c933d246cddfd');assert.equal(manifest.application.length,8);assert.equal(new Set(manifest.files.map(x=>x.file)).size,manifest.files.length);for(const item of manifest.files){assert(!item.file.startsWith('/')&&!item.file.split('/').includes('..'));const s=lstatSync(item.file);assert(s.isFile()&&!s.isSymbolicLink());const bytes=readFileSync(item.file);assert.equal(bytes.length,item.bytes,item.file);assert.equal(digest(bytes),item.sha256,item.file);}const expected=manifest.files.map(x=>x.file).concat('career-gate-source.json').sort();const tracked=execFileSync('git',['ls-files','-z'],{encoding:'utf8'}).split('\0').filter(Boolean).sort();assert.deepEqual(tracked,expected,'Tracked projection has extra or omitted paths');for(const name of ['src','public'])assert.deepEqual(inventory(name).map(x=>x.file).sort(),manifest.files.filter(x=>x.file.startsWith(name+'/')).map(x=>x.file).sort(),'Unreviewed source/art file');for(const item of manifest.application){const match=manifest.files.find(f=>f.file===item.file);assert(match);assert.equal(match.sha256,item.sha256);}return{manifest,sourceFingerprint:digest(readFileSync('career-gate-source.json'))};}
export function identity(){const commit=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();if(process.env.GITHUB_ACTIONS==='true'){assert.equal(process.env.GITHUB_REPOSITORY,'BlindAnatomist/moticos-for-cynthia');assert.equal(process.env.GITHUB_REF,'refs/heads/verify/career-20261007');assert.equal(process.env.GITHUB_RUN_ATTEMPT,'1');assert.equal(process.env.GITHUB_SHA,commit);assert.match(process.env.GITHUB_RUN_ID??'',/^\d+$/);return{kind:'github',commit,repository:process.env.GITHUB_REPOSITORY,ref:process.env.GITHUB_REF,runId:process.env.GITHUB_RUN_ID,attempt:1};}return{kind:'local-preparation',commit};}
export function freezeBuild(){const source=verifySource(),files=inventory('dist-career');assert(files.some(f=>f.file==='dist-career/career.html'));const art=CATALOG.PIECES.map(p=>{const path=fileURLToPath(p.art),bytes=readFileSync(path),sha256=digest(bytes),matches=files.filter(f=>f.sha256===sha256);assert(matches.length>=1,`Missing built art ${p.id}`);return{id:p.id,source:relative(process.cwd(),path).replaceAll('\\','/'),sha256,bytes:bytes.length,buildPaths:matches.map(x=>x.file.replace(/^dist-career\//,''))};});return{schemaVersion:1,identity:identity(),sourceFingerprint:source.sourceFingerprint,files,art};}
export function verifyBuild(proof=JSON.parse(readFileSync('career-build-proof.json','utf8'))){assert.deepEqual(proof,freezeBuild(),'Built bytes, source, identity or accepted art changed');return proof;}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){const mode=process.argv[2];if(mode==='source')verifySource();else if(mode==='freeze')writeFileSync('career-build-proof.json',JSON.stringify(freezeBuild(),null,2)+'\n');else{assert.equal(mode,'verify');verifyBuild();}console.log(`career ${mode}: exact source and build binding checked`);}
