import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {CASES,titleFor} from './careerGateScope.mjs';
export function flatten(suites,rows=[]){for(const suite of suites??[]){for(const spec of suite.specs??[])for(const test of spec.tests??[])rows.push({title:spec.title,id:spec.id,project:test.projectName,expectedStatus:test.expectedStatus,status:test.status,results:test.results??[],line:spec.line,file:spec.file});flatten(suite.suites,rows);}return rows;}
export function verifyCollection(result){assert.deepEqual(result.errors??[],[]);assert.equal(result.config.workers,1);assert.equal(result.config.fullyParallel,false);assert.equal(result.config.forbidOnly,true);assert.equal(result.config.maxFailures,1);const rows=flatten(result.suites);const expected=Object.entries(CASES).flatMap(([project,cases])=>cases.map(([id,title])=>`${project}:${titleFor(id,title)}`)).sort();assert.deepEqual(rows.map(r=>`${r.project}:${r.title}`).sort(),expected);assert(rows.every(r=>r.expectedStatus==='passed'&&r.results.length===0));assert.equal(new Set(rows.map(r=>r.id)).size,4);return{kind:'collection-only',cases:4,ids:rows.map(r=>({id:r.id,title:r.title,project:r.project}))};}
export function verifyCompleted(profile,result,events){assert(Object.hasOwn(CASES,profile));assert.deepEqual(result.errors??[],[]);assert.equal(result.config.workers,1);assert.equal(result.config.fullyParallel,false);assert.equal(result.config.forbidOnly,true);assert.equal(result.config.maxFailures,1);const rows=flatten(result.suites),expected=CASES[profile].map(([id,title])=>titleFor(id,title)).sort();assert.deepEqual(rows.map(r=>r.title).sort(),expected);assert.equal(new Set(rows.map(r=>r.id)).size,rows.length);assert(rows.every(r=>r.project===profile&&r.expectedStatus==='passed'&&r.status==='expected'&&r.results.length===1&&r.results[0].status==='passed'&&r.results[0].retry===0));assert.equal(result.stats?.unexpected,0);assert.equal(result.stats?.skipped,0);assert.equal(result.stats?.flaky,0);assert.equal(result.stats?.expected,rows.length);assert.equal(events.filter(e=>e.event==='begin').length,1);assert.equal(events.filter(e=>e.event==='end').length,1);assert.equal(events.find(e=>e.event==='end').status,'passed');assert.equal(events.filter(e=>e.event==='error').length,0);const begin=events.find(e=>e.event==='begin');assert.equal(begin.workers,1);assert.equal(begin.maxFailures,1);assert.deepEqual(begin.retries,[0]);assert.deepEqual(begin.projects,[profile]);const ends=events.filter(e=>e.event==='test-end'),starts=events.filter(e=>e.event==='test-begin');assert.equal(starts.length,rows.length);assert.equal(ends.length,rows.length);assert.deepEqual(ends.map(e=>e.id).sort(),rows.map(r=>r.id).sort());assert.deepEqual(starts.map(e=>e.id).sort(),rows.map(r=>r.id).sort());assert(ends.every(e=>e.project===profile&&e.status==='passed'&&e.retry===0&&e.errors.length===0));return{profile,status:'passed',cases:rows.length,ids:rows.map(r=>({id:r.id,title:r.title}))};}
if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){const[mode,arg]=process.argv.slice(2);if(mode==='collection'){const proof=verifyCollection(JSON.parse(readFileSync(arg,'utf8')));writeFileSync('career-results/collection-proof.json',JSON.stringify(proof,null,2)+'\n');}else{assert.equal(mode,'completed');const root=`career-results/${arg}`;const proof=verifyCompleted(arg,JSON.parse(readFileSync(`${root}/results.json`,'utf8')),readFileSync(`${root}/progress/browser-events.jsonl`,'utf8').trim().split('\n').map(line=>JSON.parse(line)));writeFileSync(`${root}/completed-proof.json`,JSON.stringify(proof,null,2)+'\n');}console.log('Exact career scope verified');}
