import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {encodeManifest,completeStatus,EXPECTED_SCREENSHOTS} from '../../scripts/packageCareerEvidence.mjs';
import {layoutViolations,MOBILE_CORE,PHONE_VIEWPORTS} from '../../scripts/careerLayoutContract.mjs';
import {CASES,BUDGETS,validateInvocation,eligibleBudget,titleFor} from '../../scripts/careerGateScope.mjs';
import {verifyCollection,verifyCompleted} from '../../scripts/verifyCareerScope.mjs';
import {fixtureNamed} from '../career-browser/fixtures.mjs';
import {validateCareer} from '../../src/career/engine.js';
const copy=x=>structuredClone(x);
function specimen(profile){const cases=CASES[profile];const rows=cases.map(([id,title],i)=>({title:titleFor(id,title),id:`real-${profile}-${id}`,tests:[{projectName:profile,expectedStatus:'passed',status:'expected',results:[{status:'passed',retry:0}]}]}));return{config:{workers:1,fullyParallel:false,forbidOnly:true,maxFailures:1},errors:[],suites:[{specs:rows}],stats:{expected:cases.length,unexpected:0,skipped:0,flaky:0}};}
function events(profile){return[{event:'begin',workers:1,maxFailures:1,retries:[0],projects:[profile]},...CASES[profile].flatMap(([id])=>[{event:'test-begin',id:`real-${profile}-${id}`,project:profile,retry:0},{event:'test-end',id:`real-${profile}-${id}`,project:profile,retry:0,status:'passed',errors:[]}]),{event:'end',status:'passed'}];}
test('scope is exactly eight desktop and four phone case IDs with finite budgets',()=>{assert.deepEqual(Object.values(CASES).map(c=>c.length),[8,4]);assert.equal(new Set(Object.values(CASES).flat().map(c=>c[0])).size,12);assert.deepEqual(Object.values(BUDGETS),[480000,240000]);});
test('exact read-only collection and approved full groups alone are admitted',()=>{const cfg='--config=playwright.career.config.js';assert(validateInvocation(['test',cfg,'--list','--reporter=json']).listing);for(const p of Object.keys(CASES)){assert.equal(validateInvocation(['test',cfg,`--project=${p}`],true).profile,p);assert.throws(()=>validateInvocation(['test',cfg,`--project=${p}`],false));for(const extra of ['--grep=C01','--workers=2','--retries=1','--repeat-each=2','--timeout=999999','--list','--reporter=json','--project=unknown'])assert.throws(()=>validateInvocation(['test',cfg,`--project=${p}`,extra],true));}});
test('budget refuses a group unless its complete cap and evidence reserve remain',()=>{assert.equal(eligibleBudget('career-chromium',585),480000);assert.throws(()=>eligibleBudget('career-chromium',586));assert.equal(eligibleBudget('career-webkit-phone',825),240000);assert.throws(()=>eligibleBudget('career-webkit-phone',826));for(const n of [-1,NaN,1.5])assert.throws(()=>eligibleBudget('career-chromium',n));});
test('collection rejects missing extra duplicate skipped or unexpected definitions',()=>{const input={...specimen('career-chromium'),suites:[...specimen('career-chromium').suites,...specimen('career-webkit-phone').suites]};for(const suite of input.suites)for(const spec of suite.specs){spec.tests[0].results=[];}assert.equal(verifyCollection(input).cases,12);for(const mutate of [r=>r.suites[0].specs.pop(),r=>r.suites[0].specs.push(copy(r.suites[0].specs[0])),r=>r.suites[0].specs[0].tests[0].expectedStatus='skipped',r=>r.errors.push({message:'bad'}),r=>r.config.workers=2]){const r=copy(input);mutate(r);assert.throws(()=>verifyCollection(r));}});
test('completion requires every exact case once and an agreeing append-only ledger',()=>{for(const profile of Object.keys(CASES)){assert.equal(verifyCompleted(profile,specimen(profile),events(profile)).status,'passed');for(const mutate of [r=>r.suites[0].specs.pop(),r=>r.suites[0].specs[0].tests[0].results.push({status:'passed',retry:1}),r=>r.suites[0].specs[0].tests[0].results[0].status='interrupted',r=>r.suites[0].specs[0].tests[0].expectedStatus='failed',r=>r.stats.skipped=1,r=>r.errors.push({message:'fatal'})]){const r=specimen(profile);mutate(r);assert.throws(()=>verifyCompleted(profile,r,events(profile)));}for(const mutate of [e=>e.pop(),e=>e.push({event:'error',message:'fatal'}),e=>e.push(copy(e[1])),e=>e[0].workers=2,e=>e[0].retries=[1]]){const e=events(profile);mutate(e);assert.throws(()=>verifyCompleted(profile,specimen(profile),e));}}});
test('all browser fixture boundary states validate without invented rewards',()=>{const three=fixtureNamed('threeOrders');assert.equal(three.orders.length,3);assert.equal(three.upgrades['bird-sorter'],1);assert.equal(three.upgrades['fern-sorter'],1);for(const name of ['fresh','ready','funded','upgraded','threeOrders','allFinal','allArt'])assert.equal(validateCareer(fixtureNamed(name)),true,name);});

test('workflow keeps one standard job, exact branch, twenty minutes and one-day public evidence',()=>{const w=JSON.parse(readFileSync(new URL('../../.github/workflows/verify-career.yml',import.meta.url),'utf8'));assert.deepEqual(w.on,{push:{branches:['verify/career-20261007']}});assert.deepEqual(w.permissions,{contents:'read'});assert.deepEqual(Object.keys(w.jobs),['career']);const j=w.jobs.career;assert.equal(j['runs-on'],'ubuntu-latest');assert.equal(j['timeout-minutes'],20);assert(!j.strategy&&!j.services);assert(j.if.includes('github.run_attempt == 1'));assert(j.steps.every(s=>!s['continue-on-error']));const uploads=j.steps.filter(s=>s.uses?.startsWith('actions/upload-artifact@'));assert.equal(uploads.length,1);assert.equal(uploads[0].with['retention-days'],1);assert.equal(uploads[0].with.path,'career-results/');assert.equal(uploads[0].with['include-hidden-files'],true);assert.equal(j.steps.filter(s=>s.run==='bash scripts/runCareerGroup.sh career-chromium').length,1);assert.equal(j.steps.filter(s=>s.run==='bash scripts/runCareerGroup.sh career-webkit-phone').length,1);assert(!JSON.stringify(w).match(/larger-runner|self-hosted|contents.*write|deploy_site|netlify|sites_deploy/));});

test('evidence cap includes final manifest bytes and fails at the exact boundary',()=>{assert.equal(EXPECTED_SCREENSHOTS.length,19);assert.equal(new Set(EXPECTED_SCREENSHOTS).size,19);assert(EXPECTED_SCREENSHOTS.includes('P03-320x568-mixed-art.png'));assert(EXPECTED_SCREENSHOTS.length+1<=20);const result=encodeManifest({status:'incomplete',files:[{file:'a',sha256:'0'.repeat(64),bytes:100}]},100,10000);assert.equal(result.manifest.bytes,100+result.encoded.length);assert.equal(result.manifest.manifestBytes,result.encoded.length);assert.doesNotThrow(()=>encodeManifest({status:'incomplete',files:[{file:'a',sha256:'0'.repeat(64),bytes:100}]},100,result.manifest.bytes));assert.throws(()=>encodeManifest({status:'incomplete',files:[{file:'a',sha256:'0'.repeat(64),bytes:100}]},100,result.manifest.bytes-1));});
test('passed browser records cannot override a failed current source/build binding',()=>{const passes=[{profile:'career-chromium',status:'passed'},{profile:'career-webkit-phone',status:'passed'}];assert.equal(completeStatus(passes,{status:'verified'}),'passed');assert.equal(completeStatus(passes,{status:'failed',message:'changed build'}),'incomplete');assert.equal(completeStatus(passes.slice(1),{status:'verified'}),'incomplete');assert.equal(completeStatus([{profile:'career-chromium',status:'passed'},{profile:'career-webkit-phone',status:'incomplete'}],{status:'verified'}),'incomplete');assert.equal(completeStatus([passes[0],passes[0]],{status:'verified'}),'incomplete');const config=readFileSync(new URL('../../playwright.career.config.js',import.meta.url),'utf8');assert(config.includes("screenshots:false,snapshots:true,sources:false"));});

function phoneProof(){const box=(x,y,width,height)=>({x,y,width,height,right:x+width,bottom:y+height}),bounds={'.career-mobile-hud':box(8,8,304,44),'.career-mobile-order-strip':box(8,56,304,64),'.career-board':box(8,124,304,296),'.career-producers':box(8,424,304,64),'.career-tools':box(8,492,304,44),'.career-status':box(8,540,304,20)};const controls=Array.from({length:25},(_,i)=>({label:`cell-${i}`,kind:'cell',box:box(15+(i%5)*58.8,131+Math.floor(i/5)*57.2,54.8,53.2)}));controls.push({label:'Bird',kind:'supply',box:box(9,425,147,62)},{label:'Fern',kind:'supply',box:box(164,425,147,62)},{label:'Undo',kind:'undo',box:box(8,492,58,44)},{label:'Send',kind:'send',box:box(241,66,64,44)});return{width:320,height:568,scrollWidth:320,scrollHeight:568,scrollY:0,largeText:false,modal:false,bounds,controls};}
test('standard phone policy requires the entire core surface before any scroll-to-hit rescue',()=>{assert.deepEqual(PHONE_VIEWPORTS,[{width:320,height:568},{width:390,height:664},{width:390,height:844},{width:430,height:932}]);assert.deepEqual(layoutViolations(phoneProof()),[]);for(const mutate of [p=>p.scrollHeight=1077,p=>p.scrollY=120,p=>{p.bounds['.career-board'].y=495.6;p.bounds['.career-board'].bottom=774.8;},p=>p.controls[0].box.bottom=775,p=>p.controls.pop(),p=>p.controls.splice(0,1),p=>p.controls[25].box.width=43,p=>p.largeText=true]){const p=phoneProof();mutate(p);assert(layoutViolations(p).length>0);}assert(layoutViolations(phoneProof(),{expectedBasicSources:2}).length>0);});
test('large-text and optional-panel scroll exceptions are explicit and cannot loosen normal play',()=>{const p=phoneProof();p.scrollHeight=1200;assert(layoutViolations(p).length>0);assert(layoutViolations(p,{mode:'large-text'}).length>0);p.largeText=true;assert.deepEqual(layoutViolations(p,{mode:'large-text'}),[]);p.modal=true;assert.deepEqual(layoutViolations(p,{mode:'panel'}),[]);assert(layoutViolations(p,{mode:'standard-phone'}).length>0);assert(layoutViolations(p,{mode:'unknown'}).length>0);});
