import test from 'node:test';
import assert from 'node:assert/strict';
import { pathToFileURL } from 'node:url';
import { resolve } from 'node:path';
const sourceRoot = process.env.CAREER_SOURCE_ROOT ? pathToFileURL(resolve(process.env.CAREER_SOURCE_ROOT) + '/') : new URL('../../', import.meta.url);
const { createCareer, createReplay, commandFor, reduceCareer, validateCareer, matchingTiles, compatiblePairs, nextOutput, chapterComplete, HISTORY_LIMIT, RECEIPT_LIMIT } = await import(new URL('src/career/engine.js', sourceRoot));
const { CATALOG, FAMILIES, STORY_ORDERS, ORDINARY_ORDERS, UPGRADES, LEVELS, STORAGE_KEY, LOCK_NAME, levelDefinition, coinBalance, orderCapacity, recipeKey } = await import(new URL('src/career/content.js', sourceRoot));
const { createCareerSession } = await import(new URL('src/career/session.js', sourceRoot));
import * as oracle from './expected-contract.mjs';
const copy = value => structuredClone(value);
function act(s,a) { const result=reduceCareer(s,commandFor(s,a)); assert.equal(result.ok,true,result.message); assert.equal(validateCareer(result.state),true); assert.equal(result.state.revision,s.revision+1); assert(result.state.nextTileSeq>=s.nextTileSeq); assert(result.state.nextOrderSeq>=s.nextOrderSeq); return result.state; }
function unchanged(s,a,code) { const before=JSON.stringify(s);const r=reduceCareer(s,a);assert.equal(r.ok,false);if(code)assert.equal(r.code,code);assert.equal(JSON.stringify(r.state),before);assert.equal(JSON.stringify(s),before);return r; }
function supply(s,familyId,basic=true) { const before=new Set(s.board.filter(Boolean).map(t=>t.id));s=act(s,{type:'supply',familyId,basic});return [s,s.board.find(t=>t&&!before.has(t.id)).id]; }
function merge(s,a,b) { const from=s.board.findIndex(t=>t?.id===a),to=s.board.findIndex(t=>t?.id===b);s=act(s,{type:'move',from,to,tileId:a,targetTileId:b});return [s,s.board[to].id]; }
function makePiece(s,pieceId) { const p=CATALOG.pieceOf(pieceId);if(p.tier===1)return supply(s,p.familyId);let a,b;[s,a]=makePiece(s,CATALOG.previousPiece(pieceId).id);[s,b]=makePiece(s,CATALOG.previousPiece(pieceId).id);return merge(s,a,b); }
function ready(s,order) { const reserved=new Set();for(const r of order.requirements){for(let n=0;n<r.quantity;n++){let t=s.board.find(t=>t?.pieceId===r.pieceId&&!reserved.has(t.id));if(!t){let id;[s,id]=makePiece(s,r.pieceId);t=s.board.find(t=>t?.id===id);}reserved.add(t.id);}}return s; }
function complete(s,o) {s=ready(s,o);return act(s,{type:'complete',orderId:o.id,tileIds:matchingTiles(s,o)});}
function route(count=9) {let s=createCareer('qa-route');for(let i=0;i<count;i++){const o=s.orders.find(o=>o.storyLetterId===STORY_ORDERS[i].id);assert(o,`Missing story ${i+1}`);s=complete(s,o);assert.equal(s.xp,oracle.xpRoute[i]);assert.equal(s.coinsEarned,oracle.coinsRoute[i]);}return s;}
function recycleAll(s) {for(let i=0;i<25;i++){if(s.board[i])s=act(s,{type:'recycle',at:i,tileId:s.board[i].id,confirmed:true});}return s;}
function setupStorage(initial, {writeFail=false,readFail=false}={}) {const map=new Map([['moticos.matching.garden.v1','old protected bytes'],['moticos.collection.garden.v1','older protected bytes']]);if(initial!==undefined)map.set(STORAGE_KEY,typeof initial==='string'?initial:JSON.stringify(initial));let active=0,tail=Promise.resolve();const audit=[];const locks={request:async(name,options,fn)=>{assert.equal(name,LOCK_NAME);assert.equal(options.mode,'exclusive');const result=tail.then(async()=>{assert.equal(active,0);active++;try{return await fn();}finally{active--;}});tail=result.catch(()=>{});return result;}};const flags={writeFail,readFail};const storage={getItem(key){assert.equal(active,1,'Reads must occur under exclusive lock');audit.push(['get',key]);if(flags.readFail)throw Error('Read denied');return map.get(key)??null;},setItem(key,value){assert.equal(active,1,'Writes must occur under exclusive lock');assert.equal(key,STORAGE_KEY);audit.push(['set',key]);if(flags.writeFail)throw Error('Quota exceeded');map.set(key,value);}};return {map,locks,storage,flags,audit};}

// The oracle is independent of the implementation's reward and recipe tables.
test('authored content exactly matches independent nine-order oracle',()=>{assert.deepEqual(LEVELS.map(x=>x.xp),oracle.thresholds);assert.equal(STORY_ORDERS.length,9);STORY_ORDERS.forEach((o,i)=>{assert.equal(recipeKey(o.requirements),oracle.recipeKey(oracle.story[i]));const [xp,coins]=oracle.story[i].reduce((a,[,t])=>[a[0]+oracle.rewards[t][0],a[1]+oracle.rewards[t][1]],[0,0]);assert.deepEqual([o.xp,o.coins],[xp,coins]);});assert.deepEqual(ORDINARY_ORDERS.map(o=>recipeKey(o.requirements)),oracle.ordinary.map(oracle.recipeKey));assert.deepEqual(UPGRADES.map(u=>[u.id,u.level,u.price]),[['bird-sorter',2,50],['fern-sorter',2,50],['order-desk',3,100]]);});
test('fresh career grants exactly four of each starter once',()=>{const s=createCareer('qa-new');assert.equal(s.board.filter(Boolean).length,8);assert.equal(s.xp,0);assert.equal(coinBalance(s),0);assert.equal(s.orders.length,1);for(const f of FAMILIES)assert.equal(s.board.filter(t=>CATALOG.pieceOf(t?.pieceId)?.familyId===f.id).length,4);const cleared=recycleAll(s);assert.equal(cleared.board.filter(Boolean).length,0);assert.equal(cleared.xp,0);assert.equal(cleared.coinsEarned,0);for(const f of FAMILIES)assert.equal(cleared.material[f.id].initial,4);});
test('complete real-action nine-letter route is eligible and earns 510 XP / 215 coins',()=>{const s=route();assert.equal(levelDefinition(s).level,4);assert.equal(s.xp,510);assert.equal(s.coinsEarned,215);assert.equal(s.milestones.length,9);assert.equal(chapterComplete(s),true);assert.equal(s.history.length,0);assert(s.orders.every(o=>o.origin==='ordinary'&&o.xp===0));});
test('the fourth delivery unlocks only vacant second slot and fifth yields 60 coins',()=>{let s=route(4);assert.deepEqual(s.orders.map(o=>o.storyLetterId),['garden-letter-5','garden-letter-6']);const retained=copy(s.orders[1]);s=complete(s,s.orders[0]);assert.deepEqual(s.orders.find(o=>o.id===retained.id),retained);assert.equal(s.xp,140);assert.equal(s.xp-80,60);assert.equal(coinBalance(s),60);});
test('all three useful purchases are funded by story route with 15 coins left',()=>{let s=route();for(const u of UPGRADES)s=act(s,{type:'purchase',upgradeId:u.id,expectedLevel:0});assert.equal(coinBalance(s),15);assert.equal(orderCapacity(s),3);assert.equal(s.orders.length,3);assert.equal(s.history.length,0);});
test('sorter is future-only, output 1/1/2, manual level 1 does not advance cursor',()=>{let s=route(5);const board=copy(s.board);s=act(s,{type:'purchase',upgradeId:'bird-sorter',expectedLevel:0});assert.deepEqual(s.board,board);assert.equal(coinBalance(s),10);for(const tier of [1,1,2,1,1,2]){assert.equal(nextOutput(s,'bird').tier,tier);const cursor=s.sources.bird.cursor;let id;[s,id]=supply(s,'bird',true);assert.equal(s.sources.bird.cursor,cursor);assert.equal(CATALOG.pieceOf(s.board.find(t=>t?.id===id).pieceId).tier,1);[s,id]=supply(s,'bird',false);assert.equal(CATALOG.pieceOf(s.board.find(t=>t?.id===id).pieceId).tier,tier);}});
test('fresh level 4 takes 8 draws + 7 merges without sorter and 6 + 5 with it',()=>{for(const upgraded of [false,true]){let s=recycleAll(route(5));if(upgraded)s=act(s,{type:'purchase',upgradeId:'bird-sorter',expectedLevel:0});let draws=0,merges=0;while(!s.board.some(t=>t?.pieceId==='b4')){[s]=supply(s,'bird',false);draws++;let pairs;while((pairs=compatiblePairs(s).filter(([a])=>CATALOG.pieceOf(s.board[a].pieceId).familyId==='bird')).length){const [a,b]=pairs[0];[s]=merge(s,s.board[a].id,s.board[b].id);merges++;}}assert.deepEqual([draws,merges],upgraded?[6,5]:[8,7]);}});
test('supply Undo restores board/cursor/material; sequence IDs and discoveries never rewind',()=>{let s=act(route(5),{type:'purchase',upgradeId:'bird-sorter',expectedLevel:0});[s]=supply(s,'bird',false);[s]=supply(s,'bird',false);const before=copy(s);[s]=supply(s,'bird',false);const supplied=copy(s);s=act(s,{type:'undo'});assert.deepEqual(s.board,before.board);assert.deepEqual(s.sources,before.sources);assert.deepEqual(s.material,before.material);assert.equal(s.nextTileSeq,supplied.nextTileSeq);assert(s.discoveries.includes('b2'));assert.equal(nextOutput(s,'bird').tier,2);assert.equal(validateCareer(JSON.parse(JSON.stringify(s))),true);});
test('merge, cut, recycle and Undo conserve mass without XP or coin farming',()=>{let s=createCareer('qa-manipulation');const start=copy(s);[s]=merge(s,s.board[0].id,s.board[1].id);const at=s.board.findIndex(t=>t?.pieceId==='b2');s=act(s,{type:'cut',at,tileId:s.board[at].id});s=act(s,{type:'undo'});s=act(s,{type:'recycle',at,tileId:s.board[at].id});s=act(s,{type:'undo'});s=act(s,{type:'undo'});assert.deepEqual(s.board,start.board);assert.deepEqual(s.material,start.material);assert.equal(s.xp,0);assert.equal(s.coinsEarned,0);assert(s.discoveries.includes('b2'));});
test('full final board: failed supply/cut leave exact state and any-tier recycle recovers it',()=>{let s=recycleAll(route());while(s.board.filter(Boolean).length<25){let id;[s,id]=makePiece(s,'b5'); // Constructing last slots recursively needs room, so compress proven material into remaining final slots below.
if(s.board.filter(Boolean).length===21)break;}
// The engine cannot make another final with only four empties via naive recursion. A valid conserved fixture isolates the full-board boundary.
for(let i=0;i<25;i++){if(!s.board[i]){s.board[i]={id:`${s.careerId}:tile:${s.nextTileSeq++}`,pieceId:'b5'};s.material.bird.generated+=16;}}s.history=[];assert.equal(validateCareer(s),true);const before=copy(s);unchanged(s,commandFor(s,{type:'supply',familyId:'bird'}));unchanged(s,commandFor(s,{type:'cut',at:0,tileId:s.board[0].id}));unchanged(s,commandFor(s,{type:'recycle',at:0,tileId:s.board[0].id}));s=act(s,{type:'recycle',at:0,tileId:s.board[0].id,confirmed:true});assert.equal(s.xp,before.xp);assert.equal(s.coinsEarned,before.coinsEarned);s=act(s,{type:'supply',familyId:'fern',to:0});assert(s.board[0]);s=act(s,{type:'undo'});s=act(s,{type:'undo'});assert.deepEqual(s.board,before.board);assert.deepEqual(s.material,before.material);});
test('wrong count, duplicate assignment, wrong recipe and stale completion are no-ops',()=>{let s=route(3),o=s.orders[0];s=ready(s,o);const ids=matchingTiles(s,o);unchanged(s,commandFor(s,{type:'complete',orderId:o.id,tileIds:[ids[0]]}));unchanged(s,commandFor(s,{type:'complete',orderId:o.id,tileIds:[ids[0],ids[0]]}));const other=s.board.find(t=>t&&!ids.includes(t.id));unchanged(s,commandFor(s,{type:'complete',orderId:o.id,tileIds:[ids[0],other.id]}));const command=commandFor(s,{type:'complete',orderId:o.id,tileIds:ids});s=act(s,{type:'complete',orderId:o.id,tileIds:ids});unchanged(s,command,'stale');unchanged(s,commandFor(s,{type:'complete',orderId:o.id,tileIds:ids}));unchanged(s,commandFor(s,{type:'undo'}));});
test('desk adds exactly one ordinary choice and preserves existing story snapshots',()=>{let s=route(8);const existing=copy(s.orders);s=act(s,{type:'purchase',upgradeId:'order-desk',expectedLevel:0});assert.equal(s.orders.length,existing.length+1);for(const o of existing)assert.deepEqual(s.orders.find(x=>x.id===o.id),o);const ordinary=s.orders.find(o=>o.origin==='ordinary');assert.equal(recipeKey(ordinary.requirements),oracle.recipeKey(oracle.ordinary[0]));const milestones=copy(s.milestones);s=complete(s,ordinary);assert.deepEqual(s.milestones,milestones);assert.equal(chapterComplete(s),false);});
test('already-promised XP survives level cap, new optional orders advertise zero XP',()=>{let s=act(route(8),{type:'purchase',upgradeId:'order-desk',expectedLevel:0});const promised=copy(s.orders.find(o=>o.origin==='ordinary'));assert.equal(promised.xp,20);s=complete(s,s.orders.find(o=>o.storyLetterId==='garden-letter-9'));assert.equal(s.xp,510);assert.deepEqual(s.orders.find(o=>o.id===promised.id),promised);s=complete(s,promised);assert.equal(s.xp,530);assert.equal(levelDefinition(s).level,4);assert(s.orders.every(o=>o.xp===0));});
test('genuinely new repeat instances consume owned material and each pay normally',()=>{let s=route();const first=s.orders[0],recipe=recipeKey(first.requirements);let seen=null;const firstCoins=s.coinsEarned;s=complete(s,first);assert.equal(s.coinsEarned,firstCoins+first.coins);for(let i=0;i<30;i++){const found=s.orders.find(o=>recipeKey(o.requirements)===recipe);if(found){seen=found;break;}s=complete(s,s.orders[0]);}assert(seen);assert.notEqual(seen.id,first.id);const coins=s.coinsEarned;const mass=copy(s.material);s=complete(s,seen);assert.equal(s.coinsEarned,coins+seen.coins);for(const r of seen.requirements){const p=CATALOG.pieceOf(r.pieceId);assert(s.material[p.familyId].delivered>=mass[p.familyId].delivered+p.mass*r.quantity);}assert.equal(s.xp,510);});
test('replaying authored story pays zero and cannot change career stock or milestones',()=>{const career=route(),bytes=JSON.stringify(career);let replay=createReplay('garden-letter-9','qa-practice');replay=complete(replay,replay.orders[0]);assert.equal(replay.xp,0);assert.equal(replay.coinsEarned,0);assert.equal(replay.orders.length,0);assert.equal(replay.milestones.length,0);assert.equal(JSON.stringify(career),bytes);assert.equal(chapterComplete(replay),false);});
test('history and receipts remain bounded during continued play',()=>{let s=route();for(let i=0;i<45;i++){s=complete(s,s.orders[0]);assert(s.receipts.length<=RECEIPT_LIMIT);}for(let i=0;i<40;i++){let id;[s,id]=supply(s,'bird');const at=s.board.findIndex(t=>t?.id===id);s=act(s,{type:'recycle',at,tileId:id});assert(s.history.length<=HISTORY_LIMIT);}assert.equal(s.history.length,HISTORY_LIMIT);assert.equal(s.receipts.length,RECEIPT_LIMIT);});
test('invalid saves are rejected including unknown schema, malformed mass, duplicate IDs, negative coins',()=>{for(const mutate of [s=>s.schemaVersion++,s=>s.rulesVersion++,s=>s.board[1]=copy(s.board[0]),s=>s.material.bird.generated++,s=>s.coinsEarned=-1,s=>s.nextTileSeq=Number.MAX_SAFE_INTEGER,s=>s.board[0].pieceId='nonexistent']){const s=createCareer('qa-invalid');mutate(s);assert.throws(()=>validateCareer(s));}});

test('session creates/loads only career key; every read/write is under exclusive lock',async()=>{const env=setupStorage();const a=createCareerSession({...env,makeCareer:()=>createCareer('qa-session')});const r=await a.open();assert.equal(r.saved,true);assert.equal(r.status,'saved');assert.equal(env.map.get('moticos.matching.garden.v1'),'old protected bytes');assert.equal(env.map.get('moticos.collection.garden.v1'),'older protected bytes');assert(env.audit.every(([,key])=>key===STORAGE_KEY));const b=createCareerSession(env);assert.deepEqual((await b.open()).state,r.state);});
test('two-tab move and claim races serialize and duplicate rewards pay once after reload',async()=>{let s=createCareer('qa-race');s=ready(s,s.orders[0]);const env=setupStorage(s),a=createCareerSession(env),b=createCareerSession(env);await Promise.all([a.open(),b.open()]);const o=s.orders[0],cmd=commandFor(s,{type:'complete',orderId:o.id,tileIds:matchingTiles(s,o)});const results=await Promise.all([a.commit(cmd),b.commit(cmd)]);assert.equal(results.filter(x=>x.ok).length,1);assert.equal(results.filter(x=>x.code==='stale').length,1);const persisted=JSON.parse(env.map.get(STORAGE_KEY));assert.equal(persisted.xp,10);assert.equal(persisted.coinsEarned,5);assert.equal(persisted.material.bird.delivered,2);assert.equal(persisted.milestones.length,1);const reloaded=createCareerSession(env);await reloaded.open();assert.equal((await reloaded.commit(cmd)).code,'stale');assert.equal(JSON.parse(env.map.get(STORAGE_KEY)).xp,10);
const command=commandFor(persisted,{type:'supply',familyId:'bird'});const moves=await Promise.all([a.commit(command),b.commit(command)]);assert.equal(moves.filter(x=>x.ok).length,1);assert.equal(moves.filter(x=>x.code==='stale').length,1);});
test('two-tab purchase race spends once and cannot partly activate an upgrade',async()=>{const s=route(5),env=setupStorage(s),a=createCareerSession(env),b=createCareerSession(env);await Promise.all([a.open(),b.open()]);const cmd=commandFor(s,{type:'purchase',upgradeId:'bird-sorter',expectedLevel:0});const results=await Promise.all([a.commit(cmd),b.commit(cmd)]);assert.equal(results.filter(x=>x.ok).length,1);const saved=JSON.parse(env.map.get(STORAGE_KEY));assert.equal(saved.coinsSpent,50);assert.equal(saved.upgrades['bird-sorter'],1);assert.equal(saved.sources.bird.sorter,1);assert.equal(saved.sources.bird.cursor,0);assert.equal(saved.history.length,0);const repeat=await a.commit(commandFor(saved,{type:'purchase',upgradeId:'bird-sorter',expectedLevel:0}));assert.equal(repeat.ok,false);assert.equal(JSON.parse(env.map.get(STORAGE_KEY)).coinsSpent,50);});
test('quota failure preserves previous exact bytes and labels candidate as unsaved practice',async()=>{let s=createCareer('qa-quota');s=ready(s,s.orders[0]);const env=setupStorage(s),session=createCareerSession(env);await session.open();const before=env.map.get(STORAGE_KEY);env.flags.writeFail=true;const o=s.orders[0];const r=await session.commit(commandFor(s,{type:'complete',orderId:o.id,tileIds:matchingTiles(s,o)}));assert.equal(r.saved,false);assert.equal(r.status,'practice');assert.equal(r.code,'practice-applied');assert.match(r.warning,/unsaved practice/i);assert.equal(env.map.get(STORAGE_KEY),before);assert.equal(r.state.xp,10);env.flags.writeFail=false;const reloaded=createCareerSession(env);const reload=await reloaded.open();assert.deepEqual(reload.state,s);assert.equal(reload.state.xp,0);});
test('missing lock, denied reads, future schemas and invalid bytes are protected',async()=>{for(const kind of ['no-lock','read-denied','future','invalid']){const s=createCareer('qa-protected'),bytes=kind==='future'?JSON.stringify({...s,schemaVersion:999}):kind==='invalid'?'{broken JSON':JSON.stringify(s);const env=setupStorage(bytes,{readFail:kind==='read-denied'});const session=createCareerSession({...env,locks:kind==='no-lock'?null:env.locks,makeCareer:()=>createCareer('qa-temporary')});const r=await session.open();assert.equal(r.saved,false,kind);assert.equal(r.status,'practice',kind);assert.equal(env.map.get(STORAGE_KEY),bytes,kind);assert.equal(env.audit.filter(([op])=>op==='set').length,0,kind);const further=await session.commit(commandFor(r.state,{type:'supply',familyId:'bird'}));assert.equal(further.saved,false);assert.equal(env.map.get(STORAGE_KEY),bytes);}});
test('source cursor/output/material survive committed Undo and a new session reload',async()=>{let s=act(route(5),{type:'purchase',upgradeId:'bird-sorter',expectedLevel:0});[s]=supply(s,'bird',false);[s]=supply(s,'bird',false);const env=setupStorage(s),session=createCareerSession(env);await session.open();const draw=await session.commit(commandFor(s,{type:'supply',familyId:'bird'}));assert.equal(draw.saved,true);const undo=await session.commit(commandFor(draw.state,{type:'undo'}));assert.equal(undo.saved,true);assert.deepEqual(undo.state.sources,s.sources);assert.deepEqual(undo.state.material,s.material);assert.deepEqual(undo.state.board,s.board);const reloaded=createCareerSession(env);const result=await reloaded.open();assert.equal(nextOutput(result.state,'bird').tier,2);assert.deepEqual(result.state.board,s.board);});
test('replacement career identity and deleted career cannot be overwritten by stale tab',async()=>{for(const replaced of [true,false]){const s=createCareer('qa-tab-old'),env=setupStorage(s),session=createCareerSession(env);await session.open();if(replaced)env.map.set(STORAGE_KEY,JSON.stringify(createCareer('qa-tab-new')));else env.map.delete(STORAGE_KEY);const before=env.map.get(STORAGE_KEY);const r=await session.commit(commandFor(s,{type:'supply',familyId:'bird'}));assert.equal(r.ok,false);assert.equal(env.map.get(STORAGE_KEY),before);assert.equal(r.code,replaced?'stale':'storage-unavailable');}});
test('random interrupted ordinary actions preserve invariants, no mutation, and no passive rewards',()=>{let s=createCareer('qa-random'),seed=73;const random=n=>{seed=(seed*1664525+1013904223)>>>0;return seed%n;};for(let i=0;i<1800;i++){const before=JSON.stringify(s),xp=s.xp,coins=s.coinsEarned,pairs=compatiblePairs(s),occupied=s.board.map((t,at)=>t?at:null).filter(x=>x!==null),choice=random(6);let action;if(choice===0)action={type:'supply',familyId:random(2)?'bird':'fern',basic:!!random(2)};else if(choice===1&&pairs.length){const [from,to]=pairs[random(pairs.length)];action={type:'move',from,to,tileId:s.board[from].id,targetTileId:s.board[to].id};}else if(choice===2&&occupied.length){const at=occupied[random(occupied.length)];action={type:'cut',at,tileId:s.board[at].id};}else if(choice===3&&occupied.length){const at=occupied[random(occupied.length)];action={type:'recycle',at,tileId:s.board[at].id,confirmed:true};}else if(choice===4)action={type:'undo'};else action={type:'sound',enabled:!s.sound};const result=reduceCareer(s,commandFor(s,action));assert.equal(JSON.stringify(s),before);if(result.ok)s=result.state;else assert.equal(JSON.stringify(result.state),before);assert.equal(validateCareer(s),true);assert.equal(s.xp,xp);assert.equal(s.coinsEarned,coins);if(i%50===0)s=JSON.parse(JSON.stringify(s));}});
test('locked or underfunded purchases leave coins, sources and history untouched',()=>{let s=createCareer('qa-unfunded');for(const upgrade of UPGRADES)unchanged(s,commandFor(s,{type:'purchase',upgradeId:upgrade.id,expectedLevel:0}));s=route(4);unchanged(s,commandFor(s,{type:'purchase',upgradeId:'bird-sorter',expectedLevel:0}));s=route(5);unchanged(s,commandFor(s,{type:'purchase',upgradeId:'bird-sorter',expectedLevel:1}));});
test('ordinary delivery matching a story recipe cannot advance that story milestone',()=>{let s=route(7);s.milestones=s.milestones.filter(id=>id!=='garden-letter-7');s.receipts=s.receipts.filter(r=>r.storyLetterId!=='garden-letter-7');const template=ORDINARY_ORDERS.find(o=>o.requirements.length===1&&o.requirements[0].pieceId==='f4');s.orders=[{id:`${s.careerId}:order:${s.nextOrderSeq++}`,slot:0,templateId:template.id,origin:'ordinary',storyLetterId:null,requirements:copy(template.requirements),xp:template.xp,coins:template.coins,rulesVersion:1}];s.history=[];assert.equal(validateCareer(s),true);s=complete(s,s.orders[0]);assert(!s.milestones.includes('garden-letter-7'));assert.equal(chapterComplete(s),false);});
test('cross-tab race between a purchase and a delivery commits exactly one whole command',async()=>{let s=route(5);const o=s.orders.find(o=>o.storyLetterId==='garden-letter-6');s=ready(s,o);const env=setupStorage(s),a=createCareerSession(env),b=createCareerSession(env);await Promise.all([a.open(),b.open()]);const results=await Promise.all([a.commit(commandFor(s,{type:'purchase',upgradeId:'bird-sorter',expectedLevel:0})),b.commit(commandFor(s,{type:'complete',orderId:o.id,tileIds:matchingTiles(s,o)}))]);assert.equal(results.filter(x=>x.ok).length,1);assert.equal(results.filter(x=>x.code==='stale').length,1);const saved=JSON.parse(env.map.get(STORAGE_KEY));assert.equal(validateCareer(saved),true);assert.equal(saved.coinsSpent,50);assert.equal(saved.xp,s.xp);assert.deepEqual(saved.board,s.board);assert(saved.orders.some(x=>x.id===o.id));});
test('quota failure during purchase leaves persisted funds and upgrade both unchanged',async()=>{const s=route(5),env=setupStorage(s),session=createCareerSession(env);await session.open();const bytes=env.map.get(STORAGE_KEY);env.flags.writeFail=true;const result=await session.commit(commandFor(s,{type:'purchase',upgradeId:'bird-sorter',expectedLevel:0}));assert.equal(result.saved,false);assert.equal(result.status,'practice');assert.equal(env.map.get(STORAGE_KEY),bytes);assert.equal(JSON.parse(bytes).coinsSpent,0);assert.equal(JSON.parse(bytes).upgrades['bird-sorter'],0);assert.equal(result.state.coinsSpent,50);assert.equal(result.state.upgrades['bird-sorter'],1);});
test('ordinary cycle yields unique eligible recipes per refill and cursor survives save',()=>{let s=act(route(8),{type:'purchase',upgradeId:'order-desk',expectedLevel:0});s=complete(s,s.orders.find(o=>o.storyLetterId==='garden-letter-9'));for(let i=0;i<25;i++){const keys=s.orders.map(o=>recipeKey(o.requirements));assert.equal(new Set(keys).size,keys.length);assert(s.orders.every(o=>o.requirements.every(r=>CATALOG.pieceOf(r.pieceId).tier<=oracle.ceiling(s.xp))));const cursor=s.ordinaryCursor;s=JSON.parse(JSON.stringify(s));assert.equal(s.ordinaryCursor,cursor);s=complete(s,s.orders.find(o=>o.slot===i%3));}});
test('large text and sound preferences persist through lock-owned commands without rewards',async()=>{const s=createCareer('qa-preferences'),env=setupStorage(s),session=createCareerSession(env);await session.open();let r=await session.commit(commandFor(s,{type:'large-text',enabled:true}));assert.equal(r.saved,true);r=await session.commit(commandFor(r.state,{type:'sound',enabled:true}));assert.equal(r.saved,true);assert.equal(r.state.xp,0);assert.equal(r.state.coinsEarned,0);assert.deepEqual(r.state.board,s.board);const reloaded=await createCareerSession(env).open();assert.equal(reloaded.state.largeText,true);assert.equal(reloaded.state.sound,true);unchanged(reloaded.state,commandFor(reloaded.state,{type:'large-text',enabled:'true'}));});
test('practice can open without crypto or Web Locks and never writes old or new save bytes',async()=>{const descriptor=Object.getOwnPropertyDescriptor(globalThis,'crypto');try{Object.defineProperty(globalThis,'crypto',{value:undefined,configurable:true});const env=setupStorage(),session=createCareerSession({...env,locks:null});const result=await session.open();assert.equal(result.status,'practice');assert.equal(result.saved,false);assert.match(result.state.careerId,/^[a-zA-Z0-9-]{1,80}$/);assert.equal(validateCareer(result.state),true);assert.equal(env.map.has(STORAGE_KEY),false);assert.equal(env.audit.length,0);}finally{if(descriptor)Object.defineProperty(globalThis,'crypto',descriptor);else delete globalThis.crypto;}});
test('malformed receipt identities/templates cannot reach receipt/postcard UI as valid saves',()=>{const base=route(1);const invalid=[r=>r.id='unrecognized-order',r=>r.storyLetterId='unknown-letter',r=>r.templateId='unknown-template'];for(const mutate of invalid){const s=copy(base);mutate(s.receipts[0]);assert.throws(()=>validateCareer(s));}const purchase=act(route(5),{type:'purchase',upgradeId:'bird-sorter',expectedLevel:0});purchase.receipts.at(-1).id='unknown-upgrade';assert.throws(()=>validateCareer(purchase));});
test('unknown source, material, upgrade and tile fields are rejected before save use',()=>{for(const mutate of [s=>s.sources.unknown={sorter:0,cursor:0},s=>s.material.unknown={initial:0,generated:0,delivered:0,recycled:0},s=>s.upgrades.unknown=0,s=>s.sources.bird.unknown=0,s=>s.material.bird.unknown=0,s=>s.board[0].unknown='unexpected']){const s=createCareer('qa-unknown-keys');mutate(s);assert.throws(()=>validateCareer(s));}});
